### ISSUE TITLE
Widget scripts being added to the dom before widget is added.

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#4223] opened 2019-09-09 18:51 UTC
I am not too sure how to report this issue but here is my test case:

1- Run blog recipe
2- Add ContentPickerField to Paragraph and Page Content Types
3- Create a new Page ContentItem and the init script for the ParagraphContentPickerField get's rendered before adding a widget (in this case the script was throwing an error)

![image](https://user-images.githubusercontent.com/4681586/64558113-1fa01380-d311-11e9-87ed-8235316a3ffe.png)

I have fixed the VueMultiselectWrapper script so it does not throw an error if the element is null but I feel like those init scripts should not be added to the dom unless the user adds the widget to the type.

**Comment by sebastienros** [comment] 2019-09-09 19:53
Maybe we should change the way widgets work in the admin by triggering a custom event, with the target as an argument, and the widgets' scripts could register to this event if they want to initialize a newly instantiated widget in the editor. Same for deletion.

Because these scripts have to run only once.

**Comment by jptissot** [comment] 2019-09-09 20:05
Yes, this is exactly what I had in mind as a possible fix. 

The action of adding a Widget would trigger an event on the dom, and the scripts (VueMultiselectWrapper for example) would react to said event.

**Comment by sebastienros** [comment] 2019-09-09 20:09
It would only slightly modify the way custom widgets are developed. Feel free to work on it if you feel like it.

**Comment by ns8482e** [comment] 2020-02-09 18:39
related #3250 #5149

**Comment by sebastienros** [comment] 2020-05-07 18:27
>  those init scripts should not be added to the dom unless the user adds the widget to the type

1. Only if the widget is added
2. Or if the widgets is already added, at least once
3. Not again if the widget is added later on dynamically
4. Some scripts might need to run each time a widget is added

And that a totally dynamic solution on the front-end, and widgets needs a new development model, this can't be easily solved with a common fix. At least each widget should be tested to work without throwing exceptions like you did.

**Comment by agriffard** [comment] 2020-09-16 13:22
@ns8482e As #5507 has been closed, can you provide a fix for this issue?

**Comment by ns8482e** [comment] 2020-09-17 01:54
@agriffard  PR #5507 and #5499 were related and  I closed both based on @sebastienros comment  - with note that the behavior is by design. 

I guess this issue also same as by design - as resource script is rendered always even if it's rendered from mock widget.

the only fix I can think for this issue is to call `initVueMultiselect` only if dom is present - as we check the same in other places e.g.  `htmlfield.edit` 

Possible solution could be,
```js
<script at="Foot" depends-on="vue-multiselect-wrapper">
    $(function () {
        var vueElementId = document.getElementById('#@vueElementId');
        if(vueElementId){
            initVueMultiselect(document.querySelector("#@vueElementId"))
        }
    })    
</script>

```

**Comment by Piedone** [comment] 2024-04-28 20:59
With the proper `depends-on` configs now in place, this isn't an issue anymore.

**Closed by Piedone** 2024-04-28 20:59 UTC
