### ISSUE TITLE
Getting error when I click on GraphQL link from admin page

### ISSUE THREAD

**Issue by kandari7** [OrchardCMS/OrchardCore#6590] opened 2020-07-05 20:00 UTC
I am getting this error "A field with the name: ContentType is already registered for GraphType: ContentType (Parameter 'Name')"

![image](https://user-images.githubusercontent.com/65922707/86541254-bc8e0600-bf4e-11ea-8f5d-e0c52e16cb40.png)

**Comment by infofromca** [comment] 2020-07-06 04:47
#6487

**Comment by kandari7** [comment] 2020-07-06 17:14
Same issue

**Comment by sebastienros** [comment] 2020-07-09 17:53
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5536

**Closed by sebastienros** 2020-07-09 17:53 UTC
Labels: GraphQL
