### ISSUE TITLE
Can we set Stereotype as a dropdown menu?

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#16005] opened 2024-05-07 16:31 UTC
### Is your feature request related to a problem? Please describe.

Now , the Stereotype is a text box, which is not user-friendly when making changes. 

For example, I can't always figure out if it's `UserCustomSettings` or `CustomUserSettings` 🤣

### Describe the solution you'd like

Maybe we have some way to get all the Stereotypes that are currently supported by the system, and then list them.

**Comment by Piedone** [comment] 2024-05-07 19:47
The issue is that stereotypes are by convention, and there's no list of the ones available currently. We could have a combobox suggesting the usual ones like you mention (or at least have them documented in a hint below it), but those values wouldn't always do anything.

**Comment by hishamco** [comment] 2024-05-07 21:08
I was thinking about that in the past, @Piedone even the are by convention we can populate the once that we use in the source and well documents, also we could add ability to register a new one

If this might be helpful which I think I can submit a PR

**Comment by hyzx86** [comment] 2024-05-08 04:23
@hishamco , Great this PR is also waiting for an autofill component interaction, I can copy your homework when you're done!🤣

https://github.com/OrchardCMS/OrchardCore/pull/15636

**Comment by sebastienros** [comment] 2024-05-09 17:37
We could have a list of string in a content manager options object where feature can add custom values for supported stereotypes. Maybe even a class with a translated description. Keep the textbox though, and some autocomplete for hints.

**Comment by hishamco** [comment] 2024-05-09 21:31
My idea is to add a textbox with autocomplete as Seb mentioned, I didn't think about translated description but it's good addition

**Comment by hyzx86** [comment] 2024-05-10 07:51
@hishamco 
How do you plan to implement this AutoComplete component? I'm in need of a similar UI component for another PR : https://github.com/OrchardCMS/OrchardCore/pull/15636 ，I know there are a lot of beautiful and powerful 3rd party UI components out there, but what are the requirements for us to introduce these front-end components?

@Skrypt Noticed you're doing a lot of VUE contributions, any plans to introduce a library of components like this?

Here's a low-code framework  from `baidu`. It uses json to build pages，
But it has a larger dependency package，It's really not cost-effective if we only use one of its autocomplete components

https://aisuda.bce.baidu.com/amis/zh-CN/components/form/input-text#%E8%87%AA%E5%8A%A8%E8%A1%A5%E5%85%A8

**Comment by hyzx86** [comment] 2024-05-10 07:58
Do we prefer bootstrap? 
https://getbootstrap.com/docs/5.3/forms/form-control/#datalists

**Comment by hishamco** [comment] 2024-05-10 12:10
Exactly, my aim is to use a textbox with autofill using datalist element

**Comment by hishamco** [comment] 2024-05-10 12:13
BTW @hyzx86 I noticed a draft PR, while I assigned this issue to me, so to save time and avoid duplicating the work if you want to handle this let me know so I can unassign myself from this issue

**Comment by hyzx86** [comment] 2024-05-10 12:14
@hishamco , I have created a PR at here #16005

**Comment by hishamco** [comment] 2024-05-10 12:21
You mean #106025, but I hope the second time you check if the issue is assigned by someone else or not to save time

**Comment by hyzx86** [comment] 2024-05-10 12:26
但是还没完成，关于如何添加模块中已定义的 Stereotype  ，我想听听你们的建议

I noticed that there is a default implementation here, but it's based on the types that have already been created, and the list is blank if it's a new tenant

https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.ContentTypes/Services/StereotypeService.cs

I plan to tweak this function to internally generate a HasSet to avoid duplicate values, and then add an implementation of IStereotypesProvider to a different module such as `CustomSettingsStereotypeProvider` , `CustomUserSettingsStereotypeProvider`. 

I'm just wondering if it's worth it. Why not use `IOptions` just to add a string?

@MikeAlhayek , I see that you added this feature.  Do you have a better suggestion about the realization of this?😊

**Closed** 2024-05-11 10:21 UTC
Labels: enhancement
