### ISSUE TITLE
The admin  menu manage page  cannot  be dragged

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#10642] opened 2021-11-05 16:40 UTC
![admin menu error](https://user-images.githubusercontent.com/15613121/140546612-c14d0884-eece-4b91-b3ab-65a7c02fd7ae.gif)

**Comment by hyzx86** [comment] 2021-11-05 16:43
![admin menu error2](https://user-images.githubusercontent.com/15613121/140546977-ef0d017e-5a0f-48c7-8bdf-6eb06e3f040d.gif)

**Comment by hishamco** [comment] 2021-11-05 18:01
Seems it's regression bug, @agriffard  @Skrypt any idea?

**Comment by Skrypt** [comment] 2021-11-05 19:57
I saw this in the Bootstrap 5 branch. I thought it was because of that. Now, it's a regression from an updated javascript dependency. I think it is JQuery UI.

**Comment by deanmarcussen** [comment] 2021-11-05 20:17
Should just switch it to use SortableJs - the underlying library the vue draggable uses. We use it in other places, it’s good and simple

**Comment by LunarChild** [comment] 2021-11-20 07:37
It seemed that the file:jquery-ui.js makes this trouble .but when I use the Nuget lib and publish a website this function work

**Comment by sebastienros** [comment] 2021-12-02 18:13
@deanmarcussen says we should try the new version of NestedSortable

**Comment by deanmarcussen** [comment] 2021-12-02 18:18
https://github.com/ilikenwf/nestedSortable

**Comment by scleaver** [comment] 2021-12-03 02:43
I was seeing this same in the site menu module... but seems to be fixed in the latest OC as of today - #10798 (this is the commit I am testing on) @Skrypt

**Comment by Skrypt** [comment] 2021-12-03 17:47
From looking at the repository @deanmarcussen linked and the file we have there is no update available on the component. We use the latest available. Which means it has not been updated since 2016.

**Comment by Skrypt** [comment] 2021-12-03 17:55
I think we need to either replace it with https://github.com/SortableJS/Sortable or revert the changes on the JQueryUI version update.

**Comment by Skrypt** [comment] 2021-12-03 18:02
Actually, now that I'm looking at the code there's not been any update on JQuery-UI for a while. So, it's just the nestedSortable.js component that doesn't work anymore with the latest browsers.

**Comment by deanmarcussen** [comment] 2021-12-03 18:16
I tried reverting jquery ui this morning with @scleaver and it worked (v 1.12 I think)

Might be best to revert in the short term

**Comment by Skrypt** [comment] 2021-12-03 18:18
ahh ! Now I see

![image](https://user-images.githubusercontent.com/3228637/144652917-b5b6a78e-dc20-4dfc-b9da-8e36524415b4.png)

**Comment by Skrypt** [comment] 2021-12-03 18:19
Ok I agree on the change just revert to JQuery-ui 1.12.1

**Comment by Skrypt** [comment] 2021-12-03 18:24
See #10804

**Closed** 2021-12-03 19:40 UTC
