### ISSUE TITLE
Table 'contentpickerfieldindex' doesn't exist while enabed `Include this element in the index` for content field.

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#5444] opened 2020-02-03 04:45 UTC
Hi, after I click 'Include this element in the index' for a content picker field, then click `Save Draft`, button, an exception occurred:

`MySqlException: Table 'lh_op.lh_contentpickerfieldindex' doesn't exist`

    MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in MySqlDataReader.cs
    MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary<string, CachedProcedure> cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlDataReader.cs
    MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList<IMySqlCommand> commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in CommandExecutor.cs
    MySql.Data.MySqlClient.MySqlCommand.ExecuteScalarAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlCommand.cs
    Dapper.SqlMapper.ExecuteScalarImplAsync<T>(IDbConnection cnn, CommandDefinition command) in SqlMapper.Async.cs
    YesSql.Commands.CreateIndexCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
    YesSql.Session.FlushAsync()
    YesSql.Session.CommitAsync()
    OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in ShellScope.cs
                    await callback(this);
    OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func<ShellScope, Task> execute) in ShellScope.cs
                    await BeforeDisposeAsync();
    OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in ModularTenantContainerMiddleware.cs
                    await shellScope.UsingAsync(scope => _next.Invoke(httpContext));

**Comment by Skrypt** [comment] 2020-02-03 04:54
Duplicate of #5443

**Closed by Skrypt** 2020-02-03 04:54 UTC
