### ISSUE TITLE
Part Validation in Admin Section can only happen once, subsequent submissions destroys the content item.

### ISSUE THREAD

**Issue by marlon-tucker** [OrchardCMS/OrchardCore#2337] opened 2018-09-05 14:48 UTC
Hi,

Using `1.0.0-beta3-68265`

This can be replicated by creating a new page, putting a form widget onto it without a title entered.

If you click publish a first time, an error correctly indicates the title part is missing a title. However, if you then click publish a second time without entering a title, the page *looks* like it has published, but if you go to edit it again, all the page contents have been wiped off of it. 

If the page has multiple widgets on it, this behavior is very destructive.

**Comment by psijkof** [comment] 2018-12-10 22:46
The difference I observe is that the first time the content item is published, the ModelState.IsValid == false.
On subsequent publish the contained contentitem (e.g. the form widget with validation errors) is not present any more. Not sure where it gets lost.

**Comment by matiasmolleja** [comment] 2018-12-15 11:02
I think this can  be the cause.
https://github.com/OrchardCMS/OrchardCore/blob/2e1ecd2997106da69a10baaf127733d20caaf055/src/OrchardCore.Modules/OrchardCore.Flows/Drivers/FlowPartDisplay.cs#L60


The code that sets to false the modelState.IsValid property is in TitlePartDisplayDriver.UpdateAsync() method.

This code is triggered by FlowPartDisplay.UpdateAsync(), that calls  "UpdateEditorPrefix" for each prefix in model.Prefixes.

The issue is that the first time you click submit, model.Prefixes is populated. So, it calls the titlepart drivers and modelstate.IsValid is set to false.

But the second time you click submit, model.Prefixes is empty. So the titlepart driver is not called, and modelState remains valid.

Just in case it helps someone with a better understanding of the flowpart @sebastienros  ? ;)

**Comment by sebastienros** [comment] 2018-12-18 02:12
Please test the PR but I am confident it's fixing everything. Here is how I found the problem: with a custom widget that had only a TitlePart (to fail the validation), which I add in a `Container` widget (Flow inside a Flow).

The first POST triggers these form values:

```
TitlePart.Title: Some title
AutoroutePart.Path: 
e30425f06a51a0e0600d03e520e7a260.TitlePart.Title: 
e30425f06a51a0e0600d03e520e7a260.ContentItem.Alignment: Justify
e30425f06a51a0e0600d03e520e7a260.ContentItem.Size: 100
208057f3121eeb9cb707554f0369fae6.FlowPart.Prefixes: e30425f06a51a0e0600d03e520e7a260
208057f3121eeb9cb707554f0369fae6.FlowPart.ContentTypes: WidgetitTitle
208057f3121eeb9cb707554f0369fae6.ContentItem.Alignment: Justify
208057f3121eeb9cb707554f0369fae6.ContentItem.Size: 100
FlowPart.Prefixes: 208057f3121eeb9cb707554f0369fae6
FlowPart.ContentTypes: Container
submit.Publish: submit.Publish
__RequestVerificationToken: CfDJ8I-PD9Qw0WlBpZGEQljcTr6l1aXxuEsGwqgVLZKjH-UL0s2iTQRfgFbV7h0O6uBKPGyjiezKGymMcJwtz_l3Mr90JBt5zE3HefglLDXk0CeMyTW4XkjPZz6mi4Rt_1xqUrysWKzOFAsXTJDdhHcOhtZIgSfkSsG5z6kUZfbn1f5ygLEVh8jhJ_1AbxcIiU2OJA
AutoroutePart.SetHomepage: false
AutoroutePart.SetHomepage: false
```

The second post triggers these ones:

```
TitlePart.Title: Some title
AutoroutePart.Path: 
76524cd5c2d3466b92f831c7f483699f.TitlePart.Title: 
76524cd5c2d3466b92f831c7f483699f.ContentItem.Alignment: Justify
76524cd5c2d3466b92f831c7f483699f.ContentItem.Size: 100
7fccbde74eb14659aa46ccc6858652aa.FlowPart.Prefixes: 76524cd5c2d3466b92f831c7f483699f
7fccbde74eb14659aa46ccc6858652aa.FlowPart.ContentTypes: WidgetitTitle
7fccbde74eb14659aa46ccc6858652aa.ContentItem.Alignment: Justify
7fccbde74eb14659aa46ccc6858652aa.ContentItem.Size: 100
208057f3121eeb9cb707554f0369fae6.FlowPart.Prefixes: 7fccbde74eb14659aa46ccc6858652aa
208057f3121eeb9cb707554f0369fae6.FlowPart.ContentTypes: Container
submit.Publish: submit.Publish
__RequestVerificationToken: CfDJ8I-PD9Qw0WlBpZGEQljcTr6KrfkpE1I8gAAMcz-KQRs9YG9YaGfn6elxbQTGRnOEHWj1vDsEuqJU-HOlggQnILr2ClddwEU7NCgivsPMBXxT3wQwlYU9lVxiKntA0K32dpMhas-0lX6UKTFJUUyHdn4C6U4ej40sTImHYb5tPyjchuiM1xjeUC8UISP0zML3zQ
AutoroutePart.SetHomepage: false
AutoroutePart.SetHomepage: false
```

We can see that the first values contain `FlowPart.Prefixes` but the second on doesn't. The first one is correct because it will target the top level FlowPart, so it has no prefix. The second set of values is missing the `FlowPart.Prefixes` element, but it's actually setting `208057f3121eeb9cb707554f0369fae6.FlowPart.Prefixes` instead. And looking at the Guid, it's the same as the last one in the first set of values. This means a Guid has leaked, or in this case a Prefix.

The issue was that when an editor is rendered, we assign it a unique Prefix such that we can group all form elements by Part. And this Prefix is a single variable in the `ViewContext` that mutates during the rendering. The symptom was that it was not correctly re-initialized to `""` before rendering the main `FlowPart`. I fixed it by always restoring the previous Prefix after it was changed.

/cc @jtkech because we have a related change in another PR.

**Closed** 2018-12-18 07:00 UTC
Labels: P0, bug
