### ISSUE TITLE
Workflow delete lock

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3028] opened 2019-01-16 08:10 UTC
Hi,

I have a issue on workflow list page when I whant to delete a element. The delete operation is locked by a previous read query that did not terminate.

The SQL Session 59 & 60 appears when showing the page but never terminate.  

![image](https://user-images.githubusercontent.com/6775094/51234798-14f1d200-196e-11e9-86c7-fa5c94bd7e77.png)

![image](https://user-images.githubusercontent.com/6775094/51234837-3f438f80-196e-11e9-9582-f8b60763dd7c.png)

![image](https://user-images.githubusercontent.com/6775094/51234725-dfe57f80-196d-11e9-9583-a888232cf237.png)

59 : 
```
<?query --
(@p0 nvarchar(4000))SELECT TOP 1 [Document].* FROM [Document] INNER JOIN [WorkflowTypeIndex] ON [WorkflowTypeIndex].[DocumentId] = [Document].[Id]  WHERE ([WorkflowTypeIndex].[WorkflowTypeId] = @p0)
--?>
```
60:
```
<?query --
(@p0 nvarchar(4000))SELECT count(*) FROM [WorkflowIndex] WHERE ([WorkflowIndex].[WorkflowTypeId] = @p0)
--?>
```
66:
```
<?query --
delete from [WorkflowIndex] where [DocumentId] = @Id
--?>
```

**Comment by sebastienros** [comment] 2019-01-16 17:57
Can you check we have an index on `WorkflowTypeId`? If not create one and see if you can repro.
Also I think we should not rely on count(*) if it's here to page workflows.
Maybe we should use a WITH NOLOCK on these queries.

**Comment by jpiquot** [comment] 2019-01-17 07:16
I don't think the issue comes from the lines 2 & 3 but from the first.

The screenshot shows active queries. The first query should be so fast that I should never se it in the list.

As you can see below I have the query active even before deleting, just after displaying the workflow list.

It looks like the code sends the query but does not respond when the result comes back, so SQL Server waits and does not release locks.

![image](https://user-images.githubusercontent.com/6775094/51301234-c22c1f00-1a2e-11e9-852e-a32a5bd74004.png)

**Comment by Skrypt** [comment] 2019-01-17 14:22
We faced having the same issue in O1 and the solution was to use WITH NOLOCK on queries. This is a known bug with all ORM's and SQL Server.

**Comment by sebastienros** [comment] 2019-01-17 20:27
@jpiquot do you know if there is a way to reproduce it easily? Like just deleting a workflow on SQL Server?

**Comment by jpiquot** [comment] 2019-01-18 16:24
I will try to isolate my workflow activities in a small test project to be able to reproduce it systematically.

**Comment by sebastienros** [comment] 2019-01-18 17:33
I think the best way to code a repro would be to create a custom action in one of the controllers that would do some code. We would then just copy this action and send a request to it. You could do whatever you want inside this method as long as it triggers it.

**Comment by jpiquot** [comment] 2019-01-19 11:33
I think the issue comes when showing workflow list page while a workflow activity is running.

**Comment by jpiquot** [comment] 2019-01-19 17:15
I verified the sql query is started when the workflow activity is started and ends when the workflow ends.
It seems like pessimistic locking is used. The read locks any delete or update until the YesSQL session is closed.
Maybe using optimistic lock with a RowVersion field in table to do an optimistic concurrency check, would avoid issues like mine or the one reported by @Skrypt ? OCC is also best for performances.

**Comment by sebastienros** [comment] 2019-01-19 18:17
I think the issue is that the session (and a transaction) is live during the time of the request, which is also the boundary of the workflow execution in this case. If the workflow is long, then the lock is kept, and other requests might be locked. I would suggest two things:
- Don't hold the session for long requests, and prefer short lived sessions. In this case the workflow module should not resolve an `ISession` because it will get the request ambient one, but resolve the `IStore` and create/dispose sessions as necessary, like to read a workflow, then to write its state when it's done.
- Another option would be to use NO LOCK statements in yessql through an option in `ISession` but that will require changes in YesSql.

I don't think the issue is about optimistic vs pessimistic concurrency, we are not trying to detect changes on rows to prevent conflict, the issue is a locking issue at the db layer.

If you are able to repro by listing the workflow while one is running, it means that the workflow itself is very long, and not paused between tasks. Could you provide a repro for that?
You can also try to change the workflow module to use local sessions using `IStore` as I explained earlier, as it should just be necessary for loading and saving a workflow instance. Each task might itself have to use the ambient session, but these should not be long either or do the same thing.

**Comment by sebastienros** [comment] 2019-01-24 20:35
Let me repeat that: optimistic or pessimistic concurrency is a different concern than SQL Server table locking (see NO LOCK). They are applied independently. The database itself is able to lock records or tables. Your code handles concurrency at a higher level (either p or o).

The issue here is at the low level of things, and we might need to use "no lock" select clauses. Looking at your code I can see parallel execution of a service, maybe that triggers the issue, because of the low level locking. Try to use "no lock" statements in your EF queries, if possible.

**Comment by jpiquot** [comment] 2019-01-26 10:11
I don't have any locking issues on EF side.

I an another workflow activity, I want to create a read model on OrchardCore (YesSQL) using content items. Data comes from a relational database that contains 500.000 inventory items.

If I understand, I can't use a scoped IContentManager in my threads as it has an injected ISession.  I need to write a new ContentManager that injects IStore to be able to do multi-threading.

**Comment by jpiquot** [comment] 2019-01-26 13:19
Hi,

I tried to create a new session but I have also blocking on Id allocation.

```
       public static async Task<IResult> InsertOrUpdate(int[] itemIds, IServiceProvider serviceProvider, CancellationToken cancellationToken)
        {
            try
            {
                using (IServiceScope scope = serviceProvider.CreateScope())
                {
                    IServiceProvider services = scope.ServiceProvider;
                    IStore store = services.GetRequiredService<IStore>();
                    store.Configuration.SessionPoolSize=64;
                    IContentManager contentManager = new DefaultContentManager(
                            services.GetRequiredService<IContentDefinitionManager>(),
                            services.GetServices<IContentHandler>(),
                            store.CreateSession(System.Data.IsolationLevel.ReadUncommitted),
                            services.GetRequiredService<IContentItemIdGenerator>(),
                            services.GetRequiredService<ILogger<DefaultContentManager>>());
                    IInventoryItemService inventoryItemService = services.GetRequiredService<IInventoryItemService>();
                    InventoryItem[] items = ((IEnumerable<InventoryItem>)await inventoryItemService.GetAsync(itemIds, 0, cancellationToken)).ToArray();
                    foreach (InventoryItem item in items)
                    {
                        IResult result = await InsertOrUpdate(item, contentManager, cancellationToken);
                        if (result.HasFailed)
                        {
                            return result;
                        }
                    }
                    return Result.Ok();
                }
            }
            catch (Exception e)
            {
                return Result.Failed(e);
            }
        }
```

<?query --
UPDATE [Identifiers] SET [nextval]=@new WHERE [nextval] = @previous AND [dimension] = @dimension
--?>
LOCKED BY
<?query --
(@p0 nvarchar(4000),@p1 bit)SELECT TOP 1 [Document].* FROM [Document] INNER JOIN [ContentItemIndex] ON [ContentItemIndex].[DocumentId] = [Document].[Id]  WHERE (([ContentItemIndex].[ContentItemId] = @p0) and ([ContentItemIndex].[Published] = @p1))
--?>

**Comment by Skrypt** [comment] 2019-01-26 13:58
You're looking in the wrong app Layer. If something could be fixed it would be in YesSQL.

**Comment by jtkech** [comment] 2019-01-26 17:10
Just for infos, normally when creating a child scope a new `ISession` instance is automatically created through the DI.

**Comment by jpiquot** [comment] 2019-01-26 17:51
@Skrypt : Yes it's a locking issue in YesSQL but I had to try to turn around it.

@jtkech : Even creating a spécific scope I have locking issues. In the code below the mono-thread foreach works, but not the multi-thread loop. I also tried to do a CommitAsync after each write buit without any success. I think that the bottleneck maybe the Id generator.


```

using System;
using System.Collections.Async;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Framework.ContentManagement;
using Framework.Infrastructure;
using Inventory;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using OrchardCore.ContentManagement;
using OrchardCore.ContentManagement.Handlers;
using OrchardCore.ContentManagement.Metadata;
using OrchardCore.Title.Model;
using OrchardCore.Workflows.Abstractions.Models;
using OrchardCore.Workflows.Activities;
using OrchardCore.Workflows.Models;
using YesSql;

namespace Tyndareus.Livres
{
    public class InventoryItemContentItemExecuteTask : TaskActivity
    {
        private readonly IApplicationLifetime _appLifetime;
        private IServiceProvider _serviceProvider;
        private readonly IInventoryItemService _itemService;
        private readonly IStore _store;

        public InventoryItemContentItemExecuteTask(
            IApplicationLifetime appLifetime,
            IServiceProvider serviceProvider,
            IInventoryItemService itemService,
            IStore store,
            IStringLocalizer<InventoryItemContentItemExecuteTask> stringLocalizer,
            IHtmlLocalizer<InventoryItemContentItemExecuteTask> htmlLocalizer)
        {
            _appLifetime = appLifetime;
            _serviceProvider = serviceProvider;
            _itemService = itemService;
            _store = store;
            T = stringLocalizer;
            H = htmlLocalizer;
        }

        public override LocalizedString Category => T[nameof(ExtenFlow)];

        public override string Name => nameof(InventoryItemContentItemExecuteTask);

        public int NumberThreads
        {
            get => GetProperty(() => 64);
            set => SetProperty(value);
        }

        public override async Task<ActivityExecutionResult> ExecuteAsync(
            WorkflowExecutionContext workflowContext, ActivityContext activityContext)
        {
            try
            {
                CancellationToken cancellationToken = _appLifetime.ApplicationStopping;
                int page = 0;
                int pageSize = 500;
                int[] itemIds = await _itemService.GetIdsAsync(cancellationToken);
                var pages = new List<int[]>((itemIds.Length / pageSize) + 1);
                var results = new ConcurrentBag<IResult>();

                do
                {
                    int[] pagedItemIds = ((page == 0) ? itemIds : itemIds.Skip(page * pageSize)).Take(500).ToArray();
                    if (pagedItemIds == null || pagedItemIds.Length == 0)
                    {
                        break;
                    }

                    page++;
                    pages.Add(pagedItemIds);
                }
                while (true);

                _store.Configuration.SessionPoolSize = Math.Min(NumberThreads, page);

                //await pages.ParallelForEachAsync(async ids =>
                //    {
                //        results.Add(await InsertOrUpdate(ids, _serviceProvider, cancellationToken));
                //    },
                //    NumberThreads,
                //    default);

                pages.ForEach(ids =>
                    {
                        results.Add(InsertOrUpdate(ids, _serviceProvider, cancellationToken).Result);
                    });

                if (results.Any(p => p.HasFailed))
                {
                    workflowContext.Workflow.FaultMessage = JsonConvert.SerializeObject(
                        results.Where(p => p.HasFailed).Select(p => p.ApplicationError.LogText()));
                    workflowContext.Workflow.Status = WorkflowStatus.Faulted;
                    return Outcomes("Failed");
                }

                return Outcomes("Done");
            }
            catch (Exception e)
            {
                workflowContext.Workflow.FaultMessage = e.FullMessage();
                workflowContext.Workflow.Status = WorkflowStatus.Faulted;
                return Outcomes("Failed");
            }
        }

        public static async Task<IResult> InsertOrUpdate(InventoryItem item, IContentManager contentManager, CancellationToken cancellationToken)
        {
            ContentItem contentItem =
                await contentManager.GetAsync(LivresConstants.ArticleLivreContentTypeName + "-" + item.Id);
            bool created = false;
            if (contentItem == null)
            {
                contentItem = await contentManager.NewAsync(LivresConstants.ArticleLivreContentTypeName);
                contentItem.ContentItemId = LivresConstants.ArticleLivreContentTypeName + "-" + item.Id;
                created = true;
            }

            UpdateContent(item, contentItem);
            if (created)
            {
                await contentManager.CreateAsync(contentItem, VersionOptions.Published);
            }
            else
            {
                await contentManager.UpdateAsync(contentItem);
            }

            return Result.Ok();
        }

        public static async Task<IResult> InsertOrUpdate(int[] itemIds, IServiceProvider serviceProvider, CancellationToken cancellationToken)
        {
            try
            {
                using (IServiceScope scope = serviceProvider.CreateScope())
                {
                    IServiceProvider services = scope.ServiceProvider;
                    IStore store = services.GetRequiredService<IStore>();
                    using (ISession session = store.CreateSession(System.Data.IsolationLevel.ReadUncommitted))
                    {
                        IContentManager contentManager = new DefaultContentManager(
                                services.GetRequiredService<IContentDefinitionManager>(),
                                services.GetServices<IContentHandler>(),
                                session,
                                services.GetRequiredService<IContentItemIdGenerator>(),
                                services.GetRequiredService<ILogger<DefaultContentManager>>());
                        IInventoryItemService inventoryItemService = services.GetRequiredService<IInventoryItemService>();
                        InventoryItem[] items = ((IEnumerable<InventoryItem>)await inventoryItemService.GetAsync(itemIds, 0, cancellationToken)).ToArray();
                        foreach (InventoryItem item in items)
                        {
                            IResult result = await InsertOrUpdate(item, contentManager, cancellationToken);
                            if (result.HasFailed)
                            {
                                return result;
                            }
                        }
                    }
                    return Result.Ok();
                }
            }
            catch (Exception e)
            {
                return Result.Failed(e);
            }
        }


        public static void UpdateContent(InventoryItem item, ContentItem contentItem)
        {
            contentItem.DisplayText = item.Name;
            if (!string.IsNullOrWhiteSpace(item.Alias))
            {
                contentItem.DisplayText += "-" + item.Alias;
            }

            contentItem.ModifiedUtc = item.ModifiedDateTime?.UtcDateTime;
            contentItem.PublishedUtc = item.ModifiedDateTime == null
                                           ? item.CreatedDateTime.UtcDateTime
                                           : item.ModifiedDateTime.Value.UtcDateTime;
            contentItem.CreatedUtc = item.CreatedDateTime.UtcDateTime;
            contentItem.Owner = string.IsNullOrWhiteSpace(item.ModifiedById)
                                    ? item.CreatedById
                                    : item.ModifiedById;
            contentItem.Author = item.CreatedById;

            TitlePart titlePart = contentItem.GetOrCreate<TitlePart>();
            titlePart.Title = contentItem.DisplayText;
            contentItem.Apply(titlePart);
            DataObjectPart doPart = contentItem.GetOrCreate<DataObjectPart>();
            doPart.Id = item.Id;
            doPart.CreatedById = item.CreatedById;
            doPart.CreatedDateTime = item.CreatedDateTime;
            doPart.ModifiedById = item.ModifiedById;
            doPart.ModifiedDateTime = item.ModifiedDateTime;
            doPart.RowVersion = item.RowVersion;
            contentItem.Apply(doPart);
            DataEntityPart dePart = contentItem.GetOrCreate<DataEntityPart>();
            dePart.Code = item.Code;
            dePart.Alias = item.Alias;
            dePart.Name = item.Name;
            dePart.ShortName = item.ShortName;
            dePart.Description = item.Description;
            contentItem.Apply(dePart);
            InventoryItemPart iiPart = contentItem.GetOrCreate<InventoryItemPart>();
            iiPart.BrandId = item.BrandId;
            iiPart.CategoryId = item.CategoryId;
            iiPart.DefaultBarcodeId = item.DefaultBarcodeId;
            iiPart.InventoryItemStatusId = item.InventoryItemStatusId;
            iiPart.ItemGroupId = item.ItemGroupId;
            iiPart.Price = item.Price;
            iiPart.ProductLineId = item.ProductLineId;
            iiPart.PurchaseAvailabilityDate = item.PurchaseAvailabilityDate;
            iiPart.PurchasePrice = item.PurchasePrice;
            iiPart.PurchaseUnitId = item.PurchaseUnitId;
            iiPart.SalesAvailabilityDate = item.SalesAvailabilityDate;
            iiPart.SalesPrice = item.SalesPrice;
            iiPart.SalesUnitId = item.UnitId;
            iiPart.VATGroupId = item.VATGroupId;
            contentItem.Apply(iiPart);
            ArticleLivrePart alPart = contentItem.GetOrCreate<ArticleLivrePart>();

            contentItem.Apply(alPart);
        }

        public override IEnumerable<Outcome> GetPossibleOutcomes(WorkflowExecutionContext workflowContext,
                                                                 ActivityContext activityContext)
            => new List<Outcome> { new Outcome(T["Done"]), new Outcome(T["Failed"]) };
#pragma warning disable IDE1006 // Naming Styles


        private readonly IHtmlLocalizer H;
        private readonly IStringLocalizer T;
#pragma warning restore IDE1006 // Naming Styles
    }
}
```

**Comment by jpiquot** [comment] 2019-01-26 18:04
@jtkech, Finally I see I have the same issue with mono-threaded version. The conflict is also between the Session used by the Workflow manager and mine.

![image](https://user-images.githubusercontent.com/6775094/51791000-0f319300-219d-11e9-849c-4b6a7a615f7a.png)

**Comment by jpiquot** [comment] 2019-01-26 19:21
In the YesSQL LinearBlockIdGenerator/LeaseRange method, I don't see the Commit. It's done elsewhere? 

```
...
                    updateCommand.Transaction = transaction;
                    affectedRows = updateCommand.ExecuteNonQuery();
                    if (retries++ > MaxRetries)
                    {
                        throw new Exception("Too many retries while trying to lease a range for: " + dimension);
                    }
                } while (affectedRows == 0);
                _increment = -1; // Start with -1 as it will be incremented
                _start = nextval;
                _end = nextval + _range - 1;
            }
        }
```

**Comment by sebastienros** [comment] 2019-01-26 19:51
We need an app that uses yessql only, with parallel calls that show how the lock happens. I will try to make one. Can be a console app, ever better would be a unit test in yessql using two threads and a lock to trigger this exact situation.

**Comment by sebastienros** [comment] 2019-01-26 20:03
You might be on something with the id generation, I will try to focus on this path.

**Comment by jpiquot** [comment] 2019-01-26 20:57
If I inject contentManager in the activity, it will have the same session as the workflow manager. In that case it works (but // not possible). It looks like the session holds a transaction on the data.

Maybe doing id allocation in a separate session with a very short transaction would be more robust. A user session can't hold locks on this table and freeze the system.

In ERP like Microsoft Dynamics AX, the Id allocation is always done in a isolated session. In this way Id allocation lifetime is short and transactions rollbacked do not rollback Id allocation (use full when wanting to recycle ids in continuous sequences).

**Comment by jpiquot** [comment] 2019-01-27 12:03
It dont understand why I have these queries 1500 times per minute. 

![image](https://user-images.githubusercontent.com/6775094/51800727-c37df880-2233-11e9-8d14-b90555a110b9.png)

**Comment by sebastienros** [comment] 2019-01-27 20:16
I have been able to replicate the issue in yessql and think I have fixed it. As you noted the id generation was using the same transaction as the ambient session. Now I am ensuring id generation gets its own transaction and is committed independently to it doesn't block any other session.

https://github.com/sebastienros/yessql/pull/149

**Comment by jpiquot** [comment] 2019-01-28 07:09
Thanks a lot! This was a quite difficult issue to turns around.

**Comment by sebastienros** [comment] 2019-01-28 18:23
The fix is actually breaking SQLite, so I will add a version of id generation that does rely on database queries for SQlite.

**Comment by sebastienros** [comment] 2019-01-30 19:53
Can you check that it's fixed with the latest dev branch (or when the packages are available)?

**Closed** 2019-01-30 19:52 UTC

**Comment by jpiquot** [comment] 2019-02-02 13:36
Yes it's much better now but I have deadlocks. Issue #3130
