### ISSUE TITLE
Orchard setup in an AKS pod

### ISSUE THREAD

**Issue by luis3199correia** [OrchardCMS/OrchardCore#9499] opened 2021-05-20 08:51 UTC
When I'm doing the setup in an AKS pod, I'm getting a 503 bad gateway(nginx), and I think this is a problem in my pod. So, I need to know the needed settings to my pod to not to get this error again.
AKS v1.18.14
nginx v1.19.6

**Comment by Skrypt** [comment] 2021-05-20 11:29
Not an Orchard Core bug. It's an AKS specific issue. Don't open duplicates please.

Duplicate of https://github.com/OrchardCMS/OrchardCore/discussions/9484

**Comment by luis3199correia** [comment] 2021-05-20 12:11
> Not an Orchard Core bug. It's an AKS specific issue. Don't open duplicates please.
> 
> Duplicate of #9484

I agree, and I apologize for the duplicate ticket. But this is a critical issue, and I need to know, on Orchard’s side, what settings the pod must have in order for there to be no such issues. I looked in the documentation and didn't find any information about deploying Orchard in AKS pod.

**Comment by Skrypt** [comment] 2021-05-20 13:08
Your AKS pod is like a Docker Swarm distribution which will require to contain at least one instance of each services required to run Orchard Core. So namely, a Database provider like SQL Server, MySQL, PostgreSQL and an Orchard Core website. You could also use SQLite which would remove the need of a container for your database provider.

That said, the Orchard Core container will need to expose it's port 80 to be served publicly and it will need to execute Orchard Core on startup. You can see what we do here by looking at the source code Dockerfile.

https://github.com/OrchardCMS/OrchardCore/blob/aa8443612b931db1ed272f7657f650db02fd20e7/Dockerfile#L10-L15

**Closed** 2021-05-20 14:26 UTC
Labels: bug

**Comment by jptissot** [comment] 2021-05-20 15:23
We have an open source helm chart that hosts OC with a Postgresql db as well here: https://github.com/StatCan/charts/tree/master/stable/orchard-cms
