### ISSUE TITLE
What could cause two active (latest, published) versions of contentItem?

### ISSUE THREAD

**Issue by tropcicstefan** [OrchardCMS/OrchardCore#8900] opened 2021-03-18 10:33 UTC
Occasionally in production environment some versionable item has two active version, for no reason known to me. 
There are two entries in Document table both having Latest and Published on true. Two entries in ContentItemIndex table, same thing. And because they have aliasPart, both entries in AliasPartIndex table.

UI then lists both of them and deleting deactivates all active versions.
In result content picker field in graphql cannot resolve that situation and causes error.

Orchard and Sql server logs are empty.

So my question is what could cause that issue?

**Comment by deanmarcussen** [comment] 2021-03-18 10:59
Yes, I've seen this happen before.

I would ask you to check though, do they have different `ContentItemVersionId`'s ?

Once it is in this state, the only thing you can do is fix the documents, and unfortunately all the indexes.

In my experience I think this is caused by concurrency related issues. Either
- double click on the Publish button really quick
- two users publishing the same content item, at around the same time.

We do need to fix this (both bits, and figure out if there are other other circumstances that could cause it).

Part of the problem however is that because they're creating a new content item document, i.e. a new version, any YesSql concurrency checking is useless, because from it's point of view the are two different documents.

So we do have already have an issue to prevent the double click thing. That's a good and easy thing to resolve.

And we would have to look at the concurrency, I think inside the content manager. With a final query to see if another version has been created, in another session, and throwing our own concurrency exception.

just a few ideas on the why's and how's of it all.

@tropcicstefan testing and proving some of my assumptions here, about what's causing it, and reporting back would be really helpful, so we can look at fixing all the possible scenarios where it can happen.

**Comment by tropcicstefan** [comment] 2021-03-18 11:39
1) They have different ContentItemVersionId.
2) "two users publishing the same content item, at around the same time" - had this issue with taxonomy field that was used as tags, in the end we removed that field, and use custom tags implementation. But with latest occurrence that isn't possible because this contentItem has custom LockingPart that prevents two different users from editing.
3) And something that caught my eye this is excerpt from ContentItemIndex
```
|   Id  | DocumentId |   ContentItemId	          |  ContentItemVersionId      | Latest | Published | ContentType |ModifiedUtc              | PublishedUtc            | CreatedUtc              | Owner                      | Author  | DisplayText                    |
|-------|------------|----------------------------|----------------------------|--------|-----------|-------------|-------------------------|-------------------------|-------------------------|----------------------------|---------|--------------------------------|
|826778 | 1126545    | 4f6j55mx2ye4g2cxs28r49z7nd | 4vcsq32qnxp6y5f93hdf079cc3 | 0      | 0         | Article     | 2021-03-18 07:48:46.647 | 2021-03-18 07:48:47.417 | 2021-03-18 06:26:49.220 | 4mt1y2jn4ev5h14cn6vpykw153 | smrdjen | Koronavirus - najnoviji podaci |
|826797 | 1126536    | 4f6j55mx2ye4g2cxs28r49z7nd | 44p4erv1k9edeyan37wz3k545t | 0      | 0         | Article     | 2021-03-18 07:48:06.533 | 2021-03-18 07:48:07.457 | 2021-03-18 06:26:49.220 | 4mt1y2jn4ev5h14cn6vpykw153 | smrdjen | Koronavirus - najnoviji podaci |
|826813 | 1126654    | 4f6j55mx2ye4g2cxs28r49z7nd | 4tgck7dgd9yw777jrtcq51jh4k | 0      | 0         | Article     | 2021-03-18 07:55:15.970 | 2021-03-18 07:55:16.570 | 2021-03-18 06:26:49.220 | 4mt1y2jn4ev5h14cn6vpykw153 | smrdjen | Koronavirus - najnoviji podaci |
```
So at the moment of my intervention DocumentId 1126545 and 1126654 were active versions(those ids occurred in other index tables). This select is made after my intervention and for some reason there is another entry between them (I am not sure how and why, but first select before intervening didn't return that ordering) with Id higher than first item. I cannot verify that entry ID 826797  was there first time

**Comment by deanmarcussen** [comment] 2021-03-18 14:01
I am confused?

What is the intervention are you making?

**Comment by Skrypt** [comment] 2021-03-18 14:02
Latest = 0 and Published = 0 means the item is "soft deleted". Though the 2 first items got update pretty much at the same time.

**Comment by tropcicstefan** [comment] 2021-03-18 15:14
> I am confused?
> 
> What is the intervention are you making?

when I say intervention I mean fixing indices and document entry

**Comment by jtkech** [comment] 2021-03-18 17:48
Yes, the existing concurrency checking option of YesSql may help when mutating the same record version, e.g. when concurrent processes are updating the existing active versions e.g. while publishing, but anyway we don't use this option for `ContentItem`, only for some other documents.

Then yes, when 2 concurrent processes hold e.g. its own new draft version and then save it, YesSql see them as 2 different entities. Here we would need a lock based on the `ContentItemId` when updating, a local lock that becomes a distributed lock if e.g. `RedisLock` is enabled, as we now do when activating a shell.

**Comment by Piedone** [comment] 2021-03-23 00:03
The "two users editing and publishing a content item at the same time" is an amusing one I've seen happening, and an issue even if it doesn't end up causing data inconsistencies. We can lock on content items to prevent inconsistencies (thinking also if not people are saving the items but they're written via a web API or even `IContentManager`) but If two people open the same content item and they save independently of each other, what should happen? One of their changes will get overwritten.

- [Basecamp's](https://basecamp.com/) solution is very simple (the UX): If someone else opened the item for editing then you'll get a message around the lines of "XY is editing this. You can ask them to close it or you can open it for editing too but then you'll overwrite what they're writing." I'd do this.
- Concurrent editing like in Word online or Confluence. This would be a massive feature of course and perhaps only useful if you're using OC as a wiki or document management engine.

Not entirely this issue but related still.

**Comment by deanmarcussen** [comment] 2021-04-01 13:30
@tropcicstefan 

I still haven't got a good repro from you, on how you are creating this error?

I see in your original, you thought you were making them from double clicking the save button, but then maybe, that isn't how you are creating them?

Quite hard to try and repro without some steps to follow.

**Comment by tropcicstefan** [comment] 2021-04-01 14:00
I reproduced it locally by double clicking. But it can occur on double user saving also

**Comment by deanmarcussen** [comment] 2021-04-01 14:26
Ok. thank you.

We have an issue here to disable the save button(s) on click

https://github.com/OrchardCMS/OrchardCore/issues/4227

That seems like a simple option to implement, and will help prevent some scenarios.

We will probably want to look at concurrency as well, but the implementation would have to be different, and is somewhat more complicated.

**Comment by tropcicstefan** [comment] 2021-04-01 14:50
We have overridden buttons shapes and blocked double click with some js, but maybe actionfilters with verification token is way to go.

**Comment by sebastienros** [comment] 2021-04-01 17:17
We have that feature in O1 and it's automatically applied to all buttons that are converted to a POST. We should do it too, it will be much simpler than trying to handle it server-side.

**Comment by Skrypt** [comment] 2021-04-01 21:16
Here it is from 01 : 

```javascript
    //Prevent multi submissions on forms
    $("body").on("submit", "form.no-multisubmit", function (e) {
        var submittingClass = "submitting";
        form = $(this);

        if (form.hasClass(submittingClass)) {
            e.preventDefault();
            return;
        }

        form.addClass(submittingClass);

        // safety-nest in case the form didn't refresh the page
        setTimeout(function () {
            form.removeClass(submittingClass);
        }, 5000);
    });
```

**Comment by Piedone** [comment] 2021-04-25 22:52
Related: https://github.com/OrchardCMS/OrchardCore/issues/4540

**Closed** 2021-06-18 15:37 UTC
Labels: bug
