### ISSUE TITLE
Import the package with deployment plan exported duplicates them

### ISSUE THREAD

**Issue by artemsv** [OrchardCMS/OrchardCore#5370] opened 2020-01-25 23:48 UTC
The deployment plan is not updated but duplicated it contains in the package to import

![image](https://user-images.githubusercontent.com/1922262/73128829-7cf9e000-3fe6-11ea-95a2-a37f81c5a7ee.png)

**Comment by agriffard** [comment] 2020-01-26 14:11
Duplicate of #1970

**Closed by agriffard** 2020-01-26 14:11 UTC

**Comment by artemsv** [comment] 2020-01-26 14:41
Merci, excuse moi, n'a pas regarde
