### ISSUE TITLE
ImageSharp/Liquid missing String.Empty check

### ISSUE THREAD

**Issue by Skrypt** [OrchardCMS/OrchardCore#3842] opened 2019-06-20 22:42 UTC
I need to work on repro's but here is one issue I get often in my logs : 

```
2019-06-20 20:38:43.2141|Default|80004970-0000-d500-b63f-84710c7967bb||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.Collections.Generic.KeyNotFoundException: The given key '' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.ToImageFilePath(String path, ImageMetaData& metaData)
   at SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.GetAsync(String key)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.ToImageFilePath(String path, ImageMetaData& metaData)
   at SixLabors.ImageSharp.Web.Caching.PhysicalFileSystemCache.GetAsync(String key)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
```

I assume that sometimes the image path returned is a String.Empty. I know I should probably add the check in my Liquid template. Though, still, it should never throw if we pass a String.Empty as a path when using the Asset_Url filter.

**Comment by deanmarcussen** [comment] 2019-06-21 17:16
I try to repro this with an empty image path from a liquid filter but I can't get the same error.

The `MediaFileProvider.IsValidRequest` always invalidates it (for me) which stops ImageSharp processing before it gets to the `PhysicalFileSystemCache.GetAsync` method.

I can reproduce this in the logs
`SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware|ERROR|The image 'https://localhost:44300/agency1/media/.jpg?&width=480&height=480&rmode=stretch' could not be resolved `

but the ImageSharp code comment says, log this as an error, but let aspnet actually handle the error, and it does, giving a 404 back.

Be great to know what the url that is causing it looks like - must be there something in the `ImageSharp.FormatUtilities.GetExtensionFromUri()` that is letting the url through

**Comment by sebastienros** [comment] 2019-07-04 19:24
No repro, closing, until someone else can repro

**Closed by sebastienros** 2019-07-04 19:24 UTC
