### ISSUE TITLE
Localization: Translations Portuguese "pt-PT" not working.

### ISSUE THREAD

**Issue by XpandIT-RFID** [OrchardCMS/OrchardCore#10150] opened 2021-08-20 13:14 UTC
Hi, I am currently trying to use the "pt-PT" translation from the crowdin but they don't seems to work, but when I try the Brazilian ones "pt-BR" or "fr" they work.

How I am testing:
- Added the "pt" and "pt-BR" folder to my root project in the Localization Folder
- Enabled "Localization" Feature
- Add "?culture=pt" to the Url. (None of the translations in the .po files work)
- Change to "?culture=pt-PT" (Still doesn't work)
- Change to "?culture=pt-BR" (Works)

Also tested with "fr" and worked. There seems to be a problem with the "pt / pt-PT" translations.
![image](https://user-images.githubusercontent.com/83280308/130238572-823d75bc-2c0e-4796-abb5-c9a4fc82f821.png)

cc: @deanmarcussen  / @Skrypt 

Can anyone else test this? I am currently working on a project that needs pt-PT translations working.

Cheers

**Comment by hishamco** [comment] 2021-08-20 15:32
Did you added 'pt-PT` as a supported culture from Admin/Cultures?

**Comment by XpandIT-RFID** [comment] 2021-08-20 15:34
> Did you added 'pt-PT` as a supported culture from Admin/Cultures?

Yeah, still makes no difference since I could do pt-BR without adding it to the supported cultures using the query string "?culture=pt-BR"

**Comment by hishamco** [comment] 2021-08-20 17:24
Ya it should work if you add the queystring. I presume the `pt-PT` should fallback to `pt`. Could you please share a minimal repo so I can figure out what's going on? Before that let us know what version are you using?

**Comment by sebastienros** [comment] 2021-09-02 17:36
Assuming `pt-PT` falls back to `pt` as expected, it might be that the `pt` language is not fully translated:

![image](https://user-images.githubusercontent.com/1165805/131889533-49d171a4-dd77-43a5-a6ab-7c55be57dd5a.png)

This would explain why it "seems" to work with BR and not PT. Otherwise can you be more precise about what "doesn't work" is it all in English still, or only a few strings are in Portuguese? Can you check with a screen that is translated in pt directly?

However I can see that `pt` is almost fully translated for the Setup screen though nothing is displayed. So an issue might be that we are not linking to the `pt` translation file. Can you try to add a custom reference to the `pt` nuget package?

```
<PackageReference Include="OrchardCore.Translations.pt" Version="1.0.0" />
```

...

and after looking at the nuget packages, I confirm that we did forgot to reference the pt package:

https://www.nuget.org/packages/OrchardCore.Translations.All/

**Comment by hishamco** [comment] 2021-09-02 19:53
@XpandIT-RFID this by design, we exclude the Portugese from all cultures package (which is referenced by default in OC) beacuse there was less 50% translations at the time of we publish the meta package,

For now you can reference the `OrchardCore.Translations.pt` package as Seb said

**Comment by sebastienros** [comment] 2021-09-02 20:52
Maybe we should include parent cultures if we include a child one. The child might contains a superset of the parent one.

**Comment by hishamco** [comment] 2021-09-02 20:55
I was thinking about that, but the issue is, if the culture doesn't have transaltions or have few, the expectation from customer perspective may different because they don't it's a lack of the translation itself not in OC

**Comment by hishamco** [comment] 2022-10-27 08:28
Closing this while there's no reply from the author

**Closed by hishamco** 2022-10-27 08:28 UTC
Labels: bug :bug:
