### ISSUE TITLE
When the liquid template theme is enabled, the blazor razor component cannot be output properly

### ISSUE THREAD

**Issue by justlucky** [OrchardCMS/OrchardCore#16459] opened 2024-07-19 06:45 UTC
When the liquid template theme is enabled, the blazor razor component cannot be output properly

enviroment:
visual studio 2022,
net8,
orchard core 1.8.3

enable liquid template theme(agency theme or blog theme)
enable module OrchardCore.Demo

Add code to hello.cshtml

// this is blazor razor component
@(await Html.RenderComponentAsync<Component1>(RenderMode.ServerPrerendered))

@* It includes the blazor.server.js. You can use Orchard Core resource management for this if you have a Blazor base project
    (i.e. adding a "Blazor" resource for this file). *@
<script src="_framework/blazor.server.js" at="Foot"></script>
![a0](https://github.com/user-attachments/assets/722205b8-6d81-40af-ba56-e3ab1b89e687)
![a1](https://github.com/user-attachments/assets/157ce029-cf0c-4895-bdc3-351a868b1b9a)
![a2](https://github.com/user-attachments/assets/bb4dd5ed-da11-4d09-abdf-323fa6617d1a)
![a3](https://github.com/user-attachments/assets/6aa704d8-c058-427d-98f7-d02710e958fb)
![a4](https://github.com/user-attachments/assets/d344c0ca-cff1-44e7-b22b-ca37542f8005)

**Comment by sebastienros** [comment] 2024-08-01 17:24
duplicate of https://github.com/OrchardCMS/OrchardCore/issues/16363
... which is also a duplicate of an exiting issue

**Closed by sebastienros** 2024-08-01 17:24 UTC
Labels: bug :bug:
