### ISSUE TITLE
Update application via OpenId Recipe and get error An application with the same client identifier already exists

### ISSUE THREAD

**Issue by hung-doan** [OrchardCMS/OrchardCore#7162] opened 2020-09-29 06:58 UTC
I use Recipe to add or update Application in OpenId Module. 
I run the Recipe for the first time. It added the Application successfully. 
However I run it again (without any modification). I got the error "An application with the same client identifier already exists"

## About OC
- OC Version: 1.0.0-rc2-14350

## Recipe steps

```
  "steps": [
    {
      "name": "OpenIdApplication",
      "ClientId": "mywebsite",
      "DisplayName": "My Website",
      "AllowPasswordFlow": true,
      "AllowRefreshTokenFlow": true,
      "Type": "public"
    }

  ]
```

## Error
```
{"errors":{"validations":["OpenIddict.Abstractions.OpenIddictExceptions+ValidationException: One or more validation error(s) occurred while trying to create a new application:\r\n\r\nAn application with the same client identifier already exists.\r\n\r\n   at OpenIddict.Core.OpenIddictApplicationManager`1.CreateAsync(TApplication application, String secret, CancellationToken cancellationToken)\r\n   at OpenIddict.Core.OpenIddictApplicationManager`1.CreateAsync(OpenIddictApplicationDescriptor descriptor, CancellationToken cancellationToken)\r\n   at OpenIddict.Core.OpenIddictApplicationManager`1.OpenIddict.Abstractions.IOpenIddictApplicationManager.CreateAsync(OpenIddictApplicationDescriptor descriptor, CancellationToken cancellationToken)\r\n   at OrchardCore.OpenId.Recipes.OpenIdApplicationStep.ExecuteAsync(RecipeExecutionContext context) in C:\\projects\\orchardcore\\src\\OrchardCore.Modules\\OrchardCore.OpenId\\Recipes\\OpenIdApplicationStep.cs:line 89\r\n   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass9_0.<<ExecuteStepAsync>b__0>d.MoveNext() in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Recipes.Core\\Services\\RecipeExecutor.cs:line 175\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Abstractions\\Shell\\Scope\\ShellScope.cs:line 206\r\n   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Recipes.Core\\Services\\RecipeExecutor.cs:line 154\r\n   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Recipes.Core\\Services\\RecipeExecutor.cs:line 100\r\n   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in C:\\projects\\orchardcore\\src\\OrchardCore\\OrchardCore.Recipes.Core\\Services\\RecipeExecutor.cs:line 117\r\n   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)\r\n   at OrchardCore.Recipes.Controllers.AdminController.Execute(String basePath, String fileName) in C:\\projects\\orchardcore\\src\\OrchardCore.Modules\\OrchardCore.Recipes\\Controllers\\AdminController.cs:line 107\r\n   at lambda_method(Closure , Object )\r\n   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)"]},"title":"One or more validation errors occurred!","status":500,"detail":"Please refer to the errors property for additional details."}
```

**Comment by deanmarcussen** [comment] 2020-09-29 17:33
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6364

**Closed by deanmarcussen** 2020-09-29 17:33 UTC
