### ISSUE TITLE
There will some messy codes in sqllite db after using the workflow to submit chinese charcatars. 

### ISSUE THREAD

**Issue by cellpaddding** [OrchardCMS/OrchardCore#3313] opened 2019-03-12 09:20 UTC
I use the workflow module and the form module to submit some chinese charcatars.
I've already set the page charset is 'UTF-8'.
When I submitted it.I find some the chinese charcatars that submitted were replaced by some  messy codes and the detail page display them like this:
![QQ截图20190312172046](https://user-images.githubusercontent.com/16536053/54188688-36dd8000-44eb-11e9-92c3-f44b1a4e7c5f.png)

The OrchardCore source code location is:
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Contents/Workflows/Activities/CreateContentTask.cs

![QQ截图20190312171104](https://user-images.githubusercontent.com/16536053/54188113-03e6bc80-44ea-11e9-9541-b962cd54eb2f.png)

So  I edit the source code like below,the charcatars display normal.
![QQ截图20190312171453](https://user-images.githubusercontent.com/16536053/54188313-63dd6300-44ea-11e9-920f-27c2ab76f9ff.png)

**Comment by Skrypt** [comment] 2019-03-12 17:16
Workflow Liquid template encoder should be set to NullEncoder.Default. We fixed this for Query templates 2 weeks ago.

**Comment by sebastienros** [comment] 2019-03-12 17:18
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3307

**Closed by sebastienros** 2019-03-12 17:18 UTC
