### ISSUE TITLE
an error in System.NullReferenceException: Object reference not set to an instance of an object.    at YesSql.QueryExtensions.Query[T](ISession session) in C:\projects\yessql-un1yf\src\YesSql.Abstractions\QueryExtensions.cs:line 11

### ISSUE THREAD

**Issue by ghenadieprocopan** [OrchardCMS/OrchardCore#3453] opened 2019-04-09 14:19 UTC
I am glad to find this project. I am novice in asp.net core.
Project is nice and helpfully.
I have downloaded and enrolled project and have started
but i have receveid message which is below
System.NullReferenceException: Object reference not set to an instance of an object.
at YesSql.QueryExtensions.Query[T](ISession session) in C:\projects\yessql-un1yf\src\YesSql.Abstractions\QueryExtensions.cs:line 11
at OrchardCore.Environment.Shell.Data.Descriptors.ShellDescriptorManager.GetShellDescriptorAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.Infrastructure\Shell\ShellDescriptorManager.cs:line 55
at OrchardCore.Environment.Shell.Builders.ShellContextFactory.OrchardCore.Environment.Shell.Builders.IShellContextFactory.CreateShellContextAsync(ShellSettings settings) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Environment\Shell\Builders\ShellContextFactory.cs:line 43
at OrchardCore.Environment.Shell.ShellHost.GetOrCreateShellContextAsync(ShellSettings settings) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 89
at OrchardCore.Environment.Shell.ShellHost.PreCreateAndRegisterShellsAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 186
at OrchardCore.Environment.Shell.ShellHost.InitializeAsync() in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Environment\Shell\ShellHost.cs:line 62
at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in C:\projects\orchardcore\src\OrchardCore\OrchardCore\Modules\ModularTenantContainerMiddleware.cs:line 39
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

Project ModernBusiness.OrchardCore-master ran well.
But newest project failed to run.
Can you help me?
Best regards.

**Comment by Skrypt** [comment] 2019-04-09 20:21
This is too vague for understanding what is happening exactly. We need repro steps. Maybe something is missing in your database.

**Comment by ghenadieprocopan** [comment] 2019-04-10 06:19
Thank you for your response.
I have resolved problem by deleting folder app_code in startup project.

Best regards, Ghenadie.

**Comment by psijkof** [comment] 2019-04-10 09:35
Yes, this was caused by upgrading an older version (using sqllite) to the latest packages, with the razor pages sample in my repo. Can close this issue.

**Closed** 2019-04-10 16:02 UTC
