### ISSUE TITLE
Import deployment plan bug

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8886] opened 2021-03-17 14:09 UTC
ValidationException: Your alias is already in use., Your permalink is already in use.

What should the desired behavior be if an alias is already in use?
Skip over it?

**Comment by deanmarcussen** [comment] 2021-03-17 14:16
It's by design.

If it skipped, then you would be left wondering where the content item you tried to import was.

**Comment by JoshTango** [comment] 2021-03-17 15:13
Ok fine.  Then there should be an intermediate page which has a list of the collisions and asks if you want to proceed.
Maybe you can even select how you want to handle the collisions.

**Comment by JoshTango** [comment] 2021-03-17 15:14
Then this should be a feature request maybe.

**Comment by sebastienros** [comment] 2021-03-18 17:47
TODO: check the logic in the test, to understand what is prevented and what is allowed to confirm there is an issue in the logic

Suggestion for error messages: Create a "dryrun" mode that could display error messages before executing the deployment. We could still get error messages back and display them. https://github.com/OrchardCMS/OrchardCore/issues/8904

**Comment by jptissot** [comment] 2021-03-21 15:23
> TODO: check the logic in the test, to understand what is prevented and what is allowed to confirm there is an issue in the logic

I tested this using various scenarios with the Menu of a Blog.

Here is how I setup the site: 
1. Setup the site using the blog recipe
2. Export the Menu ContentItem

Here are the various import paths I tried

### Same `ContentItemId`, different `VersionId`, modified DisplayText
This imported properly and the new version was properly added. No validation errors were triggerred.

### Same `ContentItemId`, different `VersionId`, same DisplayText
This imported properly, new version was added, No validation errors were triggerred.

### Different `ContentItemId`, different `VersionId`, same DisplayText
This triggerred the exception "Your alias is already in use" 
![image](https://user-images.githubusercontent.com/4681586/111910286-24ca3c80-8a37-11eb-8a2d-1e9ee6682758.png)

@deanmarcussen you were right. In our code, we were generating new `ContentItemIds` in the recipe using the `uuid()` function. This caused the exception 'Your alias is already in use' when executing the recipe.

**Comment by sebastienros** [comment] 2021-03-21 19:29
Closing since it seems to work as expected.

**Closed by sebastienros** 2021-03-21 19:29 UTC
