### ISSUE TITLE
how can i use content fields in query condition?

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3931] opened 2019-07-14 13:01 UTC
i have usarname field in content "RegisterInTest"

i'm using this code to filter list for this user name:
```

 
 var query = _session.Query<ContentItem, ContentItemIndex>();
        query = query.With<ContentItemIndex>(x => x.Latest);
        query = query.With<ContentItemIndex>(x => x.Published);

        query = query.With<ContentItemIndex>(x => x.ContentType == "RegisterInTest");
        query = query.OrderByDescending(cr => cr.ModifiedUtc);
        var pageOfContentItems = await query.ListAsync();
      var contentItemSummaries = new List<dynamic>();
        foreach (var contentItem in pageOfContentItems)
        {
            contentItemSummaries.Add(await _contentItemDisplayManager.BuildDisplayAsync(contentItem, this, "SummaryAdmin"));
        }
```
 
how i can set this condition?

`            query = query.With<ContentItemIndex>(x => x.username== "ahmad")`

**Comment by jtkech** [comment] 2019-07-14 20:59
See #3133.

**Comment by sebastienros** [comment] 2019-07-18 19:57
Duplicate of #1485

**Closed by sebastienros** 2019-07-18 19:57 UTC
