### ISSUE TITLE
Create multiple solutions files

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#5660] opened 2020-03-03 05:27 UTC
With ~153 projects inside Orchard Core source, seems it takes time to load all the projects also the compilation process may be slow little bit

What I'm suggesting to create multiple solution files for easy to manage say:

- Core.sln
- Module.sln
- Test.sln
.. etc

For instance if the intend to create a unit test loading `Test.sln` is enough instead of loading the whole ~153 projects

FYI I already such pattern in AspNetCore repo to make it easier for developers

**Comment by sebastienros** [comment] 2020-03-05 20:54
We'll still need to have all the Framework projects and the abstractions in the solutions.
So Modules will just have the Tests removed, Tests won't have anything removed, or maybe the modules it doesn't test. Core won't have the Modules.

**Comment by Piedone** [comment] 2024-05-03 20:52
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/920.

**Closed by Piedone** 2024-05-03 20:52 UTC
