### ISSUE TITLE
Enabling AdminDashboard feature with other SQL modifying features causes SQL mods to fail 

### ISSUE THREAD

**Issue by lazcool** [OrchardCMS/OrchardCore#8785] opened 2021-03-08 14:58 UTC
If the AdminDashboard feature is enabled, along with other features that modify the SQL database as part of their migration, then the SQL db isn't modified.

The easiest way to reproduce this, is to add the AdminDashboard feature to the start-up recipe.

**Comment by deanmarcussen** [comment] 2021-03-08 17:34
I would image there must be a exception going into the logs here.

Can you check the related logs @lazcool ?

What I have seen happening with these recipe migrations, that create and save content items, is that other features, which also created content item index, need to be prioritized correctly, so that the indexes they are creating, have been created, byt the time a `FlushAsync` is called (causing the db, to call into index providers, which are registered by said feature).

This is where the `Feature` attribute on migrations is important, to get them going to the feature they are linked to. and/or the correct Module / Feature depenencies.

A log will show this though

**Comment by andycyberian** [comment] 2021-03-12 17:23
I've stripped out our custom modules from our project and have tried running a fresh setup inlcuding the Admin Dashboard in the recipe, these are the Features being added below:

`    "steps": [
        {
            "name": "feature",
            "disable": [],
            "enable": [
                // SaaS
                "OrchardCore.HomeRoute",
                "OrchardCore.Admin",
                "OrchardCore.Diagnostics",
                "OrchardCore.DynamicCache",
                "OrchardCore.Features",
                "OrchardCore.Localization",
                "OrchardCore.Navigation",
                "OrchardCore.Recipes",
                "OrchardCore.Resources",
                "OrchardCore.Roles",
                "OrchardCore.Settings",
                "OrchardCore.Themes",
                "OrchardCore.Users",
                // Content Management
                "OrchardCore.Alias",
                "OrchardCore.Autoroute",
                "OrchardCore.Html",
                "OrchardCore.Https",
                "OrchardCore.ContentFields",
                "OrchardCore.ContentPreview",
                "OrchardCore.Contents",
                "OrchardCore.ContentTypes",
                "OrchardCore.CustomSettings",
                "OrchardCore.Deployment",
                "OrchardCore.Deployment.Remote",
                "OrchardCore.Feeds",
                "OrchardCore.Flows",
                "OrchardCore.Indexing",
                "OrchardCore.Layers",
                "OrchardCore.Lucene",
                "OrchardCore.Lists",
                "OrchardCore.Liquid",
                "OrchardCore.Markdown",
                "OrchardCore.Media",
                "OrchardCore.Media.Slugify",
                "OrchardCore.Menu",
                "OrchardCore.Placements",
                "OrchardCore.PublishLater",
                "OrchardCore.Queries",
                "OrchardCore.Sitemaps",
                "OrchardCore.Title",
                "OrchardCore.Templates",
                "OrchardCore.Widgets",
                "OrchardCore.AuditTrail",
                "OrchardCore.AdminDashboard",
                // Hosting
                "OrchardCore.Media.Azure.Storage",
                // Workflows
                "OrchardCore.Workflows",
                "OrchardCore.Workflows.Http",
                "OrchardCore.Workflows.Timers",
                 //Themes
                "TheAdmin"
            ]
        }
    ]
`

Trying to run this results in a SQL Exception. I'll try and upload the log file for you to look at.
[orchard-log-2021-03-12.log](https://github.com/OrchardCMS/OrchardCore/files/6131797/orchard-log-2021-03-12.log)

**Comment by deanmarcussen** [comment] 2021-03-16 15:29
I imagine the workflow content events are being activiated before the tables are being created. (probably the workflow is doing a flush, before doing a query)

Dependencies ordering may solve the issue.

But we will need a stronger way of achieving this, that doesn't involve dependencies.

In the short term I would try running two feature steps, one after the other. Activate the main set of features, then in another step activate workflows. They should be created in a seperate shell (from memory), so the transactions will have been committed.

Worth a try anyway and report back.

**Comment by jtkech** [comment] 2021-03-16 18:19
Yes, creating content trigger the related WF events

The problem is that for doing this `OC.Contents` requires `OC.WorkFlows` without depending on it

Hmm, maybe something to fix when the `RequireFeatures` atribute is used, would need to check that the feature is fully "activated", meaning e.g. that the migration is completed, i will think about it

Yes, each recipe step is executed in its own shell scope when executed through the recipe executor, but not when executed through the recipe migrator, so during a migration, the original reason was to not activate a shell while it is activating (migrations are run when activating a shell). Hmm, if we need it i think that now i can change it, because now we have the option to use a shell scope without activating it, but not sure.

**Comment by deanmarcussen** [comment] 2021-03-17 07:44
Yes @jtkech there maybe something in the `RequireFeatures` attribute.

That was why I needed to move the user picker field index to it's own feature, because in migrations we have no awareness of `RequiresFeatures` in the ordering, so it was always wanting to run before the user migration had finished.

Possibly it might be enough to apply some ordering around `RequireFeatures` during migrations rather than waiting for activation?

What is it about workflows that always causes this? Because it is executing queries and doing a Flush?

We also talked about being able to pause events when I did the content recipe idempotancy work. The idea being that when importing a batch of content items it _maybe_ useful to pause event handling during that operation.

I was never that sure we would want to do that, but at the same time it makes sense that during a batch import you might want to be able to put a hold on workflow events, for example, if you had an approval process / email that went of for every update to a content item, it would make less sense to send an email, when updating a batch. Equally it always felt like it might have to be opt-in, i.e. optional, an awareness in the workflow that an import was happening, so the workflow could decide how it wanted to handle it.

So even if we did that, I suspect the Flush would still occur before we're in a place where the workflow can decide.

**Comment by jtkech** [comment] 2021-03-18 03:05
@deanmarcussen 

Yes, i will think about it but so many other things

Hmm, maybe at some point but now i don't think that the Flush is a problem

About migrations, for me it was to alter definitions and tables, not to create contents, this in one shell scope during the shell activation. Then when we did the recipe migrator, for me it was to use recipes but only to do the same kind of definitions and database migrations. But because they are recipes, people wanted to also create contents ;)

So now as said, we may need per recipe migration step a new shell scope (that will not try to activate he shell), so that a new and necessary table (e.g. an index table) would be created and then usuable by a next step.

But still doesn't fix the ordering issue of required features.

Yes good idea to have some states / options to prevent some things to be executed, e.g. triggering WF events during a setup and / or the shell activation (where auto migrations are run)

We could also have intermediate state of features, e.g. a rising one meaning just being to be enabled, hmm we already have this kind of feature states in a document, but just updated, not yet used, look at this document in the database

    OrchardCore.Environment.Shell.State.ShellState // Managed by the ShellStateManager

See also `ShellFeatureState.cs` that defines feature states

        public enum State
        {
            Undefined,
            Rising,
            Up,
            Falling,
            Down,
        }

So a required feature would mean that the feature is enabled (Up) and not in an intermediate state (e.g. Rising)

Would need more time and to focus on it

**Comment by jtkech** [comment] 2021-03-22 18:00
As a reminder

Yes the `RequireFeatures` may introduce somewhere a circular dependency, e.g. when F1 require

Yes if F1 requires F2 to add a functionality, about ordering this functionality would need to be a pseudo feature that depends as usual on the main one F1 but also on F2, interesting, maybe a new kind of dependency strategy

Hmm, but we would have to take care if F2 also depends on F1 as it would introduce a circular dependency

Just found one, `OC.Contents` when requiring `OC.Sitemaps` that also depends on `OC.Contents`

**Comment by jtkech** [comment] 2021-04-05 00:52
Okay i could repro ;)

This by adding to the blog recipe the admin dashboard **and also the workflows feature**

It confirms the above comments, i will work on it

**Comment by jtkech** [comment] 2021-04-05 06:35
I think i found a fix for this kind of issue, see my last comment in #9046

**Closed** 2021-04-06 05:23 UTC
Labels: bug
