### ISSUE TITLE
[Question] Homepage per localization and autorouting based on language

### ISSUE THREAD

**Issue by LMSSonos** [OrchardCMS/OrchardCore#5071] opened 2019-12-18 13:15 UTC
My CMS has just four pages, a English homepage and about page and a French homepage and about page. What I want to do is to configure orchard, if a user access mysite.com and his browser is french, he will get french, else he will get english (configured as default culture in orchard). When I try to set the french homepage as homepage, it will remove the setting from the english one and the other way around.

Steps to reproduce
- Create a new OrchardCMS with Agency Theme
- Configuration -> Features -> Enable Content Localization
- Configuration -> Localization -> add second Culture (fr), so that you have en+fr
- Content -> Content definition -> Content types -> edit landingpage -> add part -> localization

After that, edit the "test" entry and save it as english. Then localize it to french

**Comment by hishamco** [comment] 2019-12-18 20:35
Orchard Core will try to look for `en` first if it's set in the browser the user will be able to see the English version. If the browser has `fr` set the user will get the French version, otherwise it will fallback to English version

**Comment by sebastienros** [comment] 2019-12-18 21:18
I would suggest to have unique urls for each language, for SEO purposes, such that google can index each page independently. Then create a rule based for `/` that would redirect the user to the corresponding url if the accept header is set.

@jptissot what kinds of feature do we already have for this. There is a picker to switch cultures, do we have a way to automatically redirect based on the current culture not matching the requested content item, if the content item is the default language.

**Comment by hishamco** [comment] 2019-12-18 21:22
> I would suggest to have unique urls for each language, for SEO purposes,

This could be done using routing localization, which is a built-in culture provider, but I'd like to hear from @jptissot if we have such thing

**Comment by sebastienros** [comment] 2019-12-19 21:07
Described what we need here: https://github.com/OrchardCMS/OrchardCore/issues/5089
It should be a specific feature in the content localization module.

**Comment by LMSSonos** [comment] 2019-12-22 21:56
@sebastienros thanks, exactly what I was looking for. Any idea for a quick workaround this?

**Comment by sebastienros** [comment] 2019-12-26 20:56
Duplicate of #5089

**Closed by sebastienros** 2019-12-26 20:56 UTC
Labels: localization
