### ISSUE TITLE
Dynamically load the module's.dll file.

### ISSUE THREAD

**Issue by Dean-ZhenYao-Wang** [OrchardCMS/OrchardCore#13765] opened 2023-05-29 10:16 UTC
### Is your feature request related to a problem? Please describe.
Dynamically load the module's.dll file.

### Describe the solution you'd like
Just like in the orchard era, we have the Module Store, which allows users to install modules directly or upload and install modules themselves, without the programmer having to recompile the code to install the required modules into the system.

### Describe alternatives you've considered
The existing '/Admin/Features' page has been revamped to look like before, where users can jump to the Modules store or upload Orchard Modules from elsewhere

**Comment by hishamco** [comment] 2023-05-29 10:55
This is hot :) I think the OC team decided at the beginning to not use the dynamic compilation because it causes many issues, hope @sebastienros explains what are the decisions in there

**Comment by sebastienros** [comment] 2023-05-29 14:35
You should find the answer by searching in previously open issues.

**Comment by ns8482e** [comment] 2023-05-30 12:55
@Dean-ZhenYao-Wang  IMO with combination latest CICD tools and technology like docker and Kubernetes are much more efficient than dynamic loading DLLs and with that you could achieve similar needs

**Comment by Dean-ZhenYao-Wang** [comment] 2023-05-31 03:09
You may have misunderstood me.
Please don't think I'm a programmer. I'm just the administrator of a website that runs on OrchardCMS.

**Comment by sebastienros** [comment] 2023-06-08 17:53
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5082

**Closed by sebastienros** 2023-06-08 17:53 UTC
Labels: enhancement
