### ISSUE TITLE
Error in content items - Object reference not set

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#7633] opened 2020-11-14 16:35 UTC
Hi, during development I ran into following problem:
![image](https://user-images.githubusercontent.com/52829889/99152006-6caf1080-269f-11eb-9e13-97e7da643b5c.png)

After some investigation I think I know where is the problem:
* In database is stored some content type, but it is not in ContentDefinition.json - e.g. when more people work on same solution
* Someone performs codename change in ContentDefinition, not in DB - similiar problem as above, it does not match with existing data.

**Comment by Skrypt** [comment] 2020-11-14 21:12
By design. Solution is to make everyone use the content definition stored in the database. Or update your ContentDefinition.json.

**Comment by MikeKry** [comment] 2020-11-15 14:06
@Skrypt 

Ok, so it is not possible to show at least some more user friendly error? E.g. "Could not parse content definition for Blog content type"? 

Because json representation has its advantages over storing configuration in DB (e.g. versioning, management in other editors etc.)

**Comment by deanmarcussen** [comment] 2020-11-15 17:45
https://docs.orchardcore.net/en/dev/docs/guides/content-definitions/

**Comment by Skrypt** [comment] 2020-11-15 17:59
@MikeKry Yes, of course, eventually a more user friendly error message could be considered. Though it is not an issue as it would also throw an exception like it already does. To fix your issue you need to use properly the ContentDefinition.json file (I think you understand that part). Then, the remaining is not a priority and will land in the backlog tasks.

**Comment by deanmarcussen** [comment] 2020-11-16 17:10
Duplicate https://github.com/OrchardCMS/OrchardCore/issues/6751

Closing this as we have too many issues trying to track the same thing, and the design is on https://github.com/OrchardCMS/OrchardCore/issues/6751

**Closed by deanmarcussen** 2020-11-16 17:10 UTC
