### ISSUE TITLE
Admin UI: Tabs not switching, Bag part title not moving to tabs

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#8806] opened 2021-03-10 07:34 UTC
Recently I noticed few UI problems (running on week old OC version):

* Tabs are not switching, if content type has Taxonomy field in Standard mode, but works when using Tags mode
* Taxonomy selection cannot be removed, when Taxonomy field is set as unique (can't deselect active item and select other) or even added (even when it is only field in content item)
* If bag part is placed to other tab, title will stay on first tab. 
* When multiple trumbowyg editors are on page with different setting for InsertMediaWithUrl, it always uses shortcodes (apparently because there are two scripts on page, also it collides with script for wywiwyg)

**Comment by MikeKry** [comment] 2021-03-11 10:01
Adding screens for bag part placement issue, if it helps:

Bagpart header on first tab:
![image](https://user-images.githubusercontent.com/52829889/110769588-a0b6ce80-8258-11eb-87d1-41752e809d22.png)

bagpart content on second tab:
![image](https://user-images.githubusercontent.com/52829889/110769978-128f1800-8259-11eb-9f8f-7c33fed6e04a.png)

**Comment by MikeKry** [comment] 2021-03-12 19:01
ad. point 2)
I have found an error message:
![image](https://user-images.githubusercontent.com/52829889/110986303-c97cb800-836d-11eb-8740-7338e3c949f2.png)

**Comment by MikeKry** [comment] 2021-03-24 07:35
Adding another UI issue to issue description

**Comment by deanmarcussen** [comment] 2021-03-24 08:32
To many issues list in one, I don't even know where to start

**Comment by MikeKry** [comment] 2021-03-26 08:34
@deanmarcussen 

It is all related to content item editor display, I can split it into multiple issues, but I felt it is unnecessary.

**Comment by MikeKry** [comment] 2021-03-26 09:14
Is https://try.orchardcore.net/  running latest OC version? I am thinking that I could create a test env. there so it would be obvious what are the errors.

**Comment by agriffard** [comment] 2021-03-26 09:40
@MikeKry I just updated http://try.orchardcore.fr/ (.fr, not .net) to latest dev package version `16018` if you want to test.

**Comment by MikeKry** [comment] 2021-03-26 10:38
@agriffard 
Thanks, just placed first demo of 
* BagPart Titles stays on different tab than bag part
* and Taxonomy when unique+required cannot be added or removed

if someone would like to look:
http://try.orchardcore.fr/cb2h1vty/admin
admin / t_@$X53F

**Comment by deanmarcussen** [comment] 2021-03-26 11:17
OK so we're down to two issues now ;) instead of three.

The problem is they are completely unrelated, so it becomes more dificult to advise on.

I'll go with the first one.

in the `ContetPart_Edit` shape we render the title of named parts
```
@using OrchardCore.ContentManagement.Metadata.Models
@using OrchardCore.ContentManagement.Metadata.Settings
@using OrchardCore.ContentManagement

@{
    ContentPart contentPart = Model.ContentPart;
    ContentTypePartDefinition typePartDefinition = Model.ContentTypePartDefinition;
    var description = typePartDefinition.Description();
    var namedPart = typePartDefinition.PartDefinition.IsReusable() && typePartDefinition.Name != typePartDefinition.PartDefinition.Name;
}

@if (namedPart)
{
    <h5>
        @typePartDefinition.DisplayName()

        @if (!String.IsNullOrEmpty(description))
        {
            <span class="hint dashed">@description</span>
        }
    </h5>
}
@foreach (var shape in Model)
{
    @await DisplayAsync(shape)
}
```
 
My current workaround is to replace the shape in a module with

```
@foreach (var shape in Model)
{
    @await DisplayAsync(shape)
}
```

Probably what we should do is generate the `named title` from a driver, and add it to the shape collection.

We don't have any alternates for these either, there is an issue tracking that.

**Comment by PiemP** [comment] 2023-04-06 16:54
Is it somethig possible to change the display mode of the named part to put the `named title` in the shape of the named part?

**Comment by sebastienros** [comment] 2023-04-27 17:45
@PiemP please file a new issue, I will close this one since it's old and I am not sure it's still accurate.

**Closed by sebastienros** 2023-04-27 17:45 UTC
Labels: bug :bug:
