### ISSUE TITLE
Missing Theme packages for versions > beta3-67921

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#2172] opened 2018-08-02 15:39 UTC
Hi,

It seems that the "TheBlogTheme" and "TheAgencyTheme are missing in lastest nuget packages.

Regards,
Jérôme

**Comment by sebastienros** [comment] 2018-08-02 19:28
Maybe Myget's disk quota is full.

**Comment by agriffard** [comment] 2018-08-02 19:30
I can see them:
https://www.myget.org/feed/orchardcore-preview/package/nuget/TheBlogTheme
TheBlogTheme 1.0.0-beta3-67921

https://myget.org/feed/orchardcore-preview/package/nuget/TheAgencyTheme
TheAgencyTheme 1.0.0-beta3-67931

**Comment by sebastienros** [comment] 2018-08-02 20:04
Maybe a transient internet connection issue, try to restore again and reopen if you still have issues.

**Comment by agriffard** [comment] 2018-08-03 11:17
Reopening. Indeed, TheAgencyTheme and TheBlogTheme are not built anymore since 1.0.0-beta3-67931 on MyGet.

**Comment by jpiquot** [comment] 2018-08-03 13:43
Yes, Now we have also OchardCore.Forms.


Package Id | Latest Version | Uploaded                                                               rss
-- | -- | --
OrchardCore.Forms | 1.0.0-beta3-67931 | 3 days ago
Authored by: OrchardCore.Forms                         Package Description

**Comment by sebastienros** [comment] 2018-08-03 21:51
Please take a look at the appveyor log

**Comment by agriffard** [comment] 2018-08-03 22:19
Example of error log: https://ci.appveyor.com/project/alexbocharov/orchard2/build/1.0.0.67946
```
Pushing TheBlogTheme.1.0.0-beta3-67946.nupkg to 'https://www.myget.org/F/orchardcore-preview/api/v2/package'...
  PUT https://www.myget.org/F/orchardcore-preview/api/v2/package/
  RequestEntityTooLarge https://www.myget.org/F/orchardcore-preview/api/v2/package/ 2089ms
nuget : Response status code does not indicate success: 413 (The package size for file 'package.nupkg' is too large. 
The feed owner may have to upgrade the MyGet subscription to resolve this issue.).
```

**Comment by kamikyo** [comment] 2018-08-06 05:51
I have the same problem.

**Comment by agriffard** [comment] 2018-08-06 08:11
@alexbocharov Can you please solve this build issue on AppVeyor?

**Comment by alexbocharov** [comment] 2018-08-06 08:13
@agriffard I'll take a look

**Comment by alexbocharov** [comment] 2018-08-06 08:38
@sebastienros @agriffard The problem is for packages larger than 1MB

**Comment by alexbocharov** [comment] 2018-08-06 08:43
|Package link|Size|
|---|---|
|https://ci.appveyor.com/api/buildjobs/lo07g29oqo7itu1w/artifacts/src%2FOrchardCore.Modules%2FOrchardCore.Forms%2Fbin%2FRelease%2FOrchardCore.Forms.1.0.0-beta3-67946.nupkg|2MB|
https://ci.appveyor.com/api/buildjobs/lo07g29oqo7itu1w/artifacts/src%2FOrchardCore.Themes%2FTheAgencyTheme%2Fbin%2FRelease%2FTheAgencyTheme.1.0.0-beta3-67946.nupkg|4MB|
https://ci.appveyor.com/api/buildjobs/lo07g29oqo7itu1w/artifacts/src%2FOrchardCore.Themes%2FTheBlogTheme%2Fbin%2FRelease%2FTheBlogTheme.1.0.0-beta3-67946.nupkg|7MB|

**Comment by sebastienros** [comment] 2018-08-06 19:36
The theme packages are big, like 7MB, we need to trim it.

**Comment by sebastienros** [comment] 2018-08-11 00:18
It's fixed now since I decreased the retention policy. The issue is not because it's more than 1MB but the quota for the whole set of package versions is limited to 500MB. For sure the images in the themes take a lot of space and we should see how we can make them smaller, while being the less intrusive in regards to the official templates.

**Closed by sebastienros** 2018-08-11 00:18 UTC
