### ISSUE TITLE
Problem upgrade using OrchardCore.Application.Cms.Targets version 1.0.0-rc1-11798

### ISSUE THREAD

**Issue by LightHeartRD** [OrchardCMS/OrchardCore#5440] opened 2020-02-02 11:28 UTC
My current project, running on version 1.0.0-rc1-10004, I would like to update to latest version and upgrade using .net core 3.1.  When upgrade and install new targets, I keep getting the following when rebuilding:

Severity	Code	Description	Project	File	Line	Suppression State	Suppression State
Error	NU1102	Unable to find package TheBlogTheme with version (>= 1.0.0-rc1-11798)
  - Found 21 version(s) in Orchard Core Beta [ Nearest version: 1.0.0-rc1-11750 ]
  - Found 11 version(s) in nuget.org [ Nearest version: 1.0.0-rc1-10004 ]
  - Found 0 version(s) in Microsoft Visual Studio Offline Packages	OneSNC.Web	C:\Temp\ONE\OneSNC.Web\OneSNC.Web.csproj	1		

Same goes for the TheTheme and TheComingSoon themes.

VS Project file:
![OrchardProject](https://user-images.githubusercontent.com/60569865/73607511-34659800-458d-11ea-9f6e-ad879299a748.png)

**Comment by arkadiuszwojcik** [comment] 2020-02-02 11:40
Duplicate of #5414

**Closed** 2020-02-02 11:53 UTC
