### ISSUE TITLE
NuGet organization and package ID prefix reservation

### ISSUE THREAD

**Issue by BenedekFarkas** [OrchardCMS/OrchardCore#10573] opened 2021-10-28 14:11 UTC
Hey, long time no see, two ideas:

1. [ ] There is an organization on NuGet called [OrchardCMS](https://www.nuget.org/organization/OrchardCMS), originally created by @sfmskywalker, but currently only @Piedone and myself are members/admins. We could mirror the ownership/leadership structure from the GitHub organization and move all the OC packages under this organization so that @sebastienros is not the only one having access to manage them, just in case.
2. [x] Reserve the "OrchardCore" package ID prefix: https://docs.microsoft.com/en-us/nuget/nuget-org/id-prefix-reservation

**Comment by sebastienros** [comment] 2021-12-16 18:49
Is it ok to create an organization that does use CMS in it?

**Comment by Piedone** [comment] 2021-12-16 19:12
Why wouldn't it be?

**Comment by Skrypt** [comment] 2021-12-16 20:58
I think we should find a name for the Framework that is different than OrchardFramework. So that we keep Orchard as the CMS brand name. Then the organizations would make sense. For example, now Facebook has Meta ... two different names.

So, here what we need is to rename the current organization to that name. And then we can have 2 different repositories in that organization for the framework and the CMS.

So that's 3 different names that are required. We keep one which is Orchard. But OrchardCMS doesn't make any sense as an organization name then.

**Comment by hishamco** [comment] 2021-12-16 21:58
> I think we should find a name for the Framework that is different than OrchardFramework. 

What's the wrong with `OrchardCore Framework`

I suggest to have an organization called `Orchard` that has the following repos:

- OrchardCoreFramework
- OrchardCoreCms (Orchard vNext)
- OrchardCms (Orchard 1)

we could have modules, themes, translation .. etc as well, this way we truly separate the CMS from actual framework

**Comment by sebastienros** [comment] 2021-12-16 22:31
@hishamco @Skrypt 

> Is it ok to create an organization that does use CMS in it?

> Why wouldn't it be?

Technically speaking it means that @Piedone doesn't see any issue with it ;) "why would it not be ok to create ..." But let's get some confirmation first.

**Comment by Skrypt** [comment] 2021-12-16 22:53
@piedone is wrong 🎅🏼

**Comment by Skrypt** [comment] 2021-12-16 23:28
Well @piedone never explained his point and was not in the meetings to understand why we want to have new names so maybe he doesn't understand why OrchardCMS as an organization is problematic if we want to advertise Orchard as a CMS and also have a framework that is totally independent of the CMS.

**Comment by Piedone** [comment] 2021-12-16 23:31
I understood "Is it ok to create an organization that does use CMS in it?" as in, "Is there any technical or legal issue with creating an organization on NuGet that has "CMS" in its name." To which I was inquiring about why it wouldn't be since I'm not aware of any such restriction. That is all.

**Comment by Skrypt** [comment] 2021-12-16 23:48
So some thoughts. Because if we want to find terms that are related to Orchard; we can't use Apple ... it's already been taken by some company out there ... what a shame 🥲 

So here are some terms hierarchically : 

- Orchard
  - Leafs
  - Fruits
  - Branches

This gives us really small possibilities for ideas of terms that are related to an Orchard that would make sense.
So, I think it would be better to have a structure where Orchard would not be rebranded and kept as is. This means finding related terms on top of the Orchard one.

- Harvester, Harvest, Cultivator (lol), ... 
  - Orchard --> CMS
  - Core --> Framework

**Comment by Piedone** [comment] 2021-12-17 00:17
One thing that we at Lombiq learned the hard way is that you want as few arbitrary names as possible, and if you must have them, then prefix them with the brand name. E.g. Zendesk did this too when they acquired the CRM called Base and rebranded it to Zendesk Sell. Microsoft did this recently by rebranding Channel 9 to Microsoft Learn (and breaking all the links while doing that but that's beside the point). And they're doing something similar with Azure services: Instead of having cool sounding but hard to remember names like Elastic Beanstalk and S3, they have Azure App Service and Azure Storage (they renamed Azure App Service like three times, mind you :)) that anyone can understand and remember.

Here, "Orchard" is the name everyone knows and which has been used for over a decade. You can make distinctions below that (like "Orchard Core", "Orchard 1.x") but to use any other name would be ill-advised. To be concrete for the NuGet organization name, I'd just use "Orchard CMS" since that's the name used here on GitHub as the org name too. Keep in mind that this is the name of the organization managing the packages and as such only interesting as the owner of the packages (apart from it being what admins see):

![image](https://user-images.githubusercontent.com/1976647/146467643-b824310b-48b1-46b7-b7aa-5e520c46d981.png)

It doesn't affect package names or the searchability and discoverability of package names. And as such, I wouldn't stress on it too much apart from keeping consistency (which is important, that your stuff is named exactly the same everywhere).

**Comment by Skrypt** [comment] 2021-12-17 00:39
One thing here is that we are talking about having an Organization name that would be the same under Nuget and Github. So, for that matter OrchardCore is already taken and I believe Orchard too. So, that leaves us really few options.

**Comment by Skrypt** [comment] 2021-12-17 00:46
The way I see this is that naming Orchard as Orchard Core was a bad decision. Because then we could have had Orchard 1.0 and Orchard 2.0 simply. But these are 2 separated repositories so it's too late.

Then the framework should have been Orchard Core. And the CMS : Orchard simply. The Organization name could have been Orchard too at this point.

**Comment by Skrypt** [comment] 2021-12-17 00:50
So everything I said before as Organization names are already taken too ...

**Comment by Piedone** [comment] 2021-12-17 02:20
Unfortunately, these things are extremely hard to change after the fact.

"Orchard CMS" is not taken, hence I'd just keep using that ;). This really doesn't need to be more complicated. I don't really see why anything would need to be changed. Also, what this issue is about is moving ownership of the NuGet packages from under Sebastien's user account, which is a SPoF, under an organization, which can be managed by multiple people. I think branching this matter off into rebranding Orchard from the ground up is something that's out of scope :).

Also, the organization name doesn't really dictate anything about the product name (i.e. Orchard CMS - Orchard Core, even though if it were 2009 again with my current knowledge, I'd suggest something else). E.g. ImageSharp is managed by an organization called Six Labors. Why would this be an issue?

**Comment by Skrypt** [comment] 2021-12-17 02:57
There is no issue else than the fact that if we are using "CMS" in the organization name then we confuse people about what we are doing which is not only a "CMS". This is where the issue is, not about the ownership of the organization, this is something that can be discussed furthermore if you want but I've never seen the issue about @sebastienros being the only owner so far. And, this is why I'm saying that OrchardCMS organization whoever owns it is not relevant for us if we think about the future and where we want to go with Orchard.

So, here the topic name is about Organization names, not ownership as far as I know. But if we want to also get into that topic maybe we should ask @sebastienros what he thinks about it. Now we get into Dotnetfoundation type of debates and this is not my bag of tea at all 😉

**Comment by Skrypt** [comment] 2021-12-17 03:35
For your concern about the "single point of failure", I don't know if this is relevant that much. If anything happens to @sebastienros the project would be taken care of by the Dotnet Foundation in some way "I think".

**Comment by BenedekFarkas** [comment] 2021-12-17 11:24
With Orchard's popularity and dev/user base growing, a single point of failure is becoming a slightly larger risk every day.

Naming things is a PITA, but brand identity and consistency is a huge value. You'll never be able to explain the full picture in a single word (or two words), but I doubt that anyone would ignore the existence of Orchard Core as a framework just because the organization has CMS in the name.

**Comment by sebastienros** [comment] 2021-12-17 18:07
We are definitely creating an org to prevent me from being the only admin of the packages.

Please watch the two meetings where we talked about renaming the GitHub organization. We mention all the reasons, pros and cons. In short we lose a bunch or users for the modular framework because they don't want a CMS. And the first thing they see, and then the last, is the word CMS. We will keep Orchard for the CMS name, also for the organization. We also talked about using a different name for the framework, under the same organization. So Orchard the product will keep being the CMS, and something else will be the framework.

**Comment by ns8482e** [comment] 2021-12-17 18:20
OrchardSeb? -lol  
`Seb` in Hindi means Apple.

**Comment by Skrypt** [comment] 2021-12-17 18:20
So like I said we need to find two names : Organization and Framework.

**Comment by Skrypt** [comment] 2021-12-17 18:24
The Orchard ... Organization. 😉 

Magnitude effect :)

**Comment by agriffard** [comment] 2022-01-06 19:19
Orchard organization has been created on Nuget by @sebastienros

Some other users can be added in this organization.

**Comment by sebastienros** [comment] 2022-01-06 20:07
Please share the NuGet usernames I need to add to the org

**Closed** 2022-01-06 20:08 UTC
Labels: discussion, NuGet

**Comment by Piedone** [comment] 2022-01-06 20:14
`zoltan.lehoczky`, please.

**Comment by BenedekFarkas** [comment] 2022-01-10 12:22
`benedek.farkas`, please, thanks!
