### ISSUE TITLE
How can I modify the OpenId default token expire time?

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#7036] opened 2020-09-08 04:05 UTC
How can I modify the OpenId defualt token expire time?

In old version of Orchard Core, I cant call `SetAccessTokenLifetime`  in `AccessController`, but now it's more complex than old version, I could not find where I can modify the OpenId token lifetime.

    ticket.SetAccessTokenLifetime(TimeSpan.FromDays(365));

![image](https://user-images.githubusercontent.com/3222379/92431692-b88a9880-f1ca-11ea-8c16-52e8ef8f0128.png)

**Comment by jtkech** [comment] 2020-09-08 04:26
Duplicate of #7035

**Comment by jtkech** [comment] 2020-09-08 04:29
Oops didn't see that #7035 is a discussion, not an issue, reopen it

**Comment by RockNHawk** [comment] 2020-09-08 04:40
@jtkech I delete the discussion, it's a mistake...

**Closed** 2020-09-08 04:57 UTC
