### ISSUE TITLE
Proposal to extend DefaultUserClaimsPrincipalFactory using providers instead of inheritance

### ISSUE THREAD

**Issue by CrestApps** [OrchardCMS/OrchardCore#8091] opened 2020-12-19 16:29 UTC
**Problem**

If a module, need to add claims to the user during login, the module will need to inherit the [DefaultUserClaimsPrincipalFactory](https://github.com/OrchardCMS/OrchardCore/blob/ed4250cd4dc3d6983b536d41da0458e9f20a4311/src/OrchardCore/OrchardCore.Users.Core/Services/DefaultUserClaimsPrincipalFactory.cs) then override the [GenerateClaimsAsync(IUser user)](https://github.com/OrchardCMS/OrchardCore/blob/ed4250cd4dc3d6983b536d41da0458e9f20a4311/src/OrchardCore/OrchardCore.Users.Core/Services/DefaultUserClaimsPrincipalFactory.cs#L22). This is done in the [DemoUserClaimsPrincipalFactory with in the demo module](https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore.Modules/OrchardCore.Demo/Services/DemoUserClaimsPrincipalFactory.cs). To override the default implementation, one will have to [replace existing implementation](https://github.com/OrchardCMS/OrchardCore/blob/1879619df4418ff175a59ba70dcb36bab89fcbb5/src/OrchardCore.Modules/OrchardCore.Demo/Startup.cs#L100).

That setup is okay in most cases, but what if there are 2 separate modules that need to add claims to the claims yes both modules are independent of each other? Which implementation will take presence over the other?

**Proposal**
My proposal is to create an interface like this

```
public interface IClaimsGenerator
{
     Task<ClaimsIdentity> GenerateAsync(IUser user, ClaimsIdentity claims);
}
```

Then in the `DefaultUserClaimsPrincipalFactory` will look something like this 

```
public class DefaultUserClaimsPrincipalFactory : UserClaimsPrincipalFactory<IUser, IRole>
{
    private readonly IServiceProvider _serviceProvider;

    public DefaultUserClaimsPrincipalFactory(
        UserManager<IUser> userManager,
        RoleManager<IRole> roleManager,
        IOptions<IdentityOptions> identityOptions,
        IServiceProvider serviceProvider) 
        : base(userManager, roleManager, identityOptions)
    {
        _serviceProvider = serviceProvider;
    }

    protected override async Task<ClaimsIdentity> GenerateClaimsAsync(IUser user)
    {
        var claims = await base.GenerateClaimsAsync(user);

        var claimsGenerators = _serviceProvider.GetRequiredService<IEnumerable<IClaimsGenerator>>();

        foreach(IClaimsGenerator claimsGenerator in claimsGenerators)
        {
             claimsGenerator.GenerateAsync(user, claims);
        }

        // Todo: In a future version the base implementation will generate the email claim if the user store is an 'IUserEmailStore',
        // so we will not have to add it here, and everywhere we are using the hardcoded "email" claim type, we will have to use the
        // new 'IdentityOptions.ClaimsIdentity.EmailClaimType' or at least its default value which is 'ClaimTypes.Email'.

        var email = await UserManager.GetEmailAsync(user);
        if (!String.IsNullOrEmpty(email))
        {
            claims.AddClaim(new Claim("email", email));

            var confirmed = await UserManager.IsEmailConfirmedAsync(user);
            claims.AddClaim(new Claim("email_verified", confirmed ? bool.TrueString : bool.FalseString, ClaimValueTypes.Boolean));
        }

        return claims;
    }
}
```

Even then the `email` and `email_verified` claims can be extracted into their own generator.

If this is an acceptable proposal, I can provide a PR.

**Comment by deanmarcussen** [comment] 2020-12-19 16:51
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/7671

Yes a `ClaimsProvider` interface pr would be great thanks. 

See the associated issue for some of the ins and outs of the design.

**Comment by CrestApps** [comment] 2020-12-20 16:46
PR #8097 was submitted to close this request

**Closed** 2021-01-12 18:32 UTC
