### ISSUE TITLE
Custom blog post query (Missing detailed lucene and sql query documentation)

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3939] opened 2019-07-16 13:48 UTC
(copied my question from gitter)

Hello everyone,
i'm sorry if the following question is already answered somewhere, but i was not able to find some examples for this.
I've looked into the documentation for lucene and sql queries in orchard, but i'm not completely sure, whats the best solution.

I'm trying to query all blog posts from a specific blog for a classic "recent blog posts" solution.
First of all, lucene or sql query ?
In case of an sql query, do i have to join the ContainedPartIndex table and if yes, like a normal sql join?
I was not able to figure out, what to do with the "Parameters" field for the sql queries nor the lucene queries.

Same with the lucene queries.
The only example i've found was this one: https://github.com/OrchardCMS/OrchardCore/issues/1485
Unfortunately there is no filter on the actual blog in this one.

**Comment by dodyg** [comment] 2019-07-16 14:34
You can check this case

https://github.com/OrchardCMS/OrchardCore/issues/3540

**Comment by Flarescape** [comment] 2019-07-16 16:04
@dodyg Thank you! Unfortunately it's still not documented and i don't really get the benefit of this field if i can do it right in the query without using the parameters.

**Comment by dodyg** [comment] 2019-07-17 10:40
You don't need the parameter. You can hard code the `{ size : 10 }` to limit the number of results you get.

**Comment by Flarescape** [comment] 2019-07-17 11:27
@dodyg So it's currently useless?

I am very grateful for your help.
Since you obviously already know the new Queries better, could you help me with my actual problem? (Filter on specific blog)

**Comment by dodyg** [comment] 2019-07-17 16:15
I assume you have multiple blogs. The problem with Lucene index on the BlogPostItem is that doesn't know which blog your blog post belongs to. So you have to add this information yourself on each blog post.

1. For your blog post definition, create text field (name it e.g. BlogId) with drop down input that contains text that contains identification (e.g. "cooking blog", "tech blog", "x blog")
2. Make this field as indexable.
3. When you do a lucene query at /OrchardCore.Lucene/Admin/Query, it will show this index as part of the result.

This is the query you can use to see all the BlogPost. Your 
```
{
  "query": {
    "term" : { "Content.ContentItem.ContentType" : "BlogPost" } 
  },
  "sort": { "BlogPost.PublishedOn": { "order": "desc" } }
}
```
4. Then you can use this "BlogId" text field to filter the blog post accordingly.

 I hope this helps. Let me know.

**Comment by Skrypt** [comment] 2019-07-18 00:43
I think this issue is a duplicate of something we discussed on a different issue. If not then open an issue about it but I think the proper resolution of this issue would be to add the parent Id of a List item in the Index.

**Comment by dodyg** [comment] 2019-07-18 07:48
@Skrypt that would solve this issue elegantly.

**Comment by sebastienros** [comment] 2019-07-18 19:36
Duplicate of #3949

**Closed by sebastienros** 2019-07-18 19:36 UTC

**Comment by Flarescape** [comment] 2019-07-25 18:14
Hi!

After a few tries i got i kind of working with an sql query.
The bigger problem was/is, that i want only a specific amount (last 2 blog posts) and that `TOP ` is not supported.
I've looked into the documentation and found out, that i should use `LIMIT ` instead.
This was my approach with `LIMIT` and a parameter (like it's in the documentation):
```
Select cpi.DocumentId 
from ContainedPartIndex cpi 
inner join ContentItemIndex cii on cpi.ListContentItemId = cii.ContentItemId
where cii.DisplayText like 'General Blog'
limit @limit:2
```
This always throws an exception: `An error occured while executing the SQL query: Incorrect syntax near '@limit'.`
Do i have to enter something in the "Parameters" field or what am i doing wrong here ?
