### ISSUE TITLE
Unable to resolve service for type 'OrchardCore.Email.ISmtpService' while attempting to activate 'OrchardCore.Email.Controllers.AdminController'.

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#4507] opened 2019-10-10 09:15 UTC
Hi all, I have a question which I would like some help.

I'm trying to integrate the orchard core to an already existent API, my goal is to have the swagger with my endpoints and CMS endpoints, and to have access to the back office.

I'm getting this error of register of dependencies when I try to open "/admin"

```
"errors": [
{
"code": "6",
"message": "Unable to resolve service for type 'OrchardCore.Email.ISmtpService' while attempting to activate 'OrchardCore.Email.Controllers.AdminController'.",
"developerMessage": null,
"exception": {
"ClassName": "System.InvalidOperationException",
"Message": "Unable to resolve service for type 'OrchardCore.Email.ISmtpService' while attempting to activate 'OrchardCore.Email.Controllers.AdminController'.",
"Data": null,
"InnerException": null,
"HelpURL": null,
"StackTraceString": "   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)\r\n   at lambda_method(Closure , IServiceProvider , Object[] )\r\n   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\r\n   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()\r\n   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()",
"RemoteStackTraceString": null,
"RemoteStackIndex": 0,
"ExceptionMethod": null,
"HResult": -2146233079,
"Source": "Microsoft.Extensions.DependencyInjection.Abstractions",
"WatsonBuckets": null
},
"moreInformation": null
}
]
}
```
This error just appears when I have this as I had before on configureServices
```
            services.AddMvc(
                .AddJsonOptions(
                    options =>
                    {
                        options.SerializerSettings.Formatting = Formatting.Indented;
                    });

```
Without it, I cant run swagger.

Anyone can help me with this?

**Comment by ruisdias** [comment] 2019-10-10 09:26
No, I just set up it as a "blank website", nothing else.

I can see the admin login page when I comment that services.AddMcv and comment swagger aswell.

but If I have like that to swagger to work, Im getting this error when I'm trying to access /admin

**Comment by hishamco** [comment] 2019-10-10 12:24
Why you comment `services.AddMvc()`?

Regarding Swagger I think there's a work going on one PR

**Comment by sebastienros** [comment] 2019-10-10 19:28
How did the `OrchardCore.Email.Controllers.AdminController` controller get invoked without the Email feature being enabled. Did you try to access it directly or did you click on a link?

**Comment by ruisdias** [comment] 2019-10-14 07:28
Even I tried to create a new solution and do the configuration for swagger and the orchard cms. When I'm trying to access '/admin' it gives me that error.

**Comment by hishamco** [comment] 2019-10-14 08:11
This seems another issue, how this is related to `OrchardCore.Email` module?

**Comment by deanmarcussen** [comment] 2019-10-14 09:08
@ruisdias from our conversation on gitter I think your issue is not swagger related, but mvc related.

the call you are making to 
```
            services.AddMvc(
                .AddJsonOptions(
                    options =>
                    {
                        options.SerializerSettings.Formatting = Formatting.Indented;
                    });
```

is overriding the Orchard routing, and making all of the orchard controllers available to mvc, which means that all controllers are trying to activate, even though the email feature is not enabled.

From the gitter conversation you had different options in your `services.AddMvc()` call. Namely to provide some filters I think.

You can configure these filters without a `services.AddMvc()` call by configuring the options instead. e.g.
```
services.Configure<MvcOptions>((options) =>
{
  options.Filters.Add( ... );
});
```

and you should be able to configure the Json options in a similar way, but you will have to look through the aspnet code to see what the extension method you are using does. I imagine it will use it's own `Configure<JsonOptions>` under the hood of the extension method. 

If this doesn't work, probably best to post your whole startup code block, so we can understand what calls you're making, but I'm pretty sure it's because you're overriding the Orchard Core routing.

**Comment by jtkech** [comment] 2019-10-14 22:17
Normally, in the startup of a given module we now can re-call `AddMvc()`. We had a problem recently because we were overriding an mvc service (to fix an mvc issue) too soon, but it's now fixed.

But is your code executed through the startup of a given module? Or through the startup of the application? If so we have helpers that allows to define things at the application but as they were defined in  a module startup.

**Comment by deanmarcussen** [comment] 2020-02-06 07:55
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5464 and should be resolved with the answers there.

Please reopen if still an issue

**Closed by deanmarcussen** 2020-02-06 07:55 UTC
Labels: Orchard.Email
