### ISSUE TITLE
media library ,delete file not success

### ISSUE THREAD

**Issue by jnucpz** [OrchardCMS/OrchardCore#15698] opened 2024-04-09 08:50 UTC
### Describe the bug
In the media library, if I delete a file and then upload another file with the same name but different content, the library still displays the deleted file. Why is this happening?

i want displays the upload another file.

**Comment by Skrypt** [comment] 2024-04-09 13:09
Either browser cache or ImageSharp cache related.

**Comment by Piedone** [comment] 2024-04-09 17:40
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/15273. This is fixed and will be part of 1.9.

In case you're experiencing this with the latest source in `main`, not with <=1.8.2, please reopen.

**Closed by Piedone** 2024-04-09 17:40 UTC
Labels: bug :bug:

**Comment by jnucpz** [comment] 2024-04-10 08:49
thanks.
