### ISSUE TITLE
Please support PKCE for OrchardCore.OpenId.Server.

### ISSUE THREAD

**Issue by aaronamm** [OrchardCMS/OrchardCore#10980] opened 2022-01-07 08:08 UTC
### Is your feature request related to a problem? Please describe.

"PCKE" (Proof Key for Code Exchange or Pixie) is a superset feature on top of OAuth2 Authorization Code grant type and **will be forced to use by OAuth 2.1 for security**.

With this grant type, even thought a hacker can get an authorization code and code challenge but cannot know a "code verifier". 
Then one cannot get an access token.

Therefore, it is important to support this feature for a security reason.

### Describe the solution you'd like

We can add add 'Enable PKCE' OpenId.Server option and enable this feature in this file.
https://github.com/OrchardCMS/OrchardCore/blob/main/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdServerConfiguration.cs#L54

OpenIddict has already implemented this feature. We only need a add little configuration to support it.

FYI  Authorization code with PKCE with a diagram.
https://www.dotnetthailand.com/faq/fundamentals/oauth#4.authorizationcodewithpkce

RequireProofKeyForCodeExchange in OpenIddictServerOptions
https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerOptions.cs#L325

RequireProofKeyForCodeExchange() in OpenIddictServerBuilder
https://github.com/openiddict/openiddict-core/blob/dev/src/OpenIddict.Server/OpenIddictServerBuilder.cs#L1738

**Comment by kevinchalet** [comment] 2022-01-07 14:34
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/7138. TL;DR: the OpenID module fully supports PKCE (token requests lacking the correct verifier will be rejected if one code challenge was initially sent) but there's currently no option to force an application to send a code challenge.

@aaronamm if you're interested in contributing to this item, let us know! 😃

**Comment by aaronamm** [comment] 2022-01-08 08:03
@kevinchalet Thanks for your prompt reply and sorry that I haven't searched an issue to make sure if there's no existing same topic.

So, I will close this issue and continue discussing on [the existing issue](https://github.com/OrchardCMS/OrchardCore/issues/7138).

**Closed** 2022-01-08 08:04 UTC
Labels: duplicate, enhancement, OpenId
