### ISSUE TITLE
msgctxt with Project Name

### ISSUE THREAD

**Issue by BarretoFilipe** [OrchardCMS/OrchardCore#5263] opened 2020-01-13 10:37 UTC
Hello, I'm using the POExtractor tool in order to generate the .POT files. Those files include the project name in the msgctxt and with it the localizer cannot find the translations. Is there any configuration required or what am I missing?

**Comment by jptissot** [comment] 2020-01-13 12:57
Did you use the complete path (not relative path) when using poextractor ?

**Comment by BarretoFilipe** [comment] 2020-01-13 14:14
Yes.
My command
`extractpo-oc C:\Users\Barreto\Documents\Projetos\AnnaLocalization\AnnaLocalization\AnnaLocalization C:\Users\Barreto\Documents\Projetos\AnnaLocalization\AnnaLocalization\AnnaLocalization\Localization`

and result:

```
#: AnnaLocalization\Views\Home\Index.cshtml:16
#. <p>@T["brother"]</p>
msgctxt "AnnaLocalization.Views.Home.Index"
msgid "brother"
msgstr ""
```

But it only works if I remove the project name "AnnaLocalization"

**Comment by jptissot** [comment] 2020-01-13 14:52
Is this a module ? A theme or the Web project ?

**Comment by BarretoFilipe** [comment] 2020-01-13 15:03
Will be API and web site, but I'm testing with razor pages

**Comment by hishamco** [comment] 2020-01-15 00:04
If the issue is in extracting the localization resources, I prefer to move this to https://github.com/lukaskabrt/PoExtractor there's already few case that not covered and trying to push some PRs there

**Comment by sebastienros** [comment] 2020-01-23 21:03
Could someone try to do the same thing on a custom module and ensure it works? At least to find where the issue is?

**Comment by hishamco** [comment] 2020-02-06 00:21
@BarretoFilipe could you please create a repo with your module, I will try to run the `extractpo-oc` at my side and check where is the issue

**Comment by BarretoFilipe** [comment] 2020-02-12 16:48
Sorry guys. I fixed my bug, my translations are applied in a centralized class in my project (a ExceptionHandlerMiddleware), because of that I can't use the "msgctxt".
Is there anything that can help me in this situation?

**Comment by hishamco** [comment] 2020-02-14 00:11
Please file an issue in PO Extractor repo and I will dig into that when I have time

So closing this ...

**Closed by hishamco** 2020-02-14 00:11 UTC
Labels: localization
