### ISSUE TITLE
Check resource definition checksum as part of the CI build

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#11915] opened 2022-06-28 19:23 UTC
Create a script that discovers all the resource definitions and ensures that the checksum for each of them is valid.

**Comment by hishamco** [comment] 2022-06-29 14:59
Seb, I already did a PR using resource generators for this one, I will update that PR to the latest bits and make it ready. I'm not sure if we need it as a part of CI, because whenever a resource has been added, the generator will calculate the proper SRI, then it will appear as a code change that will show up in Git

**Comment by Piedone** [comment] 2024-04-25 00:09
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/9941. Implemented by https://github.com/OrchardCMS/OrchardCore/pull/9947.

**Closed by Piedone** 2024-04-25 00:09 UTC
Labels: enhancement
