### ISSUE TITLE
"Attached" Media Field No Longer Able to Upload File

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore#5694] opened 2020-03-09 19:03 UTC
I am trying to determine what changed and will add an update here when available. As of right now though (code updated a couple of days ago) a Media Field set up as "Attached" will throw an error of 
```
{Field Name}: There was an error handling the files.
```

**Comment by hishamco** [comment] 2020-03-09 21:14
@deanmarcussen any idea?

**Comment by deanmarcussen** [comment] 2020-03-10 10:05
@jeffolmstead I can't repro.

Can you look at your logs, as upload issues are generally well logged.

**Comment by jeffolmstead** [comment] 2020-03-10 13:10
@deanmarcussen sorry for delay, my computer was turning into a brick so I had to clean it off - back to performance now. No logs are being thrown unfortunately. 

I did some playing around and, if I turn off Azure Media Storage, it functions properly. If I turn it back on, it doesn't work. Azure Media Storage is working fine for the "normal" uploading of media, just seems to be this field.

Here is my text example:

* ContentType: TestUpload
* ContentParts: none
* ContentFields: MediaField - ContentPartFieldSettings: Editor: "Attached"

When my **Azure Media Storage** is enabled, it throws the error.

**Comment by jeffolmstead** [comment] 2020-03-10 13:49
Interesting, "MediaFieldDriver.cs" on line 72 has it's own try / catch block so none of the issues would seem to make it to a log file:

```
try
{
     await _attachedMediaFieldFileService.HandleFilesOnFieldUpdateAsync(items, context.ContentPart.ContentItem);
}
catch (Exception)
{
     updater.ModelState.AddModelError(Prefix, S["{0}: There was an error handling the files.", context.PartFieldDefinition.DisplayName()]);
}
```

Does that make sense or should the exception be passed back to the log? 

The error I have is:
ErrorCode: BlobAlreadyExists
```
The specified blob already exists.
RequestId:e5c6a756-937a-464b-a077-f539d6d1e44b
Time:2020-03-10T13:46:28.5813902Z
Status: 409 (The specified blob already exists.)

ErrorCode: BlobAlreadyExists

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: e5c6a756-937a-464b-a077-f539d6d1e44b
x-ms-version: 2019-02-02
x-ms-error-code: BlobAlreadyExists
Date: Tue, 10 Mar 2020 13:46:28 GMT
Content-Length: 220
Content-Type: application/xml
```

The stack trace is:
```
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.<UploadAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<UploadInternal>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<UploadAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.PartitionedUploader.<UploadAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobClient.<StagedUploadAsync>d__23.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobClient.<UploadAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.FileStorage.AzureBlob.BlobFileStore.<CreateDirectoryAsync>d__20.MoveNext() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.FileStorage.AzureBlob\BlobFileStore.cs:line 296
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.FileStorage.AzureBlob.BlobFileStore.<TryCreateDirectoryAsync>d__10.MoveNext() in C:\projects\orchardcore\src\OrchardCore\OrchardCore.FileStorage.AzureBlob\BlobFileStore.cs:line 144
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Media.Services.AttachedMediaFieldFileService.<EnsureGlobalDirectoriesAsync>d__12.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Media\Services\AttachedMediaFieldFileService.cs:line 69
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Media.Services.AttachedMediaFieldFileService.<HandleFilesOnFieldUpdateAsync>d__11.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Media\Services\AttachedMediaFieldFileService.cs:line 60
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OrchardCore.Media.Drivers.MediaFieldDisplayDriver.<UpdateAsync>d__7.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Media\Drivers\MediaFieldDriver.cs:line 74
```

I am not even uploading a media file while this is throwing an error. Will let you know if I can solve it.

**Comment by deanmarcussen** [comment] 2020-03-10 14:01
yes, we should log there, as without that there's no way to track what's going on.

The issue is related to the change in the Azure.Storage.net library and how it handles directories (it's checking to see if the temp folder and mediafields folder exists).

I'll make a pr later

**Comment by jeffolmstead** [comment] 2020-03-10 14:02
I think i have it. There is a file called "OrchardCore.Media.txt" which is created (every time) and injected into the {tenant}/mediafields/temp folder. Then, this file is tried to move over to {tenant}/temp This works the first time, but the second time the file already exists so it throws an error.  Seems we either have to:

1. Prevent "OrchardCore.Media.txt" from being generated when the temp folder confirmed

I have looked and this is automatically generated in OrchardCore.FileStorage.AzureBlob in the CreateDirectoryAsync method. I am guessing this marker is to make it easier to figure out which module generated the folder. Likely changing that code is not the way to go. 

I am going to debug on source to try and find a real solution.

**Comment by jeffolmstead** [comment] 2020-03-10 14:04
Ok, I believe we are at a similar consensus so I defer to your pr (you will be 100% faster than me in that regard). Thanks so much for looking into this!

**Comment by deanmarcussen** [comment] 2020-03-10 14:37
No worries, yes it's similar to what you have found.

The problem is blob's don't really know about directories. So we use a `OrchardCore.Media.txt` file to force create a directory, but once it has files in it, the `.txt` file is no longer required, so it's not something we can use to check for directory existence.

So the only way with the new storage library to check for a directory, is to start enumerating the directory and see if it has files in it.

And in the case of the `TryCreateDirectoryAsync` it needs to check that a blog doesn't already exist by that name, and then if the folder exists. 
We could actually skip most of the check with blob storage as it would just create the folder when saving to it. 
But to keep in sync with the file system store behaviour (which wouldn't create it) we need to perform the same checks.

**Comment by DariuS231** [comment] 2020-03-11 15:33
Having the same issue... Weird thing is that we have been using Azure Storage for a few months now and it is just now when it started giving this error.  Waiting for the PR to be merged.

**Comment by ruisdias** [comment] 2020-03-11 15:40
I have the same issue as well, waiting to be merged.

**Closed** 2020-03-12 12:13 UTC
Labels: Orchard.Media
