### ISSUE TITLE
 Invalid object name 'OC_TaxonomyIndex'.

### ISSUE THREAD

**Issue by rongconzx** [OrchardCMS/OrchardCore#12943] opened 2022-12-13 14:23 UTC
### Describe the bug
I upgrade the latest Orchard Core(version 1.5) from version 1.0.0.
I tried to create and publish a new taxonomy. But an error occurs It's the same as the migration failure. The logging system just records failed migration for 'OrchardCore.Search.Lucene'. 

I think the migration process stopped when getting an error. So the table `OC_TaxonomyIndex` wasn't created. This issue will be fixed when the ticket [#12940](https://github.com/OrchardCMS/OrchardCore/issues/12940) is fixed?

```
2022-12-13 18:56:17.321 +07:00 [DBG] Executing data migrations for shell 'Default'
2022-12-13 18:56:17.389 +07:00 [INF] Updating feature 'OrchardCore.Search.Lucene'
2022-12-13 18:56:17.393 +07:00 [INF] Updating feature 'OrchardCore.Liquid'
2022-12-13 18:56:17.406 +07:00 [INF] Updating feature 'OrchardCore.Settings'
2022-12-13 18:56:17.406 +07:00 [INF] Updating feature 'OrchardCore.Contents'
2022-12-13 18:56:17.406 +07:00 [INF] Updating feature 'OrchardCore.ContentTypes'
2022-12-13 18:56:17.406 +07:00 [INF] Updating feature 'OrchardCore.Indexing'
2022-12-13 18:56:17.512 +07:00 [ERR] Error while running migration version 0 for 'OrchardCore.Search.Lucene'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at Newtonsoft.Json.Linq.JToken.EnsureValue(JToken value)
   at Newtonsoft.Json.Linq.JToken.op_Explicit(JToken value)
   at OrchardCore.Search.Lucene.Migrations.<>c__DisplayClass2_0.<Create>b__1(ContentPartDefinitionBuilder partBuilder)
   at OrchardCore.ContentManagement.Metadata.ContentDefinitionManagerExtensions.AlterPartDefinition(IContentDefinitionManager manager, String name, Action`1 alteration)
   at OrchardCore.Search.Lucene.Migrations.Create()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at OrchardCore.Data.Migration.DataMigrationManager.UpdateAsync(String featureId)
2022-12-13 18:56:17.564 +07:00 [INF] Updating feature 'OrchardCore.Taxonomies'
2022-12-13 18:56:17.648 +07:00 [DBG] Testing Azure Media Storage container cms existence
2022-12-13 18:56:18.462 +07:00 [DBG] Azure Media Storage container cms created.
2022-12-13 18:56:19.052 +07:00 [INF] Begin Routing Request
2022-12-13 18:56:20.625 +07:00 [INF] Start installing Hangfire SQL objects...
2022-12-13 18:56:21.163 +07:00 [INF] Hangfire SQL objects installed.
```

### To Reproduce
1. Upgrade the latest Orchard Core(version 1.5) from version 1.0.0
2. Enable feature Taxonomies
3. Publishing the Taxonomy 

### Screenshots
![image](https://user-images.githubusercontent.com/9065933/207358678-d6eb4b0a-6a12-45e1-9402-4d3d47e2bab8.png)

**Comment by MikeAlhayek** [comment] 2022-12-14 17:35
@Skrypt probably something null in the migration script.

>> Error while running migration version 0 for 'OrchardCore.Search.Lucene'.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'value')

**Comment by MikeAlhayek** [comment] 2022-12-14 17:36
Same as #12940

**Comment by Skrypt** [comment] 2022-12-14 19:55
That's just a consequence of having Migrations failing because that table is now missing in your database. At this point, I would simply create a new tenant from a clean source code version of OC. Then do a SQL compare on both to repair afterward if necessary. That's one option to consider. Else, without clear repro steps, I can't really know what is happening exactly. I would need to have the ContentItem JSON that makes the OrchardCore.Search.Lucene migration fails to reproduce it and fix it. All I can say is that we fixed the Migration recently. Maybe you want to restart that migration from 1.0.x to 1.5 by moving from one to the other one version at a time to prevent this from happening.

**Comment by MikeAlhayek** [comment] 2023-02-16 22:41
@Skrypt are we saying this is not a real issue? It's tagged with 1.6. Can we close it?

**Comment by sebastienros** [comment] 2023-02-21 20:50
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/12757, should be fine when we ship 1.6

**Closed by sebastienros** 2023-02-21 20:50 UTC
Labels: bug :bug:
