### ISSUE TITLE
MySQL connection Error

### ISSUE THREAD

**Issue by don-dev** [OrchardCMS/OrchardCore#873] opened 2017-07-21 15:43 UTC
While setting up, An error occurred while initializing the datastore: Unable to connect to any of the specified MySQL hosts.

I have other sites connecting to this server correctly. my connection string looks like:
`server=localhost;user id=<username>;password=<pw>;port=8889;database=Orchard;`

also as it fails, the screen reloads, displays the connection error, but removes these fields from the setup form.

**Comment by agriffard** [comment] 2017-10-01 10:13
Related to #944

**Comment by sebastienros** [comment] 2017-10-02 16:41
Duplicate of #944

**Closed by sebastienros** 2017-10-02 16:41 UTC
