### ISSUE TITLE
Cannot save content items with Content Fields Indexing (SQL) and Content Localization activated

### ISSUE THREAD

**Issue by saciervo** [OrchardCMS/OrchardCore#5187] opened 2020-01-02 10:35 UTC
Had the problem on a multi-language customer website after activating Content Fields Indexing (SQL). But verified/reproduced it with a clean install of `Version 1.0.0-rc1-10004` (both SQL Server and SQLite)

![image](https://user-images.githubusercontent.com/707898/71662991-d0646f80-2d53-11ea-96b2-bf8fc0291bbc.png)

**Comment by deanmarcussen** [comment] 2020-01-02 14:16
Although the error is a little different I suspect this issue is caused by a bug we had in RC1.

It should be fixed in dev (I couldn't repro)

See https://github.com/OrchardCMS/OrchardCore/issues/4406

**Closed** 2020-01-02 20:44 UTC

**Comment by saciervo** [comment] 2020-01-02 21:22
Yes, can confirm. I just tried `1.0.0-rc1-11358` and it works again. Although now it seems you can't create a second localization besides the default one. But I guess this is because of the bleeding edge ;)

**Comment by sebastienros** [comment] 2020-01-02 23:11
You can create other localization. Should not be broken
