### ISSUE TITLE
Response Compression causes content encoding error on tenants

### ISSUE THREAD

**Issue by DemeSzabolcs** [OrchardCMS/OrchardCore#11295] opened 2022-03-04 15:27 UTC
### Describe the bug
Enabling Response Compression on a different tenant other than the Default one causes content encoding error on that tenant's homepage.

### To Reproduce
1. Go to _Dashboard_ -> _Configuration_ -> _Tenants_
2. Click on _Add Tenant_ and create a new tenant.
3. Setup the newly created tenant (let's call it _example tenant_).
4. Go to the example tenant's  _Dashboard_ -> _Configuration_ -> _Features_ and enable **_Response Compression_**.
5. Go to the example tenant's homepage (`~/exampleTenant`). OR go back to the default tenant's _Dashboard_ -> _Configuration_ -> _Tenants_ and click on the example tenant's _View_ button.
6. See that the page doesn't load, and there is a content encoding error.

### Expected behavior
Tenants should not have content encoding errors on the homepage after enabling **_Response Compression_**.

**Comment by DemeSzabolcs** [comment] 2022-03-04 19:51
That's strange. I used the _Software as a Service_ recipe, but I was able to reproduce the error with the _Blog_ recipe too. 

I'm sure that this is a bug because I was able to reproduce it on a completely different PC.

**Comment by hishamco** [comment] 2022-03-04 20:16
Could you please share a GIF screenshot?

**Comment by Skrypt** [comment] 2022-03-04 21:43
There's pretty much nothing in that ResponseCompression module either than we enable the ASP.Net middleware.

**Comment by hishamco** [comment] 2022-03-04 22:26
You are right, may be there's a caching issue

**Comment by DemeSzabolcs** [comment] 2022-03-05 02:30
![response compression](https://user-images.githubusercontent.com/80963259/156863792-8fd9ac20-3fb5-4015-8df5-3856a6fc0fa4.gif)

Sometimes it doesn't give a content encoding error, instead displays random characters, as you can see in the gif. I reproduced this after cleaning browser caches and cookies (Chrome and Firefox) and on a different computer.

**Comment by jtkech** [comment] 2022-03-05 02:51
I could repro

![Encoding issue](https://user-images.githubusercontent.com/8586360/156865000-0d9317d6-f06e-4a45-a52b-1984b8c5624a.png)

**Comment by jtkech** [comment] 2022-03-05 02:59
And if in place of `/tenant1` I add an ending slash `/tenant1/` it works

**Comment by jtkech** [comment] 2022-03-05 03:37
And seems to work if I run the app from the command line not from Visual Studio

     bin/debug/net5.0/orchardcore.cms.web.exe

**Comment by jtkech** [comment] 2022-03-05 03:42
Maybe related https://github.com/dotnet/aspnetcore/issues/32767#issuecomment-842691720

**Comment by jtkech** [comment] 2022-03-05 04:05
So seems to be related to the hot reload feature under VStudio, after doing the following as commented here https://github.com/dotnet/aspnetcore/issues/32767#issuecomment-975583962 it was working.

> Can confirm that the injection of the scripts for the hot reloading feature is what triggers this.
Had to rip it out completely to get a working solution back. I.e. go specifically into Tools -> Options -> Debugging ->.NET / C++ Hot reload and disable all the server-side C# hot reloading features altogether in addition to everything hot-reloading related under Tools -> Options -> Projects & Solutions -> ASP.NET Core.

**Comment by Skrypt** [comment] 2022-03-05 06:04
I'm using Visual Studio 2022 17.1.0 and I can't repro this when debugging with IISExpress and Hot Reload enabled. Will try different things and report here.

**Comment by jtkech** [comment] 2022-03-05 06:14
I'm using Version 17.0.5, will try to upgrade tomorrow ;)

**Comment by hishamco** [comment] 2022-03-05 08:44
Me too when I'm using the first version of 2022 I'm facing some issues while running the app ;) but may be the issue related to an ASP.NET Core issue as @jtkech mentioned above

**Comment by jtkech** [comment] 2022-03-06 22:08
So in my case was caused by enabling `Projects and Solutions > ASP.NET Core > CSS Hot Reload`

Upgrading to Visual Studio 2022 17.1.0 fixed the issue

**Comment by Skrypt** [comment] 2022-03-06 23:51
Please report it on the aspnetcore repo issue.

**Comment by hishamco** [comment] 2022-03-13 19:07
So can we close this if it's VS related? We could document this because one may spent many hours on issues that related to VS

**Comment by DemeSzabolcs** [comment] 2022-03-16 00:19
Yes, what @jtkech said, solved it. Thanks!

**Comment by jtkech** [comment] 2022-03-16 00:39
Okay cool, thanks for confirming

**Closed by jtkech** 2022-03-16 00:39 UTC
Labels: bug :bug:, Response Compression
