### ISSUE TITLE
Blob storage - misconfiguration deletes all content

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#13714] opened 2023-05-19 07:29 UTC
### Describe the bug
It seems that all content of blob storage got deleted when I accidentally misconfigured appsettings. 

### To Reproduce

Use this in appsettings

 "OrchardCore_Media_Azure": {
        "BasePath": "OrchardCore_Media_Azure"
      }

(see that value of basepath is same as appsetting section name)

All content is deleted/archived on blob storage

### Desired behavior

Misconfiguration of basepath does not delete other folders

**Comment by hishamco** [comment] 2023-05-20 09:26
Why it should be deleted?

**Comment by MikeKry** [comment] 2023-05-21 06:55
Well, I think it should not be deleted and that it may be a bug. This happened to me when I added new tenant and it deleted also all other tenants blob storage data. I am using 1 blob with different base paths.

**Comment by hishamco** [comment] 2023-05-21 12:51
> Well, I think it should not be deleted and that it may be a bug

That's what I expect. Did you delete the tenant or did an invalid configuration delete the BLOB?

**Comment by MikeKry** [comment] 2023-05-25 08:04
@hishamco 

Exact scenario was:
* Added new tenant settings to appsettings.json for multiple tenants
* one of them had typo (as seen in original post)
* deployed this configuration to server
* launched autosetup for new tenant, autosetup recipe includes media files
* after initializing multiple tenants by autosetup, blob storage was empty - except there was folder "OrchardCore_Media_Azure" and one original folder from other tenant (should be 9 tenant folders)

There is also other possibility, why this happened: some of **already existing** tenants did not have BasePath configured, so they could possibly cause removal of all data? But by default, when they do not have configured folder, I just see all folders from blob.

**Comment by hishamco** [comment] 2023-05-25 11:39
@Piedone did you come across this issue before why Lombiq maintaining DotNest which uses Azure heavily?

/cc @jtkech

**Comment by hishamco** [comment] 2023-05-25 13:13
Neither I :)

**Comment by sebastienros** [comment] 2023-05-25 17:25
Let's try to reproduce with the provided steps. @MikeKry maybe you'd have some time to debug it locally and understand what is happening.

**Comment by MikeKry** [comment] 2023-05-31 10:02
I will be creating new tenants soon, so I can try to reproduce this

**Comment by sebastienros** [comment] 2023-07-11 19:20
Any news on this one?

**Comment by jtkech** [comment] 2023-08-01 01:40
@MikeKry 

Just tried locally with the `Azurite` emulator, indeed if I configure a wrong `BasePath` equal to `OrchardCore_Media_Azure` I no longer see my images, but if I revert back to the right config I can see them again. I saw that you don't configure the `ContainerName`, this is required to activate the feature.

That said you are talking about `AutoSetup` multiple Tenants, this means that your `ContainerName` and/or your `BasePath` need to be `Templated` (liquid syntax) so that their values are different per tenant.

Hmm, unless you are configuring these options per tenant for example by providing them under tenant sections whose names are equal to the tenant names intended to be auto setup. Or by editing the tenant specific `appsettings.json` which are in tenant specific folders `App_Data/Sites/TenantName`.

If that's the case, better to define options once but by providing templated values.

So for now I'm closing this one but feel free to re-open it if it is still an issue, and in that case can you provide more info on how blob storage is configured per tenant.

**Closed by jtkech** 2023-08-01 01:40 UTC
Labels: bug :bug:
