### ISSUE TITLE
NRE by RuleService.EvaluateAsync When Migrating Site

### ISSUE THREAD

**Issue by davidhayden** [OrchardCMS/OrchardCore#9640] opened 2021-06-08 19:39 UTC
Attempting to migrate a website from RC2-15222 and received the attached error when running the website after upgrading to the latest source code in the Dev branch. Note that I have received this same error when upgrading other websites as well.

There are no special layer rules on the website. Just the default **Always** and **Homepage** rules.

Is this an expected error now that we have the new rules engine?

![rule-service-error](https://user-images.githubusercontent.com/96801/121246924-a62faf00-c86f-11eb-9438-c1ee55479f27.png)

**Comment by deanmarcussen** [comment] 2021-06-10 15:39
Closing as a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/9641

**Closed by deanmarcussen** 2021-06-10 15:39 UTC
Labels: bug
