### ISSUE TITLE
Set smtp settings though appsettings.json

### ISSUE THREAD

**Issue by jersiovic** [OrchardCMS/OrchardCore#6264] opened 2020-05-25 07:45 UTC
Is it possible to set smtp settings though appsettings.json and by extension by environment vars?
We tried it without success?

If not, would you accept a PR to allow that?

**Comment by deanmarcussen** [comment] 2020-05-25 08:42
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6036

so yes, but we need to figure out how the ui copes :)

You can set them yourselves (I think @Piedone included a link in the issue) by registering your own `services.AddTransient<IConfigureOptions<SmtpSettings>, SmtpSettingsConfiguration>();` or using `services.PostConfigure<SmtpSettings>(x => x)`

**Comment by Piedone** [comment] 2020-05-25 13:36
You can set all the [SMTP settings](https://docs.orchardcore.net/en/dev/docs/reference/modules/Email/#smtp-settings) from [configuration](https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/), including appsettings. If you want to do that from code the example there is actually for `SmtpSettings` too

Having SMTP settings on the UI too is useful, I'd be very much against removing it.

**Comment by cesarktp** [comment] 2020-05-26 08:57
If I configure smtp settings from the UI, sending email works (to a file). If I don't configure the smtp settings from the UI and use this appsettings.json:

{
	"OrchardCore":{
		"OrchardCore.Email":{
			"DefaultSender":"sender@contoso.com",
			"DeliveryMethod":"SpecifiedPickupDirectory",
			"PickupDirectoryLocation":"/app/App_Data",
			"Host":null,
			"Port":25,
			"AutoSelectEncryption":false,
			"RequireCredentials":false,
			"UseDefaultCredentials":false,
			"EncryptionMethod":"None",
			"UserName":null,
			"Password":null
		}
	}
}
email sending (to a file again) doesn't work. The appsettings.json is placed in /app/App_Data 
What's wrong in the appsettings.json?

**Comment by jersiovic** [comment] 2020-05-26 19:03
@cesarktp is a felllow at the IT deparment I'm trying to make he falls in love with Orchard. 
Any help with this task will be very welcome :)

**Comment by Piedone** [comment] 2020-05-26 19:11
I wanted to update the docs first as an answer :D.

This won't work by default. Maybe the docs is misleading, as was my message but unless the module specifically supports it you won't be able to just add such static configs. For every module supporting `IOptions`-based configs you can, however, set up arbitrary configuration from your web project's `Startup` class. If you want to load this config from appsettings (including Orchard's cascading config files) then you need to retrieve those values via `IShellConfiguration`.

**Comment by jersiovic** [comment] 2020-05-26 19:54
Ok very clear. we will do as you explain.  Thank you!

**Comment by Piedone** [comment] 2020-05-26 23:35
So I think this confusion is cleared up. Added some clarification to the docs too.

**Closed by Piedone** 2020-05-26 23:35 UTC
