### ISSUE TITLE
Do not show draft content item in the list.

### ISSUE THREAD

**Issue by tanriverdim** [OrchardCMS/OrchardCore#1435] opened 2018-02-02 20:22 UTC
The admin panel also does not show draft content item in the list.

**Comment by jtkech** [comment] 2018-02-02 20:33
It works on my side, is your item type defined as `Listable` in the type definition

**Comment by sebastienros** [comment] 2018-02-02 20:34
And if this is a published item that also has a draft, then there is a button on the right to manipulate it.

**Comment by tanriverdim** [comment] 2018-02-02 21:11
my english is a little bad.

I guess I could not tell right.

```
public override IDisplayResult Display(ListPart listPart, BuildPartDisplayContext context)
     {
            return Shape<ListPartViewModel>("ListPart", async model =>
            {
                var pager = await GetPagerAsync(context.Updater, listPart);

                model.ListPart = listPart;
                model.ContentItems = (await QueryListItemsAsync(listPart, pager, true)).ToArray();
                model.ContainedContentTypeDefinitions = GetContainedContentTypes(listPart);
                model.Context = context;
                model.Pager = await context.New.PagerSlim(pager);
            })
            .Location("Detail", "Content:10")
            .Location("DetailAdmin", "Content:10");
        }
```
change

```
public override IDisplayResult Display(ListPart listPart, BuildPartDisplayContext context)
     {
            return Shape<ListPartViewModel>("ListPart", async model =>
            {
                var pager = await GetPagerAsync(context.Updater, listPart);

                model.ListPart = listPart;
                model.ContentItems = (await QueryListItemsAsync(listPart, pager, true)).ToArray();
                model.ContainedContentTypeDefinitions = GetContainedContentTypes(listPart);
                model.Context = context;
                model.Pager = await context.New.PagerSlim(pager);
            })
            .Location("Detail", "Content:10");

           return Shape<ListPartViewModel>("ListPart", async model =>
            {
                var pager = await GetPagerAsync(context.Updater, listPart);

                model.ListPart = listPart;
                model.ContentItems = (await QueryListItemsAsync(listPart, pager, **FALSE** )).ToArray();
                model.ContainedContentTypeDefinitions = GetContainedContentTypes(listPart);
                model.Context = context;
                model.Pager = await context.New.PagerSlim(pager);
            })
            .Location("**DetailAdmin**", "Content:10");
        
```}

**Comment by sebastienros** [comment] 2018-02-08 20:30
Can someone explain what the issue is based on the new code samples?

**Comment by sfmskywalker** [comment] 2018-04-22 10:29
I think I see. Looking at @tanriverdim 's code changes, he wants to include **published** items only in the "DetailAdmin" location. I haven't tried the list feature yet, so I'm not yet sure if it would make sense or not.

**Comment by tanriverdim** [comment] 2018-05-26 21:44
I'm misunderstood. :)
Actually #1860

**Comment by agriffard** [comment] 2018-05-26 21:47
Ok, we managed to repro it in #1859 so I close this one and it will be solved when the PR is merged.

**Closed by agriffard** 2018-05-26 21:47 UTC
