### ISSUE TITLE
Open ID JWT token format - payload is not valid JSON

### ISSUE THREAD

**Issue by ns8482e** [OrchardCMS/OrchardCore#12711] opened 2022-10-24 16:51 UTC
### Describe the bug

In Open ID Connect -> Authorization Server, setting Token Format to JWT generates JWT token however, Payload is not valid json when trying to validate on jwt.io

![image](https://user-images.githubusercontent.com/23270244/197582072-fade567b-888d-4a10-a143-158f2429a856.png)

Is there a way to to configure to generate JWT with valid JSON data in payload?

**Comment by sebastienros** [comment] 2022-11-03 17:57
@kevinchalet any insight?

**Comment by kevinchalet** [comment] 2022-11-03 18:01
Not a bug: OpenIddict encrypts all JWT tokens, including access tokens. While it's standard (it's called JWE, for JSON Web Encryption), it's not supported by jwt.io.

Closing.

**Closed by kevinchalet** 2022-11-03 18:01 UTC
Labels: bug :bug:
