### ISSUE TITLE
Possible Design Bug: reserved word needed for prefix

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4988] opened 2019-12-09 21:38 UTC
While looking at the mainifest file for a theme i noticed there was no prefix word used before all the css and javascript files. For example the agency theme just uses "TheAgencyTheme" right off the root fo the website.

Maybe look at Drupal or some other site and see how they handle the routes of the theme files.

I also have a similar issue open here:
https://github.com/OrchardCMS/OrchardCore/issues/4986

**Comment by hishamco** [comment] 2019-12-09 23:21
Yep, there's no prefix, but how this may help or make things easier?

**Comment by JoshTango** [comment] 2019-12-09 23:43
well you could create a name collision with a route someone wans to use.
Imagine someone invented a theme called Blog.
well this could create a name collision for blog entries.

**Comment by hishamco** [comment] 2019-12-09 23:51
The collision and overriden may happen if both styles in the same folder

Did you try to create two tenants with the same theme, for instance Agency theme, also you could add a custom one

**Comment by hishamco** [comment] 2019-12-09 23:52
Perhaps you are right, but we need a steps to reproduce the issue if there's

**Comment by JoshTango** [comment] 2019-12-09 23:56
I personally have no issue, I am thinking from a architects perspective.
First thing architect done is look for guidance or look at compittion
What does drupal do?

**Comment by hishamco** [comment] 2019-12-10 00:01
The prefix is useful for many scenarios, one of them is database tables, OC allow use to provide a table prefix in case more than one tenant can use the same database

Regarding the themes in Drupal I don't have a look while I know Drupal little bit, but sure for a reason

**Comment by hishamco** [comment] 2019-12-10 00:02
For that I will close this one, but you could have a try and if there's an issue feel free to open a new issue or comment here

**Closed by hishamco** 2019-12-10 00:02 UTC

**Comment by jtkech** [comment] 2019-12-10 00:07
A theme (or a module) static file `~/MyTheme/SomeScript.js` is served from the virtual path `Areas/MyTheme/wwwroot/SomeScript.js`.

`MyTheme` is the theme = area = assembly name and most of the time = project name. And we can't have 2 themes / areas / ... with the same name.

**Comment by JoshTango** [comment] 2019-12-10 00:31
I wasn't worried about 2 themes with same name.
I was just wondering if there should be some common name off of the root path called styles or css or something like that but whatever

**Comment by jtkech** [comment] 2019-12-10 01:06
Oups, sorry if i misunderstood the concern ;)

Hmm, maybe you are thinking about a static file under your app wwwroot folder e.g

    wwwroot/MyTheme/SomeScript.js

That would be also served from `~/MyTheme/SomeScript.js`

As i remember, in this case the one under the app wwwroot folder will be served because the app static file provider has an higher priority than the static file provider that serves the static files from modules / themes. But this is an expected behavior, it allows to override some modules / themes static files from the app.

**Comment by hishamco** [comment] 2019-12-10 01:48
> As i remember, in this case the one under the app wwwroot folder will be served because the app static file provider has an higher priority than the static file provider that serves the static files from modules / themes

You 're right

**Comment by JoshTango** [comment] 2019-12-10 12:42
in drupal they use /themes/ off of the root
so in drupal it would be www.mysite/themes/theagencytheme/whatever.css

**Comment by hishamco** [comment] 2019-12-10 15:06
Every CMS has it's own design goals

**Comment by JoshTango** [comment] 2019-12-10 15:22
um while true, I think this is important

**Comment by hishamco** [comment] 2019-12-10 15:26
I need you to differentiate between a tenant has it's own theme and websites that have multiple themes and one is selected

**Comment by JoshTango** [comment] 2019-12-10 15:27
not sure precisely what you are asking.
A tenant could not be called theme.
each tenant would have a theme sub folder for its theme

**Comment by hishamco** [comment] 2019-12-10 15:35
I mean OC doesn't need to have a themes folder unless it supports more than one theme

**Comment by JoshTango** [comment] 2019-12-10 15:36
This issue was only related to the collision aspect and nothing else

**Comment by hishamco** [comment] 2019-12-10 15:40
As we talked earlier there's no collision, so feel free filed an issue if you can reproduce a collision issue

**Comment by JoshTango** [comment] 2019-12-10 15:47
well I think its best to have"
www.mysite.com/themes/theagencytheme

this is regardless if it supports multiple themes or not

**Comment by hishamco** [comment] 2019-12-10 16:04
Disagree. Not necessarily to add it into the route to support multiple themes

**Comment by JoshTango** [comment] 2019-12-10 16:28
I think my point is lost
