### ISSUE TITLE
Prevent ModularBackgroundService from getting stuck on an exception

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#8180] opened 2020-12-30 00:24 UTC
In case of specific low-level exceptions during a background task execution, the ModularBackgroundService will stop permanently (see an example exception below). It can be restarted only if we restart the app. Is it possible to somehow log the exception and prevent stopping the service?

To clarify, this is not about figuring out what caused this exception, but to figure out how to avoid stopping ModularBackgroundService.

Example exception that caused stopping the ModularBackgroundService:

```
2020-12-29 17:32:36.5163||||OrchardCore.Modules.ModularBackgroundService|ERROR|Error while executing 'ModularBackgroundService', the service is stopping. System.NullReferenceException: Object reference not set to an instance of an object.
   at YesSql.Session.ReleaseConnection()
   at YesSql.Session.CommitTransaction()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 308
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 210
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass9_0.<<RunAsync>b__0>d.MoveNext() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 137
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 76    at YesSql.Session.ReleaseConnection()
   at YesSql.Session.CommitTransaction()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 308
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Shell\Scope\ShellScope.cs:line 210
   at OrchardCore.Modules.ModularBackgroundService.<>c__DisplayClass9_0.<<RunAsync>b__0>d.MoveNext() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 135
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.EnumerableExtensions.<>c__DisplayClass0_1`1.<<ForEachAsync>b__1>d.MoveNext() in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore.Abstractions\Modules\Extensions\EnumerableExtensions.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at OrchardCore.Modules.ModularBackgroundService.RunAsync(IEnumerable`1 runningShells, CancellationToken stoppingToken) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 137
   at OrchardCore.Modules.ModularBackgroundService.ExecuteAsync(CancellationToken stoppingToken) in C:\Agent2\work\OCORE-Lombiq\src\OrchardCore\OrchardCore\Modules\ModularBackgroundService.cs:line 76
```

**Comment by jtkech** [comment] 2020-12-30 00:50
I totally agree ;)

We already use a try / catch to execute each task but not on the whole `await shellScope.UsingAsync()`, and in the above trace it fails before disposing the shell scope which calls `YesSql.Session.CommitAsync()`

I will fix it

**Comment by Piedone** [comment] 2020-12-30 00:56
I think maybe the solution is as straightforward as moving this try-catch into the `while` in `ModularBackgroundService`?

**Comment by jtkech** [comment] 2020-12-30 01:04
Yes, this is what i would want to do but i want to test what happens when you stop a process, e.g. run from the command line then ctrl + c, as i remember it throws a specific exception, but not sure and I don't remember which one

I will try it

**Comment by Piedone** [comment] 2020-12-30 01:05
Thank you!

**Comment by jtkech** [comment] 2020-12-30 01:28
That's okay, here also it just cancels the stopping token

**Comment by barthamark** [comment] 2020-12-30 11:08
Thank you @jtkech :) Once we move the try-catch into the `while`, is it possible that it will flood the log file with exceptions?

**Comment by jtkech** [comment] 2020-12-30 15:03
@barthamark 

Good point, maybe you remind me step by step why I didn't do it originally ;)

Yes, if the issue is persistent, one log per minute

What are you suggesting?

Maybe a counter to check if > MaxExceptionCount, but reset this counter after a certain amount of time

**Comment by Piedone** [comment] 2020-12-30 15:07
I think retrying perpetually and logging it is fine. If it floods the logs it's still because of a critical issue. And I think it also should be retried again and again because if e.g. the DB is down the background tasks should still resume if it comes back after two hours.

**Comment by jtkech** [comment] 2020-12-30 15:12
Okay cool, and that's the simplest solution, nothing to do !

**Comment by Piedone** [comment] 2020-12-30 15:14
Yep :).

**Closed** 2020-12-30 17:44 UTC
Labels: bug
