### ISSUE TITLE
GraphQl Subscription support

### ISSUE THREAD

**Issue by rserj** [OrchardCMS/OrchardCore#6553] opened 2020-07-01 14:07 UTC
Consider adding support for GraphQl [Subscriptions](http://spec.graphql.org/June2018/#sec-Subscription)
If it will be hard to implement with GraphhQL.Net we might think about switching to [Hot Chocolate](https://hotchocolate.io/), it looks more appealing to me.

**Comment by agriffard** [comment] 2020-07-01 14:11
Duplicate of #4489

**Closed by agriffard** 2020-07-01 14:11 UTC
