### ISSUE TITLE
Do not login administrator access management link can not jump

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1044] opened 2017-09-29 09:33 UTC
Do not login administrator access management link can not jump to "/ Login? ReturnUrl =% 2Fadmin"

<<Google Chrome  61.0.3163.100>>
![6](https://user-images.githubusercontent.com/28694676/31010064-253c74b4-a53c-11e7-982b-7f87309aa51e.gif)

**Comment by agriffard** [comment] 2017-09-30 15:14
Duplicate of #985 .

**Closed by agriffard** 2017-09-30 15:14 UTC
