### ISSUE TITLE
When we update any tenant smtp configuration or enable/disable features whole application restart again. 

### ISSUE THREAD

**Issue by MohitNaroliya** [OrchardCMS/OrchardCore#9858] opened 2021-07-05 12:05 UTC
### Describe the bug
We have many tenants and managing with single app service, when we change any tenant SMTP configuration or Enable/Disable features the whole application restart again and our all the tenants website got down until the app pool restart. 

### To Reproduce
1. Go to any tenant website and change SMTP configuration or Enable/Disable feature. 
2. Now you will see whole application restart again. 

### Expected behavior
Any configuration change should be affect and reload only current tenant not the whole app pool.

**Comment by deanmarcussen** [comment] 2021-07-05 13:46
How have you identified that this is occuring?

Restarting a shell doesn't restart the app pool - they're quite different things.

Can you provide some more details please.

**Comment by liketodev1** [comment] 2021-07-08 15:09
@deanmarcussen - When we change SMTP configuration or enable/disable feature of any tenant we got 502 exception screen and whole site and tenant urls down for sometime until the app not restart again.

**Comment by Skrypt** [comment] 2021-07-08 15:16
Look at your logs and report them here. Something fails when restarting those tenants.

**Comment by liketodev1** [comment] 2021-07-09 13:49
![image](https://user-images.githubusercontent.com/54404116/125087745-60723a80-e0ea-11eb-8f75-cf9b150f1719.png)
Today I tried on my development site and was able to reproduce after this error all tenants site went down and taken to wakeup, trying to figure out logs on Azure insight.

**Comment by MohitNaroliya** [comment] 2021-07-09 13:52
![image](https://user-images.githubusercontent.com/26460323/125088432-04f47c80-e0eb-11eb-863b-467c1fbb95d7.png)
Today I tried on my development site and was able to reproduce after this error all tenants site went down and taken to wakeup, trying to figure out logs on Azure insight.

**Comment by Skrypt** [comment] 2021-07-09 14:03
Nothing in the /App_Data/logs folder?

**Comment by MohitNaroliya** [comment] 2021-07-16 09:41
@Skrypt - No there is nothing in the /App_Data/logs folder..

**Comment by deanmarcussen** [comment] 2021-07-20 11:51
This does not happen on the dev feed, or any of the sites I have in production.

@MohitNaroliya you need to turn further debugging on, i.e. increase the log level output to at least Debug, and send us some log files please

**Comment by Piedone** [comment] 2024-04-15 22:16
Closing due to no reply from author.

**Closed by Piedone** 2024-04-15 22:16 UTC
Labels: bug :bug:
