### ISSUE TITLE
Deployment plan failed to execute with related user settings

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8685] opened 2021-02-27 17:04 UTC
I enabled all the user features like registration and recaptcha and login and I also added them to my deployment plan. 
When I tried to execute my deployment plan is failed and said error.

**Comment by JoshTango** [comment] 2021-02-27 17:06
Ok I am going to remove them all and add one by one to find the one causing the problem.

**Comment by JoshTango** [comment] 2021-02-27 17:34
All are fine except the Login Settings.
That one throws an error if you add it to the deployment plan.

Not e that I had toggled use site theme for login on and off.

**Comment by hishamco** [comment] 2021-03-02 03:26
Could you please share the exception details and attach a sample recipe if it's possible

**Comment by JoshTango** [comment] 2021-03-02 12:58
It did not show me the details.

**Comment by deanmarcussen** [comment] 2021-03-02 20:20
You'll have to look in your logs @JoshTango otherwise noone will ever be able to know what the issue is.

**Comment by JoshTango** [comment] 2021-03-05 00:35
when I can reproduce I will do that

**Comment by Piedone** [comment] 2024-05-21 14:47
Closing due to no reply update the author.

**Closed by Piedone** 2024-05-21 14:47 UTC
Labels: bug :bug:
