### ISSUE TITLE
How to physically delete a ContentItem ? 

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6841] opened 2020-08-06 05:38 UTC
`IContentManager` only provide a logical deletion, how can I physically delete a ContentItem ? 

        /// <summary>
        /// Removes <see cref="ContentItem.Latest"/> and <see cref="ContentItem.Published"/> flags
        /// from a content item, making it invisible from the system. It doesn't physically delete
        /// the content item.
        /// </summary>
        /// <param name="contentItem"></param>
        Task RemoveAsync(ContentItem contentItem);

**Comment by hishamco** [comment] 2020-08-06 06:35
What if you create `ContentHandler` and override`IContentHandler.RemovingAsync()` to delete the content item permenantly

**Comment by deanmarcussen** [comment] 2020-08-06 06:48
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6056

Someone could implement the feature.

**Closed by deanmarcussen** 2020-08-06 06:48 UTC

**Comment by aaronamm** [comment] 2024-05-03 15:27
@hishamco I right now use your suggestion as how to hard remove a content item.
