### ISSUE TITLE
Media Library Edit filename issue

### ISSUE THREAD

**Issue by KapilChouhanAst** [OrchardCMS/OrchardCore#16162] opened 2024-05-27 06:07 UTC
### To Reproduce
1. Go to the Media Library
2. Go to any file
3. click on the edit button
4. change the filename and save
5. click on the view button, It will open the file URL in the new tab, but the file does not exist

### Expected behavior
When editing a filename, the file URL should update immediately, and upon clicking the view button, it should reflect the new filename URL.

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/78483178/99c2352b-70c4-47aa-8ef0-414a070fa13a)

**Comment by MikeAlhayek** [comment] 2024-05-27 17:40
@KapilChouhanAst isn't this a duplicate of #16163? Can we close this one and keep the other one open?

**Closed** 2024-05-27 19:01 UTC
Labels: duplicate

**Comment by Piedone** [comment] 2024-05-27 20:48
These two are different issues. The other one is about special characters (or at least the plus sign) in the file name. This is about the View link not updating when changing the file name. The repro steps are clear on these.

However, this has been fixed in the latest `main` already and will be part of OC 2.0.
