### ISSUE TITLE
Lucene Queries documentation

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#3550] opened 2019-04-30 12:21 UTC
Lucene Queries documentation needs more work:

* It needs to document on how to pass parameters in the query on the admin UI and via code.
* It is not clear whether it is possible to select what fields to return.
* It is not clear on how to include Content Type parts/fields in the index. The facility is available in the UI but unless you know it, it's not obvious.
* It is not clear how to find the name of the stored field once you enable indexing a Content Type parts/field.
* The UI links directly to the Elastic Search API documentation but it's unclear how many of the Elastic Search syntax is actually supported. `_source` does not seem to be supported for example.
* There is no general discussion on what Lucene module can be actually used for in Orchard Core. The Blog Theme for example has a Lucene query but it does not have paging.
* In the Admin UI, there are commands to `Reset` and `Rebuild`. It's not clear what's the difference between these two.

**Comment by Skrypt** [comment] 2019-04-30 12:25
Need examples of using "Liquid" params {{ param }} and using conditions {% if param != null %}.
I think people need to know that they can use Liquid in their Lucene Queries and to understand the fact that a Lucene Query is a Liquid Template.

**Comment by dodyg** [comment] 2019-05-01 08:25
It's also not obvious how to perform *count* query. When you are doing paging e.g. for blog posts, you need total count of all posts.

**Comment by Skrypt** [comment] 2019-05-01 13:27
Doing a count is not scalable so it's been intentionally not documented / recommended.

**Comment by Skrypt** [comment] 2019-10-18 02:30
Lucene count issue is fixed with #4554

**Comment by agriffard** [comment] 2020-02-08 16:05
Here is a basic Lucene query you can run from the admin:
```
{
  "from": {{ from }},
  "size": {{ size }},
  "query": {
    "terms": { "Content.ContentItem.FullText": ["{{ terms }}"] }
  }
}
```
with parameters:
`{ from: 0, size: 10, terms: "terms" }`

See also #4825

**Comment by hung-doan** [comment] 2020-08-23 22:07
thanks @dodyg, unfortunately changing it to true didn't help. I got the same error tho. 
```
{
  "query": {
    "bool": {
      "filter": {
        "term": {
          "Content.ContentItem.Published": true
        }
      }
    }
  }
}
```

**This bellow simple query did work**, that mean It only work with limited query template?. I don't know, but I don't want to risk myself with an approach with the un-controllable approach 😞 
```
{
  "query": {
	"term": {
	  "Content.ContentItem.Published": "true"
	},
  }
}
```

any thought on this @Skrypt  ?

**Comment by hung-doan** [comment] 2020-08-23 22:10
@dodyg good idea about the DB index, is there any guide on this ?. I want to be able to index multiple Content-Type in the same query. It must support Full-Text Search as well.

**Comment by Skrypt** [comment] 2020-08-24 06:23
If you want full-text search then I advise you staying with Lucene. Though indexing also is a good idea for quicker SQL transactions. These are 2 different things.

Here, if the issue is that the Lucene Query "filter" is not working properly, then we need to fix it.
But finding specific Content Items of multiple or single Content Types is easily achievable with the ElasticSearch / Lucene Queries. I will, when I have time, produce some Lucene Query examples for most common needs but it is really in the end a learning process of the ElasticSearch Query by looking at the documentation. Of course, some things are not yet working because the ElasticSearch Query language is based on top of the Lucene Java implementation which also has more functionalities than it's .NET Lucene implementation.

Filter here should surely work in OC. I'll try to take a look.

**Comment by Skrypt** [comment] 2020-08-24 06:39
Ok, found where is the issue (I think).
CreateFilteredQuery() in BooleanQueryProvider class.

**Comment by dodyg** [comment] 2020-08-24 11:10
@hung-doan the DB Index is really useful for listing, etc but yeah for full text search, Lucene is the way to go.

These are the tables you can query https://docs.orchardcore.net/en/dev/docs/reference/modules/SQL/. It's all basic sql. Make sure the module is enabled.

**Comment by hung-doan** [comment] 2020-09-05 13:22
> Ok, found where is the issue (I think).
> CreateFilteredQuery() in BooleanQueryProvider class.

@Skrypt @sebastienros do you want me to submit an issue to log it as a bug?.

**Comment by Skrypt** [comment] 2020-09-06 01:05
I reported the issue here : https://github.com/OrchardCMS/OrchardCore/pull/2725
This should be fixed as part of that PR.

**Closed** 2021-05-03 19:52 UTC
Labels: Lucene, documentation
