### ISSUE TITLE
Deleted fields not removed from Document table json

### ISSUE THREAD

**Issue by Flarescape** [OrchardCMS/OrchardCore#3982] opened 2019-07-29 15:53 UTC
I really don't know if this is on purpose, but i noticed that if you add a field to a content type, create content of that type and then remove the field, it will remain in the json of the document table entry.
Even the previous value of the field is saved forever.

**Comment by sebastienros** [comment] 2019-07-29 17:11
It is intended/by design. It could be an issue though in some cases where you just want to get rid of some content. In this case we would need a custom pruning tool that would process every content item to remove such dangling node.

**Comment by Flarescape** [comment] 2019-07-30 13:05
Alright, thank's, i really wasn't sure about this behavior.
The "strange" thing about this is, that if you add a field, let's say of type `Media`, remove it and than add a new field of type `Date` then this happens in the database:

Media (added and published):
`..."LandingPage":{"Image":{`**`"Paths":["refs/ref_image.jpg"]`**`}}...`

Media (removed and published):
`..."LandingPage":{"Image":{`**`"Paths":["refs/ref_image.jpg"]`**`}}...`

Date (added and published):
`..."LandingPage":{"Image":{`**`"Paths":["refs/ref_image.jpg"],"Value":"2019-07-30T00:00:00Z"`**`}}...`

**Comment by Piedone** [comment] 2024-04-28 21:39
The content item destroy feature is tracked here: https://github.com/OrchardCMS/OrchardCore/issues/6056. Since that's what's needed here, I'll close this one.

**Closed by Piedone** 2024-04-28 21:39 UTC
