### ISSUE TITLE
Feature-Request: Insert Images from the Media Library as MD Images

### ISSUE THREAD

**Issue by FelixStumvoll** [OrchardCMS/OrchardCore#6696] opened 2020-07-16 11:40 UTC
i was just creating a document with the wysiwyg editor and i thought i would be nice, to insert media as a Markdown image
for example instead of inserting this `[image]image1.jpg[/image]` to the image it would insert something like this `![altText](https://localhost:6001/media/image1.jpg)`.
this would mean it would show the actual image in the preview

**Comment by hishamco** [comment] 2020-07-16 11:46
The is nice feature especially for Markdown editors, @deanmarcussen is adding image shortcode in Markdown editor by intention? or it is a missing feature?

**Comment by deanmarcussen** [comment] 2020-07-16 11:47
It's not possible because the `media` component of the url changes from tenant to tenant when using prefixing.

i.e. 
`[image]image1.jpg[/image]`

becomes 
`/media/image1.jpg` or
`/my-tenant/media/image1.jpg`

this is why we use the shortcode

**Comment by hishamco** [comment] 2020-07-16 11:51
What if we check the current tenant is the default tenant, so we can use `/media/image1.jpg` otherwise `/media/image1.jpg`

**Comment by FelixStumvoll** [comment] 2020-07-16 11:54
if i am understanding this correctly images are stored in the corresponding tenant so it should be possible to check for the current tentant or am i wrong here

**Comment by deanmarcussen** [comment] 2020-07-16 11:59
Nope, it's dynamic. and may change across server deployments.

This was designed quite specifically, I would not be wanting to change any behaviour here.

**Comment by FelixStumvoll** [comment] 2020-07-16 12:26
okay i see how this could be an issue when you deploy it to a different server

i mean you could intercept the http request and prepend the corresponding tenant base uri but that would be kinda cursed/hacky

**Comment by FelixStumvoll** [comment] 2020-07-16 12:31
actually i just checked, if you write ![altText](/media/image.jpg) it correctly shows the image

**Comment by FelixStumvoll** [comment] 2020-07-16 16:14
wait its the same issue with multiple tenants isn't it

**Comment by Piedone** [comment] 2024-05-14 00:26
Yes, and also because the customizable /media prefix (or that you can put media files on a separate domain as well).

You can insert `![alt text!]([asset_url]about-bg.jpg[/asset_url])` (or `<img src="[asset_url]about-bg.jpg[/asset_url]">`) instead of `[image]about-bg.jpg[/image]` but that would only work if we'd render shortcodes in the editor as well; however, that goes against the point of using shortcodes.

So, I'm closing this now.

**Closed by Piedone** 2024-05-14 00:26 UTC
