### ISSUE TITLE
Cannot create a new tenant using sql server

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#9189] opened 2021-04-16 14:44 UTC
With latest dev branch when I try to create a tenant using an sql database the tenant does not get created . 
There are no errors in the log and the tenant remains unitialized.
I am using the blog recipe.
Upon clicking the finish setup button it seems it gets locked and does'nt complete. 
Not getting any responce back.

When using sqllite for the database it works.

Related : #9188

**Comment by deanmarcussen** [comment] 2021-04-16 16:16
Closing as duplicate of https://github.com/OrchardCMS/OrchardCore/issues/9188

**Closed by deanmarcussen** 2021-04-16 16:16 UTC
Labels: bug
