### ISSUE TITLE
Add tags and descriptions for nuget packages

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1249] opened 2017-11-23 07:51 UTC
Our packages in Nuget are not currently tagged, with things like `orchardcore`

Also we need to get the descriptions from the module.txt files in to the nuget packages.

**Comment by agriffard** [comment] 2018-03-23 13:49
We now use a Manifest.cs to describe a Module but I guess the issue is still to be done.

**Comment by ns8482e** [comment] 2020-07-14 04:18
Related #6404

**Comment by hishamco** [comment] 2020-07-14 10:59
Can we close this while it's a duplicate of #6404?

**Closed** 2020-07-23 17:23 UTC
