### ISSUE TITLE
Startup.cs swallowing exceptions

### ISSUE THREAD

**Issue by Jetski5822** [OrchardCMS/OrchardCore#1260] opened 2017-11-29 13:59 UTC
When a project cannot be loaded there is not much feed back to the user. We need better feedback as to what is going on

**Comment by sebastienros** [comment] 2017-12-07 20:24
Ping

**Comment by sebastienros** [comment] 2018-06-28 19:33
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2014

Not really but still more comments there

**Closed** 2018-06-28 19:32 UTC
