### ISSUE TITLE
add client side openid module for  login

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#727] opened 2017-04-27 13:29 UTC
Transfer client side openid login to orchard 2.
@ThaerAlAjlouni : will you do that?

**Comment by xperiandri** [comment] 2017-05-07 18:43
What do you mean by that?

**Comment by sebastienros** [comment] 2017-05-08 15:13
@xperiandri there is a module in Orchard1 that support open id providers as external login providers. This is probably to suggest implementing the same thing in OC.

**Comment by xperiandri** [comment] 2017-05-08 16:01
And how is it configured now in Orchard2.
I see it uses OpeIddict, right?
is configuration of identity left for developer like in usual ASP.NET Core app?

**Comment by jersiovic** [comment] 2017-05-08 16:22
Take a look to this demo at the weekly meeting https://youtu.be/pjrbhLhFSVg Orchard.OpenID demo starts at minute 35. Maybe you can skip the long into ;)

**Comment by xperiandri** [comment] 2017-05-08 17:17
You did amazing job.
I also use OpenIddict in my projects and did a few presentations about it with similar content.
So what's next?
As I understand this issue is related to SPA, isn't it?

**Comment by jersiovic** [comment] 2017-05-09 16:07
happy to hear you like it.
What's next?
Well, Orchard.OpenId module in Orchard 1 provides a client to delegate authentication on a third party OpenId server https://github.com/OrchardCMS/Orchard/blob/dev/src/Orchard.Web/Modules/Orchard.OpenId/Module.txt and in Orchard 2 this is another module with the same name but that implements an OpenId server.

IMO the most logical next step is to have in Orchard 2 a client to authenticate to a third party OpenId like in Orchard 1 or even to another Orchard 2 instance. But as far as I understand this doesn't have to be a SPA.

**Comment by jersiovic** [comment] 2017-05-09 16:14
By the moment first approach to SPA would be good to be done in the Ochard.Demo https://github.com/OrchardCMS/Orchard2/issues/234. A sample of an SPA using OpenId for authorization and conusming a demo rest API rquiring authorization could be a good starting point to discuss how and where we have to provide a web API.

**Comment by infofromca** [comment] 2017-05-10 15:29
this doesn't have to be a SPA:  for example, it can be useful for xamerin project

**Comment by sebastienros** [comment] 2017-05-10 15:32
Just to refocus in case there is a missuderstanding, the goal here is to have a simple controller and view demoing the usage of the openid module. This controller and view don't have to use any MVVM framework, they can just use jquery. In the end a user can look at this code and understand what the openid module can do for APIs, and we can also use it as functional test to ensure it works as expected.

**Comment by xperiandri** [comment] 2017-05-10 18:18
Basically it does not mater.
As you just need to install oidc-client from [IdentityModel](https://github.com/IdentityModel/oidc-client-js).
Then it becomes trivial.

So if you [explain to me what to do](https://github.com/OrchardCMS/Orchard2/issues/234#issuecomment-300320244) I will make such sample. I just need to know how to set up a custom master page at least.

**Comment by sebastienros** [comment] 2017-05-10 18:26
I realize I commented on the wrong issue.

This issue is about adding support for other open servers.

@xperiandri this issue is way to complex for you based on your early knowledge of Orchard. The fact that you are asking how to setup a master page makes it obvious for me that you don't know how theming works. Maybe try to contribute with some simpler task first?

**Comment by xperiandri** [comment] 2017-05-10 18:36
I have my company site and a coming project which I would like to build with Orchard Core.
For my site is the primary goal is to have a landing page preferably on SPA. Adding LinkedIn login and submission form then.
The side project is a geo distributed web site with localization.
So I must jump start as quickly as possible.
If you have something else to recommend I will do that.

**Comment by gentledepp** [comment] 2017-10-04 11:09
HI! I am not sure this is the right issue for this, but as @sebastienros  marked my issue to be a duplicate of this one, please let me ask to clarify things:

> We would like to allow our customers to configure their own authentication endpoints. E.g. one of them uses salesforce and would like to let their users to authenticate with their salesforce credentials (OAuth 2.0 based)
> Another customer keeps asking about WS Federation (or whatever is currently the best way to let their users authenticate using their Microsoft Active Directory accounts)
> 
> Is there any plan of your team to support such a feature?
> (Basically, this would suit perfectly into the SAAS recipe)

So is that the topic of this issue? And if so, are there any plans or at least ideas in how to solve this?
Thank you so much!

**Comment by xperiandri** [comment] 2017-10-04 11:36
Well, you need OAuthIntrospection module.
Similar to what @PinpointTownes created with OpenIddict just simpler.

**Comment by gentledepp** [comment] 2017-10-04 12:45
Really? I just read about saaskit, where they simply create a separate request pipeline per tenant.
See this great blog post here: [Multi-tenant middleware pipelines in ASP.NET Core](http://benfoster.io/blog/aspnet-core-multi-tenant-middleware-pipelines)

**Comment by sebastienros** [comment] 2017-10-04 17:46
You have a custom pipeline per tenant in Orchard too, and you only need to restart the tenant when you do changes. It only takes a few hundred milliseconds.

**Closed** 2019-04-04 01:30 UTC

**Comment by xperiandri** [comment] 2019-04-04 14:03
Do we already have that module?

**Comment by MichaelPetrinolis** [comment] 2019-04-04 17:59
Yes, is a feature in the OpenID Connect Module (OpenID Client)

**Comment by PinpointTownes** [comment] 2019-04-04 18:01
It's worth noting that the OpenID client feature doesn't yet integrates nicely with the OpenID server feature (at least, the configuration is not as pleasant as the validation feature, that allows selecting another tenant as the OIDC server.

We may want to open a new thread to track that or keep this one open not to forget to implement that 😄
