### ISSUE TITLE
Category for the "TypeDefinition"

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#11556] opened 2022-04-18 07:42 UTC
Can we create a category for "type definition"?

Just like:
C# has namespace
Sql Server has Schema

**Comment by hishamco** [comment] 2022-04-18 16:22
I already see simlar issue, hope to find it

**Comment by hishamco** [comment] 2022-04-18 16:24
BTW how this could be use in terms of content management?

**Comment by Skrypt** [comment] 2022-04-21 01:45
It could be tagged with some terms but I doubt categories would work since it would lead to a second request which would be to have 2 Content Types with the same name in different categories which would be a little harder to implement.

**Comment by ns8482e** [comment] 2022-04-21 22:27
What's the purpose? 
- Is it just for classification/filter on UI  OR
- It's really a partition between definition ?

**Comment by Skrypt** [comment] 2022-04-22 04:09
I think this is a duplicate issue; this has been discussed before. We got requests about having multiple Content Types with the same technical name under different categories so that they can be used in different contexts. And of course, when I said "Tags", I meant for the UI because it could be used to filter them eventually even if they are in "categories". So this is 2 different things that could be eventually done. But, it's been triaged in the backlog because it is not a priority. If anyone wants to contribute and propose a design you are welcome. 😄

**Comment by hyzx86** [comment] 2022-05-07 15:00
We can classify them using a property,
When getting the type name: will be the category + type name (created when filling in)
Jsut like 
 
Category : CategoryName1   
TypeName: CategoryName1+MyTypeName

**Comment by hishamco** [comment] 2022-05-07 18:36
Adding something like a namespace or schema might it needs a lot of work. So, what if you combine the category name with content type name in the technical name as the following:

| Display Name | Technical Name |
|----------------|----------------|
| Categroy         | Production_Category |
| Category         | Manifacture_Category |

This way you will have same content type name for different use case

**Comment by hyzx86** [comment] 2022-05-09 06:21
It can work like a table prefix, or a collection
Because the type name cannot be changed,
When we create a type on the interface, we can select the category and automatically concatenate the type name
This allows us to modify only the code that creates the type
The specific steps are as follows:
1. Modify the type definition and add the Category field
2. Modify the page for creating a type and add the Category field
3. Modify the creation type code. If the Category is not empty, use the `Category`+`TypeName` and save it as the new type name

**Comment by hyzx86** [comment] 2022-05-09 06:25
> This way you will have same content type name for different use case

The display name affects only the page display
We can add a prefix where the type shows the dispayname

**Comment by hishamco** [comment] 2022-05-09 06:39
> We can add a prefix where the type shows the dispayname

You can, as I said before it's doable without display name but it needs more work

**Comment by hyzx86** [comment] 2022-11-21 13:28
New discovery of recipe deployment:

I made a Recipe , which contains a common type, such as UserProfiles
There is also a UserProfiles in another tenant, but they have different functions.
At this time, if I want to distinguish the UserProfiles in the Recipe from the UserProfiles in the tenant, I have to modify the ContentType UserProfiles in Recipe to ` AntdUserProfiles`

**Comment by sebastienros** [comment] 2022-12-01 18:51
You can always prefix your content types with a namespace, `MyTypes_UserProfiles`

**Comment by hyzx86** [comment] 2022-12-31 12:16
Can we extract this content into the service? Or some other way  can rewrite it？


To be honest I have tried many ways to override Action in OC and they have all failed


https://github.com/OrchardCMS/OrchardCore/blob/0514eed0b5960ee0880865730b0d5913f6cb6d02/src/OrchardCore.Modules/OrchardCore.ContentTypes/Controllers/AdminController.cs#L96-L138

**Comment by sebastienros** [comment] 2023-01-05 18:08
> Can we extract this content into the service? Or some other way can rewrite it？
To be honest I have tried many ways to override Action in OC and they have all failed

I don't understand what is your problem here. Is it the fact that display names are checked for unicity?

**Comment by hyzx86** [comment] 2023-01-05 18:19
As mentioned above, I still want to be able to group types by module
I've done grouping on my custom script query and it works fine.

![image](https://user-images.githubusercontent.com/15613121/210851834-58979694-4cde-4370-89a4-c9d62ae3f3ee.png)
![image](https://user-images.githubusercontent.com/15613121/210851950-c7ac568d-1d1d-469b-8e6d-c764c82c1438.png)

**Comment by hyzx86** [comment] 2023-01-05 18:33
However, a new problem was discovered recently, which is that the variables in `Jint` don't seem to be deallocated

I once read a 70,000-entry excel file by calling a custom handler with` Jint`, which exploded to 800mb of memory. Then, for testing, I looped through the collection 10 times in a script and the memory ballooned to 5GB

**Comment by Piedone** [comment] 2024-04-28 22:10
Duplicate of: https://github.com/OrchardCMS/OrchardCore/issues/4808

**Closed by Piedone** 2024-04-28 22:10 UTC
Labels: enhancement
