### ISSUE TITLE
Media Library File Name and Folder Name Special Character Issue

### ISSUE THREAD

**Issue by KapilChouhanAst** [OrchardCMS/OrchardCore#16163] opened 2024-05-27 06:19 UTC
### To Reproduce
1. Go to media library
2. create a new folder under media library and add a plus (+) sign in the folder name
3. upload the file in this folder (just for an example add any image)
4. if you can see the image is not visible. When we click on the view button it shows an error
5. same thing with the filename also. If we add plus sign in the filename then that file will show same error.

### Expected behavior
if any character does not work in the file name and folder name then there should be a validation check  so that we can not add that character

### Screenshots
![image](https://github.com/OrchardCMS/OrchardCore/assets/78483178/33d83a69-0266-489b-afd2-19595dd698d3)
![image](https://github.com/OrchardCMS/OrchardCore/assets/78483178/2728923b-f3b7-4269-bb93-89609768e1ef)

**Comment by Piedone** [comment] 2024-05-27 20:43
This looks like the same issue, but specifically for Blob Storage: https://github.com/OrchardCMS/OrchardCore/issues/11673. Perhaps it needs to be fixed on a higher level, then. @IsQiao, as the reporter of the other issue, and who started to fix it under https://github.com/OrchardCMS/OrchardCore/pull/11674, what do you think? Can you provide a more generic fix?

**Comment by Piedone** [comment] 2024-05-27 20:54
This is the same issue. So, I'm closing this one as a duplicate of that earlier issue. But thank you for providing valuable different repro steps, and the insight that this is not just an Azure Blob bug!

**Closed by Piedone** 2024-05-27 20:54 UTC
Labels: bug :bug:, Media
