### ISSUE TITLE
Exception on admin for content item type Page for 1.0.0-rc2-14210

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#6987] opened 2020-08-30 15:22 UTC
![exception](https://user-images.githubusercontent.com/1761249/91662852-52748600-eae5-11ea-9c69-7d341c7aed5c.png)

**Comment by hishamco** [comment] 2020-08-30 15:26
@deanmarcussen is there a regression bug?

**Comment by jtkech** [comment] 2020-08-30 15:54
Duplicate of #6968 and #6925

**Closed** 2020-08-30 16:18 UTC
Labels: duplicate
