### ISSUE TITLE
Translation not working for resource with class name different from file name

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#3591] opened 2019-05-08 10:43 UTC
Some translations are not effective when the string to translate is in a class whose name is different from the file name or because multiple classes are in one file.

Example in OrchardCore.Users/AdminMenu.cs and the corresponding OrchardCore.Users.po for the fr culture:

```
#. .Add(T["Registration"], T["Registration"], registration => registration
#. .Add(T["Registration"], T["Registration"], registration => registration
#: OrchardCore.Users\AdminMenu.cs:65
#: OrchardCore.Users\AdminMenu.cs:65
msgctxt "OrchardCore.Users.RegistrationAdminMenu"
msgid "Registration"
msgstr "Inscription"
```
#. .Add(T["Reset password"], T["Reset password"], password => password
#. .Add(T["Reset password"], T["Reset password"], password => password
#: OrchardCore.Users\AdminMenu.cs:95
#: OrchardCore.Users\AdminMenu.cs:95
msgctxt "OrchardCore.Users.ResetPasswordAdminMenu"
msgid "Reset password"
msgstr "Réinitialiser le mot de passe"

**Comment by hishamco** [comment] 2019-05-09 10:32
> when the string to translate is in a class whose name is different from the file name

What you mean by class here?

Is that mean that it doesn't work for the `fr` culture only, or it's a bug that will occurs in all the cultures?

**Comment by agriffard** [comment] 2019-05-09 15:41
csharp class: https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore.Modules/OrchardCore.Users/AdminMenu.cs

It will occur in all cultures:
![image](https://user-images.githubusercontent.com/703248/57466574-3fe79500-7281-11e9-9d18-f820292e3230.png)

**Comment by hishamco** [comment] 2019-05-09 16:44
Ah .. let me look into it after I finishing the current content localization feature I have

**Comment by hishamco** [comment] 2019-05-09 16:52
Ah .. let me look into it after I finishing what I have in content localization

**Comment by lukaskabrt** [comment] 2019-05-09 19:22
In this case the problem is that `RegistrationAdminMenu` class resolves `IStringLocalizer` with the wrong generic parameter.

```
public RegistrationAdminMenu(IStringLocalizer<AdminMenu> localizer)
{
    T = localizer;
}
```

If the constructor uses `IStringLocalizer<RegistrationAdminMenu>` the localizer will be initialized with the correct context and translation should work.

**Comment by agriffard** [comment] 2019-05-09 19:47
Thanks @lukaskabrt , that explains the problem, I should have seen that.

**Closed** 2019-05-09 20:36 UTC

**Comment by hishamco** [comment] 2019-05-09 21:53
I was working to fix, but seems @lukaskabrt replied before I push my changes :)
