### ISSUE TITLE
can't load recipe with more than 2100 items per step

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#8410] opened 2021-01-23 00:20 UTC
### Describe the bug
**Import Deployment Packege** and **JSON Import** can't hadle more than **2100** items per step when using **MS SQL server**.

`Version: 1.0.0-rc2-15572`

### To Reproduce
1. Setup **Blank Site** with **SQL Server** database,
2. Create new ContentType **ExampleType**,
3. Add Field of type TextField named **Name**,
4. Try to import attached recipe [reproRecipe.zip](https://github.com/OrchardCMS/OrchardCore/files/5859249/reproRecipe.zip),
5. Wait a bit for error page.

### Expected behavior
Such big file should be imported without any problems, maybe by chunking into smaller pieces.

### Screenshots
![too-many-parameters](https://user-images.githubusercontent.com/6403130/105561963-a8f29300-5d18-11eb-8eec-6ebf37d0373e.png)

### Exception Details

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 418
   at YesSql.Store.ProduceAsync[T](WorkerQueryKey key, Func`2 work, Object[] args)
   at YesSql.Services.DefaultQuery.Query`1.ListImpl()
   at OrchardCore.ContentManagement.DefaultContentManager.ImportAsync(IEnumerable`1 contentItems) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs:line 453
   at OrchardCore.Contents.Recipes.ContentStep.ExecuteAsync(RecipeExecutionContext context) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.Contents/Recipes/ContentStep.cs:line 33
   at OrchardCore.Recipes.Services.RecipeExecutor.<>c__DisplayClass7_0.<<ExecuteStepAsync>b__0>d.MoveNext() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 176
--- End of stack trace from previous location ---
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 243
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 159
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 102
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 120
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)
   at OrchardCore.Recipes.Services.RecipeDeploymentTargetHandler.ImportFromFileAsync(IFileProvider fileProvider) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.Recipes/Services/RecipeDeploymentTargetHandler.cs:line 34
   at OrchardCore.Deployment.Core.Services.DeploymentManager.ImportDeploymentPackageAsync(IFileProvider deploymentPackage) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Deployment.Core/Services/DeploymentManager.cs:line 54
   at OrchardCore.Deployment.Controllers.ImportController.Import(IFormFile importedPackage) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.Deployment/Controllers/ImportController.cs:line 89
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.Diagnostics/DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at OrchardCore.ContentPreview.PreviewStartupFilter.<>c.<<Configure>b__1_1>d.MoveNext() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore.Modules/OrchardCore.ContentPreview/PreviewStartupFilter.cs:line 51
--- End of stack trace from previous location ---
   at OrchardCore.Modules.ModularTenantRouterMiddleware.Invoke(HttpContext httpContext) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantRouterMiddleware.cs:line 64
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 243
   at OrchardCore.Modules.ModularTenantContainerMiddleware.Invoke(HttpContext httpContext) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore/Modules/ModularTenantContainerMiddleware.cs:line 61
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
ClientConnectionId:5882bbef-1705-4a25-9095-371e54a22398
Error Number:8003,State:1,Class:16
```

**Comment by deanmarcussen** [comment] 2021-01-23 09:58
Yes, this would be a regression with YesSQL.

I thought it was related to some batching size code we had in OC, but actually it fails during the update, due to some batching on YesSQL that went in recently.

I suspect we will fix it on the YesSql side, while Flushing the session would probably work, better to reduce batch sizes, into multiple requests, or others will hit the issue for no good reason, and need to issue flushes.

For the moment you will need to reduce the number of items in your recipe step.

Note: it's probably not 2100 items that fail, the limit is currently probably lower, as it's to do with the number of parameters per item. i,e. one item will incur more than one parameter during the batched update.

**Comment by Sen-Gupta** [comment] 2021-01-24 09:11
@deanmarcussen I see it has been addressed by @sebastienros already on YesSQL. When can we expect OC be upgraded?

We upgraded our code and a background process that updates content reported failures. It is a show stopper for us.

**Comment by urbanit** [comment] 2021-01-24 10:04
Pls upgrade to YesSql... @sebastienros made new version yday! 2.0.0-beta-1738 for Core & Abstractions... 1.0.0-beta-1738 from databases. Tested...

**Comment by Sen-Gupta** [comment] 2021-01-24 10:45
@urbanit I'm on OrchardCore 1.0.0-rc2-15787. I see there has been update and now the latest build is: 1.0.0-rc2-15790. 
Upgraded and tested on 15790, the issue still exists.

Shall I upgrade OrchardCore or you mean I should build OrchardCore locally? 

I'm not sure!

**Comment by Sen-Gupta** [comment] 2021-01-24 10:51
@urbanit or you mean just bump the reference of YesSQL in OrchardCore web solution?

**Comment by urbanit** [comment] 2021-01-24 10:54
For the time being, you should build locally and update YesSql version. I will make a PR for it, but still it will not merged to dev directly... @deanmarcussen should I make a PR?

**Comment by Sen-Gupta** [comment] 2021-01-24 11:02
@urbanit Building locally is not viable for us, as we always develop against OrchardCore Preview Nugets.

I will try to see if assembly redirection works, it seems easier and have done this in many projects in past.
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

So in my web.config for orchard web project, I plan to redirect the old version of YesSQL to new version.

At the same time, merging the PR in dev branch should not be an issue either.

**Comment by deanmarcussen** [comment] 2021-01-24 11:06
Fix doesn't work in all scenarios.

pr here https://github.com/sebastienros/yessql/pull/340

it'll probably update by tomorrow.

@Sen-Gupta except for the fact it won't actually work, you can always just reference YesSql directly to override the OC version. No binding redirects required. Just for info.

If it is killing you today, try backing the version down.

**Comment by deanmarcussen** [comment] 2021-01-24 11:11
and for reference this is the Orchard Core pr that will fix the issue when YesSql updated. https://github.com/OrchardCMS/OrchardCore/pull/8413

**Comment by Sen-Gupta** [comment] 2021-01-24 11:13
@deanmarcussen Well understood, can't thank you guys enough!

I would rather wait until tomorrow until the dust is settled.

**Comment by deanmarcussen** [comment] 2021-01-25 08:57
@lampersky thank you for the recipe to repro this with. Made it much easier.

**Closed** 2021-01-25 08:57 UTC
Labels: bug
