### ISSUE TITLE
Unexpected behaviour of razor pages tag helper

### ISSUE THREAD

**Issue by yuriko-ushikawa** [OrchardCMS/OrchardCore#11725] opened 2022-05-18 10:06 UTC
### Issue

After following documentation instructions on setting up decoupled CMS the behaviour of `asp-page` tag helper breaks. 

For example, in the `_Layout.cshtml` file we have a navlink

 `<a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>`

which instead of redirecting to the Privacy page, redirects to

`https://localhost:7181/Admin/OrchardCore.Settings/Admin/Index?page=%2FPrivacy`

### Expected Behaviour

Page navigation works the same way as in Razor Pages project template.

**Comment by ns8482e** [comment] 2022-05-20 00:14
Everything in OC is module (area) including  host web project.  

If you project name is `OrchardCore.Cms.Web` then  tag helper to refer to Privacy page for `OrchardCore.Cms.Web/Pages/Privacy.cshtml` should be  referred in gag helper as
```html
<a class="nav-link text-dark" asp-area="OrchardCore.Cms.Web" asp-page="/Privacy">Privacy</a>
```

**Comment by Skrypt** [comment] 2022-05-20 06:08
@ns8482e While what you are saying is right; I think normally it should resolve a frontend route when we are not passing any area on a View that is rendered on the frontend. The same goes for a backend View.

**Comment by ns8482e** [comment] 2022-05-20 17:21
I guess if you don’t define area then default behavior of the tag helper takes current serving current controller’s area or first match 

here the issue is because of having tag helper is in layout and serving controller vary, so it’s better to define area

**Comment by Skrypt** [comment] 2022-05-20 19:36
Is not not related with the DI priority?

**Comment by ns8482e** [comment] 2022-05-23 20:16
@Skrypt it's ASP.NET CORE's default behavior - if  area is omitted - It would take area of executing controller

**Comment by Skrypt** [comment] 2022-05-24 15:48
Ok then it is by design and we should close the issue.

**Closed** 2022-05-25 04:46 UTC
