### ISSUE TITLE
make PersistKeysToAzureBlobStorage tenantable

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore#2353] opened 2018-09-06 21:17 UTC
right now Modules:OrchardCore.DataProtection.Azure:ConnectionString is defined  on appsettings.json,
which is only for the admin of the single default  site.
It is better to use settings to make it tenantable.

**Comment by sebastienros** [comment] 2018-09-06 23:33
We actually want to find a way to make tenant settings configured in this file too using sections. It's totally doable, and that would allow us to also set them in ENV.

Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2038

**Closed by sebastienros** 2018-09-06 23:33 UTC

**Comment by sebastienros** [comment] 2018-09-06 23:34
@infofromca if you feel like you want to work on it, you'll get my support. We should also use the same format for site settings by the way, and remove yaml. But this can be done separately.
