### ISSUE TITLE
Admin Menu Permission

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3628] opened 2019-05-12 18:04 UTC
@matiasmolleja 
you have worked on dynamic permission. but some problem still in the admin menu.

i removed all allow permissions for an editor role, and i create a new link in the admin menu.

![editor](https://user-images.githubusercontent.com/24512878/57586065-63fcdd80-74f0-11e9-8078-6e2e0a710dc8.JPG)
 
  why is not possible to set permission for admin menu? 
and HTTPS section should not show for this role.

i think it will be useful if we have the ability to set access permission in the role permission for all Admin menu node's or especially for any nodes in create node page.

**Comment by sebastienros** [comment] 2019-05-16 20:11
Is the issue that we need permission for admin menu creation?

**Comment by pgy866** [comment] 2019-05-17 09:16
yes

**Comment by aghili371** [comment] 2019-05-20 20:00
> Is the issue that we need permission for admin menu creation?

yes.

**Comment by matiasmolleja** [comment] 2019-06-02 10:19
The "manage admin menu permission" is working fine for me. When assigned to a role, the users on that role are able to create, edit, delete admin menus, and admin menu nodes.

![manage-admin-menu-permission](https://user-images.githubusercontent.com/2589629/58759812-52778600-8530-11e9-9ea7-5de6845ef564.gif)

**Comment by aghili371** [comment] 2019-06-02 14:38
> The "manage admin menu permission" is working fine for me. When assigned to a role, the users on that role are able to create, edit, delete admin menus, and admin menu nodes.

thank you for feedback.
 problem not to manage the admin menu management. the problem in show and access to nodes which we creating by admin menu. like "blog" ,"main menu",...
how we can manage access to these nodes?

**Comment by matiasmolleja** [comment] 2019-06-02 16:47
> Is the issue that we need permission for admin menu creation?



> yes. otherwise it not useable for multi-role and users. it will work for any user who has access to the admin panel.


Then what you are requesting is a different thing. Maybe what you are suggesting is a way to select a set of roles when you create an admin node? I mean, when the user creates a "content types" admin node, we could show a list of checkboxes with available roles. The user could select for example "editor" and after that the admin node should be only visible to "editors".

When we first implemented this module we though about that possibililty, but now I would not do that. It think that the decision about showing or hiding a menu item has to be done by each developer that implements a new admin menu type. For example, the "content types" admin node will display a content type only if the user has the "manage content" permission for it.

Yo mention the "blog" and "main menu" links. Those are "link-url" menu items. I don't know how to check if the user has permission to access the url. To solve that I'm working on "content item" admin menu. The user will choose a content item instead of writing its url in the editor. That way when we show the menu item I will check if the user has permission for the content item, and hide or show it.

**Comment by aghili371** [comment] 2019-06-02 17:15
i think just we need to set show and hide the nodes.

at first, we create a new admin menu and then we add nodes for this menu. so just please set permission for admin menu in the creation and when you want to render and show the nodes, check the correct role access and show or don't show the nodes.

**Comment by aghili371** [comment] 2019-06-17 20:04
@matiasmolleja @sebastienros  we will have this possibility to create an admin menu for any role or it just works for admin role?

i need that if you don't have plane i have to create a new admin panel theme to manage this issue.

**Comment by Skrypt** [comment] 2019-06-25 22:38
The issue is that if you create a "Link Admin Node" or "Lists" they won't hide based on Content Type permissions for example. If I create a "Link Admin Node" that points to a "create X content type item" like this one : https://localhost:44300/Admin/Contents/ContentTypes/Acme/Create it won't hide in the admin menu if the user role doesn't have permission to publish "Acme" content items. The reason is that at this point we are only displaying an internal route and we are not hitting the current controller action which is itself validating the permissions.

**Closed** 2019-07-11 19:51 UTC
