### ISSUE TITLE
Correct way to generate url for a bagged item

### ISSUE THREAD

**Issue by jwu-au** [OrchardCMS/OrchardCore#6234] opened 2020-05-21 12:21 UTC
Hi Orchard Team,

Suppose I have below code for generating a content item link for a bagged item `Service`
```liquid
  {% for service in services.Content.BagPart.ContentItems %}
        {% assign serviceShape = service | shape_build_display: "Summary" %}
        {% a display_for: serviceShape.ContentItem, class: "btn btn-primary" %}
              {{ service.TitlePart.Title }}
        {% enda %}
  {% endfor %}
```

So I have to generate a shape from the service `JObject` , and then pass its `ContentItem` to the `a tag` helper. Is there a directly/another way to generate a link for a contained item?

**Comment by ns8482e** [comment] 2020-05-21 14:06
> ```
> {% assign serviceShape = service | shape_build_display: "Summary" %}
> ```

May be you don't need to build display.  you can directly use `service` for `display_for`.

**Comment by jwu-au** [comment] 2020-05-22 00:42
Hi @ns8482e ,

Because the `service` inside a bag is a `JObject`, by passing service directly into `display_for`, it throws below:
```
An unhandled exception occurred while processing the request.
InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'OrchardCore.ContentManagement.ContentItem'.
OrchardCore.DisplayManagement.Liquid.TagHelpers.LiquidTagHelperActivator.CallPropertySetter<TDeclaringType, TValue>(Action<TDeclaringType, TValue> setter, object target, object value) in LiquidTagHelperActivator.cs, line 242
```

**Comment by jtkech** [comment] 2020-05-22 06:40
In the `BuildDisplayFilter` if the input value is a `JObject` we do `jObject.ToObject<ContentItem>()`. We would need to do the same in the `ContentLinkTagHelper`

**Comment by jwu-au** [comment] 2020-05-22 09:59
Hi @jtkech ,

I created a PR https://github.com/OrchardCMS/OrchardCore/pull/6242 for fixing the issue.
I'm not sure it is the best way to do it.
From my testing, it should fix all properties assignments from jObject in the tag helper.
Have a review.

**Comment by ns8482e** [comment] 2020-05-22 19:55
> InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'OrchardCore.ContentManagement.ContentItem'.

@jtkech May be ContentItem should implement implicit operator for `JObject`?

**Comment by jtkech** [comment] 2020-05-23 05:50
@jwu-au good idea

@ns8482e good idea also

Need to think about it

**Comment by jtkech** [comment] 2020-05-23 08:19
Hmm, when working from `ContentItem.Content` we get a `JObject` from which we can get parts that are also `JObject` and so on. So the problem is that we can't get e.g. a real `BagPart` whose `ContentItems` property is really a `ContentItem` collection.

i think the problem is only for liquid because in razor we can use `ContentItemExtensions` as this one `As<TPart>(this ContentItem contentItem)`

So maybe one solution would be to create a liquid filter that allows to retrieve real parts / fields from a `ContentElement` (so a `ContentItem`, or a `ContentPart`, or a `ContentField`), not its json representation, e.g `contentItem | get_element "Services"`.

**Comment by sebastienros** [comment] 2020-06-25 17:23
I would either create filter that convert a JObject to a ContentItem, or have an implicit conversion from JObject to ContentItem.

**Comment by jtkech** [comment] 2020-10-16 21:54
So, as said by @sebastienros, the right fix would be

> I would either create filter that convert a JObject to a ContentItem, or have an implicit conversion from JObject to ContentItem.

But, in place of using `Model.ContentItem.Content` that is a `JObject`, just tried the following by using `Model.Content` that is a `Shape` and then `Model.Content.Services` that is a `BagPart` holding a real `List<ContentItem>`.

    {% for service in Model.Content.Services.ContentItems %}
          {% a display_for: service, class: "btn btn-primary" %}
                {{ service.DisplayText }}
          {% enda %}
    {% endfor %}

So i close this issue, feel free to re-open it if it doesn't work for you

**Closed by jtkech** 2020-10-16 21:54 UTC
