### ISSUE TITLE
React to change the OC favorite icon

### ISSUE THREAD

**Issue by hishamco** [OrchardCMS/OrchardCore#6706] opened 2020-07-17 15:25 UTC
From UI/UX seems the logo in the admin theme not align with the updated favorite icon, here is how the new logo is look like

![Logo](https://user-images.githubusercontent.com/3237266/87803250-e43c7280-c85a-11ea-953b-9a1d16a919bd.png)

/cc @agriffard

**Comment by agriffard** [comment] 2020-07-17 15:43
The favicon and the logo in admin are not supposed to be the same.

I only changed the favicon because it was black and didn't render well on dark tabs.

**Comment by hishamco** [comment] 2020-07-17 15:52
> The favicon and the logo in admin are not supposed to be the same.

From UI/UX perspective one of them should be changed coz they should respect the color schema

**Comment by Piedone** [comment] 2020-07-17 17:16
Also see: https://github.com/OrchardCMS/OrchardCore/issues/6279

**Comment by sebastienros** [comment] 2020-08-06 18:08
Discussion in other issue
Duplicate of #6279

**Closed by sebastienros** 2020-08-06 18:08 UTC

**Comment by hishamco** [comment] 2020-08-06 18:44
Hope to see some progress in #6279
