### ISSUE TITLE
Error enabling OpenID module

### ISSUE THREAD

**Issue by alexbocharov** [OrchardCMS/OrchardCore#1457] opened 2018-02-06 12:06 UTC
When I enable a OpenID module, there is an error:
`InvalidOperationException: The connection does not support MultipleActiveResultSets.`

![image](https://user-images.githubusercontent.com/7753794/35858941-4a47a1b0-0b4f-11e8-883e-8674145849d8.png)

**Comment by PinpointTownes** [comment] 2018-02-06 13:48
I've already seen the same error but I've been unable to reproduce it consistently. It may be a concurrency or DI isolation issue.

**Comment by alexbocharov** [comment] 2018-02-06 13:49
I check solution

**Comment by PinpointTownes** [comment] 2018-02-06 14:03
Another variant:

![image](https://user-images.githubusercontent.com/6998306/35863415-e0b526b4-0b4e-11e8-93ed-d77e0b7ee75f.png)

**Comment by alexbocharov** [comment] 2018-02-06 14:06
First problem:

https://github.com/OrchardCMS/OrchardCore/blob/66a607140e593b00ab861d1040e7f902a1519891/src/OrchardCore.Modules/OrchardCore.OpenId/Startup.cs#L68

The service should probably be registered as scoped.

**Comment by PinpointTownes** [comment] 2018-02-06 14:16
I believe it used to be registered as a scoped dependency, but IIRC, @sebastienros changed that some time ago.

**Comment by alexbocharov** [comment] 2018-02-06 14:19
Reproduction steps:

1. Create new site (absolutely new)
2. Enable **OpenID**

**Comment by alexbocharov** [comment] 2018-02-06 14:21
Another variant (funny behavior):

1. Create new site (absolutely new)
2. Enable **HTTPS**
3. Enable **OpenID**

**Comment by alexbocharov** [comment] 2018-02-06 14:23
I forgot... We choose the **Software as Service**

**Comment by PinpointTownes** [comment] 2018-02-06 14:23
Thanks for the repro. I'll try to work on a fix locally.

**Comment by alexbocharov** [comment] 2018-02-06 14:25
I will also try to work on this today

**Comment by alexbocharov** [comment] 2018-02-07 06:51
Another variant:

![image](https://user-images.githubusercontent.com/7753794/35902459-586cf1e4-0bec-11e8-8cc7-eb423b1adf96.png)

@sebastienros ideas?

**Comment by sfmskywalker** [comment] 2018-02-07 10:29
I'm seeing the exact same thing happening with the Workflows module when I enable the Timers feature. In my case however it's because that feature contains a background task that access the DB at the same time Autoroute (on most occasions) accesses the DB. @jtkech is working on a fix for that. Not sure if this is helpful for this particular problem, but maybe there's a hint to be found with Jean-Thierry's findings.

**Comment by jtkech** [comment] 2018-02-07 21:15
Yes, it was just because i saw the same kind of issue with sqlite when enableing lucene worker which has a bgTask. Then just adding a dueTime of 1s when starting bgTasks timers (as done in #1372) fixed the issue, but i didn't dig into it.

Just for infos, here i could repro when enableing openId and with sql server, then here also, adding a dueTime of 1s when starting bgTasks timers, was solving the issue.

**Comment by PinpointTownes** [comment] 2018-02-07 21:37
Thanks for the details!

> Then just adding a dueTime of 1s when starting bgTasks timers (as done in #1372) fixed the issue, but i didn't dig into it.

Won't that hide the root cause of this issue? The MARS error seems to indicate the underlying SQL connection object was shared and called concurrently by multiple threads, which should never happen as we're supposed to use separate scopes.

**Comment by jtkech** [comment] 2018-02-07 22:17
> Won't that hide the root cause of this issue?

Yes you're right, it was just for info because i didn't search more in depth. If i have time and find something i will let you know.

**Comment by jtkech** [comment] 2018-02-08 00:18
So for testing, restarting the timer while the request which activate it is not ended, seems to work. Then, when `RequestServices` is null as it will be in all future executions, `EnterServiceScope()` will populate it.


            if (_httpContextAccessor.HttpContext.RequestServices != null)
            {
                var timer = _timers[groupName];
                var period = _periods[groupName];
                timer.Change(TimeSpan.FromMilliseconds(50), period);
                return;
            }

Otherwise, through `RequestServices`, 2 scopes may be not fully isolated and concurently used.

**Comment by PinpointTownes** [comment] 2018-02-08 18:51
Curious: is there any particular reason why we use the service scope associated with the request in the site service? Couldn't we just use a regular child scope?

**Comment by jtkech** [comment] 2018-02-08 22:07
I would say to not add the overhead of creating a child scope but you're right i saw it is cached at the tenant level in a memory cache. But we need to find a global solution for parallel execution which rely on `HttpContext` as with timers, and maybe if someone want to run parallel tasks during a request.

As suggested maybe a fake `HttpContext`, i remember  i did something in O1 with `LogicalCallContext` which do cloned copies. Maybe we could use `AsyncLocal` which flows data among threads in an `async / await` pattern but i think which is not thread safe for parallel tasks because it only does shallow copies.

But i think we just need to pass a new isolated fake `HttpContext` and which flows data when using `async / await`. I have to re-put my mind into this, as i have time i will work on it.

**Comment by PinpointTownes** [comment] 2018-02-08 22:15
> I would say to not add the overhead of creating a child scope

Cached or not, it shouldn't be a super expensive operation (after all, that's what ASP.NET Core does per request).

> But we need to find a global solution for parallel execution which rely on HttpContext as with timers, and maybe if someone want to run parallel tasks during a request.

FYI, `DefaultHttpContextAccessor` is registered as a singleton and uses `AsyncLocal` under the hood so you should be able to access the HTTP context even outside the HTTP context request services scope.

IMHO, it would be better to avoid all these problematic uses of `IHttpContextAccessor` if we can avoid them.

**Comment by jtkech** [comment] 2018-02-08 22:37
Yes, i saw it uses `AsyncLocal` but this doesn't solve the concurrency issue, that's why i'm thinking to provide a new fake `HttpContext` when running concurently as for the specific case of timers executions.

> IMHO, it would be better to avoid all these problematic uses of IHttpContextAccessor

I agree, hmm, but we have many places where we use it.

**Comment by PinpointTownes** [comment] 2018-02-09 00:57
Maybe I'm missing something, but I still don't understand why you need the `HttpContext` for background tasks. That doesn't sound like a good idea. IMHO, the two worlds should be completely separate and background tasks should NEVER access the HttpContext, fake or not.

**Comment by jtkech** [comment] 2018-02-09 01:08
Yes you're right, it was just for testing.

So, i will just suggest this change through a PR in case we can't prevent (or we want) bgTasks from using services which uses the `IHttpContextAccessor` to retrieve scoped services.

**Comment by sebastienros** [comment] 2018-02-09 01:38
A background "task" needs a serviceprovider. It should get a new one each time it runs, by using IORchardHost, getting the tenant, and asking for a new scope. Then dispose it.

**Comment by PinpointTownes** [comment] 2018-02-09 01:59
> A background "task" needs a serviceprovider. It should get a new one each time it runs, by using IORchardHost, getting the tenant, and asking for a new scope. Then dispose it.

I think we all agree about that.

The problem is that `ShellContext.ServiceScopeWrapper` replaces `HttpContext.RequestServices` by a new child scope (different than the one initially built by ASP.NET Core for the request). This not only impacts the background tasks but also the original HTTP request during which the background task service started (i.e it shares the same `IServiceProvider` as the background tasks).

Since both are run concurrently, weird errors like the ones described in this post occur.

**Comment by jtkech** [comment] 2018-02-09 08:06
@PinpointTownes 

1. So, i suggested a PR just to show the idea, but as you said maybe better to remove the usage of `IHttpContextAccessor` in services which can be potentially called from a bgTask.

2. But i remember with O1, the main goal to have a fake context was to be able to render view / shapes with the ability to invoke the same drivers / handlers as in a "normal" request.

If we do 1. we still need a different implementation of `EnterServiceScope()` which here would just call `ServiceProvider.CreateScope()` this to not update at all the `HttpContext`.

**Comment by PinpointTownes** [comment] 2018-02-12 17:06
@jtkech actually, I would not "just" avoid using `IHttpContextAccessor` in background tasks, I'd make that completely impossible.

I haven't profiled the current code to confirm my theory, but I'm tempted to say that the fact we capture the "initial HTTP context" in the background task service's timer (via `ExecutionContext`/`AsyncLocal`) prevents it from being disposed as it should.

It would be much safer to adopt a super defensive approach and ensure the timer doesn't capture the execution context:

```csharp
_timers = _tasks.Keys.ToDictionary(x => x, x => CreateTimer(DoWorkAsync, x));
```

```csharp
[SecuritySafeCritical]
private static Timer CreateTimer(TimerCallback callback, string name)
{
    // Prevent the current execution context from being captured to ensure async-local
    // elements like the HTTP context of the initiating request are not flowed and accessible
    // from background tasks, which would prevent the HTTP context instance from being GCed.
    var restore = false;
    try
    {
        if (!ExecutionContext.IsFlowSuppressed())
        {
            ExecutionContext.SuppressFlow();
            restore = true;
        }

        return new Timer(callback, name, Timeout.Infinite, Timeout.Infinite);
    }
    finally
    {
        if (restore)
        {
            ExecutionContext.RestoreFlow();
        }
    }
}
```

**Comment by sebastienros** [comment] 2018-02-12 17:33
I agree we should not have provide the `IHttpContextAccessor` in the first place, just `IServiceProvider`. And then if some background task. And if some tasks need a http context we might have to explicitly create a fake one (for rendering views, templates, ...) that need to generate links. But probably in a different PR.

**Comment by jtkech** [comment] 2018-02-12 21:33
@sebastienros @PinpointTownes 

> I would not "just" avoid using IHttpContextAccessor in background tasks ...

Okay, that was my first feeling.

> I'm tempted to say that the fact we capture the "initial HTTP context" in the background task service's timer (via ExecutionContext/AsyncLocal) prevents it from being disposed as it should.

Not sure because we hold it only in the `using` of the service scope wrapper.

**So, maybe what i suggest in #1471 is okay**.

- By assigning a new value to the `AsyncLocal<HttpContext>()` in the timer thread, we don't override the value of the parent thread. i have checked that, when we start the bgTask before the end of the request, we retrieve the original `HttpContext` at the end of the request execution.

- Then, during the bgTask execution, this `new DefaultHttpContext()` will be shared among thread swithings (e.g due to async code) but not between execution of different timers.

- Finally we are sure that we don't hold a reference of the original `HttpContext`.

- Note: Similarly, at the end of the request, when `HttpContextFactory` is disposing and does `_httpContextAccessor.HttpContext = null`, it doesn't override any new async local value of timers.

**Comment by jtkech** [comment] 2018-02-16 09:46
@PinpointTownes looking at your suggestion just before leaving

Not sure where you want to call `CreateTirmer()`, in the ctor or in `Activate()`? That said, in both cases, if we suppress the flow, what would happen in the calling thread if afterwards there are async / await patterns which cause some thread switchings?

But again not sure, just as i understand and no time right now to test it. I'm also thinking to check the following in `BackgroundTasksStarter`.


        public Task ActivatedAsync()
        {
            using (ExecutionContext.SuppressFlow()) // return an AsyncFlowControl
            {
                _backgroundService.Activate(); // where we start timers
            }
            // disposing do AsyncFlowControl.Undo()

            return Task.CompletedTask;
        }

**Comment by jtkech** [comment] 2018-02-16 22:59
@sebastienros @PinpointTownes

I tried your suggestion, it works as i have checked. One avantage of your solution is that in the context of a bgTask, in `EnterServiceScope()` we can check if `HttpContext` is null before creating a new `DefaultHttpContext()`, so without having to pass a `newHttpContext = true` parameter.

That said what you think of the following, it does quite the same but by calling `Undo()` on the async flow.


        [SecuritySafeCritical]
        private static Timer CreateTimer(TimerCallback callback, string name)
        {
            AsyncFlowControl flow;
            try
            {
                if (!ExecutionContext.IsFlowSuppressed())
                {
                    flow = ExecutionContext.SuppressFlow();
                }

                return new Timer(callback, name, Timeout.Infinite, Timeout.Infinite);
            }
            finally
            {
                if (flow != null)
                {
                    flow.Undo();
                }
            }
        }

And what about doing it in one pass for all timers. Here without try / catch blocks, do you think try / catch blocks are necessary?

            using (ExecutionContext.SuppressFlow())
            {
                _timers = _tasks.Keys.ToDictionary(x => x, x => new Timer(DoWorkAsync, x, ... ));
            }

**Comment by PinpointTownes** [comment] 2018-02-20 18:21
> That said what you think of the following, it does quite the same but by calling Undo() on the async flow.

IIRC, `AsyncFlowControl` is a struct, so not sure the null check makes sense (but I may be wrong).

**Comment by jtkech** [comment] 2018-02-20 21:25
Oups, thanks, i will update the related PR.

**Closed** 2018-02-21 00:07 UTC
Labels: Orchard.OpenId, bug
