### ISSUE TITLE
Media permissions

### ISSUE THREAD

**Issue by sebastienros** [OrchardCMS/OrchardCore#9369] opened 2021-05-06 18:13 UTC
Create dynamic permissions for each first level folder:

- List files
- Serve files (requires custom middleware, if we don't have a custom one already)
- Edit (add, delete) files

When rendering or editing files in the admin, check for current user permissions.

**Comment by pgy866** [comment] 2021-08-20 17:29
Can files under media permissions support historical versions, or can all content have historical versions that can be rolled back? The metadata of the database record file. Is there any adoption value?
`媒体权限下文件可以支持历史版本，或所有内容都有历史版本可以回滚呢？数据库记录文件元数据。是否有采用价值？`

**Comment by sebastienros** [comment] 2021-09-09 17:37
> Can files under media permissions support historical versions

No, and there are no events to support this I believe since it's just showing what is on the filesystem. To do this you would need to create a custom content item which would store the image for each version.

**Comment by saleemhaq** [comment] 2022-03-23 20:22
can anyone guide how we achieve like below:

https://github.com/OrchardCMS/OrchardCore/discussions/11429

If that related to above discussion can guide how i achieved that?

**Comment by Piedone** [comment] 2024-03-22 20:41
Related, or rather this is somewhat of a duplicate of: https://github.com/OrchardCMS/OrchardCore/issues/3590.

**Comment by Piedone** [comment] 2024-03-22 23:06
Please check out this PR for an intended Secure Media feature: https://github.com/OrchardCMS/OrchardCore/pull/15173. While this doesn't implement edit permissions for folders in itself, it does add view permissions and fixes ManageOwnMedia, so I think it's good enough.

**Comment by intellimedhu** [comment] 2024-04-05 14:47
We only need to protect the Media root directories, and their subdirectories should inherit that. I think can create as many folders and permissions as necessary to properly segment the files.

**Comment by Piedone** [comment] 2024-04-05 22:14
Sounds good, thanks!

**Comment by sebastienros** [comment] 2024-04-11 17:45
@gvkries you stole my idea!!! Tremendous ideas ;)

**Comment by gvkries** [comment] 2024-04-12 07:17
> @gvkries you stole my idea!!! Tremendous ideas ;)

@sebastienros  I only steal from the best 😇😉

**Comment by Piedone** [comment] 2024-04-17 21:07
If anybody has any feedback on the https://github.com/OrchardCMS/OrchardCore/pull/15173 PR, please let us know under it. Otherwise, I'll merge it in a week.

**Closed** 2024-04-25 20:39 UTC
Labels: Media
