### ISSUE TITLE
Db lock on setup with dependent recipes

### ISSUE THREAD

**Issue by alberthajdu** [OrchardCMS/OrchardCore#1609] opened 2018-03-14 12:01 UTC
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 6: 'database schema is locked: main'.

Repro (cut the saas recipe into two):
1. saas.recipe.json content:
```
{
  "name": "SaaS",
  "displayName": "Software as a Service",
  "description": "Provides default SaaS features like managing multiple websites.",
  "author": "The Orchard Team",
  "website": "http://orchardproject.net",
  "version": "2.0",
  "issetuprecipe": true,
  "categories": [ "default" ],
  "tags": [ "developer", "default" ],
  "steps": [
    {
      "name": "feature",
      "disable": [],
      "enable": [
        // SaaS
        "OrchardCore.Mvc",
        "OrchardCore.Admin",
        "OrchardCore.Commons",
        "OrchardCore.Diagnostics",
        "OrchardCore.DynamicCache",
        "OrchardCore.HomeRoute",
        "OrchardCore.Localization",
        "OrchardCore.Features",
        "OrchardCore.Navigation",
        "OrchardCore.Recipes",
        "OrchardCore.Resources",
        "OrchardCore.Roles",
        "OrchardCore.Settings",
        "OrchardCore.Tenants",
        "OrchardCore.Themes",
        "OrchardCore.Users",

        // Themes
        "TheTheme",
        "TheAdmin",
        "SafeMode"
      ]
    },
    {
      "name": "recipes",
      "Values": [
        {
          "executionid": "OrchardCore.Setup",
          "name": "test"
        }
      ]
    }
  ]
}
```
2. test.recipe.json content:
```
{
  "name": "test",
  "displayName": "test",
  "description": "Provides default SaaS features like managing multiple websites.",
  "author": "The Orchard Team",
  "website": "http://orchardproject.net",
  "version": "2.0",
  "categories": [ "default" ],
  "tags": [ "developer", "default" ],
  "steps": [
    {
      "name": "settings",
      "HomeRoute": {
        "Action": "Index",
        "Controller": "Home",
        "Area": "OrchardCore.Commons"
      }
    },
    {
      "name": "themes",
      "admin": "TheAdmin",
      "site": "TheTheme"
    }
  ]
}
```
3. Setup with the saas recipe.
4. Exception.

**Comment by jtkech** [comment] 2018-03-14 22:31
I think this is the same issue we had with deferred tasks which execute at the end of a request. The problem is when we have a parent service scope and a nested scope which try to update the same table. It works with sql but not with sqlite.

For deferred tasks at the end of the request but still in the parent scope (here the request scope), the solution was to first release the  request scope. Another solution would be to be out of the request scope.

So, i think the issue is specific to sqlite but here i don't know yet what we could do. As i have time i will try this scenario.

**Comment by sebastienros** [comment] 2018-03-14 22:36
Each recipe step runs in its own service scope, the issue here is the step is executing an external recipe, so it will itself create a new one, but the parent one is not yet done. If the inner one had been included in the parent recipe, then all the steps would have been done serially. I assume here we should then close the previous scope and create a new one.

There are many ways to fix this, like passing the service scope as reference, and reassigning a new one, or closing it explicitly, then we would have to change the way we closed it initially.

**Comment by jtkech** [comment] 2018-03-14 23:16
Oh, forgot to mention that for deferred task (used e.g when enable / disable a feature) when doing `GetOrCreateShellContext()` then `EnterServiceScope()` a new scope was created but with a **reloaded shellContext** (because of the feature changes) so with a new session which was trying to write to the same table when disposing ...

So, maybe the same problem here, but not sure now, always hard to remember all details around this, need to re-put this in my mind e.g by trying this scenario.

**Comment by jtkech** [comment] 2018-03-14 23:31
@sebastienros oh yes, re-reading your comment, maybe here not a problem of nested scopes but just because the previous one was not released (more precisely its related shellContext), but again not sure at the moment.

I will try it on my branch because in the shellContext i added a `_scopeCount` and in this branch the shellContext is auto disposed when a scope ends if there is no active requests (`_refCount = 0`) and no other active scopes (`_scopeCount` = 0).

**Comment by jtkech** [comment] 2018-03-15 05:19
@alberthajdu @sebastienros 

I returned back on this one, as said in my first comments i could see a nested scope but what i said in my last comment is wrong. @sebastienros you are right i could see the inner scope because of the `RecipesStep` step which executes itself a recipe.

I didn't find an obvious way for reassigning a new scope or closing it explicitly. What i could do created other issues, but maybe i didn't do it right, i will re-try it tomorrow.

But, for testing, i could fix it by checking in `ExecuteStepAsync()` if it is a `RecipesStep`, and if so by calling a new `ExecuteRecipeStepAsync()` which doesn't create a new scope, and uses the existing scope services through an `_httpContextAccessor` just to resolve `recipeStepHandler`. This knowing that the triggered handler (the `RecipesStep`) will recall itself `_recipeManager.ExecuteAsync()` where each inner step execution will create a new scope ...

**Comment by jtkech** [comment] 2018-03-15 07:40
@sebastienros 

I couldn't get it working by reassigning / closing the scope. Maybe i didn't do it right, i will re-try tomorrow, no luck to have to do this for sqlite. Meanwhile here the testing solution which works for me.

Add this at the beginning of `ExecuteStepAsync()`.

        private async Task ExecuteStepAsync(RecipeExecutionContext recipeStep)
        {
            if (String.Equals(recipeStep.Name, "Recipes", StringComparison.OrdinalIgnoreCase))
            {
                await ExecuteRecipeStepAsync(recipeStep);
                return;
            }
            ... // for a regular step we create a new scope

And the new `ExecuteRecipeStepAsync()` which doesn't create a new scope because the `RecipeStep` will recall the recipe executor, so the above `ExecuteStepAsync()` will be recalled for each inner step.

        private async Task ExecuteRecipeStepAsync(RecipeExecutionContext recipeStep)
        {
            var serviceProvider = _httpContextAccessor.HttpContext.RequestServices;
            var recipeStepHandlers = serviceProvider.GetServices<IRecipeStepHandler>();

            foreach (var recipeStepHandler in recipeStepHandlers)
            {
                await recipeStepHandler.ExecuteAsync(recipeStep);
            }
        }

**Comment by jtkech** [comment] 2018-03-16 05:40
Finally @sebastienros gave me the idea to enlist the inner recipes for later executions ... First tests seem to work, so it will be fixed soon.

**Closed** 2018-04-02 16:59 UTC

**Comment by alberthajdu** [comment] 2018-04-04 09:52
Tested, it works well now, thank you.
