### ISSUE TITLE
Question: Delete Tenant

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5137] opened 2019-12-26 22:22 UTC
I see no way to delete a tenant in the admin UI.
To delete it manually do I delete the folder and remove it from the tenants json file?
Is that it?
I noticed you guys have talked about this before but still no delete ability?

**Comment by hishamco** [comment] 2019-12-26 22:53
Duplicate of #1212

**Closed by hishamco** 2019-12-26 22:53 UTC
Labels: duplicate

**Comment by JoshTango** [comment] 2019-12-26 22:59
well I choose separate SQLite database for each tenant so that means just delete the folder yes?

**Comment by hishamco** [comment] 2019-12-26 23:02
Also you should delete it's entry from `tenants.json`

**Comment by JoshTango** [comment] 2019-12-26 23:14
yes that's what I asked.
I tried and it all worked fine.
Delete folder and entry in tenants.json
