### ISSUE TITLE
Break recipe json file up into smaller ones for migration

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#13094] opened 2023-01-16 18:20 UTC
In Asp.Net we have the ability break up a config file up into smaller ones like so:

  "<appSettings configSource="AppSettings.config" />"

I would like this same ability used for recipes.  

I really don't like large recipes because they are large json files which I hate.  I prefer to break them up and make them more granular especially for source control purposes.  

Now you might say that Orchard already has the ability in a recipe to invoke other smaller recipes.  This is true.  The problem is that it doesn't support global variables.  There is no way to declare global variables and send them into the recipe.

So I would like recipes json files to support references to other json files to complete the whole json file.

**Comment by ns8482e** [comment] 2023-01-17 14:30
you can always call other recipes from a recipe.  

You can define your recipe in separate self contained recipe specific to feature groups, and then you can have an umbrella recipe that defines those recipes.

**Comment by JoshTango** [comment] 2023-01-17 14:33
Yes I said that but if the parent recipe declares some global variables can the child recipes access it?  I think the snwer is no.

**Comment by jtkech** [comment] 2023-01-17 15:10
Can you try it?

Looking at the code of `RecipeExecutor.ExecuteAsync()` it seems that for inner recipes we recursively call `ExecuteAsync()` by passing the same `IDictionary<string, object> environment` parameter which may be used for what you want, `methodProviders.Add(new ParametersMethodProvider(environment))`.

**Comment by JoshTango** [comment] 2023-01-17 18:51
I have this:

 "steps": [
    {
      "name": "recipes",
      "Values": [
        {
          "executionid": "OCPlatform",
          "name": "TestRecipe"
        }

      ]
    }
  ]

but it wont work.
Both recipes are inside the migrations folder.  Is this correct?
Also are the errors masked?  It won't bubble me up an error.

**Comment by jtkech** [comment] 2023-01-18 21:29
> Both recipes are inside the migrations folder. Is this correct?

For info recipes are intended to be uder a `Recipes` folder of a Module or Theme.

**Comment by JoshTango** [comment] 2023-01-18 22:08
Yes

**Comment by JoshTango** [comment] 2023-01-18 23:49
I actually had tried with the parent recipe in the migrations folder and the child recipe in the Recipes folder but that didnt work either.  I will play with some more configurations.

**Comment by JoshTango** [comment] 2023-01-19 15:01
Ok so I removed the recipes from my migrations folder and put them in the recipe folder.  I went to the recipes admin menu option and ran the parent recipe.  It successfully ran the child recipe so there is nothing wrong with my recipes.

**Comment by JoshTango** [comment] 2023-01-19 15:07
Alright I now try withmy parent recipe in the migrations folder and the child recipe in the recipes folder.  When I enable my module my app HANGS with no error dislayed.  So maybe there is a bug here?  Maybe the recipes step does not work for migrations?

**Comment by JoshTango** [comment] 2023-01-19 21:06
I opened a bug for this: #13118

**Comment by JoshTango** [comment] 2023-01-22 01:46
Ok I tried just having the variables defined in the parent recipe but it looks like the child recipe can't access global variables because I got this message:

An unhandled exception occurred while processing the request.
ValidationException: The variable 'tagsContentItemId' was used in the recipe but not defined. Make sure you add the 'tagsContentItemId' variable in the 'variables' section of the recipe.

**Comment by jtkech** [comment] 2023-01-22 03:35
Did you tried it with a regular recipe, not a migration recipe? Hmm, I assume it will be the same.

Yes, looks like we don't pass global variables to inner recipes, in fact we use a `_methodProviders` dictionary on which we add `methodProviders` including a `ParametersMethodProvider()`.

    ...
    _methodProviders.Add(executionId, methodProviders);
    methodProviders.Add(new ParametersMethodProvider(environment));
    ...

But as you can see, to update this dictionary we use as a key the `executionId` of the current recipe, so because we generate a different id per inner recipe, I think each recipe retrieve isolated providers.

Note: Looks like it is useless to specify `executionid` as they are generated by code.

    if (recipeStep.InnerRecipes != null)
    {
        foreach (var descriptor in recipeStep.InnerRecipes)
        {
            var innerExecutionId = Guid.NewGuid().ToString();
            await ExecuteAsync(innerExecutionId, descriptor, environment, cancellationToken);
        }
    }

So we would need a new `GlobalParametersMethodProvider()` that would use the execution id of the parent recipe to be able to use the provider giving access to the params of the parent recipe. The 
`environment` param is also a dictionary that we pass as is to all inner recipes, maybe we could use it to pass the execution id of the parent recipe.

**Comment by JoshTango** [comment] 2023-01-22 04:01
Yes I am now trying with normal recipes

**Comment by JoshTango** [comment] 2023-01-22 04:05
Looks like someone wanted to enforce uniqueness for some reason as far as the execution id's are concerned.

**Comment by JoshTango** [comment] 2023-01-22 04:29
I would have thought that you had made a recipe execute class and made an instance object for each inner recipe and called object.Execute().
But it seems you have one object to execute all of the inner recipes.I see your pattern now I think.

**Comment by JoshTango** [comment] 2023-01-22 04:31
also the next issue coming down the road is what happens if an inner recipe spawns an inner recipe which spawns another inner recipe etc etc and you end up with a huge tree of inner recipes.

**Comment by JoshTango** [comment] 2023-01-22 05:22
Ok so ExecuteAsync is a recursive method.  I see now.
Actually I have thought the whole thing through and I don't think you support the concept of global variables the way things are designed.  I will try and write my explanation down and post it tomorrow.  My original idea of breaking up the json file into smaller chunks is probably more correct.

**Comment by JoshTango** [comment] 2023-01-22 16:01
The issue here is name collisions of the variables.  Each inner recipe can define its own variables.  These variable names could potentially collide with the name of a variable in another recipe.
 
Now one way of implementing this is each time an inner recipe is processed it creates a distinct list of variables using the variables defined inside it plus the variables sent into it from the parent. If it came across a name collision it would swap in the value of the inner recipe for the value provided by the parent recipe.  That way the inner recipe uses the values of the most recent scope.  The inner recipe would then send this new distinct list of variables with the latest values down to any further inner recipe.  And so on and so on.
 
While this can be done the real issue here is the perspective of the authors.  Orchard has communicated a certain design at the moment.  It appears the recipes are authored to be self contained units.   How would the author know that recipes are to be designed in such a way that they will be processed in a hierarchy? 
 
You might have to add a syntactical sugar change to the json recipes files for example.  Perhaps when you define a variable instead of saying js:  uuid you can say get value from parent recipe?  That way the recipe expects a parent recipe to send in a value for the variable.  It gets to be tricky as to how far you want to go with this and support it.  
 
I suspect at the moment the design team might say low priority or no completely but maybe in the future they might give this a higher priority.  You can think about it.

**Comment by sebastienros** [comment] 2023-01-26 18:25
When sub recipes are invoked, we should be able to pass custom variables (name and values). Then if the sub-recipe declares a variable, you use this name. There can't be conflicts.

**Comment by Piedone** [comment] 2024-05-21 20:03
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/11227.

**Closed by Piedone** 2024-05-21 20:03 UTC
Labels: enhancement
