### ISSUE TITLE
MySQL: Data too long for column 'Content' at row 1

### ISSUE THREAD

**Issue by Sen-Gupta** [OrchardCMS/OrchardCore#8111] opened 2020-12-21 14:59 UTC
Hello OrchardCore Team,

While running recipe, in MySQL with around 150 items with around 30 fields we received the following error:

Data too long for column 'Content' at row 1

   at MySql.Data.MySqlClient.MySqlDataReader.ActivateResultSet() in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 116
   at MySql.Data.MySqlClient.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlDataReader.cs:line 391
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 62
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySql.Data.MySqlClient/MySqlCommand.cs:line 220
   at Dapper.SqlMapper.ExecuteMultiImplAsync(IDbConnection cnn, CommandDefinition command, IEnumerable multiExec) in /_/Dapper/SqlMapper.Async.cs:line 654
   at YesSql.Commands.UpdateDocumentCommand.ExecuteAsync(DbConnection connection, DbTransaction transaction, ISqlDialect dialect, ILogger logger)
   at YesSql.Session.FlushAsync()
   at YesSql.Session.CommitAsync()
   at OrchardCore.Data.Documents.DocumentStore.CommitAsync() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Data/Documents/DocumentStore.cs:line 143
   at OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 345
   at OrchardCore.Environment.Shell.Scope.ShellScope.UsingAsync(Func`2 execute, Boolean activateShell) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Abstractions/Shell/Scope/ShellScope.cs:line 243
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteStepAsync(RecipeExecutionContext recipeStep) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 158
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 102
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken) in /home/runner/work/OrchardCore/OrchardCore/src/OrchardCore/OrchardCore.Recipes.Core/Services/RecipeExecutor.cs:line 119
   at OrchardCore.Recipes.Services.RecipeExecutor.ExecuteAsync(String executionId, RecipeDescriptor recipeDescriptor, Object environment, CancellationToken cancellationToken)

**Comment by Sen-Gupta** [comment] 2020-12-21 15:04
We looked at the definition of "Document" Table in MySQL

CREATE TABLE `<tablePrefix_Document` (
  `Id` int NOT NULL,
  `Type` varchar(255) NOT NULL,
  **`Content` text,**
  `Version` bigint DEFAULT '0',
  PRIMARY KEY (`Id`),
  KEY `IX_Document_Type` (`Type`)
)

Looks like, it Content Field is "Text", should we ahead and make it **LONGTEXT**?

**The first result in google says this:**

**TEXT** is a string data type that can store up to 65,535 characters. TEXT is commonly used for brief articles. 
**LONGTEXT** is a string data type with a maximum length of 4,294,967,295 characters.

**Comment by deanmarcussen** [comment] 2020-12-21 15:24
It would be helpful if you could identify the document, i.e. content item or ??? with the error, and post it here.

**Comment by Sen-Gupta** [comment] 2020-12-21 15:42
It has only ContentTypes and ContentParts Definition.

I have linked the file here. 

Happy to do a PR for this, just point me to file where the change is [needed.]


https://file.io/fKJZVc4ugVHq (Can only download once)

@deanmarcussen file length: 184051 and it is way above the allowed length for text field: 65,535 in my SQL!

**Comment by deanmarcussen** [comment] 2020-12-21 17:12
OK, had a look at the file. 

Good to know it is a Content Definition Document.

So too many content definitions for the document table.

This is one for https://github.com/sebastienros/yessql

Can you open an issue there please?

Short term you could probably alter the column type yourself (but make a backup!)

**Comment by Sen-Gupta** [comment] 2020-12-21 17:32
@deanmarcussen Thanks!

Is 50 contentTypes too many? (They are actually 49)

**Comment by Sen-Gupta** [comment] 2020-12-21 17:32
@deanmarcussen created an issue on YesSQL project. The issue belonged to YesSql.

**Comment by deanmarcussen** [comment] 2020-12-21 17:41
Great. We'll keep it open here for when the issue is cleared and a YesSql update merged in.

**Closed** 2021-05-13 17:35 UTC
