### ISSUE TITLE
Running as docker image - no content

### ISSUE THREAD

**Issue by fenngineering** [OrchardCMS/OrchardCore#5771] opened 2020-03-21 20:24 UTC
I have compiled a empty ASP.Net Core Web with the OrchardCore CMS dependencies, I have not changed anything in the source code and the app runs fine using docker desktop, I was able to setup the default tenent, however when running the app in my kubernettes cluster, i get no content.

I have exec'd on to the pod that is hosting the app and tried curling to localhost i still get no content. I'm scratching me head here i dont know how to debug the app, i dont know where any logs are or whether there is some verbose logging i can enable.

This is the output from 
`curl localhost -v`

`* Expire in 149991 ms for 3 (transfer 0x55a054547f50)`
`* Expire in 200 ms for 4 (transfer 0x55a054547f50)`
`* Connected to localhost (127.0.0.1) port 80 (#0)`
`> GET / HTTP/1.1`
`> Host: localhost`
`> User-Agent: curl/7.64.0`
`> Accept: */*`
`>` 
`< HTTP/1.1 200 OK`
`< Date: Sat, 21 Mar 2020 20:10:33 GMT`
`< Server: Kestrel`
`< Content-Length: 0`
`< X-Powered-By: OrchardCore`

As you can see there is no content served by kestrel for OrchardCore.

The app was running fine in docker desktop, as soon an i create the pod with the image attached the app stops returning content.

This is the console output
`warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]`
      `Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted` `outside of the container. Protected data will be unavailable when container is destroyed.`
`warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]`
     `No XML encryptor configured. Key {e85121c1-becc-4ecf-93d3-48a57f3d5687} may be persisted`  `to storage in unencrypted form.`
`info: Microsoft.Hosting.Lifetime[0]`
`      Now listening on: http://[::]:80`
`info: Microsoft.Hosting.Lifetime[0]`
`      Application started. Press Ctrl+C to shut down.`
`info: Microsoft.Hosting.Lifetime[0]`
`      Hosting environment: Production`
`info: Microsoft.Hosting.Lifetime[0]`
`      Content root path: /app`
`info: OrchardCore.Environment.Shell.ShellHost[0]`
`      Start creation of shells`
`info: OrchardCore.Environment.Shell.Builders.ShellContextFactory[0]`
`      Creating shell context for tenant 'Default'`
`info: OrchardCore.Environment.Shell.ShellHost[0]`
`      Done pre-creating and registering shells`

If you need any thing from me please let me know. 
As i'm running curl directly on the host we can eradicate any configuration higher up in the stack, the above output was taken directly on the box.

Thanks for you help :)

**Comment by hishamco** [comment] 2020-03-21 20:26
This is duplicate of #5762

**Comment by fenngineering** [comment] 2020-03-21 20:28
can you please close the #5762 and keep this one open, as the i believe the issue is the app and not the kube cluster

**Comment by hishamco** [comment] 2020-03-21 20:33
@deanmarcussen any idea why this happening?

**Comment by fenngineering** [comment] 2020-03-21 23:01
These are the steps to reproduce:-

 `git clone https://github.com/fenngineering/FennasPrem.git `
`cd .\FennasPrem.Web`
`docker build . -t fennasprem:latest`
`docker image save -o fennasprem.tar <built image>`
copy image to kube cluster
`sudo docker load --input fennasprem.tar`
`sudo docker tag <imported image> fennasprem:latest`

create the kube deployment:-
`apiVersion: apps/v1`
`kind: Deployment`
`metadata:`
`  name: fennasprem`
`replicas: 1`
`spec:`
`  selector:`
`    matchLabels:`
`      app: fennasprem`
`  strategy:`
`    type: Recreate`
`  template:`
`    metadata:`
`      labels:`
`        app: fennasprem`
`    spec:`
`      containers:`
`        - image: fennasprem:latest`
`          imagePullPolicy: IfNotPresent` 
`          name: fennasprem`
`          env:`
`            - name: ASPNETCORE_ENVIRONMENT`
`              value: Production`
`          ports:`
`            - containerPort: 80`
`---`
Must have mysql server running as configured in appsettings.Production.json with granted access.

Exec on the pod run the below:-
`curl http://localhost -v`

You will see the below:-
`< HTTP/1.1 200 OK`
`< Date: Sat, 21 Mar 2020 20:10:33 GMT`
`< Server: Kestrel`
`< **Content-Length: 0**`
`< X-Powered-By: OrchardCore`

I can prove a dump of the mysql database if required.

**Comment by Skrypt** [comment] 2020-03-22 18:16
As explained here : https://hub.docker.com/r/orchardproject/orchardcore-cms-linux

> Either a relative or absolute file system path where the information about the configured tenants will be stored. A persistent storage is necessary to persist site configuration when an image is restarted. Using a folder that is shared across docker instances will ensure that the same site configuration can be shared across images.

Or you can enable the Azure Dataprotection module and store the Dataprotection key in Azure Blob Storage.

**Comment by fenngineering** [comment] 2020-03-22 20:28
Thanks for you steady reply, I have got to the bottom of the issue, after switching environment from prod to dev the site started to work. After inspecting the appsettings for both i looked at the "RequestUrlHost" of the tenent, it seemed that i had entered "http://fennasprem.co.uk" as the host name, this is incorrect, after removing the "http://" out of the string and re-deployed the app the site started to serve.

i'm interested to now how to configure the DataProtection-Keys for a kubernettes pod, as the app has one pod at the moment, when i start scaling this will become a problem. Looking at the link provided above the guide discusses the ORCHARD_APP_DATA env variable, if this env variable configurable in my setup?

i'm thinking about configuring the deployment spec as below:-

`env:`
`   - name: ASPNETCORE_ENVIRONMENT`
`      value: Production`
`   - name: ORCHARD_APP_DATA 
`     value: \some\shared\dir`

Would this be the right approach?

Thanks for your help, if you visit [http://fennasprem.co.uk](http://fennasprem.co.uk) you'll see the site is live with SSL and https redirect using letsencrypt.

**Comment by Skrypt** [comment] 2020-03-22 21:57
Right, though I would not say that we recommend using OC with multiple instances as the data caching strategy is in dev still. So each instances would probably not have the same data served if you want to do this as of now ; they are not synced. I think this is mainly why we are not providing any tutorial for doing this yet, it is experimental. Though, @jtkech is making progress on it.

**Comment by deanmarcussen** [comment] 2020-03-23 08:26
Yes, moving the App_Data to a shared volume is reasonably crucial if you are bringing different containers up and down.

@Skrypt is correct in not advising not running multiple instances at the same time.

Other features you should / could consider during your Docker / OC journey
- The Azure DataProtection feature (enabled in Configuration -> Features - Data Protection)
- Azure Media Storage
- Database Content Definition Store
- Recently added to dev (myget feed, not available on RC1 the Database and Azure Shells Configuration feature)

Will close this as I believe the issue has been resolved

**Closed by deanmarcussen** 2020-03-23 08:26 UTC
