### ISSUE TITLE
Boolean fields not working with switch editor

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#6074] opened 2020-05-01 08:00 UTC
Using the switch editor for boolean fields in a widget do not toggle the on/off state.

To repro :

- Using the blog recipe create a new Contenttype with stereotype "Widget"  and name it  eg "Carousel"
- For this new widget type add a  boolean field name "Include Controls" and set the  editor to "Switch" control.

- Create a new page and in the flow part add a new widget "Carousel".
- Try and toggle the state of the "Include Controls" boolean field. **It does not change its state.**
- Publish the page and now the boolean field toggling works.

It seems it has to do with the rendered output for check box 

As shown below in screenshot it renders 2 hidden input fields per boolean field. To my knowledge on mvc binding it should only render one. 
But when you save the page and examine the html for the check box no hidden fields are rendered (which is why the switch toggle then works).
In first case if you delete the 2 hidden inputs then the switch works  in create mode as well. 

![image](https://user-images.githubusercontent.com/1516981/80791441-52e22c00-8b9a-11ea-829f-b9dd6ad7dca5.png)

**Comment by Flarescape** [comment] 2020-09-28 16:10
duplicate of #3944

**Closed** 2020-09-28 16:21 UTC
Labels: duplicate
