### ISSUE TITLE
problem in RTL culture  in admin menu

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3139] opened 2019-02-04 23:03 UTC
if i set Default Culture to Persian, admin menu it will be hidden and doesn't work. I think it's better to move menu panel to right side too.

![capture](https://user-images.githubusercontent.com/24512878/52243289-77891e80-28d9-11e9-8dc4-cd248811a923.PNG)

**Comment by sebastienros** [comment] 2019-02-07 21:12
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3015

**Closed by sebastienros** 2019-02-07 21:12 UTC
Labels: localization
