### ISSUE TITLE
IExternalLoginEventHandler & UpdateRoles problem: RolesToAdd is readonly and can't be modified

### ISSUE THREAD

**Issue by mikoskinen** [OrchardCMS/OrchardCore#4983] opened 2019-12-09 10:24 UTC
I'm trying to implement a custom IExternalLoginEventHandler. I would like to use the custom implementation to modify user roles after Azure AD login.

The problem is that UpdateRolesContext's RolesToAdd and RolesToRemove are readonly and of size 0, so it it seems that it isn't actually possible to modify user roles.

For now I'm going around the issue using reflection:

            var field = typeof(UpdateRolesContext).GetField("<RolesToAdd>k__BackingField", BindingFlags.Instance | BindingFlags.NonPublic);
            field.SetValue(context, new string[]{"Administrator"});

**Comment by hishamco** [comment] 2019-12-09 15:40
Why you didn't use `UserRoles`

@MichaelPetrinolis why the properties `RolesToAdd` and `RolesToRemove` are readonly with size 0?

**Comment by mikoskinen** [comment] 2019-12-09 16:11
@hishamco I checked the AccountController's ExternalLoginSignInAsync and it seems that modifying UserRoles doesn't work. But I have to admit that I didn't try using it. 

Here's how AccountController executes the IExternalLoginEventHandlers:

                foreach (var item in _externalLoginHandlers)
                {
                    try
                    {
                        await item.UpdateRoles(context);
                    }
                    catch (Exception ex)
                    {
                        _logger.LogError(ex, "{externalLoginHandler} - IExternalLoginHandler.UpdateRoles threw an exception", item.GetType());
                    }
                }
                rolesToAdd = context.RolesToAdd;
                rolesToRemove = context.RolesToRemove;

And after that:

            await _userManager.AddToRolesAsync(user, rolesToAdd.Distinct());
            await _userManager.RemoveFromRolesAsync(user, rolesToRemove.Distinct());

**Comment by MichaelPetrinolis** [comment] 2019-12-09 20:21
Hi, @hishamco, it is a bug. I tested the script based scenario and did not see that those properties where readonly. @mikoskinen the handler should inspect current roles (UserRoles property) and based on the received claims should set the rolesToAdd and rolesToRemove. If multiple handlers are set up (which should not be the case), one could also inspect those properties set by other handlers to decide which roles should be set. I will make a PR ASAP, fixing also some other issues that are reported (#4980)

**Comment by jtkech** [comment] 2019-12-09 22:01
For database documents that are cached, we introduced a new `Load / Get` pattern, the related services exposing the 2 methods. When we `Get` a document from the tenant level cache, to be thread safe it is marked as readonly. For updating in a given scope we need to `Load` an isolated document.

This is the case for `RoleStore` that uses an `IMemoryCache`.

The problem is when a mutation go through the `UserManager`, that's why e.g in `.FindByIdAsync()` we now use `LoadRolesAsync()`. So maybe there is a new path where the user manager, before doing a mutation, uses our `.Roles` that uses `GetRolesAsync` that returns read only data.

I will take a look on this.

**Comment by hishamco** [comment] 2019-12-09 23:55
> Update: But here seems to be only related to an User mutation, so, after a quick look, what i was saying above seems to not be related to this issue, sorry ;)

After I looked to the update I stopped to say anything 😄

**Closed** 2019-12-11 18:31 UTC
Labels: Orchard.Users, bug
