### ISSUE TITLE
get permission to save cookie in user browser

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#4987] opened 2019-12-09 20:56 UTC
Regarding European roles, the user should accept save a cookie in his browser. 

is orchard save a cookie in user browser?
i have seen this message in the orchard before but it looks doesn't exist.

please if it is necessary to use, inform me where i can find this script?

**Comment by hishamco** [comment] 2019-12-09 23:24
If am not wrong I already filed an issue long time back about cookies consent

I will search for it because this is a duplicate

**Comment by hishamco** [comment] 2019-12-10 00:27
Duplicate of #3580, I think I will start on this before 1.0

**Closed by hishamco** 2019-12-10 00:27 UTC
