### ISSUE TITLE
customize the specific ContentItems design 

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#6445] opened 2020-06-17 15:01 UTC
Many of the ContentItems I work with have an attached ListPart with multiple content items attached to the parent.i need an option on ListPart for search and sort .How can i customize the specific ContentItems design. 
Example:  i have an ContentItem named **Events** with ListPart **Event**  .
Now i need to sort published,unpublished and search for specific content item inside the listpart.

**Comment by agriffard** [comment] 2020-06-21 08:48
Duplicate of #5349 : Improve List UI

**Closed by agriffard** 2020-06-21 08:48 UTC
