### ISSUE TITLE
Adding authorization providers per tenant

### ISSUE THREAD

**Issue by gentledepp** [OrchardCMS/OrchardCore#1048] opened 2017-09-29 18:23 UTC
Hi!
I am currently playing around with the Optin ID Connect module of OrchardCMS.

We would like to allow our customers to configure their own authentication endpoints. E.g. one of them uses salesforce and would like to let their users to authenticate with their salesforce credentials (OAuth 2.0 based)
Another customer keeps asking about WS Federation (or whatever is currently the best way to let their users authenticate using their Microsoft Active Directory accounts)

Is there any plan of your team to support such a feature?
(Basically, this would suit perfectly into the SAAS recipe)

**Comment by sebastienros** [comment] 2017-10-03 22:34
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/727

**Closed by sebastienros** 2017-10-03 22:34 UTC

**Comment by gentledepp** [comment] 2017-10-04 11:07
May be a duplicate, however, issue #727 is quite a mess so I do not really understand what it is really about.

Just a thought:
Could the module system of orchard enable us to register different asp.net middleware for each tenant? 
Or is that technically not possible?

**Comment by sfmskywalker** [comment] 2017-10-04 16:43
That is definitely possible. The way that works is that you would have a number of Startup classes in your module. Each Startup class would be associated with with a feature (using the `FeatureAttribute`). And since you can constrol per tenant which features are enabled and disabled, you effectively control which middleware you add per tenant.

**Comment by sebastienros** [comment] 2017-10-04 17:48
@gentledepp If you think it's a different issue I am ok to reopen.
