### ISSUE TITLE
Admin: Cultures setting

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#434] opened 2016-12-17 16:19 UTC
Allow to set the allowed cultures and the default one in the admin.

**Comment by agriffard** [comment] 2017-09-09 14:20
This will allow to use the site.Culture setting that appears in TheAgency theme but returns nothing.

**Comment by agriffard** [comment] 2017-09-09 14:23
Wouldn't it be interesting in the future to also add the list of cultures and timezones in the setup to allow to select here the ones you want for the site?

**Comment by agriffard** [comment] 2017-10-07 10:26
Will also allow to initialize the cultures of the application.

https://github.com/OrchardCMS/OrchardCore/blob/8d78c6761297d2198c7a101b4179e28fe67f3651/src/OrchardCore.Modules/OrchardCore.Localization/Startup.cs#L18

**Comment by agriffard** [comment] 2018-05-26 17:56
The current culture setting will be important for the CultureDateTimeFormatProvider and the Localization.

**Comment by Skrypt** [comment] 2018-06-01 01:36
![image](https://user-images.githubusercontent.com/3228637/40816374-8eb6be06-651a-11e8-9a03-c0847dbac806.png)

Here is a screenshot from Drupal to analyse how they do this.

**Comment by agriffard** [comment] 2018-06-04 11:56
Module localization does not seem to work anymore.
In ModularPoFileLocationProvider.cs, where it enumerates the locations to find the .po files:
https://github.com/OrchardCMS/OrchardCore/blob/c6279959a6fbe88ae9d9be9a01e957e886c2ddb6/src/OrchardCore.Modules/OrchardCore.Localization/ModularPoFileLocationProvider.cs#L50

The extensions SubPath are like `.Modules/OrchardCore.ModuleName` so it is trying to find a path like this: `.Modules\\OrchardCore.Admin\\App_Data\\Localization\\en-US.po` and it returns a NotFoundFileInfo
Same problem with the Themes, it won't search in the correct folder.

@jtkech : May be it was working when the /Packages folder was created but not anymore?

**Comment by agriffard** [comment] 2018-06-04 12:03
I also tried try to hardcode the culture in Localization\Startup to test with a fr-FR.po file:

```
public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            var supportedCultures = new[]
            {
                new CultureInfo("en-US"),
                new CultureInfo("fr-FR")
            };

            app.UseRequestLocalization(new RequestLocalizationOptions()
            {
                DefaultRequestCulture = new RequestCulture("fr-FR", "fr-FR"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            });

            base.Configure(app, routes, serviceProvider);
        }
```

but the ModularPoFileLocationProvider only loads the en-us.po in the GetLocations method. 

Is it because the Localization Startup.Configure occurs after, as I can see it in Debug?

**Comment by jtkech** [comment] 2018-06-04 19:28
Yes, `.Modules/{module}/App_Data/Localization/{culture}.po` is the right path, po files are embedded in the related module assembly as other assets. For testing, i created a `fr-FR.po` file in `OC.Body`.

    msgid "Evolutive"
    msgstr "Evolutive"

Then, after enabling `OC.Localization`, in `PortableObjectStringLocalizer` i could see the `Translation`.

![pofiles](https://user-images.githubusercontent.com/8586360/40936426-93e5f364-683b-11e8-86a7-a155afb8921b.png)

So, first check if VS didn't remove your po file from the embedded resources in your csproj file. Then, check if your po file is requested. In my case if i add a `en-US.po` file it is not requested.

I didn't look at it in depth but in `PortableObjectStringLocalizerFactory` i saw the following which creates a `PortableObjectStringLocalizer` using `CultureInfo.CurrentUICulture` which for me is always `fr-FR`.

    public IStringLocalizer Create(Type resourceSource)
    {
        return new PortableObjectStringLocalizer(CultureInfo.CurrentUICulture,
            resourceSource.FullName, _localizationManager, _logger);
    }

Hmm, maybe here we need to use something else than `CultureInfo.CurrentUICulture`.

**Comment by Skrypt** [comment] 2018-06-04 20:09
![image](https://user-images.githubusercontent.com/3228637/40939025-7d861d9e-6811-11e8-86ba-b6b4ed56caa4.png)
I just tested and it works. I had created my po file in /App_Data directly and now after moving it to /App_Data/Localization/ it works.

**Comment by agriffard** [comment] 2018-06-04 20:43
Thank you for the explanations @jtkech 

1) I don't really know why but my culture is en-US, while my computer is in fr-FR and even in Localization\Startup.cs, I set `DefaultRequestCulture = new RequestCulture("fr-FR", "fr-FR")`
This will have to be taken into account when the culture will be set from the Site.Culture setting that @Skrypt is implementing in his PR.


2) One difference was that I added a line with msgctxt:
```
msgctxt "TheAdmin.Views.Admin.AdminDashboard"
msgid "Welcome to Orchard"
msgstr "Bienvenue dans Orchard"
```
so the key in the dictionary was "theadmin.views.admin.admindashboard|Welcome to Orchard"

That is something that should work because .po files format is more like this.


3) I had created the folders and added the .po files from the Windows Explorer, not from VS and they appeared with a little red minus icon in the solution explorer so may be they were not included previously as you explained.

**Comment by Skrypt** [comment] 2018-06-04 20:51
If I remember in 01 we never change the CultureInfo.CurrentUICulture or CultureInfo.CurrentCulture because it is too "overkill". So CultureInfo.CurrentUICulture used in PortableObjectStringLocalizerFactory should be replaced by retreiving the current site culture with ILocaleCulture.GetLocalCultureAsync();

**Comment by jtkech** [comment] 2018-06-04 21:20
@Skrypt yeah, certainly something like that but, as i understood, maybe based on some culture providers / selectors with a given priority so that the selected culture could come from the site settings or the browser or a given user ... As maybe you already did to select the right local date time and format ...

@agriffard just tried your example which works if in a `fr-FR.po` file.

![pofiles2](https://user-images.githubusercontent.com/8586360/40941708-0d27c008-684c-11e8-9b53-d95bde77f353.png)

**Comment by Skrypt** [comment] 2018-06-04 23:01
Yes exactly though we need to have the ILocalCulture service to get the proper DateTime format. This is what I'm currently working on. Though for the PortableObjectStringLocalizerFactory it is registed as a singleton and our ILocalCulture is a scoped service. I think the PortableObjectStringLocalizerFactory should be also scoped but I'm investigating on this since I can't register a Scoped service inside a Singleton service.

**Comment by jtkech** [comment] 2018-06-05 00:56
Okay i see. Hmm, didn't see it in depth but i think that our `IStringLocalizerFactory` need to be registered as a singleton, e.g if resolved by other mvc factory which are singletons. So maybe use `IHttpContextAccessor` so that when creating an `IStringLocalizer` we could resolve a scoped service to get the selected culture.

Hmm, but after a quick look, we already add the following middleware which has options.

    app.UseRequestLocalization(new RequestLocalizationOptions()
    {
        //TODO set supported cultures
    });

Where we could define the default request culture, supported cultures and ui cultures ... Then, the options has an interesting property.

    public IList<IRequestCultureProvider> RequestCultureProviders { get; set; }

Here the definition of the interface. As you can see when calling `DetermineProviderCultureResult` they pass an `httpContext` from which we could resolve scoped services.

    namespace Microsoft.AspNetCore.Localization
    {
        /// <summary>
        /// Represents a provider for determining the culture information of an <see cref="HttpRequest"/>.
        /// </summary>
        public interface IRequestCultureProvider
        {
            /// <summary>
            /// Implements the provider to determine the culture of the given request.
            /// </summary>
            /// <param name="httpContext">The <see cref="HttpContext"/> for the request.</param>
            /// <returns>
            ///     The determined <see cref="ProviderCultureResult"/>.
            ///     Returns <c>null</c> if the provider couldn't determine a <see cref="ProviderCultureResult"/>.
            /// </returns>
            Task<ProviderCultureResult> DetermineProviderCultureResult(HttpContext httpContext);
        }
    }

**Comment by Skrypt** [comment] 2018-06-05 01:59
Yeah I was looking at httpContext as an alternative thanks @jtkech

**Comment by jtkech** [comment] 2018-06-05 21:04
Yes, so one way would be to make a provider inheriting of [this abstract class ](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestCultureProvider.cs#L13) and uses the Request Services in `DetermineProviderCultureResult()`. Then insert this provider in the options `.RequestCultureProviders` before the default ones, and also provide the options `.SupportedCultures` and `.SupportedUICultures`.

 Then the [middleware will use our provider here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L73) to grab our selected cultures. Then the [request culture feature will be set here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L132) and [the **current thread culture** will be updated here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L146). [See here one of the default implementations](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/AcceptLanguageHeaderRequestCultureProvider.cs#L16) of a `RequestCultureProvider`.

Also normally `.UseRequestLocalization()` needs to be called before `.UseMvc()`, in our case this stuff is done in our `ModularTenantRouterMiddleware`. After a quick look seems to be ok but needs to be tried, maybe we will need a lower value the startup order (or the priority) of the localization module.

---

The **1st above solution** makes things at the soure **but i have a little concern**, the localization middleware will execute in a tenant pipeline where some thread switchings may have been done from the original thread of the request, and maybe the updated thread cultures could be lost when coming back to a parent thread.

Would need to be tried, if it is not a concern the 1st solution would be good, but maybe this middleware has to run very first and this would also concern the default culture providers. If so, maybe we could forbid the usage of e.g `CultureInfo.CurrentUICulture` and always retrieve the request culture from this [httpContext feature which would be set here](https://github.com/aspnet/Localization/blob/dev/src/Microsoft.AspNetCore.Localization/RequestLocalizationMiddleware.cs#L132). But some libraries may use `CultureInfo` directly.

As a **2nd solution** maybe better to not use the localization middleware at the tenant level and just use our `IStringLocalizerFactory` which will use an `IHttpContextAccessor`. And maybe we could still call `.UseRequestLocalization()` but at the host level by the app to not loose the default providers which will still set the thread cultures to some coherent values but not too late.

**Sorry for the long story**, maybe the 1st solution is already ok OR we just have to use the 2nd one and without using the localization middleware at all, but not sure, we will just need to do some tests.

**Comment by Skrypt** [comment] 2018-06-06 00:50
Yeah, I'm ambivalent here as we used to never alter the `CultureInfo.CurrentUICulture` and `CultureInfo.CurrentCulture` so if we want to reproduce the same pattern as in 01 we should opt for **2nd solution**. Though I'm going to try both solutions and do some testing. I should be able to work on this mostly this week-end as I'm quite busy this week. We'll see.

**Comment by jtkech** [comment] 2018-06-06 02:56
Okay. So, i made some tests, the 1st part is the results of my tests, and maybe the 2nd part is more pertinent on what we have to do.

- To make the localization module configure running first, i used a startup order of `int.MinValue` (the mvc module now has the same value). And a manifest priority of `-15` (mvc now has a priority of -10).

- Then i added what @agriffard did in the localization startup to see the default providers in action.

            var supportedCultures = new[]
            {
                new CultureInfo("en-US"),
                new CultureInfo("fr-FR")
            };

            var options = new RequestLocalizationOptions()
            {
                DefaultRequestCulture = new RequestCulture("fr-FR", "fr-FR"),
                SupportedCultures = supportedCultures,
                SupportedUICultures = supportedCultures
            };

            app.UseRequestLocalization(options);

    And put a breakpoint here.

      public IStringLocalizer Create(Type resourceSource)
      {
          return new PortableObjectStringLocalizer(CultureInfo.CurrentUICulture,
              resourceSource.FullName, _localizationManager, _logger);
      }

    Then, to see the `AcceptLanguageHeaderRequestCultureProvider` in action, i changed my browser language to `en-US`. Then i could see the right `CultureInfo.CurrentUICulture` so what i was saying about loosing the thread cultures was maybe wrong.

    **That said there are exceptions** when we start the application, in the first 3 calls we don't have the right culture. The 1st one is when doing automatic migrations while activating the shell, this because it occurs before the tenant middlewares, and we resolve `DataMigrationManager` which uses an `IStringLocalizer`.

    The two other ones was when a module resolve a service in its own startup configure method, so before the localization middleware could have been executed. It was the `FilesScriptEngine` and the `JavaScriptEngine` which use an `IStringLocalizer`.

    **Otherwise, in all subsequent calls, for the lifetime of the app, we retrieve the right culture**.

- Then i added a simple custom provider, here a delegate version, where, remember, context is an httpContext so it will be easy to resolve your custom local culture provider.

      options.RequestCultureProviders.Insert(0, new CustomRequestCultureProvider(context =>
      {
          return System.Threading.Tasks.Task.FromResult(new ProviderCultureResult("en-US"));
      }));

    Then the result was the same, we get the right culture unless on the first 3 calls when we start the app as described above. But maybe it is not a concern and this solution would be good, this if it is useful to keep the default culture providers, e.g if our own provider returns a not found culture.

- Finally, by using the same code but in the startup of the application, i could see the right culture even on the 1st calls when starting the app. But it is just for infos because we want cultures per tenant.

---

That said one compromise, if we want to keep the default request culture providers and we don't want to rely on `CultureInfo.CurrentUICulture` neither on the request culture feature which all are updated by the localization middleware, **would be to not use the localization middleware at all**.

Then we could have a custom scoped culture manager which would resolve our own culture(s) provider(s), and one of them with the same interface (and a lower priority) which only wraps the usage of the default ones, maybe in a separate feature. The default providers would be easy to retrieve and then used as fallbacks of our providers with a higher priority (if enabled), this without using the middleware and then without updating the thread cultures and the request culture feature.

    var options = new RequestLocalizationOptions().RequestCultureProviders;
    if (_options != null)
    {
        foreach (var provider in _options.RequestCultureProviders)
        {
            var providerResultCulture = await provider.DetermineProviderCultureResult(context);
            if (providerResultCulture == null)
            {
                continue;
            }
            ...

Then our `PortableObjectStringLocalizerFactory` could use an `IHttpContextAccessor` to resolve this scoped culture manager (or another name).

**Comment by Skrypt** [comment] 2018-06-06 05:43
Scoped culture manager = ILocaleCulture in my new branch.

**Comment by jtkech** [comment] 2018-06-06 06:34
Okay cool, just saw your branch, seems that you already create all the needed infrastructure 👍 so i think it will be easy to make it working (if it is not already the case). I will take a look tomorrow night.

**Comment by agriffard** [comment] 2018-06-18 11:57
http://hishambinateya.com/what%27s-new-in-asp.net-core-2.1-localization

In 2.1, it seems you can now use a new builder API for configuring UseRequestLocalization.

**Comment by hishamco** [comment] 2018-07-21 12:20
@agriffard yep, localization builder APIs simplify the setup for the supported cultures

**Closed** 2018-08-08 22:42 UTC
Labels: localization
