### ISSUE TITLE
Brand new setup error

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8547] opened 2021-02-08 19:44 UTC
I configured a brand new installation with 2 databases.
One for the content called MainDB and one for the shell called ConfigDB.
I set my appsettings.json file with shell config and default table.
When I run the setup page for the first time I get only 2 tables with the prefix of default.
Default_Documents and Default_Identifiers
The rest of the tables have no prefix.

The webpage simply goes back to the setup page.

```
 "OrchardCore": {
    "ConnectionString": "Server=???????;", // Set to the database connection string.,
    "DatabaseProvider": "SqlConnection",
    "OrchardCore_Shells_Database": {
      "DatabaseProvider": "SqlConnection", // Set to a supported database provider.
      "ConnectionString": "Server=???????", // Set to the database connection string.
      "TablePrefix": "OrchardConfig_", // Optionally, configure a table prefix.
      "MigrateFromFiles": false // Optionally, enable to migrate existing App_Data files to Database automatically.
    },
    "Default": {
      "TablePrefix": "Default"
    }
  }
```

**Comment by Skrypt** [comment] 2021-02-09 00:00
Which database provider you are using?

**Comment by JoshTango** [comment] 2021-02-09 00:16
Microsoft SQL Azure

**Comment by JoshTango** [comment] 2021-02-09 00:16
Oh I actually forgot to fill that in.  But it created tables anyways.

**Comment by Skrypt** [comment] 2021-02-09 00:30
The only reason I can see why it created these tables with the "Default_" prefix is because that it tried creating a tenant with a prefix set to "Default". 

I think you found an exception there. It's probably related to the fact that the "Default" tenant doesn't use normally prefixed table names. And here you probably tried to name your tenant explicitly "Default". So a tenant name should never be named "Default".

Need to have repro steps. But we have some lead here that could be the potential issue.

**Comment by JoshTango** [comment] 2021-02-09 00:32
Well I got it from this documentation:

**Comment by Skrypt** [comment] 2021-02-09 00:37
Ok, thanks, I will try it when I get the time.
In the mean time, try removing the prefix for the default tenant.

**Comment by JoshTango** [comment] 2021-02-09 00:38
Yes I suspect that will work but the documentation said to name it DEFAULT

**Comment by Skrypt** [comment] 2021-02-09 00:40
Yes, documentation can be fixed but I believe the default tenant should never use a prefix. So, I think this is where the issue is. We are missing a validation there in the Configurations to avoid this from happening.

**Comment by JoshTango** [comment] 2021-02-09 00:43
I see, it almost sounds like the documentation is providing guidance to configure a prefix for the default tenant.

**Comment by jtkech** [comment] 2021-02-09 04:33
@Skrypt we can have a table prefix for the default tenant, and it can be named `Default`.

@JoshTango All need to be under the OrchardCore section, also your `Default` `TablePrefix`, see https://github.com/OrchardCMS/OrchardCore/issues/8532#issuecomment-774822157

    {
        "OrchardCore": {
        "ConnectionString": "...",
        "DatabaseProvider": "SqlConnection",
        "Default" : {
            "TablePrefix": "Default"
        }
    }

The documentation has been fixed #8540

**Comment by JoshTango** [comment] 2021-02-09 12:01
Yes I did move the location in my appsettings.json file for the default table prefix. 
I still got an error.
@jtkech

**Comment by JoshTango** [comment] 2021-02-09 12:35
BTW I do think the tenants should be moved under their own TENANT node in the appsettings.json file.  Putting them directly under OrchardCore is not ideal.  Should be OrchardCore-->Tenants-->list of all tenants.

**Comment by jtkech** [comment] 2021-02-09 12:40
@jagbarcelo 

Okay, so maybe it is not allowed when using shell settings in the database, i will try it when i will have time

Can you check if it still works to use `.AddDatabaseShellsConfiguration()` but without any prefix?

**Comment by jtkech** [comment] 2021-02-09 17:55
@JoshTango 

Okay i could get it working

First, i forgot that when we want pre-configured properties for a given tenant, we need to specify a valid tenant `State`, most of the time we don't have a full running pre-configured tenant, so `Uninitialized` is okay. As documented here https://docs.orchardcore.net/en/dev/docs/reference/core/Configuration/#tenant-preconfiguration

    "Default": {
      "State": "Uninitialized",
      "TablePrefix": "Default"
    }

Then, when there is any pre-configured property specific to a tenant, as here for the prefix, when using the shells settings from the database, it fails on an NRE, otherwise without any tenant specific config value it works.

Already fixed on my machine, i will commit a fix soon

Thanks to have find this issue

**Comment by JoshTango** [comment] 2021-02-09 18:02
Then this will mean a document change as well I assume?

**Comment by jtkech** [comment] 2021-02-09 18:05
Do you mean the documentation?

Having to add ` "State": "Uninitialized"` is already documented in the above link

**Comment by Skrypt** [comment] 2021-02-09 18:07
![image](https://user-images.githubusercontent.com/3228637/107407514-c032ce00-6ad7-11eb-95b7-7b0c31981c23.png)

Add it to this example in the documentation to avoid confusion since it is mandatory to have a state.

**Comment by jtkech** [comment] 2021-02-09 18:09
Okay, need to be added here also ;)

**Comment by JoshTango** [comment] 2021-02-09 18:32
Um yes having to set state is documented but its confusing because you dont think of the first instance as a tenant

**Closed** 2021-02-10 01:39 UTC
Labels: bug
