### ISSUE TITLE
Oidc Client  module not work 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#12747] opened 2022-11-01 15:18 UTC
we have a oauth2 server  , not use oc  ,mabe that is a java application.
I'm trying to connect that with my oc application .

see the follow picture .  we have got the code succeed .

![image](https://user-images.githubusercontent.com/15613121/199266627-064308d9-4a64-4b9c-94c7-571d209651bb.png)

but the callback page prompt : "An error occurred while executing this request."

At present, the log is as follows

``` LOG
2022-11-01 22:53:43.6844|Default|00-25e04a055430ce03cdf8fe8545951356-d9e1a389f89a13a6-00||Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler|ERROR|Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null', status code '400'. 
2022-11-01 22:53:43.6844|Default|00-25e04a055430ce03cdf8fe8545951356-d9e1a389f89a13a6-00||Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler|ERROR|Exception occurred while processing message. Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()    at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
2022-11-01 22:53:43.6844|Default|00-25e04a055430ce03cdf8fe8545951356-d9e1a389f89a13a6-00||Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|ERROR|An unhandled exception has occurred while executing the request. System.Exception: An error was encountered while handling the remote login.
 ---> Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolException: Message contains error: 'invalid_client', error_description: 'Invalid authentication method for accessing this endpoint.', error_uri: 'error_uri is null'.
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.RedeemAuthorizationCodeAsync(OpenIdConnectMessage tokenEndpointRequest)
   at Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler.HandleRemoteAuthenticateAsync()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)    at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.HandleRequestAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

```

I tried to find this class in the source code of the `OrchardCore` project, but I did not find it, nor did I find it in the `OpenIdirect-core` project..

Where it is ~?

`Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectHandler`

@kevinchalet  Could you help me ?

**Comment by hyzx86** [comment] 2022-11-01 15:25
![image](https://user-images.githubusercontent.com/15613121/199271054-2a47f02e-df2b-494a-9998-d8bd7d5d5865.png)

**Comment by kevinchalet** [comment] 2022-11-01 16:05
The root cause is clearly identified in the logs:

> Invalid authentication method for accessing this endpoint.

By default, the MSFT OIDC handler uses `client_secret_post` to send the client secret but it's likely your server expects `client_secret_basic`, which is not supported by the MSFT handler. Try to see if you can change that in the options of your server.

Closing, as it's not related to Orchard.

**Closed by kevinchalet** 2022-11-01 16:05 UTC
Labels: bug :bug:

**Comment by hyzx86** [comment] 2022-11-01 16:15
Thanks !

**Comment by hyzx86** [comment] 2022-11-02 03:03
I found it. Maybe I can re implement it

https://github.com/OrchardCMS/OrchardCore/blob/59c51763a0b255c4e8d58b295c842d0bc7f828f5/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdClientConfiguration.cs#L50

**Comment by hyzx86** [comment] 2022-11-02 14:26
Is the `Authentication Client` module in OC a complete module?
Or do I need to implement some operations in the way of development?

I found ` Events MessageReceived ` The event is not implemented in the Microsoft OidcHandler or handled in OC

After a series of checks, it went to the 'RedeemAuthorizationCodeAsync'

**Comment by hyzx86** [comment] 2022-11-02 14:38
![1667399855597](https://user-images.githubusercontent.com/15613121/199518564-f4706fd4-9f29-451c-8f4d-8a8e1f4675cd.jpg)

**Comment by hyzx86** [comment] 2022-11-02 14:46
Sorry, the screenshot above is in the wrong position
should be here

![image](https://user-images.githubusercontent.com/15613121/199520470-5dcca70b-bd45-4a02-8308-a153976aafae.png)

**Comment by hyzx86** [comment] 2022-11-02 15:16
And here 

``` C#
  await Events.AuthorizationCodeReceived(context);
            if (context.Result != null)
            {
                if (context.Result.Handled)
                {
                    Logger.AuthorizationCodeReceivedContextHandledResponse();
                }
                else if (context.Result.Skipped)
                {
                    Logger.AuthorizationCodeReceivedContextSkipped();
                }
            }
```

@kevinchalet  Is it necessary for us to customize the processing method in OC for the above?
I still missed something
