### ISSUE TITLE
Error creating site from template occms

### ISSUE THREAD

**Issue by devhomecali** [OrchardCMS/OrchardCore#6388] opened 2020-06-09 23:18 UTC
**Describe the bug**
Creating a website using the **occms template** from the command prompt, generates an error because it **cannot find a ContentDefinition.json** configuration file. The error only appears when selecting the **Agency recipe** with either a Sqlite or Sql server database. For the blog recipe it does not generate error. 

**To Reproduce**

1. [Follow this guide Code Generation Templates](https://docs.orchardcore.net/en/dev/docs/getting-started/templates/).
2. If the LocalDb\MsSqlLocalDb database does not exist, you must create it from Visual Studio 2019.
3. Create a folder. 
4. Run command from that folder: **dotnet new -i OrchardCore.ProjectTemplates::1.0.0-rc1-***
5. Run command from that folder: **dotnet new occms**
6. Run command from that folder: **dotnet run**
7. Set up the website **with recipe (Agency)**. Connection string: configure **LocalDb\MsSqlLocalDb** database and use **dm7** prefix for tables. There are no tables in the database with the prefix dm7, but there are others.

**Expected behavior**
The Orchardcore CMS website is created with the Agency recipe

**Screenshots**
[Image](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-Cms-Agency-Recipe.png).

**Files**

[File: Error detail](https://github.com/devhomecali/OrchardCore/blob/master/OrchardCore-Error-Setup-Cms-Agency-Recipe.pdf)

**Desktop (please complete the following information):**
- OS: Window 10 Pro x64 1809 updated to date
- Browser: Edge  83.0.478.44

**Comment by sebastienros** [comment] 2020-07-02 17:45
Duplicate of #6360 where LocalDb has been also tested

**Closed by sebastienros** 2020-07-02 17:45 UTC
