### ISSUE TITLE
Time constrained URLs break HTTP Request event workflows

### ISSUE THREAD

**Issue by jonvee** [OrchardCMS/OrchardCore#2200] opened 2018-08-09 17:01 UTC
After some time, forms fail to reach token URLs for HTTP Request events (404) and prevents workflows from triggering. Sebastien mentioned this is due to time constrained URLs.

**Comment by sebastienros** [comment] 2018-08-09 19:30
@sfmskywalker we might need to talk

**Comment by sfmskywalker** [comment] 2018-08-20 12:42
Sounds like that's exactly the issue. We discussed there should be a setting on the HTTP Request Event activity to control the TTL (including an option to set it to indefinitely).

I'm tracking an issue for it here: #1753

**Comment by sebastienros** [comment] 2018-08-23 19:49
Duplicate of #1753

**Closed by sebastienros** 2018-08-23 19:49 UTC
