### ISSUE TITLE
Monaco editor and completion for Liquid Templates

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#5242] opened 2020-01-09 12:38 UTC
Would it be possible to use Monaco to edit the Liquid Templates and to provide code completion for liquid keywords filters?

There is a Handlebars syntax provider which is close to Liquid.
You can also add a custom language with rules:
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-custom-languages

Ex: 
https://colinvermander.com/2018/06/28/dynamics-365-portals-v9-solutions-now-available-and-liquid-editor-change/
https://microsoft.github.io/monaco-editor/playground.html#extending-language-services-completion-provider-example

Even better if we manage to know which Liquid expression is available when you edit a specific content template and provide the available syntax terms.
Ex: https://stackoverflow.com/questions/49244426/how-to-set-intellisense-hints-in-monaco-editor-js-for-handlebars-language

**Comment by agriffard** [comment] 2020-01-09 12:46
https://gist.github.com/LucGranato/e57ffcc68289be404894c52028a8d7b7

**Comment by jptissot** [comment] 2020-01-09 13:51
https://github.com/OrchardCMS/OrchardCore/issues/2345

**Comment by sebastienros** [comment] 2020-01-09 18:45
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2345

**Closed** 2020-01-09 18:45 UTC
