### ISSUE TITLE
Coming soon theme: Toggle form element not working in Edit

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore#2878] opened 2018-12-17 08:21 UTC
When I edit in admin the homepage of a site created with the ComingSoon theme, there are javascript errors and the form elements can not be toggled.

```
popper.js:2423 Uncaught SyntaxError: Unexpected token export
media.js:29 mediaApplicationUrl variable is not defined
```

It is also very weird because the entire 'Edit Coming Soon' block is repeated twice in the page. 
Idem when you want to create a new 'Coming soon' item.

**Comment by MichaelPetrinolis** [comment] 2018-12-17 18:34
It is strange. I tested it with version 70098 I installed yesterday, and experienced the same behavior. Rolled back to a previous version, and the bug vanished. Updated again to 70098 and could not reproduce.

**Comment by sebastienros** [comment] 2018-12-17 18:48
Refreshed scripts maybe?

**Comment by agriffard** [comment] 2018-12-17 18:57
After a hard refresh, it seemed to work but the js errors are still there and after a few toggles, it reappears.

**Comment by sebastienros** [comment] 2018-12-19 00:40
I think the script is included twice, maybe in BS and then by itslef. Remember a recent change from @matiasmolleja which added it where is was missing. I assume it was not missing in all these places.

**Comment by sebastienros** [comment] 2018-12-19 00:40
But I am working on it, and fixing the other issues that were introduced recently 😉 😉

**Comment by MichaelPetrinolis** [comment] 2018-12-19 05:57
Maybe that's the reason you need to click twice on a 'dropdown' classed button for the menu to appear.

**Comment by sebastienros** [comment] 2018-12-19 06:12
It's fixed in my pr.

**Comment by agriffard** [comment] 2018-12-23 10:20
I tried again and when I edit the homepage, the whole content is still repeated twice.

I don't think that the error comes from popper.js, I hard refreshed the cache.

**Comment by agriffard** [comment] 2018-12-27 09:45
Ok, found the issue: It was because the OrchardCore.Media module was not enabled.

Do we need to add it explicitly in the recipe?

It is weird because it is a requred feature in OrchardCore.Html for the HtmlBodyPart that is used as a Widget in the form. Why hasn't it been enabled?

**Closed** 2018-12-31 18:36 UTC
