### ISSUE TITLE
Trumbowyg icon doesn't display

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6416] opened 2020-06-14 08:29 UTC
Hi, while using trumbowyg editor it doesn't show the icons. I think there is something wrong with .js file please refer to attached screent shot. Data passed to serializeToString function is null as define in line 237.
Kindly advise?
![error](https://user-images.githubusercontent.com/56805276/84588674-e7fc6400-ae6c-11ea-9558-4a48365cde5b.png)

**Comment by Piedone** [comment] 2020-06-16 14:53
Can you export your site's content so we can see how the FaqHtml content type is defined? Or can you at least share screenshots of the type and field settings editor?

**Comment by agriffard** [comment] 2020-07-11 14:14
Duplicate of #6634

**Closed by agriffard** 2020-07-11 14:14 UTC
