### ISSUE TITLE
OC versioning

### ISSUE THREAD

**Issue by agentgates** [OrchardCMS/OrchardCore#1195] opened 2017-11-09 11:56 UTC
Hello Everyone,

May I have a suggestion that a version indicator would be rather useful on the dashboard to distinguish instances of multiple servers with different versions of OC. I believe the bottom left corner, below the menu, would be the most ideal place.

Many thanks in advance.

**Comment by agriffard** [comment] 2017-11-09 15:01
Duplicate of #432

**Closed** 2017-11-09 20:41 UTC
