### ISSUE TITLE
Support AzureAD B2C

### ISSUE THREAD

**Issue by Narnain** [OrchardCMS/OrchardCore#3712] opened 2019-05-27 16:10 UTC
Please support AzureAD B2C under Microsoft Authentication.

**Comment by sebastienros** [comment] 2019-05-30 19:42
@MichaelPetrinolis isn't it already supported?

**Comment by MichaelPetrinolis** [comment] 2019-05-31 08:07
We support Azure AD and Azure B2B which is a feature of AAD. Azure B2C is a different service. It is a good candidate to replace local authentication, as @PinpointTownes said in #2029. Otherwise it would need roles synchronization and disabling local pasword login for users.

**Comment by psijkof** [comment] 2019-07-05 13:10
Then maybe we should see if we could integrate with other IDaaS providers like auth0, okta, etc...?

**Comment by MichaelPetrinolis** [comment] 2019-07-05 15:29
@psijkof you can use the OpenID connect client to link local users with another IDaaS provider

**Comment by jimitndiaye** [comment] 2021-09-23 18:19
I'm interested in this exact scenario. Are there some specific stumbling blocks to be aware of? I notice that it is currently marked for the 1.1 milestone but if we need to roll our own due to time constraints it would help if had an idea of potential problems.

**Comment by aderderian** [comment] 2022-07-02 14:13
Hello, have we made any progress on this one? I have it configured, but am getting an error upon login : 

An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: IDX21336: Both 'id_token' and 'access_token' should be present in OpenIdConnectProtocolValidationContext.ProtocolMessage received from Token Endpoint. Cannot process the message.
Microsoft.IdentityModel.Protocols.OpenIdConnect.OpenIdConnectProtocolValidator.ValidateTokenResponse(OpenIdConnectProtocolValidationContext validationContext)

Exception: An error was encountered while handling the remote login.
Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler<TOptions>.HandleRequestAsync()

**Comment by MichaelPetrinolis** [comment] 2022-07-02 14:51
It seems you have configured a flow that requires ID and Access token, like hybrid. If this is your case, I suppose you must configure azuread to provide them for your client. I haven't use B2C but the documentation states it can be used with OpenID connect, so you should be able to configure both parties to work together.

**Comment by aderderian** [comment] 2022-07-02 15:10
I am configuring it using the OC Orchard OpenId Client Setup...I configured a basic flow in Azure B2C. Is there a recommend config you know works on both ends? Thanks @MichaelPetrinolis !

**Comment by MichaelPetrinolis** [comment] 2022-07-02 15:59
I would try to require OpenID profile and email scopes on orchard core side and enable id_token and access token on server side.

**Comment by aderderian** [comment] 2022-07-02 16:46
I think I have all that : Here is the config :

![image](https://user-images.githubusercontent.com/868165/177009203-1b9e6f6c-3cfc-4170-9f62-6ba4cb3fc304.png)

![image](https://user-images.githubusercontent.com/868165/177009182-45533839-bf9b-493b-a62f-e404aaef065b.png)


![image](https://user-images.githubusercontent.com/868165/177009167-87975f69-e3cb-4e87-8885-e462e2f31efd.png)

**Comment by aderderian** [comment] 2022-07-05 19:00
@MichaelPetrinolis setting up OC OIDC Client settings to use Implicit Flow instead of Code or Hybrid got it working. I am still getting an issue where it is requiring an email for registration and failing for some reason. I added 'email' scope to additional scope in OC settings and am not asking for email in settings.

![image](https://user-images.githubusercontent.com/868165/177396810-250d7bf8-ea63-4b54-add6-9d89f7c0dc76.png)

**Comment by MichaelPetrinolis** [comment] 2022-07-05 21:07
@aderderian you must add the email claim in AzureAD B2C. Check the documentation. In the [AzureAD integration how-to guide](https://docs.orchardcore.net/en/dev/docs/guides/azuread-integration/) we do the same, we add the email optional claim.

**Comment by MichaelPetrinolis** [comment] 2022-07-07 05:20
@aderderian  so it seems you need to add `<OutputClaim ClaimTypeReferenceId="signInNames.emailAddress" PartnerClaimType="email"/>` in your  `TrustFrameworkBase.xml` file.

**Comment by aderderian** [comment] 2022-07-07 14:08
Thanks @MichaelPetrinolis . Is there a blog or document you could point me to on how to take an Out of the Box User Flow and just edit that single line in the existing TrustFrameworkBase.xml file? The path I took was downloading the existing xml for my signin process as well as the other 4 base policies behind it. I then had to split them out and re-upload to custom policies. Super manual and painful process. I also had to create two apps and 4 secrets just to support this. Is there an easier way to achieve this one line change?

Any advice would be great. I think then this ticket could be closed as supported by OC. I can summarize in docs if it helps others as well.

Blogs I looked at :

Step 1 - https://blog.wojtek.pro/azure-ad-b2c-custom-policies-how-to-begin/
Step 2 - https://blog.wojtek.pro/azure-ad-b2c-custom-policies-importing-the-exported/
Step 3 - https://docs.microsoft.com/en-us/azure/active-directory-b2c/tutorial-create-user-flows?pivots=b2c-custom-policy#register-applications

**Comment by aderderian** [comment] 2022-07-11 17:09
@MichaelPetrinolis any idea on how you modify this one setting you mentioned without having to build custom policies? Is there a way to update this TrustFrameworkBase.xml using the baked in User Flows? Thx

**Comment by MichaelPetrinolis** [comment] 2022-07-11 18:11
@aderderian unfortunately I haven't used Azure AD B2C. Maybe you should ask Azure Support for help.

**Comment by MichaelPetrinolis** [comment] 2022-07-12 22:04
@aderderian maybe we should extend the IExternalLoginEventHandler and add a method to define the email in the context, and use that in order to match an existing user. But `email` and `email_verified` are standard claims defined in the [openid spec](https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.5.1) and they should be used if no email is set in the context.

**Comment by aderderian** [comment] 2022-07-25 21:48
@MichaelPetrinolis I spoke with MSFT and they're investigating this issue with the email claim not being returned as well. Secondarily, in the end of all this I want to be able to use Azure B2C as my central authorization provider. @sfmskywalker wrote an article some time ago (https://medium.com/swlh/orchard-core-open-id-connect-and-graphql-f003a222260a) that involved using JWTs to validate GraphQL calls via the Token Validation module. The scenario I am testing now is that when I use Azure B2C as my Authentication Provider for OC and then have a completely separate Web App that uses Azure B2C auth, I can't use the token that comes back from Azure B2C via the Web App to then query the GraphQL module. I want to use OC in a headless way so I can return content to my web app via GraphQL. 

The issue I am getting is that the ValidationOptions are failing with the Issuer not matching. When you use the Token Validation module I set the Authority to the policy endpoint like in the Client Settings. ({https://xxx.b2clogin.com/{domain}/B2C_1_Blazor_SignUp_Signin/v2.0}

This results in the Issuer in the token being "https://xxx.b2clogin.com/{tenantid}/v2.0/" and the issuer it seems to be matching on being "https://xxx.b2clogin.com/{domain}/B2C_1_Blazor_SignUp_Signin/v2.0". Any insight here? Has anyone used an extracted provider in this way?

**Comment by aderderian** [comment] 2022-08-20 13:37
So I solved the issue with uploading a custom policy to AzureB2C and following a simpler route than the blogs provided. 

The remaining issue here is the TokenValidation module. @iaspnetcore wrote the module it seems. Anyone who is more experience with OIDC and this module understand the problem here with the token not being validated? @MichaelPetrinolis  ?

**Comment by MichaelPetrinolis** [comment] 2022-08-20 15:38
Good to hear that you solved the issue with email claim and AzureB2C! 
If you can, please share the solution in case anyone else  tries to use AzureB2C with OC. 

Now, If I understand correctly, you have the following scenario

1. OC Identity Provider that uses AzureB2C as external Provider. So all your users are in AzureB2C and they are authenticated through OC IdP.
2. A SPA application that authenticates with OC.
3. An API that is protected by AzureB2C
4. Authenticate users from SPA with OC IdP and store the user tokens provided by AzureB2C.
6. Make calls from SPA to API with the stored user tokens

check the .well-known/openid-configuration/jwks of the AzureB2C authority to see the metadata it receives.
OrchardCore OpenId Token Validation feature is based on the fantastic OpenIdDict lib, written by @kevinchalet, and should work out of the box for OpenIdConnect authorities.

**Comment by aderderian** [comment] 2022-08-21 15:39
I will definitely post the solution here!

Your description is a little off. Here it is and picture below.

1. OC IDP that uses Azure B2C as external provider. So users are registered via Azure B2C Custom Policy and put into the OC Users repository as well for now.
2. A Blazor Web/Client SPA that authenticates users via Azure B2C. New users would get pushed to register through OC flows for Azure B2C so they appear in Azure B2C and OC.
3. When a user is authenticated via the Client Blazor App, then we can load information about them via B2C as well as OC if needed. We then can query content which is stored in OC via the GraphQL Api.
4. We want to make calls to OC GraphQL Api via the token provided by Azure B2C being the main goal. Secondarily, administrators of content would be allowed into the OC side of the house as well to administer content that appears in their SPA. Web, Mobile apps via the GraphQL Api.

Currently, the Token Validation is failing when I uses the token given to me via Azure B2C in the Blazor App to try and access the OC GraphQL Api. I assume the issue is that token has a different authority than the one OC is expecting based on its settings. The best I could find is that the well known documentation was not being downloaded in the Token Validation module for the authority, and instead using the authority provided in the Token Validation configuration screen.

Here is what we're looking at :

![image](https://user-images.githubusercontent.com/868165/185798804-3cb3f715-20f8-471f-a7aa-120cf03d4410.png)

**Comment by aderderian** [comment] 2022-08-21 16:33
@MichaelPetrinolis I think what I am seeing is that the token I get back from Azure B2C in my spa has an issue of https://{mytenant}.b2clogin.com/{mytenantid}/v2.0/. Then in the Authority settings of OC for the token validation module I am setting it to https://{mytenant}.b2clogin.com/cloudgamingbetatenant.onmicrosoft.com/{mypolicy}/v2.0 to match the Authority in my OIDC Client Settings of OC. The code in OC checks the issuer against the authority rather than downloading the well known metadata and comparing the issuer. I "think" this is the problem, but I am not 100% sure. Perhaps the setting in the Token Validation module should be "Issuer"?

**Comment by aderderian** [comment] 2022-08-23 20:50
@MichaelPetrinolis after some more investigation, here is what I cam up with. I modified OpenIdValidationConfiguration.cs in the OrchardCore OpenId module to manually set the Issuer and MetadataAddress. Doing this allows the well known information to be properly downloaded and the Issuer is set to the proper Issuer as well.

Currently the code sets the Issuer only and sets it to the Authority server url we put in the Token Validation module. Should we have more options to set the proper urls? Is Azure B2C causing the Issuer and Authority to not match and thus resulting in mismatches? Can we add more field to the Orchard module to support this situation? I appreciate any insight here as I am not sure the proper solution @MichaelPetrinolis .

//options.Issuer = settings.Authority;
options.Issuer = new Uri("https://{mytenant}.b2clogin.com/{tenantid}/v2.0/");
                options.Audiences.Add(settings.Audience);
                options.MetadataAddress = new Uri("https://{mytenant}.b2clogin.com/{mytenant}.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration");

**Comment by kevinchalet** [comment] 2022-08-24 13:34
> Is Azure B2C causing the Issuer and Authority to not match and thus resulting in mismatches?

Unsurprisingly, Azure B2C is not standard-compliant: the OIDC discovery spec explicitly says that the metadata URL is created by concatenating the issuer and `/.well-known/openid-configuration`: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata

> Can we add more field to the Orchard module to support this situation?

I'm personally not against making the metadata address configurable, but it will need to be optional and in an "advanced" section with a proper comment indicating it shouldn't be necessary to set it in most cases.

**Comment by aderderian** [comment] 2022-08-24 13:48
Hey @kevinchalet I think the issue is with how the OpenId OC module is setting the Issuer in the OpenID Validation Configuration options. It seems to be setting the ValidIssuer to the Authority url when configuring the Open ID Settings. When I set the Authority url in the token validation module to the Issuer instead, the OpenID modules fails because it can't download the configuration properly. Perhaps we should not be setting Issuer at all? Something is not right :). Any guidance from OIDC experts would be great.

**Comment by kevinchalet** [comment] 2022-08-24 13:54
Authority is not really an OIDC concept but is used as a synonymous of "issuer" (retrospectively, we should have used "issuer" in `OpenIdValidationSettings` - like in OpenIddict - instead of "authority", but it's likely too late to change that 🤣)

> It seems to be setting the ValidIssuer to the Authority url when configuring the Open ID Settings.

It's the right thing to do 😃 

>  When I set the Authority url in the token validation module to the Issuer instead, the OpenID modules fails because it can't download the configuration properly. Perhaps we should not be setting Issuer at all? Something is not right :)

As I said, the address of the server configuration document in Azure B2C is not standard, so if something is not right, you know where to look at 🤣 

Making the metadata address configurable should be enough to fix the kind of issue you're seeing. Interested in sending a PR? 😄

**Comment by aderderian** [comment] 2022-08-24 14:00
If that's the appropriate fix, then I am happy to do it! Stand by and thanks!

**Comment by aderderian** [comment] 2022-08-24 14:16
@kevinchalet it looks like just setting the metadata address is not enough. In the end I needed to change code in three places. I think as well as having a metadata configuration option we also need a way to override Issuer as well. Would this be OK to add? Use the Issuer and Metadata if provided, otherwise use the Authority Url only.

**Comment by kevinchalet** [comment] 2022-08-24 14:21
The issuer should always be set, whether you're using a custom metadata address or not.

**Comment by aderderian** [comment] 2022-08-24 14:22
OK, well right now its just set to the Authority url provided. Its confusing to me that we do that because it seems this would get downloaded via metadata (well known url) and then set dynamically. 

I think if we provide an option in the UI with metadata address we will be good in this case.

**Comment by kevinchalet** [comment] 2022-08-24 14:24
OpenIddict uses the configured issuer to validate the discovery document and ensure the returned "issuer" is identical, as required by the specification:

> The issuer value returned MUST be identical to the Issuer URL that was directly used to retrieve the configuration information. This MUST also be identical to the iss Claim value in ID Tokens issued from this Issuer.

https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationValidation

**Comment by aderderian** [comment] 2022-08-24 14:30
OK...but should authority and issuer always match? In the Azure B2C it does not, which is where I think this problem is stemming from.

**Comment by kevinchalet** [comment] 2022-08-24 14:34
> OK...but should authority and issuer always match? 

As I said, these concepts are identical. We still use "authority" in the validation options because the validation feature was initially based on the JWT bearer middleware developed by MSFT, that uses "authority" instead of "issuer". Retrospectively, we should have made the breaking change to reduce the confusion here.

> In the Azure B2C it does not, which is where I think this problem is stemming from.

I'm not familiar enough with B2C. Can you share the actual values?

**Comment by aderderian** [comment] 2022-08-24 14:41
Sure. 

Authority : https://{mytenant}.b2clogin.com/{mytenant}.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0

Metadata Url = https://{mytenant}.b2clogin.com/{mytenant}.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration

Issuer : https://{mytenant}.b2clogin.com/{tenantid}/v2.0/

**Comment by kevinchalet** [comment] 2022-08-24 14:54
> Issuer : https://{mytenant}.b2clogin.com/{tenantid}/v2.0/

It's the value returned by the configuration endpoint, right?
Do things work correctly when you use "https://{mytenant}.b2clogin.com/{tenantid}/v2.0/" as the authority/issuer in the validation settings *and* configure the metadata endpoint to the URL you provided?

**Comment by aderderian** [comment] 2022-08-24 14:57
Correct, that is what is returned when you query the metadata address. No they do not work right because although that would succeed in matching the configuration with the metadata and the token issuer, the metadata is not available at https://{mytenant}.b2clogin.com/{tenantid}/v2.0/.well-known/openid-configuration . So it gets a failure response when it tries to download the metadata later on in OpenIddict.

**Comment by kevinchalet** [comment] 2022-08-24 15:00
> So it gets a failure response when it tries to download the metadata later on in OpenIddict.

I'm confused. Even if you configure `https://{mytenant}.b2clogin.com/{mytenant}.onmicrosoft.com/B2C_1A_SIGNUP_SIGNIN/v2.0/.well-known/openid-configuration` as the metadata address?

**Comment by aderderian** [comment] 2022-08-24 15:16
Well it works if I do that, yes. That was my manual hack to figure this out. I think we need to add two new properties to the Token Validation module for metadata and issuer. And set them properly if they're set.

**Comment by kevinchalet** [comment] 2022-08-24 15:23
> I think we need to add two new properties to the Token Validation module for metadata and issuer.

We only need one new property (for the metadata address). The issuer is already set correctly:

https://github.com/OrchardCMS/OrchardCore/blob/94a301a6f0fda5488b005071ea316457d624ecaf/src/OrchardCore.Modules/OrchardCore.OpenId/Configuration/OpenIdValidationConfiguration.cs#L107

> And set them properly if they're set.

It's simply: only set `options.MetadataAddress` if one was set in the settings. Otherwise, don't touch it and OpenIddict will compute it using the configured issuer.

**Comment by kevinchalet** [comment] 2022-08-24 15:45
I don't see why: don't things work as expected if you use https://{mytenant}.b2clogin.com/{tenantid}/v2.0/ as the issuer/authority?

In any case, we won't accept a change introducing an issuer property while keeping authority. The two refer to the same concept and it's not sane to have both in OrchardCore.

**Comment by aderderian** [comment] 2022-08-24 16:24
I see what you mean now. I did not go back and test it prior with just metadata manually configured and then updating Authority url to the Issuer value. I just did it, and it did work! So I think I understand the fix now. Thanks for your help!

**Comment by aderderian** [comment] 2022-08-25 11:31
Done : https://github.com/OrchardCMS/OrchardCore/pull/12265

**Comment by BenedekFarkas** [comment] 2024-04-03 14:45
#12265 is merged, can this be closed then?

**Comment by Piedone** [comment] 2024-04-26 18:11
Yeah, I think so. If not, please reopen.

**Closed by Piedone** 2024-04-26 18:11 UTC
