### ISSUE TITLE
 The AdminDashboard module is more versatile. 

### ISSUE THREAD

**Issue by chinasqzl** [OrchardCMS/OrchardCore#14549] opened 2023-10-21 02:57 UTC
Similar to the functionality of Workspaces in ERPNext, it allows for the creation of multiple workspaces. For example, the E-commerce module can have its own workspace.

A Workspace represents a module. A Workspace includes the following:

A dashboard section for that particular module.
A shortcut section for frequently used masters, transactions or pages.
A masters section where all the reports and masters are grouped and listed.

[ERPNext Workspace](https://docs.erpnext.com/docs/user/manual/en/desk-page)

![image](https://github.com/OrchardCMS/OrchardCore/assets/16968103/bbe5d545-44c8-4d8e-96b1-56e0c85c623c)

**Comment by hishamco** [comment] 2023-10-21 08:58
I remember @agriffard did a dashboard module that allows you to create widgets. It would be nice if there's a tutorial or a section to be added in our docs to add such thing, I mean "How to add a customizable widgets in Dashboard"

**Comment by sebastienros** [comment] 2023-10-26 17:27
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/14588

**Closed by sebastienros** 2023-10-26 17:27 UTC
Labels: enhancement
