### ISSUE TITLE
HTML Editor is broken in localized content (RTL)

### ISSUE THREAD

**Issue by dodyg** [OrchardCMS/OrchardCore#10654] opened 2021-11-07 12:18 UTC
### Describe the bug

WYSIWYG Editor in Localized content (Arabic) is broken in version 1.0.

This is the error at the browser
```Uncaught TypeError: langs is undefined```

### To Reproduce
1. Create a new content definition with HtmlBody Part and set editor to WYSIWYG .
2. Add Localization Part.
3. Create content in English.
4. Translate content to Arabic. You will see the HTML Editor is broken (missing). 

### Expected behavior

For HTML Editor to work. Right now it just shows a multiline field.

**Comment by hishamco** [comment] 2021-11-07 12:27
Is this related to Arabic (which I don't think so), could you try another language and check if the issue still exist

**Comment by dodyg** [comment] 2021-11-07 12:53
Arabic, English, French

![arabic](https://user-images.githubusercontent.com/1761249/140645723-3c135e17-117c-4211-9ec9-25e7c55f8b48.png)
![english](https://user-images.githubusercontent.com/1761249/140645726-0ee64b27-de44-4421-ac72-9fd7e56fe0f6.png)
![french](https://user-images.githubusercontent.com/1761249/140645727-456a9cdf-1022-4c62-9325-b014d3e8bc16.png)

**Comment by hishamco** [comment] 2021-11-07 12:59
Please try another RTL language, I'm expecting the issue trelated to RTL script

**Comment by dodyg** [comment] 2021-11-07 13:10
Farsi
![farsi](https://user-images.githubusercontent.com/1761249/140646312-15e18513-8e7f-4e0e-b12e-b04433bee538.png)

**Comment by dodyg** [comment] 2021-11-07 13:11
Hebrew
![hebrew](https://user-images.githubusercontent.com/1761249/140646377-37fcdd57-42a6-423e-a84e-a5de8cce89c8.png)

**Comment by hishamco** [comment] 2021-11-07 13:20
As expected, let me check ..

**Comment by Skrypt** [comment] 2021-11-08 05:13
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/4709

**Closed by Skrypt** 2021-11-08 05:13 UTC
