### ISSUE TITLE
Indexing Latest not working as intended (breaking)

### ISSUE THREAD

**Issue by mariojsnunes** [OrchardCMS/OrchardCore#12690] opened 2022-10-23 00:55 UTC
### Describe the bug
1. Rebuild an index with latest items doesn't work and removes all indexed items.
2. Saving items (publish or draft) will index all versions (won't just keep the latest).

### To Reproduce
1. Go to a new project with Blog Recipe
2. Create an index with "Index latest version" option
3. Save an article (publish or draft)
4. Query the index, the article is there (as it should)
5. Rebuild the index, the article is no longer there (breaking issue!)

Also if you save the article multiple times, it will add a version to the index each time.
I believe this was not the case before. Only the latest was kept.

I did some debugging and found out that it never entered the 2nd if as the `contentItem` is always null.
Couldn't figure out why yet

https://github.com/OrchardCMS/OrchardCore/blob/411206031d8d3e7626ed2f80c50c9bbfce958c9d/src/OrchardCore.Modules/OrchardCore.Search.Lucene/Services/LuceneIndexingService.cs#L169-L178

@Skrypt can you please take a look? IMO this is blocking for 1.5 release

**Comment by hishamco** [comment] 2022-10-23 11:07
@Skrypt is this blocker? If Yes, we should task a suitable action before release `1.5`

**Comment by Skrypt** [comment] 2022-10-23 16:57
The services and handlers for Lucene didn't change. I need to see why it is happening. But more likely maybe related to ContentItemVersionId.

**Comment by Skrypt** [comment] 2022-10-23 18:13
Fixed in my PR. These are regressions that I created by changing how we index ContentItemId and ContentItemVersionId with Lucene. My bad, I thought using a StoredDocument would have been enough to retrieve a document by ContentItemId since it is a technical value only. StringField is a non-tokenizing field in Lucene so it should be good.

**Closed** 2022-10-25 19:38 UTC
Labels: bug :bug:
