### ISSUE TITLE
MySqlException: Table 'exam.identifiers' doesn't exist

### ISSUE THREAD

**Issue by uussoft** [OrchardCMS/OrchardCore#6770] opened 2020-07-25 01:39 UTC
When I installed orchardcore, this exception occurred when selecting MySQL database

![微信图片_20200725093805](https://user-images.githubusercontent.com/3772962/88446223-b9ee4480-ce5a-11ea-8756-fcc328abb905.png)

**Comment by uussoft** [comment] 2020-07-25 01:41
My database version is mysql-5.5

**Comment by hishamco** [comment] 2020-07-25 18:03
Please provide us with the steps to reproduce

**Comment by hodamz** [comment] 2020-09-01 06:24
@uussoft was you able to fix this?

**Comment by sebastienros** [comment] 2020-09-03 17:18
I'd suggest we add the current functional tests running with other databases.

**Comment by hishamco** [comment] 2020-10-04 19:48
@agriffard do you know how to run the functional test multiple time, so I can finalize this one

**Comment by Skrypt** [comment] 2020-10-05 05:23
You will need Docker containers for doing this. I've started working on a PR for testing the UserId migration which could run wathever we need. We might want to build / test this also directly with the CI's later on.

**Comment by Skrypt** [comment] 2020-11-19 05:40
Should we close this one if functional test works fine on the CI? I assume that the issue comes from a custom IndexProvider since the table concerned is "exam" and we don't have this in OC. Looks like a failed migration that happened.

**Closed** 2020-11-19 05:55 UTC
Labels: investigating

**Comment by lengockyquang** [comment] 2021-02-04 14:20
i'm having this issue with mariadb version 10.1.47. Any ideas to fix it ?

**Comment by Skrypt** [comment] 2021-02-04 15:37
Repro steps?

**Comment by lengockyquang** [comment] 2021-02-04 16:07
i just normally created empty database then put connection string at the setup setup. After i click save, it throw error that Identifiers does not exist. When i checked database, only table Document was created. I will try to create video for this issue tomorrow if i have free time :) almost 11pm from vn now

**Comment by scil** [comment] 2022-08-23 19:03
I use mysql-5.7.4-m14-winx64.zip and encounter the same error.

**Comment by Skrypt** [comment] 2022-08-23 19:13
Generally, we have issues under SQL Server when the database table is accessed with a different Schema. But under MySQL, a schema is a synonym for a table. Also, "exam.identifiers" here seems like a bad prefix issue if you prefixed your table names with "exam" then it should be "exam_identifiers". Need to see details.

**Comment by scil** [comment] 2022-08-24 01:26
> @Skrypt I used mysql-5.7.38 and everything went well. Today I use mysql-5.7.4-m14-winx64.zip and encounter this error.
> 
> mysql 5.7.38 vs 5.7.4

my collegues have fixed it. 

just change mysql  character from utf8mb4_unicode_ci to utf8_unicode
