### ISSUE TITLE
Replace the default dependency injection container 

### ISSUE THREAD

**Issue by EternityTeam** [OrchardCMS/OrchardCore#2112] opened 2018-07-15 08:37 UTC
I want to replace the dependency injection container into Autofac. Please give me some hints. And according to the Autofac official modification method for aspnetcore program seems to be not applicable.

**Comment by hishamco** [comment] 2018-07-21 14:00
Have a look to [this](http://autofac.readthedocs.io/en/latest/integration/aspnetcore.html)

**Comment by 0lukasz0** [comment] 2018-08-27 20:27
It looks like Orchard is overwritting IServiceLocator from Autofac with default implementation. Services are registered properly, and I am able to resole them at Startup.cs file, but when I'm trying to resolve them at Controller they are not available. I was trying to figure it out looking at your source, but I have no idea how to fix it. 

The closes guess would be that there is something wrong around ServiceProviderExtensions.CreateChildContainer/ShellContainerFactory.CreateContainer with creating child providers for tenants. 

At ShellContainerFactory.CreateContainer using _serviceProvider.GetType() returns {Autofac.Extensions.DependencyInjection.AutofacServiceProvider} and I'm able to resolve my service using _serviceProvider.GetService<ITestService>(). Constructor injected service provider into controller is of type {Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope}, and my service is not registered there. 

Additionally it seems that IServiceCollection applicationServices does not contains registration for my ITestService. 

minimal example:

    public class Startup
    {
        public static IContainer ApplicationContainer { get; set; }

        public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddOrchardCms();

            var builder = new ContainerBuilder();
            builder.Populate(services);
            builder.RegisterType<TestService>().As<ITestService>().SingleInstance();

            var container = builder.Build();
            ApplicationContainer = container;
            IServiceProvider autofacServiceProvider = new AutofacServiceProvider(container);

            //working resolving:
            //var y = autofacServiceProvider.GetService<ITestService>();
            //var z = y.Magic();

            return autofacServiceProvider;
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();

            }

            app.UseStaticFiles();
            app.UseOrchardCore();
        }
    }
	
	public interface ITestService
    {
        int Magic();
    }

    public class TestService : ITestService
    {
        public int Magic()
        {
            return 42;
        }
    }
	
	public class HomeController : Controller
    {
        private readonly ITestService testService;
        private readonly IServiceProvider serviceProvider;

        public HomeController(
		 ITestService testService, 
		 IServiceProvider serviceProvider)
        {
            this.testService = testService;
            this.serviceProvider = serviceProvider;

            var x = serviceProvider.GetType();
        }

        public IActionResult Index()
        {
            var x = testService.Magic();
            return View();
        }
	}

**Comment by sebastienros** [comment] 2018-08-30 19:50
Could there be an issue with how the aspnet DI optimizes the constructors to inject services?

**Comment by 0lukasz0** [comment] 2018-08-30 20:02
If you change services.AddOrchardCms(); to services.AddMvc(); everything is working as espected, it seems that problem lies around multi tenant support at Orchard.

**Comment by 0lukasz0** [comment] 2018-10-13 12:28
As a workaround  I can suggest sticking to default aspnet DI with additionl Scrutor library for fluent registration.

https://github.com/khellang/Scrutor

**Comment by neolution-ch** [comment] 2019-07-04 07:57
@sebastienros is it possible to investigate this further? At the moment it seems to be impossible to use an own or a third party IServiceProvider with OrchardCore. Scrutor, the library @0lukasz0 suggested consists only of extension methods for Microsoft Dependency Injection. If you need to use more advanced DI features **you have to use** a third party container (such as Autofac, DryIoc, StructureMap etc.). With .NET Core web apps you can do that by building/using an adapter to Microsoft DI. But this technique somehow does not work in OrchardCore.

**Comment by sebastienros** [comment] 2019-07-04 19:13
If you mean with the modular framework only, then I think we should look into this. At least be able to switch the implementation of the multi-tenant one if the way it's done is not compatible with other DI containers. However it won't be a priority for us, so I would recommend you start taking a look at how to change things on your own and submit a PR. Feel free to ask anything if you have questions. @jtkech will probably be able to help if necessary.

**Comment by jtkech** [comment] 2019-07-04 20:50
Okay no problem, i don't remember anything on autofac but i can help on how we create isolated child container per tenant, how we clone host / app level services to each tenant container, and so on.

**Comment by neolution-ch** [comment] 2019-07-05 11:33
We use the CMS and also the Framework. The current problem is that we want to add custom authentication with our own ASP.NET Core Identity implementation for pages that are separated from the CMS but still run in the same app. With DryIoc it would be possible to add a condition to the resolver that then decides if the current request needs the Orchard Identity or our own Identity.

In a "normal" ASP.NET Core app this is possible by just changing the `ConfigureServices` method in the Startup class:

    public IServiceProvider ConfigureServices(IServiceCollection services)
    {
        return BuildServiceProvider(services);
    }

The `BuildServiceProvider` method creates a DryIoc container, adapts the services registered in the service collection and then returns a `IServiceProvider` based on the DryIoc container, so it is compatible with Microsoft DI. We have this working in several apps already, but for Orchard it doesn't. Probably bacause Orchard has a different startup mechanism? Which ignores the new signature of the `ConfigureServices` method (returns `IServiceProvider` instead of `void`)?  

I think it would already be really helpful if you could help us finding the point where this happens at the startup of Orchard to see if we could change it so that it uses the returned `IServiceProvider` (if provided) as the service provider to resolve dependencies and then create a PR.

**Comment by hishamco** [comment] 2019-07-05 12:36
What if you register them as `IEnumerable<>` and query for your own implementation, you can use a static property to avoid querying each time

**Comment by neolution-ch** [comment] 2019-07-05 14:00
@hishamco Good thought, will try this as a workaround. But ideally, I would prefer the resolver to make the decision to not violate the dependency inversion principle.

**Comment by hishamco** [comment] 2019-07-05 16:23
AFAIK the current implementation allow registering multiple instance for the same type. I think this may solve the issue with sort of service locator pattern, but if you prefer constructor injection over others to return single instance I will ask you how Dryloc can help to decide which is suitable implementation after resolving?

**Comment by jtkech** [comment] 2019-07-06 00:57
@neolution-ch some infos

- Most things run in a tenant context, we can have multiple tenants but at least one, the `Default` tenant, a tenant being composed of modules / themes. For each tenant we precreate a `ShellContext` which holds a service provider and a pipeline that are created on a 1st request. Then, on this service provider we can create child scoped providers, e.g on a request, that is held by a `ShellScope` so that we can resolve scoped services.

- This is in `ShellContainerFactory.CreateContainer()` that a tenant container is created. It first calls `ServiceProviderExtensions.CreateChildContainer()` that clones the app level service descriptors (for an app level singleton, the same instance will be shared by all tenants), see the source for more details.

- Then, each module participates by registering their own services.

      // Let any module add custom service descriptors to the tenant
      foreach (var startup in startups)
      {
          ...
          startup.ConfigureServices(featureAwareServiceCollection);
      }

    Note: when cloned, an app level singleton is wrapped in a `ClonedSingletonDescriptor` so that in a given module startup we can check if it is a singleton coming from the host, retrieve its parent implementation type. Useful e.g to filter some services as in the 3.0 branch where we want to isolate each tenant from the host level routing services.

- Then, still in `ShellContainerFactory.CreateContainer()` we have.

      var shellServiceProvider = tenantServiceCollection.BuildServiceProvider(true);

    Hmm, maybe this is here that we would have to resolve from the host a service provider factory, with a default implementation that just do the above but that could be overridden.

**Comment by neolution-ch** [comment] 2019-07-11 14:21
@hishamco E.g. based on the namespace of the class that requests the dependency. There are lots of options with DryIoc (https://bitbucket.org/dadhi/dryioc/wiki/RegisterResolve)

@jtkech Thank you very much, I got some time to go through the code to look for a solution. I noted the following:

There is the `OrchardCore.Modules.IStartup` interface which kind of looks like the `Microsoft.AspNetCore.Hosting.IStartup`. 

The major difference between those two interfaces is the `ConfigureServices(IServiceCollection services)` method which returns `void` in the OC variant and `IServiceProvder` in the AspNet variant.

When starting up an ASP.NET Core application we usually use `WebHost.CreateDefaultBuilder(args).UseStartup<Startup>().Build().Run()`  which ends up creating a `Microsoft.AspNetCore.Hosting.ConventionBasedStartup` object ([see here](https://github.com/aspnet/AspNetCore/blob/0f02facb045cfd65858ff5ebcc65fcbcb891fb1a/src/Hosting/Hosting/src/WebHostBuilderExtensions.cs#L95)). 

This object enables us to configure whatever `IServiceProvider` implementation we like, by returning it with the `ConfigureServices` method. I do not have the expertise on how this exactly works internally, but I suspect the way OC registers the services (many defined in modules) is somehow not compatible since its `IStartup` interface differs from Microsoft's. Also it's used differently when looking at `ShellContainerFactory.CreateContainer()`

**Comment by hishamco** [comment] 2019-07-11 20:06
As expected, I thought there are variant ways to resolve the dependencies from the constructor. With that I think the better way is to use `IStartup` as mentioned above

**Comment by xumix** [comment] 2019-08-15 13:49
Pinging this again since this really limits my usage with Orchard, Microsoft DI cannot even resolve a collection of services if the have multiple registrations.
This code in `IStartup` also does not work
```
public override void ConfigureServices(IServiceCollection srv)
{
       srv.AddAutofac();
}
```

**Comment by sebastienros** [comment] 2019-08-15 16:51
>  Microsoft DI cannot even resolve a collection of services if the have multiple registrations

I don't understand this, can you provide an example?

Have you tried to clone the source and see what changes we should do to enable this? I don't think any "core" contributor will have time to look into this, but if you are willing to work on that I don't any reason not to do some changes here.

**Comment by xumix** [comment] 2019-08-16 09:10
@sebastienros I have multiple registered `IService` interfaces, when I'm trying to inject them like `Component(IService[] services)` I have errors that they are not registered. If I register them as `IService[]` - it works.
I'll look into required changes for Autofac integration

**Comment by arkadiuszwojcik** [comment] 2019-08-16 11:37
@xumix instead of `Component(IService[] services)` try: `Component(IEnumerable<IService> services)`

**Comment by xumix** [comment] 2019-08-16 15:17
@arkadiuszwojcik the problem is not only this, but also inability to use autofac modules etc

**Comment by sebastienros** [comment] 2019-08-16 17:22
@xumix how is your PR solving this issue

**Comment by xumix** [comment] 2019-08-16 17:53
@sebastienros It allows registering a standard `IServiceProviderFactory<TContainerBuilder` withing orchard configuration, so the `IServiceProvider` that is built for shells and modules is created via this factory `.AddOrchardCms(b => b.UseServiceProviderFactory(new AutofacProviderFactory()))`

**Comment by xumix** [comment] 2019-08-16 17:56
Another option would be finding `Configure{0}Container` methods inside main Startup class and then resolving the factory from the main service collection but this involves much reflection work and basically copying `ConvetionBasedStartup` class code.

**Comment by YYOHAN** [comment] 2019-11-07 02:28
We have a current project where the DI we use is Autofac, the factories from some of the libraries we use were developed for Autofac and even for some dynamic registration .We need to use OrchardCMS Core and have a way to override the DI at an Orchard Module with Autofac.

**Comment by sebastienros** [comment] 2019-11-07 20:23
@YYOHAN feel free to take over this PR and make it functional: https://github.com/OrchardCMS/OrchardCore/pull/4053

**Comment by albert-sosa** [comment] 2019-12-20 20:31
Hello guys thank you very much for the hard work, Orchard Core is an excellent tool, unfortunately I'm facing the same issues while trying to migrate an existing application with some third party tools that depends on Autofac and Solr multicores. I just did the migration to .net Core 3.1and they did an excellent job on the way you can overwritte the default injector mechanism. I tried to make #4053 functional.. no success.

**Comment by xumix** [comment] 2019-12-21 12:17
>I tried to make #4053 functional.. no success.
I ended up extracting orchard to full separate application with no custom code over it, using it as a simple CMS and not app framework. Double registration and injection problems are "no go" for any serious application.

**Closed** 2020-11-11 20:50 UTC
Labels: documentation
