### ISSUE TITLE
Smtp test settings field lacks format validation

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#1864] opened 2018-05-27 11:22 UTC
smtp test settings 
To 
Bcc 
Cc 
Reply To
字段填写非正确的格式，错误提示"An error occured while executing this request."，而不是提示字段格式错误？

![2](https://user-images.githubusercontent.com/28694676/40585319-1428d32a-61e3-11e8-9088-d17b8b3207c2.gif)

**Comment by hishamco** [comment] 2019-04-10 00:10
@pgy866 could you please try to reproduce this issue using the latest bits, I'm unable to reproduce it

**Comment by pgy866** [comment] 2019-04-10 15:38
好的，明天我测试下
Ok, I will test it tomorrow.

**Comment by Skrypt** [comment] 2019-04-10 16:04
There is no validation because the email field can take multiple email adresses. We made the email field a text field instead of an email field which can't take more than one email. The email validation would need to be made on the server side to prevent this from happening.

**Comment by hishamco** [comment] 2019-04-10 18:26
@Skrypt can we made a client side validation for email field?

**Comment by Skrypt** [comment] 2019-04-10 19:26
Sure we can but this will be custom javascript code. Right now the validations are made with JQuery UI validations which doesn't cover the case where a text field needs to handle multiple emails separated by a semicolon ";"

**Comment by pgy866** [comment] 2019-04-11 01:26
填写错误的邮箱格式，将正常提示错误，多个邮箱地址请用“；”，成功发送。
@hishamco Fill in the wrong mailbox format, prompting an error, multiple email addresses ";", successfully sent. The latest branch issue has been resolved.

**Can close the problem**

![1554945581(1)](https://user-images.githubusercontent.com/28694676/55924125-2d0a8200-5c3b-11e9-9466-e0c7a0674105.png)
![微信截图_20190411092251](https://user-images.githubusercontent.com/28694676/55924217-84a8ed80-5c3b-11e9-99a1-79bf6869988c.png)

**Comment by hishamco** [comment] 2019-04-11 09:05
> Can close the problem

Yes you can, while the original issue has been resolved

**Comment by pgy866** [comment] 2019-04-11 13:36
Close issue

**Comment by hishamco** [comment] 2019-04-11 14:03
I don't have the power to close it .. you can close from your side  :)

**Closed** 2019-04-12 12:41 UTC
Labels: P3
