### ISSUE TITLE
Parent Part and Children Part

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8641] opened 2021-02-20 17:17 UTC
2 new parts.
One called Parent Part and the other called Children Part.
The Parent part would have one value for the parent content item Id.
The Children Part would have an array of content item Id's for the children.
Of course the Children Part would allow sorting by drag and drop.
A child can only have one parent.
A content item with the children part can edit the parent part of the child it selects.
This would mean when you save a content item with children it would also edit and save the children content items as well.

So if I had a content item with the children part and I added 3 children using a content picker and pressed the save button this would save 4 content items.  1+3 =4.

This way hierarchal items can be assembled.

**Comment by JoshTango** [comment] 2021-02-21 20:49
The user saving would also need permissions to edit the 3 children.

**Comment by deanmarcussen** [comment] 2021-02-22 19:13
I think you are intending this to be like a `LinkContentType`  where the entire content item would just exist to provide linkages between other content items.

But it's very hard to be sure from your description.

Taxonomies achieve this better, though perhaps not in the way you see it.

**Comment by JoshTango** [comment] 2021-02-22 19:20
"the entire content item just exists to provide linkages"

no I don't want this because people could create multiple copies of this and a child could have more than one parent.
I want a way to enforce only one parent.

**Comment by deanmarcussen** [comment] 2021-02-22 19:22
You'll have to describe what you want better. I don't understand from your description.

It's either taxonomies or the list part. Or a content picker field.

Perhaps you could describe what is wrong with the existing solutions?

**Comment by JoshTango** [comment] 2021-03-01 21:56
Ok lets assume I want to make a content type called Folder.
A folder can have one parent only and many children.

**Comment by deanmarcussen** [comment] 2021-03-02 12:27
A list part allows children, any they can be nested. It is a very normal way of building a hierachy.

An item can only ever be contained in one list.

Please explain how your request is not a `ListPart`.

**Comment by JoshTango** [comment] 2021-03-02 12:58
I did not know an item could only ever belong to one list?
I believe there is a feature coming to add existing items to a list so therefore an item could belong to more than one list.

That's the problem.

**Comment by deanmarcussen** [comment] 2021-03-02 13:46
> I believe there is a feature coming to add existing items to a list so therefore an item could belong to more than one list.

There is no feature coming to do that.

The container only supports one parent. That is by design.

There have been request for features to detach, or move an item, and there are issues tracking these.

Move will only ever support removing from one list and moving to another list.

Anything else would be a different part. If you search there was a design for a container part.

I'm going to close this.

If you have further question please find the related issues for the features and post them there.

**Closed by deanmarcussen** 2021-03-02 13:46 UTC
Labels: enhancement

**Comment by JoshTango** [comment] 2021-03-02 14:02
Ok I have a better understanding now of Lists.
Maybe update this documentation:

A ListPart allows you to associate content items to a parent container (Ex: A blog contains a list of blog posts).

and add the fact that a content item can only ever belong to ONE List.
