### ISSUE TITLE
Markdown Strikethrough

### ISSUE THREAD

**Issue by DiomedesDominguez** [OrchardCMS/OrchardCore#7422] opened 2020-10-28 20:47 UTC
I'm using the version 1.0.0-rc2-13450 from nuget following this [guide](https://docs.orchardcore.net/en/dev/docs/guides/decoupled-cms/) for creating a decoupled CMS Website (great btw). When parsing the strikethrough's markdown in the side by side panel is correct, but not in the website.

![image](https://user-images.githubusercontent.com/4379316/97494644-f25f5c00-193c-11eb-823f-64f8d0a16f5c.png)
![image](https://user-images.githubusercontent.com/4379316/97494708-0d31d080-193d-11eb-817f-1660ac9420b6.png)

**Comment by Skrypt** [comment] 2020-10-28 22:19
Html sanitized maybe.

**Comment by hishamco** [comment] 2020-10-29 05:25
I don't think so, because as I see from the screenshot the bold text rendered fine

**Comment by deanmarcussen** [comment] 2020-10-29 08:31
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6502

Please configure the markdown pipeline for this.

I'll leave this open, we could potentially add the extensions by default.

**Comment by hishamco** [comment] 2020-10-29 09:41
Dean what if we add it as an optional setting?

**Comment by deanmarcussen** [comment] 2020-10-29 10:03
Not a setting, it's already configurable, 

Personally I'm ok with adding them by default, they could still be removed through `IConfiguration` if someone really didn't want them

**Comment by sebastienros** [comment] 2020-10-29 17:53
We should enable more features if they are safe and commonly known.

**Comment by hishamco** [comment] 2020-10-30 13:33
Seb using `UseAdvancedExtensions()` will enable the following features:

- UseAbbreviations()

- UseAutoIdentifiers()

- UseCitations()

- UseCustomContainers()

- UseDefinitionLists()

- .UseEmphasisExtras()

- .UseFigures()

- .UseFooters()

- .UseFootnotes()

- .UseGridTables()

- .UseMathematics()

- .UseMediaLinks()

- .UsePipeTables()

- .UseListExtras()

- .UseTaskLists()

- .UseDiagrams()

- .UseAutoLinks()

- UseGenericAttributes()

**Closed** 2020-11-01 13:27 UTC
