### ISSUE TITLE
Use ISession in EventHandler will cause MySqlConnection is already in use exception.  

### ISSUE THREAD

**Issue by RockNHawk** [OrchardCMS/OrchardCore#6069] opened 2020-04-30 15:21 UTC
Hi,

When I use ISession.Query in EventHandler, an `MySqlConnection is already in use` exception courried:

Code:

    public class RegistrationFormEventHandler : IRegistrationFormEvents
    {
        private readonly InvitationService _service;
        private readonly YesSql.ISession _session;

        public RegistrationFormEventHandler(
            InvitationService service,
            YesSql.ISession session
            )
        {
            this._session = session;
            this._service = service;
        }

        public async Task RegisteredAsync(IUser user)
        {
              ....
              var from = await ses.Query<UserInvitationInfo>()
              .With<UserInvitationInfoIndex>(x => x.InvitationCode == invitationCode)
              .FirstOrDefaultAsync();
        }

        public Task RegistrationValidationAsync(Action<string, string> reportError)
        {
            return Task.CompletedTask;
        }
    }

-----

Error Stack:

![image](https://user-images.githubusercontent.com/3222379/80728206-4083d600-8b39-11ea-84a9-25563dfec285.png)

    InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
    MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command) in ServerSession.cs
    MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList<IMySqlCommand> commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in CommandExecutor.cs
    MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQueryAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlCommand.cs
    MySql.Data.MySqlClient.MySqlTransaction.CommitAsync(IOBehavior ioBehavior, CancellationToken cancellationToken) in MySqlTransaction.cs
    MySql.Data.MySqlClient.MySqlTransaction.Commit() in MySqlTransaction.cs
    YesSql.Session.CommitTransaction()
    YesSql.Session.CommitAsync()
    OrchardCore.Environment.Shell.Scope.ShellScope.BeforeDisposeAsync() in ShellScope.cs

        public static void AddDeferredTask(Func<ShellScope, Task> task) => Current?.DeferredTask(task);
        public async Task BeforeDisposeAsync()
        {
            foreach (var callback in _beforeDispose)
            {
                await callback(this);

**Comment by jtkech** [comment] 2020-05-01 01:39
Just for infos as I was not able to repro, but with sqlite

That said, normally the session is committed at the end of the scope, but when creating an user the `UserStore` does it before as it needs to return an `IdentityResult` to the aspnetcore `UserManager`.

So here the only specific thing i see is that your query is done after the session has been commited.

But normally `CommitAsync` releases the transaction and the connection so doing then a query will create a new connection and transaction, but maybe the same is returned from a connection pool.

Then because a new transaction has been created, at the end of the scope yessql will do again `_transaction.Commit()` and it seems that it fails at this point.

Could you show us more code of your `RegisteredAsync` as i see that you use the async modifier but you terminate your method with `Task.CompletedTask`, are you doing some mutations and any `_session.Save()`?

Could you try to do the same but in `RegistrationValidationAsync` to see if it still fails and if it is related to the `CommitAsync` executed before your handler method.

**Comment by RockNHawk** [comment] 2020-05-01 09:31
Uh, the last `return Task.CompletedTask;` not in actual code, it's an copy error :-)

more code:

    var invitationCode = _httpContextAccessor.HttpContext?.Request?.Form?["InvitationCode"].ToString();
    var clientId = _httpContextAccessor.HttpContext?.Request?.Form?["ClientId"].ToString();
    var ip = _httpContextAccessor.HttpContext?.Connection.RemoteIpAddress.ToString();

// when call this method, exception throws.
    var from = await _session.Query<UserInvitationInfo>()
                    .With<UserInvitationInfoIndex>(x => x.InvitationCode == invitationCode)
                    .FirstOrDefaultAsync();

`RegistrationValidationAsync ` there no `User` object, I can't do something, but I will have a try.

It seems an Orchard inner issue.

**Comment by RockNHawk** [comment] 2020-05-01 09:32
@jtkech 
Than you for reply, Uh, the last `return Task.CompletedTask;` not in actual code, it's an copy error :-)

more code:

    var invitationCode = _httpContextAccessor.HttpContext?.Request?.Form?["InvitationCode"].ToString();
    var clientId = _httpContextAccessor.HttpContext?.Request?.Form?["ClientId"].ToString();
    var ip = _httpContextAccessor.HttpContext?.Connection.RemoteIpAddress.ToString();

// when call this method, exception throws.
    var from = await _session.Query<UserInvitationInfo>()
                    .With<UserInvitationInfoIndex>(x => x.InvitationCode == invitationCode)
                    .FirstOrDefaultAsync();

`RegistrationValidationAsync ` there no `User` object, I can't do something, but I will have a try.

It seems an Orchard inner issue.

**Comment by RockNHawk** [comment] 2020-05-01 10:04
@jtkech 
Hi, I have tested,if I move code to the `RegistrationValidationAsync`, still have Exception.

![image](https://user-images.githubusercontent.com/3222379/80797987-cc4b4000-8bd5-11ea-9ddb-a2f800067f89.png)

        public async Task RegistrationValidationAsync(Action<string, string> reportError)
        {
            var invitationCode = _httpContextAccessor.HttpContext?.Request?.Form?["InvitationCode"].ToString();
            var clientId = _httpContextAccessor.HttpContext?.Request?.Form?["ClientId"].ToString();
            var ip = _httpContextAccessor.HttpContext?.Connection.RemoteIpAddress.ToString();
            var ses = this._session;
            var from = await ses.Query<UserInvitationInfo>()
                .With<UserInvitationInfoIndex>(x => x.InvitationCode == invitationCode)
                .FirstOrDefaultAsync();

            // an Exception happend above , and this code directly canceled
            reportError("AA", "BB");
        }

![image](https://user-images.githubusercontent.com/3222379/80798005-dcfbb600-8bd5-11ea-80c7-b4f27d8de581.png)

**Comment by jtkech** [comment] 2020-05-01 22:57
Okay

So as i can't repro but with sqlite, before having to install the mysql tools on my side, can you try to do a fresh setup but by selecting sqlite (that only creates a local `yessql.db` file) and then retry it to see if the issue is related to mysql.

And can you show me how and where you register your `IRegistrationFormEvents`.

**Comment by RockNHawk** [comment] 2020-05-03 12:20
@jtkech I registered in Module's `Startup.cs`.

And sorry, I add an try-catch in `RegisteredAsync` the Exception.Message in `catch` block is a SQL query error (the table not  exists, this is my module's problem).

And in `RegistrationValidationAsync` it's also not a Orchard Session exception, but a SQL query exception (when the eception courred in this method, the subsequent code is directly skipped).

So the `Session` is works well, but if an exception throws in EventHandler in `RegisteredAsync` method, the Orchard will show a `MySqlConnection is already in use` exception.

If exception throws in `RegistrationValidationAsync`  method, the exception will ignored.

**Comment by jtkech** [comment] 2020-05-04 07:39
Cool then ;)

So i will close it but feel free to reopen if you still have an issue

About the exception, yes we are doing some try cacth and then rethrow but only on a fatal exception as `OutOfMemoryException`, but in this case we are logging errors in a file under `App_Data/logs`.

**Closed by jtkech** 2020-05-04 07:39 UTC
