### ISSUE TITLE
Feature Request: Naming stategy for grouping content definitions

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#4809] opened 2019-11-14 20:46 UTC
This is in relation to this thread:
https://github.com/OrchardCMS/OrchardCore/issues/4808#issuecomment-554059349

I made a new issue so as not to contaminate the other thread.
I prefer a different name then category.  Lets say there are 2 vendors and they each create a set of content definitions that they claim model a product cms best.  I would want them in 2 separate hierarchy nodes.  Therefore if they had a package name or namespace name this would be best.

However if you use category then both vendors would choose "product" as the category and both sets of content definitions would be mixed and mingled together as a flat list.  This is bad.

The same would go for 2 different blogging engines.  People could have different approaches as to how to model a blog.

**Comment by JoshTango** [comment] 2019-11-14 21:11
I can see the day where you have an import button for importing different packages of content types.
There is no reason to switch recipes just to get a different set of content definition types.

**Comment by JoshTango** [comment] 2019-11-15 14:13
I've opened a big can of worms here but its a good can of worms to open up.  Further more content parts would have to have a package name also.  You can keep the Title Part as a primitive type which does not belong to any package.  

Packages of Content definition types should be self contained except for the primitive content part definitions.

**Comment by JoshTango** [comment] 2019-11-15 14:14
For now you should probably keep the category property you are adding and add the "package" property later on.  There should be 2 properties: category and package.  they both have different meanings.

**Comment by sebastienros** [comment] 2019-11-21 20:58
You can have different technical names, and still use the same display name. Then with categories they will be displayed differently. Or use the first part of the content type as a "package".

**Comment by JoshTango** [comment] 2019-11-21 21:05
in other words use the old prefix strategy

**Comment by sebastienros** [comment] 2021-08-19 17:16
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/4809

**Closed by sebastienros** 2021-08-19 17:16 UTC
