### ISSUE TITLE
System.IO.IOException inside MediaFileStoreResolverMiddleware

### ISSUE THREAD

**Issue by lampersky** [OrchardCMS/OrchardCore#9319] opened 2021-04-29 13:37 UTC
After deploying app to azure, Media module stopped working.

(we are using Azure Media Storage, and we have 4 instances in our app service plan)

![image](https://user-images.githubusercontent.com/6403130/116556667-012fc700-a8fe-11eb-9e45-28db5d08fab5.png)

![image](https://user-images.githubusercontent.com/6403130/116557411-b3678e80-a8fe-11eb-86c1-2b7fd2663930.png)

**First exception:**
```
System.IO.IOException:
   at System.IO.FileStream.ValidateFileHandle (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream.CreateFileOpenHandle (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream..ctor (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream..ctor (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.File.Create (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.File.Create (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at OrchardCore.Media.Core.DefaultMediaFileStoreCacheFileProvider+<SetCacheAsync>d__9.MoveNext (OrchardCore.Media.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
```

![image](https://user-images.githubusercontent.com/6403130/116557751-093c3680-a8ff-11eb-9622-bc056170cb59.png)

**Second exception:**
```
System.IO.IOException:
   at System.IO.FileStream.ValidateFileHandle (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream.CreateFileOpenHandle (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream..ctor (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.FileStream..ctor (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.IO.File.Create (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.File.Create (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at OrchardCore.Media.Core.DefaultMediaFileStoreCacheFileProvider+<SetCacheAsync>d__9.MoveNext (OrchardCore.Media.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at OrchardCore.Media.Services.MediaFileStoreResolverMiddleware+<>c__DisplayClass7_0+<<Invoke>b__1>d.MoveNext (OrchardCore.Media, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
```

![image](https://user-images.githubusercontent.com/6403130/116557644-eb6ed180-a8fe-11eb-92f2-161d11f35307.png)

**Comment by deanmarcussen** [comment] 2021-04-29 14:28
Did you use zip deploy?

it’s often the issue, as zip deploy isn’t writable

needs to be web deploy

**Comment by lampersky** [comment] 2021-04-29 15:28
@deanmarcussen it was WebDeploy

![image](https://user-images.githubusercontent.com/6403130/116576862-3e04b980-a910-11eb-95ce-03ead5eedd59.png)

**Comment by deanmarcussen** [comment] 2021-04-29 17:13
Can you have a look in scm and see if it has created the ms-cache folder under the wwwroot?

Generally this is a permissions issue. Have you mounted a shared volume, or done anything with your server configuration that would impact on drive access?

See if you can created a file manually in that folder, through scm.

And if possible paste a full exception from the logs, just in case there's something else that can help us diagnose it for you.

**Comment by lampersky** [comment] 2021-04-29 17:23
@deanmarcussen I've checked first instance, and "ms-cache" exists, and I was able to create another file manually.
![image](https://user-images.githubusercontent.com/6403130/116592489-5da3de00-a920-11eb-9754-737127f7f09a.png)

**Comment by lampersky** [comment] 2021-05-06 06:25
@deanmarcussen maybe it will be usuful, "Purge All" gives me this exception:

```
System.IO.IOException:
   at System.IO.FileSystem.RemoveDirectoryRecursive (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.FileSystem.RemoveDirectory (System.IO.FileSystem, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at OrchardCore.Media.Core.DefaultMediaFileStoreCacheFileProvider.PurgeAsync (OrchardCore.Media.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)
```

![image](https://user-images.githubusercontent.com/6403130/117251122-83f7db00-ae44-11eb-9016-1cd187b572ac.png)

**Comment by lampersky** [comment] 2021-05-06 07:38
few more related exceptions

![image](https://user-images.githubusercontent.com/6403130/117259277-2cf70380-ae4e-11eb-9876-bb9cd06a4d09.png)

![image](https://user-images.githubusercontent.com/6403130/117259817-b60e3a80-ae4e-11eb-9471-563acc677db9.png)

**Comment by lampersky** [comment] 2021-05-06 11:37
Steps to reproduce:
1) latest dev OC,
2) deploy to azure (web deploy), **This bug can't be reproduced locally!**,
3) enable feature "Azure Media Storage" it depends on "Media Cache",
4) configure appsettings
```
"OrchardCore": {
	"OrchardCore_Media_Azure": {
		"ConnectionString": "DefaultEndpointsProtocol=https;AccountName={enter-account-name};AccountKey={enter-key-here};EndpointSuffix=core.windows.net",
		"ContainerName": "media",
		"BlobName": "",
		"CreateContainer": true
	},
},
```
5) import few images to nested directories,
6) go to `Admin/MediaCache` and click on "Purge All",
7) disable browser cache
![image](https://user-images.githubusercontent.com/6403130/117290004-95091200-ae6d-11eb-95ec-25f130d5198b.png)
8) open `/Admin/Media` and try to navigate between few directories, and you should see this:
![image](https://user-images.githubusercontent.com/6403130/117290230-d7325380-ae6d-11eb-813e-fa8c41bb419b.png)

@deanmarcussen I've created an account for you on our dev plain OC instance.
https://orchard-core-media-problem.azurewebsites.net/
PM me for credentials if you are interested

logs are available here 
[logs.txt](https://github.com/OrchardCMS/OrchardCore/files/6434074/logs.txt)


Here is a screen from remote debug:
**FileExists** returns true, **FileDelete** throws an exception "DirectoryNotFoundException"
![image](https://user-images.githubusercontent.com/6403130/117289249-abfb3480-ae6c-11eb-9925-07b1614389a2.png)
Here you can see, directory really doesn't exist:
![image](https://user-images.githubusercontent.com/6403130/117290411-12348700-ae6e-11eb-8254-8b9902c3d3c2.png)

**Comment by deanmarcussen** [comment] 2021-05-06 13:37
Why is the home volume pointing at C: ? 

Is that something you have changed yourself?

Can you check your environment variables in kudo.

I would have expected the `Home` environment variable to be the D: on Azure.

I'm not ruling out an issue with the OC code, but this still feels like a configuration in azure issue, as this all just works on all our sites.

Feel free to reach out to me on gitter or skype, might be easier to help sort it out for you

**Comment by lampersky** [comment] 2021-05-06 13:59
everything here is set by default, the only thing here is that I'm using azure "premium v3" plan, and as you can see HOME is pointing to `C:`
![image](https://user-images.githubusercontent.com/6403130/117310722-d60c2100-ae83-11eb-97db-e50fcecbc5a9.png)

![image](https://user-images.githubusercontent.com/6403130/117310111-4bc3bd00-ae83-11eb-9474-44488fcb8666.png)

those are new plans on azure:
![image](https://user-images.githubusercontent.com/6403130/117310421-8f1e2b80-ae83-11eb-92e0-31dccc6bbb55.png)

(I've just checked some other old plan, and HOME is pointing to `D:`)

@deanmarcussen I can't find you on skype, will send an email

**Comment by sebastienros** [comment] 2021-05-06 18:00
Create a new website or new app service plan and this should go away. This is a common enough issue that I have seen that in other dotnet apps not related with Orchard. Sometime it's prevent the app from starting if the issue happens with the dotnet runtime.

**Comment by lampersky** [comment] 2021-05-06 18:56
@deanmarcussen suggests to try without "media azure", so I've created another app, but without "media azure" and "media cache" and everything works as expected, so it looks like "media cache" related issue

![image](https://user-images.githubusercontent.com/6403130/117350772-3d8a9680-aead-11eb-87b0-f758e0f03ca5.png)

**Comment by sebastienros** [comment] 2021-05-06 19:15
@lampersky Thanks for confirming it's not an azure issue.

**Comment by lampersky** [comment] 2021-05-06 19:21
@sebastienros if there is anything I can do to help investigate this issue, just let me know

**Comment by sebastienros** [comment] 2021-05-06 19:35
Did you manage to repro locally with the blob storage feature enabled?

**Comment by lampersky** [comment] 2021-05-06 19:40
> Did you manage to repro locally with the blob storage feature enabled?

as mentioned [here](https://github.com/OrchardCMS/OrchardCore/issues/9319#issuecomment-833454307), this can be only observed on azure deployed version, I deployed many versions Release/Debug, and both are affected

locally everything works like a charm

**Comment by sebastienros** [comment] 2021-05-06 20:56
@deanmarcussen could it be related to the stream not disposed issue that was recently fixed in IS ?

**Comment by deanmarcussen** [comment] 2021-05-06 21:11
@sebastienros i don’t think so. This seems to be related to source images, rather than cache images, which was the is issue. 
It’s also a different error to what we would see when is had left a stream open.

I am wondering about the cancellation token from the http request again and may suggest some code to try tomorrow- without a way to repro it will have to be some trial and error as I don’t see it on azure

**Comment by lampersky** [comment] 2021-05-06 21:36
@deanmarcussen ping me tomorrow and let's do some screen sharing, I have debbuger connected to my deploeyed version, this way you could "touch" this weird issue

**Comment by jtkech** [comment] 2021-05-06 22:35
@deanmarcussen 

Don't remember the details so maybe not related, but just retrieved one of my comments here, related to a cancelled request, if it may help https://github.com/OrchardCMS/OrchardCore/pull/8750/files#r588218960

**Comment by lampersky** [comment] 2021-05-07 08:52
few more facts:
1) restarting web app fixes issue temporarily,
2) when you click on "purge all" media library stops working again.

I recorded video:

https://user-images.githubusercontent.com/6403130/117424621-436e8f00-af22-11eb-96fe-af6dbf2259de.mp4

**Comment by lampersky** [comment] 2021-05-07 09:04
this line:
`var isFileCached = await _mediaFileStoreCache.IsCachedAsync(subPathValue);`
from:
MediaFileStoreResolverMiddleware:66

is returning TRUE after purging :-O

**Comment by jtkech** [comment] 2021-05-08 09:05
@lampersky If @deanmarcussen can repro, for sure he will fix it ;)

**Comment by deanmarcussen** [comment] 2021-05-08 10:46
This is currently reproducable as either an azure issue, or a `PhysicalFileProvider` on azure issue.

Add a very long file name (+80 chars), then delete the file through `File.Delete`, after finding it with  a physical file provider (or via ftp, so more likely azure related, but only seems so far reproducable when using a `PhysicalFileProvider` to find the files (ie. it doesn't reproduce (so far) with standard System.IO), it will appear to lock the underyling file system access, whether just dotnet, or indeed IIS, or the file system itself.

The result is that any further file system request on `File.Exists` return true, yet `File.Delete` throws an exception, until the app service pool is restarted.

There are possibly other ways to reproduce, however, that was the one I found.

Current suggested workaround is not to use really long file names.

Because this is reproducable via both dotnet code, and deleting the files via ftp, my current thinking is towards azure file system weirdness.

The suggestion is to 
- remove all these long file names from the site, and see if the issue goes away, at which point we can make some choices
- create a small repro, outside of OrchardCore, to see if the complexity of reproducing can be reduced (this at least would eliminate any of our code, and prove the above repro, so we can consider if we need a workaround)

**Comment by lampersky** [comment] 2021-05-10 15:15
I isolated the problem outside of OC.
Will share small repro repo later today.

**Comment by sebastienros** [comment] 2021-05-10 17:13
@deanmarcussen @lampersky this is sad, but also very nice that you found a repro. Hopefully it will ensure it can be fixed in aspnet core and/or in Azure App Service.

**Comment by lampersky** [comment] 2021-05-10 20:15
Here is a minimal repro [repo](https://github.com/lampersky/PhysicalFileProviderRepro), maybe there is a way to minimize it more. I deployed it to azure and was able to see same exceptions.

https://user-images.githubusercontent.com/6403130/117718507-7348bb80-b1dc-11eb-8696-d16b453b1e9e.mp4

it would be good if anybody could confirm

**Comment by sebastienros** [comment] 2021-05-25 16:18
I tried to build a repro which doesn't require clicking on links, but couldn't repro the issue this way. Here is my code, where I tried to follow what the provider is doing, and what you are scripting: https://gist.github.com/sebastienros/007d085fc1493d5ff4fea6b27b7c45fe

It works locally and on Azure App Services for me. I just copy the files using Kudu and do dotnet run.

**Comment by sebastienros** [comment] 2021-05-25 17:35
Debugged the code, and the issue happens when `Directory.Exists(dirPath)` is called once the files have been purged. The folder doesn't exist but it returns `true`, then in the same method it tries to create the file but it fails due to the folder missing. So something says the folder is there and something else not.

**Comment by deanmarcussen** [comment] 2021-05-25 18:08
I tried a small repo last friday as well, but was struggling to repo in a console app.

However I wondered if it was related to `Directory.Delete(dir.FullName, true);` <-- where this is a recursive delete, which has presented some weirdness in the past.

**Comment by lampersky** [comment] 2021-05-29 06:45
> I tried to build a repro which doesn't require clicking on links, but couldn't repro the issue this way.

This was my first approach, with no luck too. Then I decided to divide into steps. It looks like some time must pass between steps.

**Comment by jtkech** [comment] 2021-05-30 00:02
@lampersky 

Just cloned your repro example and deployed it to azure app services, **i couldn't repro**. Then i deployed it on azure app (linux) but to get the home page working i needed to use a NullFileProvider, otherwise, with this linux deployment, i would need to mount an azure file storage.

So, before going further, did you deploy on linux?

Also i saw that you were using 4 instances in your plan.

So, did you try your repro with only one running instance?

**Comment by lampersky** [comment] 2021-05-30 08:35
> So, did you try your repro with only one running instance?

@jtkech yes, I tried with single instance.
Dean also was able to repro this on single instance.
Also I tried with different app service plans. But all of them are on Windows.

**Comment by jtkech** [comment] 2021-05-30 23:46
@lampersky Okay thanks, so just to say that i could not repro.

And the only difference that i can see in my config is that each time you have `C:\` i have `D:\`, each time you have you have `D:\` i have `C:\`, and that i used a free plan.

So, hard to analyse if i can't repro, one thing i thought about is that maybe some files are marked as deleted but some file handles are still open. I also updated the project to use razor runtime compilation that uses files watching, but I could not repro the issue in this case too.

I would like to know if it could work on your side by just using a simple free plan ;)

**Comment by lampersky** [comment] 2021-05-31 05:02
> I would like to know if it could work on your side by just using a simple free plan ;)

@jtkech I will check today with free plan

**Comment by lampersky** [comment] 2021-05-31 07:11
Few more observations from my tries:
- I've tried to reproduce the problem with single click, by adding some delay between steps (**could not repro this way**):
```
        [HttpGet("break-3")]
        public async Task<IActionResult> Break3()
        {
            for (int i = 0; i < 5; i++)
            {
                await _myFileProvider.Recreate();
                await Task.Delay(200);
                await _myFileProvider.ReadThemAll();
                await Task.Delay(200);
                await _myFileProvider.PurgeAsync();
                await Task.Delay(200);
                await _myFileProvider.ReadThemAll();
                await Task.Delay(200);
                await _myFileProvider.PurgeAsync();
                await Task.Delay(200);
                await _myFileProvider.Recreate();
            }
            return Ok();
        }
```
- also I've tried with http client (**could not repro this way too**):
```
        [HttpGet("break-4")]
        public async Task<IActionResult> Break4([FromServices] IHttpClientFactory httpClientFactory)
        {
            var httpClient = httpClientFactory.CreateClient();
            httpClient.BaseAddress = new System.Uri($"{Request.Scheme}://{Request.Host.Value}");

            for (int i = 0; i < 5; i++)
            {
                await httpClient.GetStringAsync("/recreate-files-and-directories");
                await Task.Delay(100);
                await httpClient.GetStringAsync("/read-them-all");
                await Task.Delay(100);
                await httpClient.GetStringAsync("/purge");
                await Task.Delay(100);
                await httpClient.GetStringAsync("/read-them-all");
                await Task.Delay(100);
                await httpClient.GetStringAsync("/purge");
                await Task.Delay(100);
                await httpClient.GetStringAsync("/recreate-files-and-directories");
            }

            return Ok();
        }
```
- I've noticed that, when **kudu** is opened, and for example the deepest directory is opened, **purge** is ending with some errors, because it's able to remove just files but not directories, and because directories are locked I can't reproduce the problem:

https://user-images.githubusercontent.com/6403130/120153316-dda6b780-c1ee-11eb-97ec-8ece27721987.mp4

- here is an example with **Default** directory opened in **kudu**:

https://user-images.githubusercontent.com/6403130/120153517-1a72ae80-c1ef-11eb-8f3e-b760a2c76a0b.mp4

- this can be **only** reproduced on paid azure plans, so far I wasn't able to reproduce on free plan nor locally,

- for some reason the problem only can be observed when all those operations (purge, create, read) are executed within distinct requests.

/cc @sebastienros @jtkech @deanmarcussen

**Comment by lampersky** [comment] 2021-05-31 07:40
This is also weird, that for non existing files I'm getting two different exceptions :D
![could-not-find-a-part-of-the-path2](https://user-images.githubusercontent.com/6403130/120158205-2614a400-c1f4-11eb-8d42-aee81e1e5428.png)
![could-not-find-file2](https://user-images.githubusercontent.com/6403130/120158224-2b71ee80-c1f4-11eb-9377-c9020fb1d7a1.png)

**Comment by jtkech** [comment] 2021-05-31 21:38
@lampersky 

Okay, so maybe good to find a workaround to get it working also on your paid plan.

Can you give me some accesses so that i could try to find a workaround, i may have some ideas.

**Comment by jtkech** [comment] 2021-06-01 01:31
So where i'm is that if we delete all files but not the directories it works.

Let me know when you will have an easier way to restart the site so that i could do more tests.

But only when you will have time, nothing urgent for me ;)

**Comment by lampersky** [comment] 2021-06-01 05:10
> > I've tried to reproduce the problem with single click, by adding some delay between steps (could not repro this way):
> > also I've tried with http client (could not repro this way too):
> 
> On your paid instance?

yes

**Comment by jtkech** [comment] 2021-06-02 02:08
@lampersky 

So, in your paid plan the maximum path length seems to be 208 chars, normally `MAX_PATH` is 260 chars including a terminating null character (unless long paths is enabled), from where is comming the difference 260 - 1 - 208 = 51 ?

Hmm, maybe because there is a mapping linking `c:` (2 chars) with `D:\DWASFiles\Sites\#1orchard-core-media-problem__5336` (53 chars) => adding 53 - 2 = 51 chars, but not 100% sure ;)

So, it seems that on the free plan long paths are enabled, but not on a paid plan where as i remember you don't necessarily get a better machine but a dedicated one. Maybe you can configure it to enable long paths.

So, this is where i'm, not sure if we need to implement something, maybe shorter file names for caching, e.g. hash codes but with possible collisions, will see.

**Comment by deanmarcussen** [comment] 2021-06-02 10:23
@jtkech @lampersky that was the conclusion I reached as well, as without the long file name, the issue doesn't present. Why I can't say.

@sebastienros was trying to repro to see if it is something we should try to mitigate against, or present as an issue.

I'm reluctant to try and implement hashing inside the file provider, it feels like it would be fragile, knowing that we need to be able to provide the same hash variation for the StaticFileMiddleware, and ImageSharp, as they pick up the file later down the line, however it might be the correct approach.

If we do need a mitigation, I would prefer to limit file name lengths, perhaps via options, as it's going to be hard to know exactly what size causes the issue, but that has it's own potential issues.

What I haven't had time to look at, is what exception gets thrown if the path actually exceeds 260 chars. I would assume a relevant exception, rather than this unknown error - that might suggest the mitigation route, as blob storage will support a much higher path length, than I imagine NTFS will.

**Comment by lampersky** [comment] 2021-06-02 11:49
Let's wait for Microsoft team thoughts, for sure they will find solution what is going on.

If this is really too long path issue, why everything works fine, when all those operations (create, read, purge) are executed inside **same request** without any problems.

**Comment by jtkech** [comment] 2021-06-02 18:04
@lampersky @deanmarcussen

Yes i agree, just to say that it works with 208 chars but not with 209, and as described maybe we reach a limit if somewhere `c:\` is expanded to `D:\DWASFiles\Sites\#1orchard-core-media-problem__5336\`.

Then, as @lampersky pointed out, why does it work if done in the same request, would need to debug it and step into the offending method, but maybe still worth to add these info to the dotnet issue, and that it is related to a path length.

Maybe interesting to retry it but with a shorter name for the `#1orchard-core-media-problem__5336` plan.

**Comment by sebastienros** [comment] 2022-09-29 17:44
They have fixed related issues last year. We'll see if people can still repro.

**Closed by sebastienros** 2022-09-29 17:44 UTC
Labels: bug :bug:

**Comment by lampersky** [comment] 2022-09-29 18:52
> They have fixed related issues last year. We'll see if people can still repro.

@sebastienros do you mean this one https://github.com/dotnet/runtime/issues/52753 ? I'm surprised it is fixed, because nobody marked it as fixed there.
