### ISSUE TITLE
Can't use custom User module with OrchardCore.OpenId because it tied to OrchardCore.Users

### ISSUE THREAD

**Issue by YaoaY** [OrchardCMS/OrchardCore#1023] opened 2017-09-26 05:00 UTC
I want to extend the User model,but have not yet found a simple way.
So i decide to implement IUser,IUserStore,IUserService in a new module called 'OrchardCore.MyUsers'(almost the same as 'OrchardCore.Users').

I replaced 'OrchardCore.Users' with this 'OrchardCore.MyUsers' in recipe,and the setup is successful.
It works as I expected, now i have my custom User model;I can find user by PhoneNumber e.g..... 

But when i enable OrchardCore.OpenId in admin dashboard,the OrchardCore.Users module is also enabled.

then 💥... 😭  

@PinpointTownes

**Comment by YaoaY** [comment] 2017-09-26 06:17
Temporary work around:

1. 
Add `Dependencies: OrchardCore.Users` to 'OrchardCore.MyUsers' module.txt
Since it can not be disabled, simply I also enabled it，at least to ensure that my module is loaded at a later time.

2.
Remove the code in `OrchardCore.MyUsers.Startup.ConfigureServices` which i copied from `OrchardCore.Users.Startup.ConfigureServices`.

Avoid configuration services twice then cause errors.

3.
Then add my custom services:
`services.AddScoped<UserManager<IUser>, MyUserManager>();`
`services.AddScoped<IUserStore<IUser>, MyUserStore>();`
`services.AddScoped<IUserService, MyUserService>();`

Use `AddScoped` instead of  `TryAddScoped`  to ensure that the previously registered services are replaced.

Now it works with `OrchardCore.OpenId` module,but I do not know if this is correct.

🤐

**Comment by YaoaY** [comment] 2017-09-26 08:01
and...

In file `src\OrchardCore.Modules\OrchardCore.Users\Controllers\AdminController.cs`:

line 81:
```
var users = _session.Query<User, UserIndex>();
```

This could cause an `InvalidCastException` in view Admin/Index.cshtml.
`line:55 <a asp-action="Edit" asp-route-id="@await UserManager.GetUserIdAsync(entry.User)" class="btn btn-primary btn-sm">@T["Edit"]</a>`

What can i do now? 😹 
I am trying to live with `OrchardCore.Users` peacefully 🕊

**Comment by PinpointTownes** [comment] 2017-09-26 13:03
@alexbocharov any idea of what could be causing that? Would decoupling the OpenID module from `OrchardCore.Users` (or even from ASP.NET Core Identity) help fix this kind of issue?

/cc @sebastienros

**Comment by alexbocharov** [comment] 2017-09-26 14:15
@PinpointTownes  The problem is
https://github.com/OrchardCMS/OrchardCore/blob/e7fc8a1550e46be18418fd8945b70991d95937f4/src/OrchardCore.Modules/OrchardCore.OpenId/Module.txt#L9

**Comment by PinpointTownes** [comment] 2017-12-13 02:41
Closing as I believe this was fixed in the recent bits. Please re-open if it's not.

**Closed by PinpointTownes** 2017-12-13 02:41 UTC
Labels: Orchard.OpenId

**Comment by PinpointTownes** [comment] 2018-05-11 23:17
@YaoaY FYI, I sent a prototype PR that decouples the OpenID module from Roles and Users: https://github.com/OrchardCMS/OrchardCore/pull/1786

**Comment by YaoaY** [comment] 2018-05-12 00:46
Nice~~! Thank you! @PinpointTownes  👍
