### ISSUE TITLE
GraphQL, MARS issue: Content Picker field 

### ISSUE THREAD

**Issue by MikeKry** [OrchardCMS/OrchardCore#11400] opened 2022-03-18 15:17 UTC
### Describe the bug
I get error on a Content Picker field: 
"GraphQL.ExecutionError: Error trying to resolve contentItems.\r\n ---> System.InvalidOperationException: The connection does not support MultipleActiveResultSets.
when I create custom field which loads data from index. 

Not sure why, but it collides only with custom **field**, parts etc. behave normally.

I am using ResolveLockedAsync, so it should create separate lock and work together. It breaks (only) when I try to query index, if I use dataloader as in ContentPicker field, then it works together. Maybe it is just in cache, so it does not query DB two times if I do it with dataloader.

Resolve method:
![image](https://user-images.githubusercontent.com/52829889/159030282-d1f06ad6-a2d7-4877-9843-f192fb9ff4d3.png)

Maybe ContentPicker field should use ResolveLockedAsync too?

**Comment by Skrypt** [comment] 2022-03-20 03:23
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/9330

**Closed** 2022-03-20 03:23 UTC
