### ISSUE TITLE
Swith boolean field not working inside tabs

### ISSUE THREAD

**Issue by jptissot** [OrchardCMS/OrchardCore#5910] opened 2020-04-10 22:11 UTC
Place a boolean field in a tab of a widget being created as part of Flow. It becomes impossible to toggle the switch. This switch was the last field in the tab.

**Comment by sebastienros** [comment] 2020-04-10 23:24
I think it's a duplicate

**Comment by sebastienros** [comment] 2020-04-10 23:25
duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3944

**Closed by sebastienros** 2020-04-10 23:25 UTC
