### ISSUE TITLE
Author role bugged

### ISSUE THREAD

**Issue by nickelnext** [OrchardCMS/OrchardCore#6193] opened 2020-05-15 16:28 UTC
Running 1.0.0-rc1-13211

I create an author

![Author User](https://user-images.githubusercontent.com/8006102/82073384-74363280-96d9-11ea-830a-d1ac3e48c58b.png)

Trying to open contents I get this error
Also, sometimes some pages showing content are showing, but using the paging system (going to page 2 for example) triggers the error.
![Content Items Error](https://user-images.githubusercontent.com/8006102/82073433-89ab5c80-96d9-11ea-9703-8faaf444677d.png)

These are the permissions
![Content Permissions](https://user-images.githubusercontent.com/8006102/82073459-929c2e00-96d9-11ea-99e3-b449f574b993.png)

**Comment by TFleury** [comment] 2020-07-09 15:41
I was unable to reproduce it.
Could you confirm and provide logs or close the issue ?

**Comment by hishamco** [comment] 2020-07-09 15:42
@nickelnext please use RC2 and have a try

**Closed** 2020-07-09 17:14 UTC
