### ISSUE TITLE
Unauthorized ApiController request should not return 200 status code

### ISSUE THREAD

**Issue by HengzheLi** [OrchardCMS/OrchardCore#8423] opened 2021-01-25 04:50 UTC
### Describe the bug
I used PostMan to try ApiController. The requesting path is /api/content/[contentitemid] with an Authorization hearder whose value is only "Bearer"(no "token"). 
The response is empty and the status code is 200. 

### Reproduce steps
1. Create a fresh tenant using agency recipe.
2. Use postman to send a below request
```
"request": {
"auth": {
	"type": "bearer",
	"bearer": [
		{
			"key": "token",
			"value": "",
			"type": "string"
		}
	]
},
"method": "GET",
"header": [],
"url": {
	"raw": "https://localhost:5001/api/content/[replace to your content item id]",
	"protocol": "https",
	"host": [
		"localhost"
	],
	"port": "5001",
	"path": [
		"api",
		"content",
		"[replace to your content item id]"
	]
}
```

### Expected behavior
Unauthenticated request should get 401 return code.

I debugged the code and located to below code line in class OrchardCore.Mvc.Utilities.ControllerExtensions
```
controller.User.Identity.IsAuthenticated ? (ActionResult)controller.Forbid(authenticationSchemes) : (ActionResult)controller.Challenge(authenticationSchemes);
```
Seems like the code assumes that the request is sent by a login user. But actually, controller.User is null in this case as I didn't login when I sent the request. 

BTW, I take a look at the code of the class ApiAuthenticationHandler which is an authentication handler for schema "Api". It only check if there is a "Bearer" word in SchemaMap. 
```
protected override async Task<AuthenticateResult> HandleAuthenticateAsync()
        {
            if (!_authenticationOptions.Value.SchemeMap.ContainsKey(Options.ApiAuthenticationScheme))
            {
                return AuthenticateResult.NoResult();
            }

            return await Context.AuthenticateAsync(Options.ApiAuthenticationScheme);
        }

        protected override Task HandleChallengeAsync(AuthenticationProperties properties)
        {
            if (!_authenticationOptions.Value.SchemeMap.ContainsKey(Options.ApiAuthenticationScheme))
            {
                return Task.CompletedTask;
            }

            return Context.ChallengeAsync(Options.ApiAuthenticationScheme);
        }
```
Seems like this behavior can't defend an unthenticated user. So what does this authencation handler use for? In my understand, shouldn't it validate if there is a valid token here?

**Comment by sebastienros** [comment] 2021-01-28 18:18
Need to be reproduced. There might still be a cookie sent. 

@HengzheLi is the content item also returned?

**Comment by HengzheLi** [comment] 2021-01-29 08:27
No content item returned. 
I didn't log in. So I think the cookie wasn't sent.

**Comment by deanmarcussen** [comment] 2021-02-12 17:26
I can't reproduce this in postman.

**Comment by deanmarcussen** [comment] 2021-02-13 10:43
Ok, I can repro.

@HengzheLi by default we have no `Bearer` scheme registered. I always assume people will turn on `OpenID Token Validation` to use an api controller.

However, if you don't turn on OpenID Token Validation, you are correct, you get a 200 response back.

@kevinchalet this is because of the change we made to return `Forbid("Api")` because this code

```
            if (!_authenticationOptions.Value.SchemeMap.ContainsKey(Options.ApiAuthenticationScheme))
            {
                return Task.CompletedTask;
            }
```

makes it a noop, if we haven't registered a `Bearer` scheme - which of course `OpenID` does.

Many options are possible.

I am mostly tempted to remove the check, so that it just throws an exception. 
Or throw a more meaningful exception, like `You must use the OpenID Token Validation feature, or register your own Bearer scheme`

Or some other approach might be better?

**Comment by kevinchalet** [comment] 2021-02-13 11:39
> I am mostly tempted to remove the check, so that it just throws an exception.

When @sebastienros introduced this handler, the goal was to avoid this exception, that may be annoying/blocking when things are not fully configured yet. You'll probably want to check with him whether a different option should be implemented. In all cases, nothing can really work until the OpenID token validation feature is enabled and configured (or a custom module handling the `Bearer` scheme is added).

**Comment by sebastienros** [comment] 2021-02-25 19:07
I like @deanmarcussen 's suggestion of registering a default Bearer scheme that will fail.

**Comment by deanmarcussen** [comment] 2021-08-24 18:17
Fixed by https://github.com/OrchardCMS/OrchardCore/pull/9318

**Closed by deanmarcussen** 2021-08-24 18:17 UTC
Labels: bug
