### ISSUE TITLE
Create a configurable DashBoard Admin  Landing Page

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#1368] opened 2018-01-11 13:46 UTC
Allow users  to define the content displayed when accessing the admin dashboard right next to main navigation menu in the content area.  The content will be defined using existing flow part  and access will be provided to users with proper permissions from the Settings menu in the admin.

**Comment by sebastienros** [comment] 2018-01-11 20:41
I suggest we keep your extensibility point with the custom shape, so that we can provide different modules to make a dashboard. A module would just have to provide a custom shape to trigger their behavior.

**Comment by sebastienros** [comment] 2018-08-23 19:54
Duplicate of #2246

Keeping the other issue as the comments are better

**Closed by sebastienros** 2018-08-23 19:54 UTC
