### ISSUE TITLE
Ability to automatically or en mass trim old `Workflow`s

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#16447] opened 2024-07-16 22:37 UTC
### Is your feature request related to a problem? Please describe.

Executing a Workflow Type creates a `Workflow` document, and a corresponding `WorkflowIndex`. Unless you delete `Workflow`s manually (either one by one, or in bulk page by page), this causes both the `Document` and the `WorkflowIndex` table to grow indefinitely.

This becomes a real issue if workflows are executed frequently. E.g., the site of one of our client uses Workflows to handle form submissions, which forms are submitted by thousands of people every workday. The result is that the Document table is now 12 GB with 860k rows, and the SQL query behind `/Admin/Workflows/Types` (`SELECT DISTINCT [WorkflowIndex].[WorkflowTypeId] FROM [WorkflowIndex]`) times out, resulting in an error page.

Related to https://github.com/OrchardCMS/OrchardCore/issues/6056.

### Describe the solution you'd like
A feature that would periodically delete `Workflow`s older than a given threshold, much like Audit Trail trimming works, would be ideal.

This needs special care and batching, since there can be a huge number of `Workflow`s (860k for us), especially the first time it runs.

### Describe alternatives you've considered
The ability to delete `Workflow`s en mass mass, more than just 10 items on a page.

**Comment by deanmarcussen** [comment] 2024-07-18 20:52
possibly duplicate of https://github.com/OrchardCMS/OrchardCore/issues/11609

We actually wrote this internally (pruning/trimming), and have been wanting to pr it back.

With any luck that might actually happen soon

**Comment by Piedone** [comment] 2024-07-18 21:31
That would be awesome!

**Closed** 2024-07-18 21:31 UTC
Labels: enhancement
