### ISSUE TITLE
Media fields filter type not correct except the first one.

### ISSUE THREAD

**Issue by yqzhen1990** [OrchardCMS/OrchardCore#16440] opened 2024-07-15 12:52 UTC
### Describe the bug
When a content type contains multiple media fields, the filter types set for all media fields are overwritten by the filter type of the first media field.

### Orchard Core version
release-1.8.3

### To Reproduce
1. Set content type's first media field extensions with video type.
2. Set content type's other media fields extensions with image type.
3. Create a content item with this content type and edit the media fields.
4. You'll find all the media fields filter extensions turned to be video type.

### Expected behavior
Configure the correct filter extensions for each media field.

### Logs and screenshots
![image](https://github.com/user-attachments/assets/c3dee8a2-ea34-4b26-a1e8-b4708e83f872)
![image](https://github.com/user-attachments/assets/e5512667-b82a-4a3f-a06a-014ac14ee28c)
![image](https://github.com/user-attachments/assets/61df6185-e915-42d4-9e0f-968b590cdd0e)
![image](https://github.com/user-attachments/assets/7b85324c-a362-4313-afa7-e923c5590e43)
![image](https://github.com/user-attachments/assets/7af59137-13bf-4f75-be2e-e7c841740b7b)

**Comment by Piedone** [comment] 2024-07-17 16:09
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/15569.

**Closed by Piedone** 2024-07-17 16:09 UTC
Labels: bug :bug:
