### ISSUE TITLE
Get contentItem by alias when it is just a draft

### ISSUE THREAD

**Issue by ruisdias** [OrchardCMS/OrchardCore#5186] opened 2020-01-02 09:15 UTC
Hi,

When I try to get a content item by alias which isn't published ( just saved as a draft) it returns null.

I'm using GetContentItemByAliasAsync method from IOrchardHelper.

I went to source code to try to understand it why it happens, so :

Basically, when I save it, just as a draft, it does not create a new row in the AliasPartIndex Table, and that's why it does not return me the item.

I was also try to see how preview is actually working (because if it works, could be just my problem) but I discovered, actually, it uses the contentItemId, so it doesn't need the AliasPartIndex  table.

`<a class="dropdown-item btn-sm" href="/Contents/ContentItems/4a3m37nmyacp8v43f3edb98xne/Preview">Preview Draft</a>`

The row is just added in the AliasPartIndex  table when I publish the contentItem, don't know if it's the expected behavior but I need to get it even when it is just a draft. 

If it a normal situation, please say so.

Thanks in advance,

Rui Dias

**Comment by deanmarcussen** [comment] 2020-01-02 15:50
I think this is by design.

Normally display of content items is based on published, so the idea of getting an draft content item by alias is not something we would have thought was normal as such.

However if you could explain where and why you are trying to get this draft there might be other ways to achieve it

**Comment by sebastienros** [comment] 2020-01-02 17:02
Looking at the index provider, it only stores the content items that are published by design. So if a content item has never been published it won't be available from `GetContentItemByAliasAsync`. That could be an issue for instance when using the decoupled mode and trying to do a preview of a new item. This is how the decoupled guide in the docs proceeds.

If we removed the test on `Published` we would get as many records as content item versions, which is not recommended. However I assume we could filter on `Latest`, in which case old versions would get removed from the index automatically, we'd still have one index record per content item, and content items with only a draft version would still work. I think we should make this technique clear in all index providers:
- IsPublished to only get an index for published content item versions
- IsLatest to get a single index per content item, but including the ones with only a draft version

**Comment by sebastienros** [comment] 2020-01-02 17:03
And maybe review the common indexes to see if we should change them.

**Comment by sebastienros** [comment] 2020-01-02 20:53
Now a caveat is that if we index the Latest version then the alias that will be indexed might be the draft one, so if it is changed, the published version won't be found (with the published alias). It's a corner case but that needs to be handled. Or we could only update the alias text if the content is published. And we would still be able to Preview the content item, as the record exists already (for the published version).

**Comment by sebastienros** [comment] 2020-01-02 20:56
Other option: index both versions (published and draft) and add a new `Published` column, like the autoroute part index does.

**Comment by ruisdias** [comment] 2020-01-03 08:36
Hi @deanmarcussen  and  @sebastienros,

That's exactly what I was trying to achieve.

Right now, I'm using orchard as a decoupled CMS and I wanted to preview my draft before I publish it.

Thanks for your quick reply guys.

**Closed** 2020-01-15 22:02 UTC
