### ISSUE TITLE
tag helper <style asp-name""> not work in my module

### ISSUE THREAD

**Issue by MRSheikh** [OrchardCMS/OrchardCore#16036] opened 2024-05-12 06:32 UTC
### Discussed in https://github.com/OrchardCMS/OrchardCore/discussions/16031

<div type='discussions-op-text'>

<sup>Originally posted by **MRSheikh** May 11, 2024</sup>
hi.
I use Orchardcore without cms "OrchardCore.Application.Mvc.Targets" to my projects and add my module to it. 
I know to add 
`builder.Services.AddOrchardCore().ConfigureServices(s =>
{   s.AddResourceManagement();
    s.AddTagHelpers<LinkTagHelper>();
    s.AddTagHelpers<MetaTagHelper>();
    s.AddTagHelpers<ResourcesTagHelper>();
    s.AddTagHelpers<ScriptTagHelper>();
    s.AddTagHelpers<StyleTagHelper>();
});` 
in my program and then implement `ResourceManifest.cs` for my module too. 
after that in `_ViewImports.cshtml` add 
`@addTagHelper *, OrchardCore.DisplayManagement
@addTagHelper *, OrchardCore.ResourceManagement`

and in `_ViewStart.cshtml` use tag helpers like this:

> <style asp-name="bootstrap"></style><style asp-name="site"></style><script asp-name="myjquery"></script><script asp-name="bootstrap"></script><script asp-name="site"></script>

 all scripts were added successfully into my module but nothing for styles????

what should I do to import my module styles to tag helper?</div>

**Comment by MikeAlhayek** [comment] 2024-05-13 15:11
Make sure you add reference to `OrchardCore.DisplayManagement` on your module. Also make sure that your module is different that your web project. so have a web project where you add `builder.Services.AddOrchardCore()....` then add a module project for your module where you can reference `OrchardCore.DisplayManagement`

**Comment by Piedone** [comment] 2024-05-13 16:37
Duplicate of the https://github.com/OrchardCMS/OrchardCore/discussions/16031 discussion. Please open either a discussion or an issue, but not both. For questions, only open a discussion.

**Closed by Piedone** 2024-05-13 16:37 UTC
