### ISSUE TITLE
Bug rendering Layout.cshtml on Windows Server 2016 with IIS - menu disappears!

### ISSUE THREAD

**Issue by orchardc** [OrchardCMS/OrchardCore#3919] opened 2019-07-12 21:54 UTC
There seems a bug when rendering the **Layout.cshtml** on Windows Server 2016 running IIS, and **The menu bar doesn't show up**. - see the code highlighted below, it should render the main-menu but it isn't.

![image](https://user-images.githubusercontent.com/16193516/61160129-4ea72e00-a4f6-11e9-8bbb-d78db05d7b8d.png)

However the same site works fine in Windows 10 with IIS express (Visual Studio 2017)

I'm not sure if it caused by the Razor: 
https://docs.microsoft.com/en-us/aspnet/core/mvc/views/view-compilation?view=aspnetcore-3.0
https://docs.microsoft.com/en-us/aspnet/core/razor-pages/sdk?view=aspnetcore-3.0

**Comment by Skrypt** [comment] 2019-07-12 22:02
First thing is to provide us with exception logs from your server which should lead to the cause.

**Comment by orchardc** [comment] 2019-07-12 22:12
Hi @Skrypt , where can I find the exception logs ?

**Comment by Skrypt** [comment] 2019-07-12 22:55
`\src\OrchardCore.Cms.Web\App_Data\logs`

**Comment by Piedone** [comment] 2024-04-25 22:43
Closing due to no reply from author.

**Closed by Piedone** 2024-04-25 22:43 UTC
Labels: bug :bug:
