### ISSUE TITLE
Exception: Shape type 'Layout' not found

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#5469] opened 2020-02-06 00:37 UTC
Exception: Shape type 'Layout' not found

How do I narrow this down?
I made a software as a service app then I made a tenant
When I run my custom theme I get this error on the home page

**Comment by Skrypt** [comment] 2020-02-06 00:39
Do you have a Layout.liquid or Layout.cshtml file in your /Views folder of that Theme?

**Comment by JoshTango** [comment] 2020-02-06 01:15
yes and the theme will work if it is not a tenant

**Comment by Skrypt** [comment] 2020-02-06 01:27
Well I don't understand then. There's too few details here for me to help more. If you look at our documentation this is something that should work. If you did something custom then provide more code details.

**Comment by Craige** [comment] 2020-02-06 03:09
Duplicate of #3346?

**Closed** 2020-02-06 03:10 UTC

**Comment by JoshTango** [comment] 2020-02-06 09:28
Actually It does happen when I run the recipe and not enable the theme

**Comment by JoshTango** [comment] 2020-02-06 09:29
#3346 might be on to something

**Comment by muradzade** [comment] 2020-12-18 12:42
I had the same problem.
For solution: You need to check recipe file.Include your theme name.
    {
      "name": "themes",
      "admin": "TheAdmin",
      "site": "YourTheme"
    }
