### ISSUE TITLE
change text in cms for localization like nopcommerce

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore#2176] opened 2018-08-03 11:30 UTC
in NopCommerce there is a part for languages that can import and export and Edit Languages easily.

**Comment by Skrypt** [comment] 2018-08-03 16:54
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/2081

**Closed** 2018-08-03 16:54 UTC
