### ISSUE TITLE
Accessing Menu using API Query - Question

### ISSUE THREAD

**Issue by khurram4u2** [OrchardCMS/OrchardCore#6692] opened 2020-07-16 05:34 UTC
Hi, I exposed my menus to a third party application using API query.  it was  working fine before ContentMenuItem was added to Menu as I was getting name and the path of the content. But now for ContentMenuItems, it returns the content name and Id.

I know we can use the following liquid code to get the code within CMS. 
{{ contentMenuItem.SelectedContentItem.ContentItemIds.first | display_url }}.

But how can I use id in an external application to access the cms page ? Kindly advise

Can we have path of the content as well along with id.

**Comment by deanmarcussen** [comment] 2020-07-21 13:19
I think this is a duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6100

But I'm not sure, I assume you are using the GraphQL API @khurram4u2 ?

In which case it is not implemented @khurram4u2 but feel free to provide a pr for it

**Closed** 2020-07-26 11:57 UTC
Labels: question
