### ISSUE TITLE
Search Implementation Help!

### ISSUE THREAD

**Issue by MuhammadTalha10** [OrchardCMS/OrchardCore#5192] opened 2020-01-03 11:47 UTC
Hello! i am new to orchard core cms building a food website i gave some categories sub categories and products in it . i want to implement search on my website kindly guide me how i can implement this i am using decoupled approach.

**Comment by hishamco** [comment] 2020-01-03 11:58
There's SQL queries and Lucene queries as well

**Comment by MuhammadTalha10** [comment] 2020-01-03 12:05
yes ! but i dont know how to use them kindly refer me any tutorial or something from which i can understand the flow (Orchard Documentation is not enough)

**Comment by hishamco** [comment] 2020-01-03 12:10
Have a look to https://github.com/EtchUK/Etch.OrchardCore.Search & https://github.com/OrchardCMS/OrchardCore/issues/4142

**Comment by Skrypt** [comment] 2020-01-03 20:21
The documentation is on ElasticSearch documentation website. But we could add some examples to make this easier.

**Comment by hishamco** [comment] 2020-01-03 20:36
You 're right, I refer to a related issue, BTW my intend to point out to the 3rd party module just to show how to use the search while there's no much details in our docs :)

**Comment by hishamco** [comment] 2020-01-03 20:38
I think we need to close this while it duplicate of #4142 

Am I right Jasmin?

**Closed** 2020-01-03 20:41 UTC
