### ISSUE TITLE
Content Items - Manage Items Filter not cleared when filter text is cleared out with the 'x'

### ISSUE THREAD

**Issue by tabzone** [OrchardCMS/OrchardCore#6844] opened 2020-08-06 08:33 UTC
In the content items ->Manage content screen , if a text filter is applied and then cleared , the results without the filter are not shown. There is an 'x' to clear out the filter. It should reset and clear the filter to display all results.

**Comment by hishamco** [comment] 2020-08-06 15:31
Let me try to reproduce the issue

**Comment by hishamco** [comment] 2020-08-06 15:48
I can reproduce the bug if you filter by content type

**Comment by hishamco** [comment] 2020-08-06 15:56
@agriffard is the intend of "x" button to close the list or clear out the search filter

**Comment by hishamco** [comment] 2020-08-07 00:09
> https://recordit.co/XBvfkKFLPY

Copying your screen cast for reference and to separate the two issues, @tabzone I didn't see any "x" button on the filter textbox, which browser you are working on? Coz all my tests on the latest bits

**Comment by tabzone** [comment] 2020-08-07 00:16
I am seeing the x on both , Chrome and Edge 
![cap1](https://user-images.githubusercontent.com/2137586/89595118-8a4f1d00-d808-11ea-9f67-ef1d35759766.PNG)

**Comment by hishamco** [comment] 2020-08-07 00:28
This is a browser one not OC one, please check my latest comments in my PR

**Comment by tabzone** [comment] 2020-08-07 00:41
Yes, in firefox the 'x' does not show. But in modern browsers like  chrome /edge it does show 'x' in the filter box.

**Comment by hishamco** [comment] 2020-08-07 00:45
This is a feature for some browsers, so I will close this one while it's not a bug, thanks because you let me discover another bug ;)

Feel free to open an issue if you face an issue ...

**Closed by hishamco** 2020-08-07 00:45 UTC
