### ISSUE TITLE
Lucene API Controller cookie authentication

### ISSUE THREAD

**Issue by jpiquot** [OrchardCMS/OrchardCore#3158] opened 2019-02-08 07:32 UTC
Hi,

I have tried to use lucene api in SPA mode but I have an authentication issue. It seems that cookie authentication does not work.

![image](https://user-images.githubusercontent.com/6775094/52464483-5e9f9800-2b7b-11e9-97d8-3ea873b67adc.png)

 ```
  [Route("api/lucene")]
    [ApiController]
    [Authorize(AuthenticationSchemes = "Api"), IgnoreAntiforgeryToken, AllowAnonymous]
    public class ApiController : Controller
    {
 
```
If I remove AuthenticationSchemes = "Api", the cookie authentication works.

 ```
  [Route("api/lucene")]
    [ApiController]
    [Authorize, IgnoreAntiforgeryToken, AllowAnonymous]
    public class ApiController : Controller
    {
 
```

**Comment by PinpointTownes** [comment] 2019-02-13 19:02
API controllers are not meant to be used with cookies as they explicitly disable antiforgery validation for every action they expose (not just GET actions). Yet, using cookies with AF disabled would be terrible in this case.

Instead, consider using access tokens. The OpenID module can help you with that.

**Comment by jpiquot** [comment] 2019-03-03 09:31
It's just a OC cshtml page that contains a javascript grid that queries the lucene api. Most examples found with google show opendid authentication with Angular/Vue/React but not with simple javascript.

What's the best to do? 
1) Get the token while doing cshtml rendering on server side or use a JS oidc client?

**Comment by sebastienros** [comment] 2019-03-14 20:19
Cookie Auth works with GraphQL, is it because it doesn't follow the ApiController convention? 
Eventually we'll have mutations, should be forcibly disable cookie auth in this case? (I kind of know the answer already)

**Comment by carlwoodhouse** [comment] 2020-01-09 22:55
Could argue this is a dupe of #5247 too @sebastienros - though i think it's a valid question re: graphql and should we disable cookie auth for it but probably a separate issue

**Comment by Piedone** [comment] 2024-04-25 23:20
All APIs use the Api authentication scheme now.

**Closed by Piedone** 2024-04-25 23:20 UTC
