### ISSUE TITLE
No content when running as docker image

### ISSUE THREAD

**Issue by fenngineering** [OrchardCMS/OrchardCore#5762] opened 2020-03-20 13:16 UTC
So i have an issue where by when deploying my own docker image of OrchardCore the server starts fine see the below.

`Now listening on: http://[::]:80`
`info: Microsoft.Hosting.Lifetime[0]`
`      Application started. Press Ctrl+C to shut down.`
`info: Microsoft.Hosting.Lifetime[0]`
`      Hosting environment: Sandbox`
`info: Microsoft.Hosting.Lifetime[0]`
      `Content root path: /app` 

However when I access the site I get no content at all, and running within Insomnia I see the below:-
`> GET / HTTP/1.1`
`> Host: mysite.co.uk`
`> User-Agent: insomnia/7.1.1`
`> Accept: */*`

`< HTTP/1.1 200 OK
`< Server: nginx/1.17.8`
`< Date: Fri, 20 Mar 2020 12:04:21 GMT
`< Content-Length: 0`
`< Connection: keep-alive`
`< X-Powered-By: OrchardCore`
`< Strict-Transport-Security: max-age=15724800; includeSubDomains`

I know that the service is being hit but why would there be no content?

I know the database is configured correctly as the site builds\runs fine through visual studio and docker etc i was able to run the setup for 2 tenants i'm able to add content to both tenants and i can see the data being created in the mysql instance.

This is my setup:-
- kubernetes cluster 
- one pod & service for the app
- one pod & service for mysql
- ingress-nginx configured and working

Are there special settings for the ingress-nginx that are required for OrchardCore, which i could possibly be missing?

Hope someone can help me out.

**Comment by vitalybrandes** [comment] 2020-03-20 20:49
@fenngineering  I have no idea how to help u with ur question, but I am new to kubernates and plannig to build exactly the same scenario of infrastracture. Can you share with me ur yaml file of k8 for the start point?

**Comment by fenngineering** [comment] 2020-03-20 21:55
So i have an issue where by when running a pod with OrchardCore (Asp.net Core 3.1) installed running on port 80, so the server\pod starts fine see the below when deployed.
`Now listening on: http://[::]:80`
`info: Microsoft.Hosting.Lifetime[0]`
`Application started. Press Ctrl+C to shut down.`
`info: Microsoft.Hosting.Lifetime[0]`
`Hosting environment: Sandbox`
`info: Microsoft.Hosting.Lifetime[0`
`Content root path: /app`
I have a service and ingress deployed as below:-
`metadata:`
`  name: fennasprem-service`
`  namespace: default`
`  labels:`
`    app: fennasprem-service`
`  annotations`:
`    ngi`nx.ingress.kubernetes.io/proxy-read-timeout: '3600'
`spec:`
`  ports:`
`    - protocol: TCP`
`      port: 80`
`      targetPort: 80`
`  selector:`
`    app: fennasprem`
`---`
`kind: Ingress`
`apiVersion: extensions/v1beta1`
`metadata:`
`  name: fennasprem-ingress`
`  namespace: default`
`  annotations:`
`    cert-manager.io/cluster-issuer: letsencrypt-prod`
`    kubernetes.io/ingress.class: nginx`
`    kubernetes.io/tls-acme: 'true'`
`spec`:
`  tls:`
`    - hosts:`
`        - mysite.co.uk`
`        - mysite-ten1.co.uk`
`      secretName: letsencrypt-prod`
`  rules:`
`    - host: mysite.co.uk`
`      http:`
`        paths:`
`          - path: /`
`            backend:`
`              serviceName: fennasprem-service`
`              servicePort: 80`
`    - host: mysite-ten1.co.uk`
`      http:`
`        paths:`
`          - path: /`
`            backend:`
`              serviceName: fennasprem-service`
`              servicePort: 80`
I have ingress-ngnix deployed and running, this is the service spec and config map
`kind: Service`
`apiVersion: v1`
`metadata:`
`  name: ingress-nginx`
`  namespace: ingress-nginx`
`  labels:`
`    app.kubernetes.io/name: ingress-nginx`
`    app.kubernetes.io/part-of: ingress-nginx`
`spec:`
`  ports:`
`    - name: http`
`      protocol: TCP`
`      port: 80`
`      targetPort: 80`
`      nodePort: 31080`
`    - name: https`
`      protocol: TCP`
`      port: 443`
`      targetPort: 443`
`      nodePort: 31443`
`  selector:`
`    app.kubernetes.io/name: ingress-nginx`
`    app.kubernetes.io/part-of: ingress-nginx`
`  clusterIP: 10.96.40.80`
`  type: LoadBalancer`
`  sessionAffinity: None`
`  externalTrafficPolicy: Cluster`
`---`
`kind: ConfigMap`
`apiVersion: v1`
`metadata:`
`  name: nginx-configuration`
`  namespace: ingress-nginx`
`  labels:`
`    app.kubernetes.io/name: ingress-nginx`
`    app.kubernetes.io/part-of: ingress-nginx`
`data:`
`  client-header-buffer-size: 64k`
`  http2-max-field-size: 16k`
`  http2-max-header-size: 128k`
`  large-client-header-buffers: 8 64k`
`  proxy-buffer-size: 128k`
`  proxy-buffers: 4 256k`
`  proxy-busy-buffers-size: 256k`
`  proxy-hide-headers: Server`
`  server-tokens: 'False'`
`  use-forwarded-headers: 'true'`
`  use-forwarded-host-header: 'true'`
`  use-proxy-protocol: 'false'`
I have metallb running along in with letsencrypt issuing me certificates fine..
`kind: ConfigMap`
`apiVersion: v1`
`metadata:`
`  name: config`
`  namespace: metallb-systemdata:`
`  config: `
 `   address-pools:`
 `   - name: default`
 `     protocol: layer2`
 `     addresses:`
 `     - 192.168.0.100-192.168.0.120`
The ingress-gninx service is running in LoadBalancer mode so that metallb serves me an ip, and exposes the service on ports 80 and 443.
However when I access the site I get no content at all, and running within Insomnia I see the below:-
`* Preparing request to http://mysite.co.uk/`
`* Using libcurl/7.57.0-DEV OpenSSL/1.0.2o zlib/1.2.11 libssh2/1.7.0_DEV`
`* Current time is 2020-03-20T18:48:26.070Z`
`* Disable timeout`
`* Enable automatic URL encoding`
`* Enable SSL validation`
`* Enable cookie sending with jar of 0 cookies`
`* Connection 22 seems to be dead!`
`* Closing connection 22`
`* Connection 21 seems to be dead!`
`* Closing connection 21`
`*   Trying X.X.X.X...`
`* TCP_NODELAY set`
`* Connected to mysite.co.uk (X.X.X.X) port 80 (#23)`
`> GET / HTTP/1.1`
`> Host: mysite.co.uk`
`> User-Agent: insomnia/7.1.1`
`> Accept: */*`
`< HTTP/1.1 308 Permanent Redirect`
`< Date: Fri, 20 Mar 2020 18:48:25 GMT`
`< Content-Type: text/html`
`< Content-Length: 164`
`< Connection: keep-alive`
`< Location: https://mysite.co.uk/`
`* Ignoring the response-body`
`* Received 164 B chunk`
`* Connection #23 to host mysite.co.uk left intact`
`* Issue another request to this URL: 'https://mysite.co.uk/'`
`*   Trying X.X.X.X...`
`* TCP_NODELAY set`
`* Connected to mysite.co.uk (X.X.X.X) port 443 (#24)`
`* ALPN, offering http/1.1`
`* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH`
`* successfully set certificate verify locations:`
`*   CAfile: C:\Users\afenn\AppData\Local\Temp\insomnia_7.1.1\2017-09-20.pem`
`*   CApath: none`
`* TLSv1.2 (OUT), TLS header, Certificate Status (22):`
`* TLSv1.2 (OUT), TLS handshake, Client hello (1):`
`* TLSv1.2 (IN), TLS handshake, Server hello (2):`
`* TLSv1.2 (IN), TLS handshake, Certificate (11):`
`* TLSv1.2 (IN), TLS handshake, Server key exchange (12):`
`* TLSv1.2 (IN), TLS handshake, Server finished (14):`
`* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):`
`* TLSv1.2 (OUT), TLS change cipher, Client hello (1):`
`* TLSv1.2 (OUT), TLS handshake, Finished (20):`
`* TLSv1.2 (IN), TLS change cipher, Client hello (1):`
`* TLSv1.2 (IN), TLS handshake, Finished (20):`
`* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256`
`* ALPN, server accepted to use http/1.1`
`* Server certificate:`
`*  subject: CN=mysite.co.uk`
`*  start date: Mar 18 19:56:12 2020 GMT`
`*  expire date: Jun 16 19:56:12 2020 GMT`
`*  subjectAltName: host "mysite.co.uk" matched cert's "mysite.co.uk"`
`*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3`
`*  SSL certificate verify ok.`
`> GET / HTTP/1.1`
`> Host: mysite.co.uk`
`> User-Agent: insomnia/7.1.1`
`> Accept: */*`
`< HTTP/1.1 200 OK`
`< Date: Fri, 20 Mar 2020 18:48:25 GMT`
`< Content-Length: 0`
`< Connection: keep-alive`
`< X-Powered-By: OrchardCore`
`< Strict-Transport-Security: max-age=15724800; includeSubDomains`
`* Connection #24 to host mysite.co.uk left intact`
As you can see there is no content coming from the service and ingress-ngnix shows this in the logs:-
`10.244.1.1 - - [20/Mar/2020:18:53:15 +0000] "GET / HTTP/1.1" 308 164 "-" "insomnia/7.1.1" 83 0.000 [default-fennasprem-service-80] [] - - - - f0457c519f0099ffff47afcc4053ea95`
`127.0.0.1 - - [20/Mar/2020:18:53:15 +0000] "GET / HTTP/1.1" 200 0 "-" "insomnia/7.1.1" 83 0.006 [default-fennasprem-service-80] [] 10.244.2.90:80 0 0.008 200 0cdcf676f5c3f9f1ea692b6ee4f25262`
I know that the service is being hit as i see "< X-Powered-By: OrchardCore" in the headers, I also see that the certs have been successfully issued but why would there be no content?
Hope someone can help me out, been scratching my head for a few days wondering whats going on....
Just to note this is an on-premise setup, no cloud providers configured.

**Comment by hishamco** [comment] 2020-03-22 07:54
This duplicate of #5771

**Closed by hishamco** 2020-03-22 07:54 UTC
Labels: duplicate
