### ISSUE TITLE
Exception on Editing Page Content in Admin module-  Shape type 'ShortcodeModal' not found

### ISSUE THREAD

**Issue by VJC-NTT** [OrchardCMS/OrchardCore#6981] opened 2020-08-28 15:11 UTC
I am on rc214210. When I try to get to the admin console and edit the page, I get the exception  - Internal Server Error

An unhandled exception occurred while processing the request.
Exception: Shape type 'ShortcodeModal' not found

![image](https://user-images.githubusercontent.com/68251424/91582613-ab8dbf80-e915-11ea-910e-b7048cf2940a.png)

This last worked in rc054 and there after this exception started showing up. Am I missing any reference? Please advise. Below is the log file attached

![image](https://user-images.githubusercontent.com/68251424/91583463-e17f7380-e916-11ea-9eec-06d40bcc9c32.png)

[orchard-log-2020-08-28.log](https://github.com/OrchardCMS/OrchardCore/files/5142788/orchard-log-2020-08-28.log)

**Comment by deanmarcussen** [comment] 2020-08-28 15:35
Please reenable the feature again

Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/6925

**Closed by deanmarcussen** 2020-08-28 15:35 UTC
