### ISSUE TITLE
After zooming the dashboard interface, "" user, logout "" disappeared. Is this design? Did you miss it?

### ISSUE THREAD

**Issue by pgy866** [OrchardCMS/OrchardCore#5629] opened 2020-02-25 06:03 UTC
After zooming the dashboard interface, "" user, logout "" disappeared. Is this design? Did you miss it?

![截图录屏_选择区域_20200225132550](https://user-images.githubusercontent.com/28694676/75217950-96539f00-57d3-11ea-9d75-79a0ad715ca0.gif)
![截图录屏_google-chrome_20200225132627](https://user-images.githubusercontent.com/28694676/75217952-9784cc00-57d3-11ea-8bf1-b3fcbd3c40c7.jpg)
![Uploading 截图录屏_选择区域_20200225132643.jpg…]()

**Comment by Skrypt** [comment] 2020-02-25 06:28
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3964

**Closed by Skrypt** 2020-02-25 06:28 UTC

**Comment by pgy866** [comment] 2020-02-25 07:06
OOPS。。
cool
