### ISSUE TITLE
Lucene query: Return randomised content items

### ISSUE THREAD

**Issue by DannyT** [OrchardCMS/OrchardCore#7153] opened 2020-09-28 14:14 UTC
Is it possible to execute a query that returns a randomised, limited result set from matching criteria?

Say for example, I had 10 blog posts flagged as `featured : true` but only wanted to present 3 of those at random. Is this something that can be configured in the lucene query?

**Comment by Skrypt** [comment] 2020-09-28 20:43
There is a PR here that sorta does a random : https://github.com/OrchardCMS/OrchardCore/pull/6918
Maybe it could work for you. We decided to keep the PR on hold because we can achieve this a better way.
Though if you need this, that PR will do a random on every records retrieved by a Lucene Query.
I did not try if it will work with a `sort column DESC` at the same time though. The PR is there to test it.

**Comment by hishamco** [comment] 2020-09-28 21:14
@Skrypt is the sort done after retrieving the data?

**Comment by Skrypt** [comment] 2020-09-28 22:30
It's done inside the Lucene Query

**Comment by DannyT** [comment] 2020-09-30 04:55
Thanks @Skrypt, looks like what I'm after but I'm not in a position to use a custom build at the moment so I'll wait for this to hit the main branch. Consider this a +1 for that feature though!

**Comment by sebastienros** [comment] 2020-10-01 17:36
Duplicate of #6916

**Closed by sebastienros** 2020-10-01 17:36 UTC

**Comment by aminmohammadi05** [comment] 2022-10-29 07:20
> Is it possible to execute a query that returns a randomised, limited result set from matching criteria?
> 
> Say for example, I had 10 blog posts flagged as `featured : true` but only wanted to present 3 of those at random. Is this something that can be configured in the lucene query?

Could you find a solution for this problem? I have the same problem.
