### ISSUE TITLE
Taxonomy Terms Management is broken

### ISSUE THREAD

**Issue by urbanit** [OrchardCMS/OrchardCore#15590] opened 2024-03-25 22:46 UTC
### Describe the bug
Terms in a Taxonomy cannot be deleted and hierarchy cannot be created

### To Reproduce
1. Create a new site with Blog Recipe
2. Go To Category Taxonomy
3. Add a new term
4. Publish
5. Try to delete a term
6. A notification that term is deleted appears but term is still there

### Expected behavior
Terms Management should include Term Deletion, Add Child Term, Move Term as Child

**Comment by urbanit** [comment] 2024-03-25 22:46
It works on 1.8.2, broken on main branch

**Comment by Piedone** [comment] 2024-03-26 00:36
Can you share the logs? I'd guess it has something to do with the Json.NET migration.

**Comment by urbanit** [comment] 2024-03-26 09:22
For deleting term no logs are created :-(
For hierarchy, see attached...
[orchard-log-2024-03-26.log](https://github.com/OrchardCMS/OrchardCore/files/14755834/orchard-log-2024-03-26.log)

Full reproduction here: https://app.screencastify.com/v3/watch/g2Pv1BYQThXnZR3EoTsV

**Comment by MikeAlhayek** [comment] 2024-03-26 18:09
Did you try it out using the latest commit on main? I think there was an issue with STJ where remove was broken but should be fixed. Can you please confirm that the issue exists even after pulling the latest from main?

**Comment by urbanit** [comment] 2024-03-26 22:27
Exactly the same behavior... No deletion, no hierarchy, no child term addition
![image](https://github.com/OrchardCMS/OrchardCore/assets/1871551/e4eb0fda-00d8-459e-93c9-661d38707fc5)

**Comment by MikeAlhayek** [comment] 2024-03-27 02:00
Guessing this is where it fails

https://github.com/OrchardCMS/OrchardCore/blob/4d892b6f49d4340c4ecbe4630d3e9ac4fba61acb/src/OrchardCore.Modules/OrchardCore.Taxonomies/Controllers/AdminController.cs#L324

**Comment by hishamco** [comment] 2024-03-27 02:18
I think we need to fix the remove issue as we did in the admin menu

@hyzx86 @sarahelsaig I think you did a PR to fix this everywhere, right?

**Comment by hishamco** [comment] 2024-03-27 02:23
@hyzx86 this PP #15509 should fix the issue, right? or Shall I did a similar fix to the admin menu

**Comment by hyzx86** [comment] 2024-03-27 02:37
@hishamco , No，The PR #15509 just and some method ， 
looking at the logs, it looks like the problem is with the JNode class,
PR https://github.com/OrchardCMS/OrchardCore/pull/15524 was update the JNode  class,
@sarahelsaig  can you  take a look ？

**Comment by hishamco** [comment] 2024-03-27 02:46
Shall I do a similar fix to what I did in the admin menu?

**Comment by hyzx86** [comment] 2024-03-27 04:31
Perhaps we can tweak the implementation of remove to be compatible with older api actions

**Closed** 2024-03-28 18:26 UTC
Labels: bug :bug:
