### ISSUE TITLE
Shape "Menu" and "BreadcrumbMenu" are rendered as a "ContentCulturePicker"

### ISSUE THREAD

**Issue by jagbarcelo** [OrchardCMS/OrchardCore#8948] opened 2021-03-23 08:39 UTC
We have a site running OC 1.0.0-rc2-15878 with tree different shapes (`Menu`, `BreadcrumbMenu` and `ContentCulturePicker`) which work perfectly on production. Here's a screnshot:

![image](https://user-images.githubusercontent.com/6704109/112114721-aa292a80-8bb8-11eb-8bfe-b8a737846b1f.png)

You can see the `Menu` at the right of the company logo, the `ContentCulturePicker` at the right-top side and the `BreadcrumbMenu` at the bottom of the header (the rest of the page is not shown).

Now we are trying to update OC to yesterday's release 1.0.0-rc2-16003 and here are the results (in development machine/debug):

![image](https://user-images.githubusercontent.com/6704109/112115144-26bc0900-8bb9-11eb-8f33-b8b226538be3.png)

We end up having 3 ContentCulturePicker but only one is correct. The other two are wrongly rendered from a `Menu` shape (that has not been modified) and a `BreadcrumbMenu` shape (that has not been modified either).

The important part of the `Layout.liquid` file is as follows:

```
<div class="culture-wrapper">
        <div class="culture-picker">
            {% shape "ContentCulturePicker" %}
        </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
        <div class="container">
            {% assign locale_homepage = '~/' | append: twoLetterISOLanguageName %}            
            <a class="js-scroll-trigger ahed-logo" href="{{ locale_homepage | href }}">
              {{ "Home" | t }}
            </a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu <svg style="height:1em" aria-hidden="true" focusable="false" data-prefix="fas" data-icon="bars" class="svg-inline--fa fa-bars fa-w-14" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"></path></svg>
            </button>
            {% assign locale_menu_name = 'main-menu-' | append: twoLetterISOLanguageName %}
            {% assign alias_locale_menu_name = 'alias:' | append: locale_menu_name %}
            {% shape "Menu", alias: alias_locale_menu_name, cache_id: locale_menu_name, cache_tag: locale_menu_name %}
        </div>
    </nav>
    <div{% render_section "MainDivTagAttrs", required: false %}>
        {% render_section "Header", required: false %}
        <div class="container" id="main">
            {% shape "BreadcrumbMenu" %}
            {% render_section "Messages", required: false %}
            {% render_section "Content" %}
        </div>
        {% render_section "Footer", required: false %}
        {% resources type: "FootScript" %}
    </div>
```

The complete `Menu.liquid` file is quite simple:

```
<div class="collapse navbar-collapse" id="navbarResponsive">
  <ul class="navbar-nav text-uppercase mr-auto">
    {% for item in Model.Items %}
      {{ item | shape_render }}
    {% endfor %}
  </ul>
</div>
```

But it is not properly rendered as it was with 1.0.0-rc2-15878. Any ideas why? Had there been any changes in the last month (more or less) that could explain this behaviour?

PS: The `BreadcrumMenu.cshtml` file is far more long and complex. Hence, it is probably easier to fix this issue for the `Menu` shape first, since the other one might be related too.

Thanks.

**Comment by hishamco** [comment] 2021-03-23 20:59
@jtkech when I saw the culture dropdown twice I remembered a recent issue in blog title in the admin site, which you worked on

**Comment by jtkech** [comment] 2021-03-23 21:16
About the blog title rendered twice it is "normal" one is the Title of the admin page, the other is the title of the blog rendered in the DetailAdmin display type, so it's just because the same text and size are rendered twice.

So i think it is not related

Here, at least i will try to render a culture picker shape under liquid

**Comment by hishamco** [comment] 2021-03-23 21:20
> So i think it is not related

I see ..

> We end up having 3 ContentCulturePicker but only one is correct

@jagbarcelo why you add three CCP?

**Comment by jagbarcelo** [comment] 2021-03-23 21:24
There are only one  `{% shape "ContentCulturePicker" %}`, one `{% shape "Menu", alias: ... %}` and one `{% shape "BreadcrumbMenu" %}`. However (see the second image) the latter two shapes end being rendered as if they were CCPs. That's the weird issue.

**Comment by jtkech** [comment] 2021-03-23 21:34
Just tried `{% shape "ContentCulturePicker" %}`, it is not rendered twice

But just for info because i trust you ;)

**Comment by jtkech** [comment] 2021-03-23 22:50
@jagbarcelo 

Just saw some little problems, i will work on it soon

**Comment by jtkech** [comment] 2021-03-24 00:49
Okay i can repro when i put the picker shape before the menu shape

The picker is rendered twice, the menu is not rendered

I saw where the issue is, will be fixed soon

![ShapeTag](https://user-images.githubusercontent.com/8586360/112236627-367f3000-8c41-11eb-92da-466fcbc33d7c.png)

@sebastienros 

If we use `{% shape "Type1" %}` then `{% shape "Type2" %}` the same `ShapeTag` instance will be always used and the `Type` property is not updated, so the first one wins and is rendered twice. I can easily fix the `Type` update but it is not thread safe as the same instance is always used. So, as already done for the `contentitem` tag we would need to create a `menu` tag, a `content_culture_picker` tag and so on, then to replace the usage by e.g.

    {% shape "menu" ... %} => {% menu ... %}

**Closed** 2021-03-24 02:14 UTC
Labels: bug
