### ISSUE TITLE
OrchardCMS beta2 workflow implementation- Destination url is unreachable

### ISSUE THREAD

**Issue by devanathan2017** [OrchardCMS/OrchardCore#1701] opened 2018-04-23 10:25 UTC
Hi,
Created the HttpRequestEvent in the local host with the below and the event got triggered and working fine.
![image](https://user-images.githubusercontent.com/34333687/39120072-1b272dcc-470b-11e8-9be7-06d44e1746b0.png)

The application is hosted and able to see the same url values but the event is not triggering. Getting the error "Destination url is unreachable" the only change between these two are below
http://localhost:2502.
http://somedomain.cloud
  So the generated http get request is for that particular host and port? in this case local host and cannot be triggered by the other site! . Correct me if i am wrong.

![image](https://user-images.githubusercontent.com/34333687/39120623-91011d2c-470c-11e8-9026-0c6dbbf7a2fc.png)

**Comment by sfmskywalker** [comment] 2018-04-23 10:50
The generated URL does not "hardcode" the base URL, so it should theoretically just work. I'll have a look and will let you know what I find.

**Comment by sfmskywalker** [comment] 2018-04-23 12:25
I can't seem to reproduce the issue. Please provide detailed repro steps.

**Comment by sfmskywalker** [comment] 2018-04-24 20:44
Closing, but feel free to reopen if you have any repro steps.

**Closed by sfmskywalker** 2018-04-24 20:44 UTC

**Comment by Vikas-C** [comment] 2018-05-02 07:06
@sfmskywalker @devanathan2017  Devnathan and I are working on this implementation together. Here's what we could find. The issue seems to be that orchard isn't able to resolve a route with the url mentioned. The request to the url gives a 404 since there doesn't seem to be any definition for it. Which is strange.. since when we do generate it at first, it is able to get to it. Not sure what's happening to it at a later stage.

**Comment by sfmskywalker** [comment] 2018-05-02 09:59
Perhaps it's an issue with the security token service that for some reason isn't able to parse the provided SAS token. You can try it out by commenting out the following in `HttpWorkflowController`:

![image](https://user-images.githubusercontent.com/938393/39517374-f618da3e-4dff-11e8-80f0-5116049df538.png)

The `securityTokenService` uses the `ITimeLimitedDataProtector`. I don;t know if that thing relies on machine keys or anything, and whether your environment is multi-node or not, but check if it's the SAS decryption that is failing or not.

**Comment by sfmskywalker** [comment] 2018-05-02 09:59
I just noticed the logging statement - perhaps check the log files first to see if that "Invalid SAS token provided" is there.

**Comment by Vikas-C** [comment] 2018-05-02 11:27
@sfmskywalker yes it was infact the `_securityTokenService.TryDecryptToken` which was throwing the error. I believe that the time elapsed also could be a reason for the failure to decrypt. Since the `ITimeLimitedDataProtector` is being used, is there a way to set the time until which the url would be active/available?

**Comment by Vikas-C** [comment] 2018-05-02 11:47
Also, if the keys are dependent on the machine, I suppose it would affect the flow if we all use the same db during development.

**Comment by sfmskywalker** [comment] 2018-05-02 16:16
> Also, if the keys are dependent on the machine, I suppose it would affect the flow if we all use the same db during development.

Depending on where the encryption/decryption key is stored, I can imagine that if the SAS token is generated on one machine, decrypting it on another one will fail - unless the same key is used.

This article should help: https://docs.microsoft.com/en-us/aspnet/core/security/data-protection/configuration/overview?view=aspnetcore-2.1&tabs=aspnetcore2x

> When the Data Protection system is initialized, it applies default settings based on the operational environment. These settings are generally appropriate for apps running on a single machine. There are cases where a developer may want to change the default settings:

> The app is spread across multiple machines.
> For compliance reasons.

**Comment by sfmskywalker** [comment] 2018-05-02 16:19
> Since the ITimeLimitedDataProtector is being used, is there a way to set the time until which the url would be active/available?

Perhaps the `HttpRequestEvent` should be changed to:

* Allow the user to chose the type of data protection
* When time-limited data protection is selected, the user should be able to specify a lifetime (time span)

@sebastienros Thoughts?

**Comment by sebastienros** [comment] 2018-05-02 16:38
The delay could be configurable, be it should be opt-in such that the default is still time limited. And use a big delay instead of no delay at all (for simplification of implementation).

But the main issue here is the key ring, which is set to be unique per tenant. I would suggest that you create a custom DataProtector implementation that stores the key in the database in this case, this is what we have in mind when it was designed. Or to configure App_data to be on a shared drive, which is already implemented by using the `ORCHARD_APP_DATA` environment variable. see https://github.com/OrchardCMS/OrchardCore/blob/f21331698a6c670d470fc5f4d60a7ae167a24c86/src/OrchardCore/OrchardCore.Environment.Shell/ShellOptionsSetup.cs#L26

**Comment by sfmskywalker** [comment] 2018-05-02 17:00
Makes sense. I created an issue for the configurable delay here: #1753.

With regards to the custom DataProtector, should this be a gallery module, or does it make sense for such an implementation to be available as an optional feature shipped with OC?

**Comment by sebastienros** [comment] 2018-05-02 17:03
We can have it in Core, but maybe it's not possible (chicken and egg issue), I don't recall, I had this conversation with @PinpointTownes who will obviously remember/know.

**Comment by PinpointTownes** [comment] 2018-05-02 17:40
It's definitely possible to have a dedicated module that stores the DP key ring in the database (or in Azure Blob Storage or in Amazon S3 or anywhere else).

It's not complicated to implement as you basically have to create a custom `IXmlRepository`, it's just time that needs to be spent (@sebastienros you should ask your boss to fund us so we can all work full time on OrchardCore :trollface:)

Another option would be to make registering "tenant services" from `Startup.cs` much easier, so that folks can use third-party packages (e.g https://github.com/hotchkj/AspNetCore.DataProtection.Aws) without having to write their own modules.

```csharp
services.AddOrchardCore()
    .AddModules(options =>
    {
        options.RegisterTenantServices(collection =>
            collection.AddDataProtection()
                .SetApplicationName("my-application-name")
                .PersistKeysToAwsS3(Configuration.GetSection("myS3XmlStorageConfiguration")));
    });
```

**Comment by sebastienros** [comment] 2018-05-02 17:47
https://github.com/OrchardCMS/OrchardCore/issues/1755

**Comment by Vikas-C** [comment] 2018-05-04 11:26
One quick point we wanted to ask here. Is it possible, with the current version of workflow, to have the tasks be part of other modules? And show up based on whether that module is enabled or not?

**Comment by sfmskywalker** [comment] 2018-05-05 06:29
Yes, there is a card on the backlog to display a trail of executed activities and any exceptions that might have occurred. I hadn’t thought of highlighting the faulting activity though, might be a good idea. I am also considering to highlight the traveled path, but need to convince @sebastienros that we want it ;)
