### ISSUE TITLE
Edit Content Part, Add New Field, Kills GraphQL

### ISSUE THREAD

**Issue by kef7** [OrchardCMS/OrchardCore#5536] opened 2020-02-12 22:11 UTC
Adding "OpenInNewWindow" Bool field to LinkMenuItemPart from Orchard Core Admin breaks GraphQL. (I believe the content part definition for LinkMenuItemPart came from The Agency theme.)

- Accessing /api/graphql gives 400 Bad Request

- GraphQL admin area shows "No Schema" message; can't execute queries

- IIS error in Windows Event Log: 
Category: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware
EventId: 1
RequestId: 80000d14-0400-f900-b63f-84710c7967bb
RequestPath: /api/graphql
SpanId: |c69cdb0c-44c6865f99a2049c.
TraceId: c69cdb0c-44c6865f99a2049c
ParentId: 

An unhandled exception has occurred while executing the request.

Exception: 
System.ArgumentOutOfRangeException: A field with the name: linkMenuItem is already registered for GraphType: LinkMenuItem (Parameter 'Name')
   at GraphQL.Types.ComplexGraphType`1.AddField(FieldType fieldType)
   at OrchardCore.ContentManagement.GraphQL.Queries.Types.DynamicContentTypeBuilder.Build(FieldType contentQuery, ContentTypeDefinition contentTypeDefinition, ContentItemType contentItemType) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.GraphQL\Queries\Types\DynamicContentTypeBuilder.cs:line 65
   at OrchardCore.ContentManagement.GraphQL.Queries.ContentTypeQuery.BuildAsync(ISchema schema) in C:\projects\orchardcore\src\OrchardCore\OrchardCore.ContentManagement.GraphQL\Queries\ContentTypeQuery.cs:line 63
   at OrchardCore.Apis.GraphQL.Services.SchemaService.GetSchemaAsync() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\Services\SchemaService.cs:line 56
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.ExecuteAsync(HttpContext context, ISchemaFactory schemaService) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\GraphQLMiddleware.cs:line 79
   at OrchardCore.Apis.GraphQL.GraphQLMiddleware.Invoke(HttpContext context, IAuthorizationService authorizationService, IAuthenticationService authenticationService, ISchemaFactory schemaService) in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Apis.GraphQL\GraphQLMiddleware.cs:line 70
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext() in C:\projects\orchardcore\src\OrchardCore.Modules\OrchardCore.Diagnostics\DiagnosticsStartupFilter.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

Fixed by removing the added ContentPartFieldDefinitonRecord from the LinkMenuItemPart item under ContentPartDefinitionRecords in file ContentDefinition.json. It's possible there are in fact two definitions for LinkMenuItemPart and they are conflicting; not sure how to check this accurately.

**Comment by jtkech** [comment] 2020-02-13 01:48
Okay, i can repro, i will dig into it asap

**Comment by jtkech** [comment] 2020-02-13 02:49
So, it doesn't happen if you add a field to a content type, but it happens for any field that you add dynamically to any part.

I think it is because of `DynamicContentTypeBuilder` that allows to take into account a part that you create dynamically through the admin but also **when you add a field to an existing part**.

I'm working on it

**Comment by jtkech** [comment] 2020-02-13 04:59
@carlwoodhouse or another GraphQL expert

So, if we add a field to an existing part (e.g a `TextField` to the `HtmlBodyPart`) that is used in a content type, we get the above issue saying that the GraphQL element is already registered. This because in `DynamicContentTypeBuilder` the related element is already registered by `TypedContentTypeBuilder`.

So, in this case i thought about forcing the collapsing of fields, so just to show what i needed to prevent it from failing, in `DynamicContentTypeBuilder` i added for testing the following check

                var test = contentItemType.GetField(partName.ToFieldName());

                if (_contentOptions.ShouldCollapse(part) || test != null)
                {
                     ... 

I also noticed that in both builders we check

                // Check if another builder has already added a field for this part.
                if (contentItemType.HasField(partName)) continue; // Never true

Just for confirmation because it is never true, should we use `partName.ToFieldName()` as used for registering? Notice that if i use `partName.ToFieldName()` it doesn't fail because the `HtmlBody` is not registered twice but then the `TextField` that has been added dynamically is not resolved.

**Comment by carlwoodhouse** [comment] 2020-02-13 09:49
heh, for sure that check is wrong ... but probably what we should be doing is checking if it has the field already, if it does then just add the dynamic fields to the existing field.

**Comment by carlwoodhouse** [comment] 2020-02-13 10:53
if you don't have time to work on it @jtkech i can take it if you like

**Comment by jtkech** [comment] 2020-02-14 04:51
@carlwoodhouse

Yes thanks, it was just to show my findings but you are better placed to fix it in the right way

**Comment by Fermain** [comment] 2020-05-19 18:24
@carlwoodhouse Have you made any headway with this?

**Comment by carlwoodhouse** [comment] 2020-05-19 18:29
I looked into it a bit but I need to pick it back up.

There’s an easy fix (as suggested here; the check for did I already build
this part in another  builder is checking the wrong case of the field name;
so it re-adds it; this is technically what breaks it ..) so the simplest
fix is to check the right case.

But this isn’t actually ideal; as you’d never be able to mix types and
dynamic parts; you’d only ever get the typed definition .. so we actually
need to merge them.

I’ll try take a proper look on Friday when I have some time.

Carl.

**Comment by hyzx86** [comment] 2020-06-19 09:07
![image](https://user-images.githubusercontent.com/15613121/85116070-510a2000-b24f-11ea-9fba-6baa2e56831f.png)

**Comment by hyzx86** [comment] 2020-06-26 13:04
I have created a pull request  , https://github.com/OrchardCMS/OrchardCore/pull/6477

**Comment by agriffard** [comment] 2020-08-13 09:59
Has it been fixed by #6536 ?

**Comment by carlwoodhouse** [comment] 2020-08-13 17:35
Not as far as I can see Antoine

**Comment by agriffard** [comment] 2021-01-28 21:47
@carlwoodhouse Can you see a way to fix the issue?

**Comment by carlwoodhouse** [comment] 2021-01-28 21:52
Will try and pick it up / been manic at work; the issue is when a dynamic
field name clashes with a static one; it’s supposed to ignore the static
one but the case is wrong; that’s not a great fix though ... really we need
to add them with unique names or so

**Closed** 2021-02-26 16:57 UTC
Labels: GraphQL, P1
