### ISSUE TITLE
Taxonomy terms drag and drop doesnt work

### ISSUE THREAD

**Issue by giannik** [OrchardCMS/OrchardCore#10755] opened 2021-11-25 12:05 UTC
When trying a new instance using the blog recipe : 
  --From the admin go to **Categories** taxonomy and add a new term. 
  -- Try to drag and  drop terms in the UI . It doesnt work. 
  -- Javascript error  occurs  : Uncaught TypeError: Cannot read properties of undefined (reading 'vertical')

**Comment by Skrypt** [comment] 2021-11-25 15:54
JQuery UI version update that created this regression. Known issue, thanks for reporting.

**Comment by hishamco** [comment] 2021-11-30 08:22
I think there's another opened issue reporting the same thing

**Comment by sebastienros** [comment] 2021-12-02 18:36
https://github.com/OrchardCMS/OrchardCore/issues/10642

**Comment by scleaver** [comment] 2021-12-03 02:40
This seems to be fixed in the latest version.

**Closed** 2021-12-03 19:40 UTC
