### ISSUE TITLE
Order Liquid Query by field

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5088] opened 2019-12-19 20:11 UTC
i added a new field "ordershow " to set a number of order blogs. how can i use this field in a query?

i checked the index otion and i have this field when i run the query: "Blog.ordershow" 
 

```
{
  "query": {
    "term" : { "Content.ContentItem.ContentType" : "Blog" } 
  },
  "sort": { "Content.ContentItem.Blog.ordershow": { "order": "asc" } } ,
  "size": 3
}
 
```

**Comment by sebastienros** [comment] 2019-12-19 20:31
For @Skrypt

**Comment by Skrypt** [comment] 2019-12-19 20:32
Related https://github.com/OrchardCMS/OrchardCore/issues/3278

**Comment by Skrypt** [comment] 2019-12-22 03:02
```
{
  "query": {
    "term": {
      "Content.ContentItem.ContentType": "Blog"
    }
  },
  "sort": {
    "Content.ContentItem.Blog.ordershow": {
      "order": "asc",
      "type": "double"
    }
  },
  "size": 3
}
```

We are missing documentation on how to select the proper type on a sort query.
I'm closing as this is a duplicate of #3278

**Closed by Skrypt** 2019-12-22 03:02 UTC
Labels: Orchard.Lucene, documentation
