### ISSUE TITLE
Per content item permissions - Add users

### ISSUE THREAD

**Issue by JoshTango** [OrchardCMS/OrchardCore#8642] opened 2021-02-20 20:01 UTC
I want the ability for the author of a content item to have the ability to pick users that may edit the content item or some other permission.

I imagine a User Permissions Part which could be added.  This Part would not be a content Part as its not content which is displayed.   Then it would have a user picker.  Then for each user I could decide their role or permissions over the content item.

Maybe a user picker is not desirable if you don't want each author to see all the other usernames.  Maybe they type a name into a textbox manually.

**Comment by deanmarcussen** [comment] 2021-02-22 19:16
Custom `AuthorizationHandler` combined with the `UserPickerField`

Auth handler evaluates if the user picker field exists, with the name, and then checks the permission request, and fails it if it does not meet.

I'm not sure we would want to put this into Orchard Core directly. The usage is always quite custom in my experience, and hard to achieve something like this, that is universal enough for everyone.

**Comment by Piedone** [comment] 2021-08-15 20:46
Per-user access control (as opposed to role/group-based) are generally advised against. Instead, we could have role-based content item permissions: https://github.com/OrchardCMS/OrchardCore/issues/5925

**Comment by sebastienros** [comment] 2021-08-19 17:42
Issue is valid, but using roles like @Piedone is suggesting.

**Comment by Piedone** [comment] 2021-08-19 18:01
Do you agree that this is a duplicate of #5925 @JoshTango, then?

**Comment by JoshTango** [comment] 2021-08-19 18:13
Well we don't have channels working yet or planed I don't think.
The idea is that you would give permissions to certain people to edit the content or create the content such as employees but only you would be the one who could approve it for publishing.

**Comment by Piedone** [comment] 2021-08-19 18:16
What do you mean by channels?

What you described is covered by content item permissions, as envisioned under the linked issue.

**Comment by JoshTango** [comment] 2021-08-19 18:39
YouTube ahs channels which allow given others users different permission I believe.

**Comment by Piedone** [comment] 2021-08-23 12:34
I'm not aware of how YouTube channels affect permissions. Are you referring to the feature that you can show a different channel intro video based on whether the user is a subscriber already or not? Something like this is again covered by role-based content item permissions.

It seems to me #5925 covers this use-case completely. If there's something missing, please add details there.

**Closed by Piedone** 2021-08-23 12:34 UTC
Labels: enhancement
