### ISSUE TITLE
Insert Media will insert into all open Trumbowyg editors

### ISSUE THREAD

**Issue by Piedone** [OrchardCMS/OrchardCore#6436] opened 2020-06-15 23:10 UTC
1. Set up site with the Blog recipe.
2. Change the Raw Html Widget's Html Field to use the Trumbowyg editor.
3. Add two Raw Html widgets to a Page.
4. Insert Media (any image provided by the recipe) to one of the open editors. So far so good.
5. Insert different Media into the other editor. Now both editors have the same `[image]` tags, i.e. the tags were overridden in both editors.
6. Repeated Media insertion will also overwrite tags in the other editor.

Repro (only managed to insert the first image on the second try :)):
![Media insert bug](https://user-images.githubusercontent.com/1976647/84714436-efeffd00-af6d-11ea-800c-59b792466bc8.gif)

**Comment by agriffard** [comment] 2020-06-21 08:45
Duplicate of #6137 
See PR #6167

**Closed by agriffard** 2020-06-21 08:45 UTC
