### ISSUE TITLE
PR #14290 breaks metadata on RazorViewCompiledItem

### ISSUE THREAD

**Issue by ShaneCourtrille** [OrchardCMS/OrchardCore#14341] opened 2023-09-15 16:24 UTC
@jtkech 
I left a comment on PR #14290 showing where the problem is but I'm not 100% sure you'll see that since the PR is already closed. It's just missing a _metadata = metadata; line.

**Comment by jtkech** [comment] 2023-09-15 19:40
@ShaneCourtrille Yes I saw it and answered, thanks for looking at it.

> It's a copy of the aspnetcore internal `DefaultRazorViewCompiledItem` whose ctor doesn't have a metadata parameter, the Metadata property being auto built if null from assembly attributes.

But you may be right, maybe better to keep this ctor parameter.

**Comment by MikeAlhayek** [comment] 2023-12-22 15:24
@jtkech @ShaneCourtrille this is the only issue that is tagged with 1.8 milestone. The PR is closed but the issue is not. Is this still an issue or can we close it?

**Comment by sebastienros** [comment] 2024-01-04 18:11
@ShaneCourtrille do you mean that the change below should be applied?

Can you file an issue (if not this one) describing the problem, a repro, and why you think this is the fix? 

![image](https://github.com/OrchardCMS/OrchardCore/assets/1165805/ea365bf6-ea8e-428c-9472-72cc88a10b40)

**Closed** 2024-01-18 21:20 UTC
Labels: bug :bug:
