### ISSUE TITLE
Custom lucene index

### ISSUE THREAD

**Issue by awyl** [OrchardCMS/OrchardCore#1253] opened 2017-11-28 05:48 UTC
Need configuration in admin for Lucene indices.  Currently only allow creation with no customization.

Todo:
https://github.com/OrchardCMS/OrchardCore/blob/efe497b6d4ac38a607f87ac6b071a5ed582da145/src/OrchardCore.Modules/OrchardCore.Lucene/Handler/LuceneIndexingContentHandler.cs#L29

**Comment by sebastienros** [comment] 2017-11-30 20:21
I want to completely change how indices are created, by allowing custom logic to be defined to create a document, probably using some Javascript too on the documents, that would return a json object containing the data to index, and how to index it (store, tokenize, ...)

**Comment by sebastienros** [comment] 2018-02-21 01:39
Duplicate of #1485

More details in this discussion

**Closed by sebastienros** 2018-02-21 01:39 UTC
