### ISSUE TITLE
Does the query now support returning the total number of rows? 

### ISSUE THREAD

**Issue by hyzx86** [OrchardCMS/OrchardCore#6939] opened 2020-08-19 15:53 UTC
If not, I want to try implement this function, but I don’t know how to start .

**Comment by hyzx86** [comment] 2020-08-20 13:32
https://github.com/graphql-dotnet/graphql-dotnet/blob/master/src/GraphQL/Types/Relay/ConnectionType.cs

**Comment by sebastienros** [comment] 2020-08-27 18:07
We don't have that, and I am not sure we should provide it. Unless it takes "paging options" into account such that it can't "scan" the full content item table which can be expensive.

**Comment by carlwoodhouse** [comment] 2020-09-15 20:04
@sebastienros this is a potential duplicate of https://github.com/OrchardCMS/OrchardCore/issues/5693

**Comment by hyzx86** [comment] 2021-01-15 10:49
> We don't have that, and I am not sure we should provide it. Unless it takes "paging options" into account such that it can't "scan" the full content item table which can be expensive.

Hi @sebastienros  , I've written some code, but I haven't finished yet. I don't think the calculation of the total number of rows here will result in scanning the whole table

https://github.com/hyzx86/OrchardCore/blob/dfdc6d13f0bf1d018fdcf08d3ee1178073c249a4/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentItemsFieldType.cs#L105

We need to modify the return result of a resolve, which is similar to this:
```
{
 data:{
    totalcount:100 ,
    items:[
               contentItem1,
               contentItem2
             ]
   }
}
```
But the query results refer to many places. I don't know how to find them to modify  result,
Or is there another way to make all `contentItem` queries support the return total, such as creating a new query.

**Comment by carlwoodhouse** [comment] 2021-01-15 10:57
IMO if we want more powerful paging we should just implement connections;
this is the accepted standard in graphql.

Both the above and connections are fairly large breaking model changes
though; though with connections you could probably support both by just
having separate connection queries.

**Comment by hyzx86** [comment] 2021-01-15 14:52
I think this is a very important feature, even if it requires some disruptive updates.
I will be working full time on this feature for a while.
At that time, I hope you can provide some guidance and suggestions. Thank you！

**Comment by hyzx86** [comment] 2021-01-18 03:37
Hi ，There is a problem here. How can I get a `ConnectionType` from this instance object:`typeType `d ? 
https://github.com/hyzx86/OrchardCore/blob/d755c00fa7aaf4f602b80c717d18db46f42ccc31/src/OrchardCore/OrchardCore.ContentManagement.GraphQL/Queries/ContentTypeQuery.cs#L66

I see a similar problem here, but I don't understand how to operate it.
https://github.com/graphql-dotnet/graphql-dotnet/issues/393

**Comment by hyzx86** [comment] 2021-01-19 15:50
Hi guys, Is there have any execamlple?

**Comment by hyzx86** [comment] 2021-01-20 04:12
move to https://github.com/OrchardCMS/OrchardCore/discussions/8359

**Comment by hyzx86** [comment] 2021-04-09 04:40
https://github.com/OrchardCMS/OrchardCore/pull/4554

**Comment by Skrypt** [comment] 2021-04-09 18:20
Can implement for Lucene Queries. Can't be added for SQL Queries as it's equivalent to do a second query like : `SELECT COUNT(*) FROM TABLE`

**Comment by hyzx86** [comment] 2021-04-21 05:54
> Can implement for Lucene Queries has we return a TotalHits count. Can't be added for SQL Queries as it's equivalent to do a second query like : `SELECT COUNT(*) FROM TABLE`
Yes, that's a better implementation and doesn't affect existing functionality

**Comment by hyzx86** [comment] 2021-04-23 02:36
https://github.com/OrchardCMS/OrchardCore/pull/9259

**Comment by hyzx86** [comment] 2021-04-23 03:44
Although the API query method can do this, 

https://github.com/OrchardCMS/OrchardCore/pull/9259

I prefer to use GraphQL, because it returns cleaner results.

Can  it be achieved through a general schema? 

Classic way:
```
{
    "type": "ContentItem/BlogPost"
}
```
paged query 
```
{
    "type": "PagedResult/ContentItem/BlogPost"
}
```

**Comment by hyzx86** [comment] 2021-04-23 05:26
But ，I am not very familiar with GraphQL. . Can someone help me analyze how to implement it?

**Comment by hyzx86** [comment] 2021-04-25 16:11
@jtkech Could you help me ?

**Comment by jtkech** [comment] 2021-04-26 00:53
@hyzx86

Sorry, not so familiar about this too ;)

@carlwoodhouse is the expert in this area

**Comment by carlwoodhouse** [comment] 2021-04-26 10:07
i think we need @Skrypt if we're specifically talking about the lucene implementation (ive never actually touched it ;p). I do still think we should be thinking about a general approach using graphql connections though as this is the expected/standard way of doing paging in graphql; rather then just rolling our own by tacking on a field that actually doesnt describe the graph object been returned, https://github.com/graphql-dotnet/relay

**Comment by Skrypt** [comment] 2021-11-02 10:06
When you execute a Query it now returns an `IQueryResults` which can be typed as a `LuceneQueryResults` which will return a `Count`. So, in GraphQL you just need to strongly type the Query made to a Lucene Query as a LuceneQueryResults to retrieve its Count.

**Comment by hyzx86** [comment] 2022-02-10 05:20
Done at here:

https://github.com/EasyOC/EasyOC/blob/master/src/Modules/EasyOC.OrchardCore.OpenApi/GraphQL/LuceneQueryFieldTypeProvider.cs

When the schema contains `"hasTotal": true`,
The result in Graphql will change to include a total, and Items
schema:
```
{
  "type":"contentItem/Customer" ,
  "hasTotal": true
}
```
![image](https://user-images.githubusercontent.com/15613121/153342162-f2c0d06e-cef2-4ac7-8345-bdfc64c08dee.png)

It seems to have met my needs so far.

@Skrypt  But is it possible for me to design this for integration into OC?

**Comment by Skrypt** [comment] 2022-02-10 09:44
Yes make a PR so that we can review the entire thing and adjust if needed.

**Closed** 2022-02-10 18:48 UTC
Labels: GraphQL, Lucene

**Comment by hyzx86** [comment] 2022-05-22 04:13
@Skrypt I have submitted a PR at ：https://github.com/OrchardCMS/OrchardCore/pull/11159
