### ISSUE TITLE
CMS Date field options Idea

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#3664] opened 2019-05-18 12:36 UTC
i think it's better to have an option for a date of the system.

it's not correct to show date fields from default culture. it better to have an option in the defined date field to select with the type (Persian, Arabic, chines,..) it is.

and in showing value of this field, we should use this definition or develop a new filter to convert date to our special date to show.

in Arabic, Persian,... culture the people using two different type calendars so its better to have this possibility to set for any date field, with type calendar should be using.

**Comment by hishamco** [comment] 2019-05-20 13:03
It's a duplicate for #3635, please close this and probably you can rename the old one

**Comment by aghili371** [comment] 2019-05-20 19:55
@hishamco this is different than the persian problem. i mean option in a define date field in any new content type. 
the date field should be specific for any date.

**Comment by hishamco** [comment] 2019-05-20 22:20
> in Arabic, Persian,... culture the people using two different type calendars so its better to have this possibility to set for any date field, with type calendar should be using.

This could be done with Calendar Support that we already added, it picks up the appropriate calendar based on the CurrentUICulture. There's an option that I will work on to choose a custom calendar from within the admin site

**Comment by sebastienros** [comment] 2019-05-23 19:58
I don't understand the issue

**Comment by hishamco** [comment] 2019-05-23 20:09
@sebastienros I thought he is talking about datetime picker localization but seems he want sort of specifying a calendar per  datetime picker

For example in Arabic we are using two calendars: Gregorian (1/1/2019) & Hijri (1/1/1440), so to make this happen we should use which calendar is associated with the datetime picker

So please set the milestone for this, but I think we need to localize the datetime picker first, because it has a priority

**Closed** 2020-02-18 14:47 UTC
Labels: enhancement, localization

**Comment by hishamco** [comment] 2020-02-18 15:36
@agriffard why this closed?!!

**Comment by Skrypt** [comment] 2020-02-18 16:18
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/4593

**Comment by agriffard** [comment] 2020-02-18 16:20
@hishamco you said:

> It's a duplicate for #3635, please close this and probably you can rename the old one

**Comment by Skrypt** [comment] 2020-02-18 16:23
He talks about a Date field so it's a duplicate of #4593 which is a DatetimeOffset field implementation. So there is 2 different topics in this issues. It's fine to close this one as there is already 2 differents issues about these.

**Comment by hishamco** [comment] 2020-02-18 17:09
Seems I forgot it's duplicate ;) but as @Skrypt said there 're two different topics here
