### ISSUE TITLE
MyGet subscription issue: The package size is too large.

### ISSUE THREAD

**Issue by jtkech** [OrchardCMS/OrchardCore#5414] opened 2020-01-31 08:10 UTC
@sebastienros on AppVeyor

    Error publishing package. NuGet server returned 413: The package size is too large.
    The feed owner may have to upgrade the MyGet subscription to resolve this issue.

**Comment by Skrypt** [comment] 2020-02-02 06:18
That's not good if the packages don't get uploaded to MyGet.

**Comment by mdockal** [comment] 2020-02-02 19:00
I'm getting the same errors as #5440 when I try to install or upgrade OrchardCore.Application.Cms.Targets

**Comment by arkadiuszwojcik** [comment] 2020-02-02 20:31
```
[135/139] src\OrchardCore.Themes\TheAgencyTheme\bin\Release\TheAgencyTheme.1.0.0-rc1-11805.nupkg (4,411,771 bytes)...100%
[136/139] src\OrchardCore.Themes\TheBlogTheme\bin\Release\TheBlogTheme.1.0.0-rc1-11805.nupkg (8,594,734 bytes)...100%
```

BlogTheme - more than 8MB? Something here is not right.

**Comment by jtkech** [comment] 2020-02-02 20:41
This is the embedded static files, bootstrap, fontawesome, images ...

**Comment by arkadiuszwojcik** [comment] 2020-02-02 20:43
Maybe fontawesome should be load from CDN?

**Comment by jtkech** [comment] 2020-02-02 20:46
As i remember it has been changed recently to make it more standalone in case of a network issue.

**Comment by blacksun1** [comment] 2020-02-02 23:43
If you are pulling in something like font awesome, shouldn't it be pulled in via NPM on build or something instead of being embedded into the application?

**Comment by Skrypt** [comment] 2020-02-02 23:55
Not if the idea is to make it work for someone that has the source code but no internet.

**Comment by jtkech** [comment] 2020-02-03 00:20
> shouldn't it be pulled in via NPM on build

Yes, this is what we do for the app level localization files through translation packages, but now with the **new project system** this kind of files are only referenced, not automatically injected in the project. That's why we needed to create custom msbuild .targets files to copy them on building.

This is one reason why we embed module static files and also razor / liquid views. Will be also useful for environment without a regular file system.

**Comment by blacksun1** [comment] 2020-02-03 00:53
Yeah, I guess this makes sense when I think about it more... the whole point of downloading a `npm` package is that it should include the bits already.

Do the packages just need to be broken up more then? Like, putting the Themes into seperate packages for instance?

For instance, how many people would actually need to include all of the themes anyway?

I'm probably just talking rubbish but I'm just spitballing really.

**Comment by jtkech** [comment] 2020-02-03 01:17
No problem

Maybe it is not only related of the package size of a given package as we thought here, maybe it is related to the total size of all packages we have on myget knowing that we keep the 10 last versions.

If so, maybe in a some new incomplete versions we will be able to push a complete one.

That said the owner is @sebastienros, i think he will update the subscription tomorrow.

**Comment by Skrypt** [comment] 2020-02-03 18:21
I tried removing the Font-Awesome assets by pushing a PR and the issue still remains. I think the issue is about the fact that we are reaching the limit of MyGet total size of all packages like @jtkech is suggesting.

https://github.com/OrchardCMS/OrchardCore/commit/f06c6f1eab0d6d4bff3588cf3032c41785394adb

This PR needs to be reverted or I'll push a PR that reverts the changes I made in this one.

**Comment by Skrypt** [comment] 2020-02-03 20:01
Maybe time to look into moving this to Github package repositories?

**Comment by deanmarcussen** [comment] 2020-02-03 20:06
They are on github package repositories https://github.com/OrchardCMS/OrchardCore/packages/

However the myget feed failure maybe stopping them getting there.

The other issue was that to use github package repositories you need to be logged in.

However anyone struggling to get a build going may find the link useful

**Comment by Skrypt** [comment] 2020-02-03 20:08
Yes the latest build is referenced on that link. Though @sebastienros mentioned on Gitter that they both have a limit of 500 GB (Myget or Github nuget repo).

**Comment by sebastienros** [comment] 2020-02-03 20:44
I changed the retention settings in myget, and cleaned some other packages. This should be fixed now, or at least with the next build.

I also found a long term solution to this issue.

**Comment by mdockal** [comment] 2020-02-03 20:56
I am no longer having any issues, thanks @sebastienros!

**Closed** 2020-02-03 20:57 UTC
Labels: P0
