### ISSUE TITLE
User Time Zone feature results in DI loop

### ISSUE THREAD

**Issue by mvarblow** [OrchardCMS/OrchardCore#17069] opened 2024-11-26 01:42 UTC
### Describe the bug

After enabling the User Time Zone feature, the site hangs and no longer responds to new requests.

### Orchard Core version

2.1, 2.1.1

### To Reproduce

1. Clone the repo
2. Start the OrchardCore.Cms.Web project
3. Use the default recipe and complete setup
4. Login and go to the Features admin page
5. Enable the User Time Zone feature
6. The site hangs

### Expected behavior

The site should continue to function, but with the user time zone feature enabled. 

### Logs and screenshots

After the site hangs, I can break in the debugger and inspect the call stack. It's truncated by VS to about 4000 call sites. This is repeated on the call stack over and over:

![image](https://github.com/user-attachments/assets/1776f75a-6efd-448c-8c32-553b8a22a621)

That repeated section of call stack includes this:

![image](https://github.com/user-attachments/assets/17b1703a-5f73-4fd5-8ea5-9d3f3d159e43)

and this:

![image](https://github.com/user-attachments/assets/03017e9c-b43b-4cbd-87bc-77893c1d2b10)

**Comment by mvarblow** [comment] 2024-11-26 01:50
@MikeAlhayek, I think this PR introduced the problem.

https://github.com/OrchardCMS/OrchardCore/pull/16942

Reverting that PR seems to resolve the problem.

**Comment by MikeAlhayek** [comment] 2024-11-26 05:41
I briefly looked at the code. think the problem is here: 

https://github.com/OrchardCMS/OrchardCore/blob/1cc5fdd7a63a4d62b0f2c437a478c67a0ab2caae/src/OrchardCore.Modules/OrchardCore.Users/Drivers/UserDisplayDriver.cs#L36

The `IEnumerable<IUserEventHandler> userEventHandlers` should be lazily resolved instead of constructor injection. You can inject IServiceProvide and resolve when needed only. 

I can try it out tomorrow if time permits. But you can give it a try and if it works, please submit a PR and ping me.

**Comment by hishamco** [comment] 2024-11-26 08:21
After a quick look, seems the issue in the context, I created a PR #17071

**Comment by hishamco** [comment] 2024-11-26 09:14
Also, there's an issue with the service registration. The PR was tested and the feature enabled without any issue

**Closed** 2024-11-26 18:50 UTC
Labels: bug :bug:
