### ISSUE TITLE
Order list by OrderByDescending and OrderBy method

### ISSUE THREAD

**Issue by aghili371** [OrchardCMS/OrchardCore#5049] opened 2019-12-15 16:02 UTC
i want to have an ordered list but with all fields, I got the same ordered list.

```
     var queryAcademyTerm = _session.Query<ContentItem, ContentItemIndex>();
            queryAcademyTerm = queryAcademyTerm.With<ContentItemIndex>(x => x.Latest);
            queryAcademyTerm = queryAcademyTerm.With<ContentItemIndex>(x => x.Published);

            queryAcademyTerm = queryAcademyTerm.With<ContentItemIndex>(x => x.ContentType == "SportAcademyTerm");
            queryAcademyTerm = queryAcademyTerm.OrderByDescending (cr => cr.PublishedUtc);
            var contentItemAcademyTerm = await queryAcademyTerm.ListAsync();
```

my question is is it correct core?

how can i order or filter by my field? for example i have "isactive" field for "SportAcademyTerm" content type. how can i filtter for order by this field?

**Comment by Skrypt** [comment] 2019-12-15 20:51
You need to activate the ContentFieldIndex module and Query on these FieldIndexes. Or alternatively you can create your own IndexProviders for your custom content types.

**Comment by Skrypt** [comment] 2019-12-15 20:53
Also duplicate of : https://github.com/OrchardCMS/OrchardCore/issues/4899

**Closed by Skrypt** 2019-12-15 20:53 UTC
