### ISSUE TITLE
[Bug] The confirm and cancel button have text 'undefined'

### ISSUE THREAD

**Issue by jamestran1** [OrchardCMS/OrchardCore#5612] opened 2020-02-22 13:32 UTC
Many dialogs have this text
![image](https://user-images.githubusercontent.com/8802680/75093221-6083a000-55b2-11ea-8d9b-59e204d80064.png)

**Comment by Skrypt** [comment] 2020-02-22 17:50
I have not seen that one since I updated my custom TheAdminTheme layout.cshtml file and .js files. Need to be more precise and give us details if this is actually happening on the actual dev branch and where or on your own admin theme?

**Comment by jamestran1** [comment] 2020-02-24 18:03
@Skrypt I'm currently find a way to reproduce it. It's very weird, maybe at the first time to run the application

**Comment by hishamco** [comment] 2020-02-24 18:49
> maybe at the first time to run the application

May be or are you sure ;)

**Comment by Skrypt** [comment] 2020-02-24 20:35
This could be simply a browser cache issue then.

**Comment by hishamco** [comment] 2020-02-24 22:43
I will close this for now while there's no proper steps to reproduce the issue, @jamestran1 feel free to reopen if the issue raise again after clearing the browser cache

**Closed by hishamco** 2020-02-24 22:43 UTC
