### ISSUE TITLE
Removing or Unpublishing a content item can't be prevented from a ContentHandler

### ISSUE THREAD

**Issue by barthamark** [OrchardCMS/OrchardCore#14779] opened 2023-11-28 14:20 UTC
### Describe the bug

Removing a content item can't be prevented from a ContentHandler (e.g., a content item is required for the site's functionality, so you'd create a `ContentHandlerBase` implementation that cancels the operation in `RemovingAsync`). `UnpublishingAsync` has a `context.Cancel` property but it's completely ignored.

### To Reproduce
1. Create a `ContentHandlerBase`.
2. Override `RemovingAsync` or `UnpublishingAsync`.
3. Observe that you can't cancel the removing operation.
4. Observe that even if you set `context.Cancel = true` in `UnpublishingAsync` it won't take effect during unpublishing.

### Expected behavior
Removing and unpublishing can be canceled from content handler.

### Workaround
The below code solves the issue but it's not ideal since the successful message will still be displayed and other handlers might still do logic that is not reverted.

```
public class DeletionGuardContentHandler : ContentHandlerBase
{
    private readonly IHtmlLocalizer<DeletionGuardContentHandler> H;
    private readonly INotifier _notifier;
    private bool _isPublished;
    private bool _isLatest;
    private DateTime? _modifiedUtc;

    public DeletionGuardContentHandler(
        IHtmlLocalizer<DeletionGuardContentHandler> htmlLocalizer, INotifier notifier)
    {
        _notifier = notifier;
        H = htmlLocalizer;
    }

    public override Task UnpublishingAsync(PublishContentContext context)
    {
        // Some logic to ignore items you don't want to protect...

        _modifiedUtc = context.ContentItem.ModifiedUtc;
        // It appears to be ignored but leaving it here anyway...
        context.Cancel = true;

        return Task.CompletedTask;
    }

    public override async Task UnpublishedAsync(PublishContentContext context)
    {
        // Some logic to ignore items you don't want to protect...

        context.ContentItem.ModifiedUtc = _modifiedUtc;
        context.ContentItem.Published = true;

        await _notifier.ErrorAsync(
            H[
                "The content item '{0}' cannot be unpublished because it's required for certain features on the site.",
                context.ContentItem.DisplayText]);
    }

    public override Task RemovingAsync(RemoveContentContext context)
    {
        // Some logic to ignore items you don't want to protect...

        _isPublished = context.ContentItem.Published;
        _isLatest = context.ContentItem.Latest;

        return Task.CompletedTask;
    }

    public override async Task RemovedAsync(RemoveContentContext context)
    {
        // Some logic to ignore items you don't want to protect...

        context.ContentItem.Published = _isPublished;
        context.ContentItem.Latest = _isLatest;

        await _notifier.ErrorAsync(
            H[
                "The content item '{0}' cannot be deleted because it's required for certain features on the site.",
                context.ContentItem.DisplayText]);
    }
}
```

**Comment by MikeAlhayek** [comment] 2023-11-28 16:35
@barthamark Do you want to submit a PR?

The line https://github.com/OrchardCMS/OrchardCore/blob/4482cb0e81ea0b569e6185232a6713ce62d39100/src/OrchardCore/OrchardCore.ContentManagement/DefaultContentManager.cs#L483

need to have

```
if (context.Cancel)
{
    return;
}
```

**Comment by lampersky** [comment] 2023-11-28 18:43
https://github.com/OrchardCMS/OrchardCore/issues/14589

**Comment by sebastienros** [comment] 2023-12-14 18:38
Duplicate of https://github.com/OrchardCMS/OrchardCore/issues/14589

**Closed by sebastienros** 2023-12-14 18:38 UTC
Labels: bug :bug:
