### ISSUE TITLE
CTRL + S / CTRL + SHIFT + S

### ISSUE THREAD

**Issue by kdubious** [OrchardCMS/OrchardCore#8859] opened 2021-03-13 20:25 UTC
Would be great to have keyboard commands to Save / Save and continue while editing.

**Comment by hishamco** [comment] 2021-03-13 21:06
This is duplicate of #8059

**Closed by hishamco** 2021-03-13 21:06 UTC
Labels: duplicate, enhancement

**Comment by kdubious** [comment] 2021-03-13 21:07
Oops. Thanks.

**Comment by hishamco** [comment] 2021-03-14 04:29
Feel free if you are going to push a PR for that one
