### ISSUE TITLE
Number Formats in Liquid

### ISSUE THREAD

**Issue by cohoweb** [OrchardCMS/OrchardCore#5615] opened 2020-02-22 18:36 UTC
The shopify money filters are not working in liquid templates.  I can't find any information on best practice for money or other number pattern formatting filters.  Any help is appreciated

**Comment by Skrypt** [comment] 2020-02-22 18:49
duplicate of https://github.com/OrchardCMS/OrchardCore/issues/3166

**Closed by Skrypt** 2020-02-22 18:49 UTC
