### ISSUE TITLE
[Orchard.Autoroute] Part with custom DisplayRouteValues does not use autoroute url when displayed

### ISSUE THREAD

**Issue by timmahon** [OrchardCMS/OrchardCore#836] opened 2017-06-19 10:56 UTC
**Summary:**
If you set custom DisplayRouteValues in the handler of a content part, and have an Autoroute part attached to the same content item, the Autoroute url is no longer used.

**Steps to Reproduce:**
- Create a custom content part and in the handler set the DisplayRouteValues of the ContentItemMetadata. For example:-

```
public override void GetContentItemAspect(ContentItemAspectContext context, PackagePart packagePart)
        {
            context.For<ContentItemMetadata>(metadata =>
            {
                metadata.DisplayRouteValues = new RouteValueDictionary
                {
                    {"Area", "Area.MyArea" },
                    {"Controller", "MyController" },
                    {"Action", "MyAction" },
                    {"ContentItemId", packagePart.ContentItem.ContentItemId }
                };
            });
        }
```
- Observe the URL when the content is viewed, it will not be the Autoroute url.

**Comment by sebastienros** [comment] 2017-06-19 19:13
The autoroute part will always for to the Content controller. I assume in your case you want to keep the slug generation but point to a different controller? 

Are you doing it for all the instances of a content item/content part, or for something more dynamically driven?

**Comment by timmahon** [comment] 2017-06-20 09:01
Yes. That's right, I want to keep slug generation and route it to my own controller.  I am doing this for any item that has my content part attached.

**Comment by sebastienros** [comment] 2017-06-20 17:13
Then it might be better to have the autoroute part configurable to be able to provide a custom route at the type level. Because right now it's hard coded. Probably not from the UI but at least with a service interface that is called by the autoroute.
Can you tell me more about what is special in your controller that you don't get with the existing infrastructure?

**Comment by timmahon** [comment] 2017-06-20 18:35
One of my O1 modules is for hosting Facebook applications, which I want to use Autoroute to let the user determine the URL.  I have a FacebookCanvasPart which stores the application key.  When Facebook load the canvas app (loaded in an iFrame), they POST to the URL with a signed key that contains the current Facebook user and other data.  So the controller I need to route to, I need to have anti-forgery turned off (as this isn't sent by Facebook) and also need to process the posted data.  The output is largely cached but we replace a few sections depending on the posted data.

Another use we had in O1 in some of the legacy modules (pre Dynamic Forms) was for contact forms to allow the URL where these were hosted to be localised, but still allow for these to route through to our own controller.  

For URLs in general, we also made use of the O1 `IAliasService` in our SEO module, where we could have multiple links to a single content item.  This would consist of the primary route, and all other routes were from legacy site URLs which would then route to a permanent redirect controller to the primary URL. 
 This would enable old bookmarked links to continue working and get the links updated in search engines.  Right now, I don't see a way of doing the same in O2 unless I duplicate a lot of what Autoroute is doing.

**Comment by sebastienros** [comment] 2017-06-20 18:55
I understand the issue is that you use the content item's url from facebook to do a POST. And you need to do some custom code on this. Then I think what I suggest is great, we just need  a new service for AutoroutePart to provide a different route. `IAutorouteRoutingProvider` and the default implementation would provide the Content one. The within your module you create a new implementation that will check for the content item to have the FacebookPart before returning your custom route to your custom controller. And your controller will have a `[IgnoreAntiforgeryToken]` attribute.

For the alias and the redirections, this is a recurring question. I suggest we do another feature called AlternateUrls or similar, which would have a part that would attach to a content item to provide handlers to other urls. Or we could have an option on the autoroute part to be able to provider alternate urls. They would go through the same `IAutorouteRoutingProvider` logic to provide custom controllers (whatever url reaches the current content item, they will all go to the same controller). 

1- Do we need to be able to customize what happens for a specific url like permanent redirection, non-permanent, or just render the controller/action without redirection?
2- I assume it's better to manage the custom url in the content item editor instead of having a screen with all mappings (I don't see any advantage in the latter).

**Comment by Piedone** [comment] 2024-04-25 22:54
Closing due to no reply from author.

**Closed by Piedone** 2024-04-25 22:54 UTC
