### ISSUE TITLE
Create content by using SQL query

### ISSUE THREAD

**Issue by ziyadsv** [OrchardCMS/OrchardCore#7755] opened 2020-11-25 08:36 UTC
can we create create ContentItemIndex and Documetn by using Sql query?

How the DocumentId and ContentItemIndexId will create by using sql query?

**Comment by jptissot** [comment] 2020-11-25 12:17
I don't think you can do this easily at the moment. If you can I don't know how. The issue is that there are many other indexes and yessql is the layer that updates them. I suggest you look into using recipes to create content. Or use an api.

**Comment by Skrypt** [comment] 2020-11-25 12:40
I strongly advise not using directly SQL Queries to create content items. Use the ContentManager else your content items won't be indexed in Lucene. We have Handlers (events) that are executed when someone does ContentManager.Create() ... 
Using the REST API will also trigger the event handlers. So, you can use SQL Queries but be aware that some things won't work properly.

**Comment by sebastienros** [comment] 2020-12-17 18:15
Closing until you explain why you would need to do it.

**Closed by sebastienros** 2020-12-17 18:15 UTC
